/* Bathroom range, taken from the live capitaltiles.com.au bathroom
   collection: names, blurbs, brands and the colour / finish / size options
   each product actually ships with. */

export const BATHROOM = [
  {
    name: "Ardesia Paver",
    handle: "ardesia-collection",
    blurb: "The ARDESIA collection captures the timeless elegance of slate, bringing the raw beauty of nature into refined interior and exterior spaces. With its ",
    brand: "Muses",
    colours: ["Ivory", "Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Chiswick Collection",
    handle: "chiswick-collection",
    blurb: "Where Natural Stone Meets Contemporary Performance Bring timeless elegance and modern function together with the Chiswick Collection —a sophisticated ",
    brand: "Capital Tiles",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    finishes: ["Honed", "Matte"],
    sizes: ["600x1200", "600x600", "300x600", "75x300"],
  },
  {
    name: "Crete Collection",
    handle: "crete-collection",
    blurb: "Soft Stone-Look Porcelain for Seamless Indoor-Outdoor Design The Crete Collection is a refined take on natural stone, offering gentle movement and a s",
    brand: "Capital Tiles",
    colours: ["Warm Beige", "Pearl Grey", "Nero Black", "Bianco White"],
    finishes: [],
    sizes: ["75x300mm", "300x600mm", "600x600mm", "600x1200mm"],
  },
  {
    name: "Jura Collection",
    handle: "jura-collection",
    blurb: "Timeless Limestone-Look Elegance Inspired by the natural beauty of limestone from the Jura region in Germany, the Jura Series brings a refined and sop",
    brand: "Capital Tiles",
    colours: ["White", "Greige", "Grey", "Ivory"],
    finishes: [],
    sizes: ["75x300", "300x300", "300x600", "600x600"],
  },
  {
    name: "Arctic Tundra",
    handle: "arctic-tundra",
    blurb: "Nature-Inspired Porcelain for Seamless Indoor & Outdoor Spaces Discover the pristine beauty of the wild with the Arctic Tundra Collection – a porcelai",
    brand: "Capital Tiles",
    colours: ["White", "Grey", "Beige"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Jade Collection",
    handle: "jade",
    blurb: "Soft Texture, Polished Sophistication Bring subtle elegance and contemporary calm to your interiors with the Jade Collection . Inspired by the smooth ",
    brand: "HF Tiles",
    colours: ["Beige", "White"],
    finishes: ["Soft Matt", "Polish", "Matt"],
    sizes: ["600x600", "600x1200"],
  },
  {
    name: "Travertine",
    handle: "travertine",
    blurb: "Classic Stone Look, Modern Performance Bring timeless sophistication to your interiors with the Travertine Collection, inspired by the enduring beauty",
    brand: "HF Tiles",
    colours: ["Beige", "White"],
    finishes: ["Matt", "Lappato"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Alps",
    handle: "alps",
    blurb: "Seamless Stone-Look Indoors & Out Inspired by the raw beauty of alpine stone, the Alps Collection delivers a sophisticated, textured finish perfect fo",
    brand: "Capital Tiles",
    colours: ["Beige", "Silver", "Grey"],
    finishes: ["In&Out Solution"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Everest",
    handle: "everest",
    blurb: "Bold Stone Look, Built for Endurance Elevate your space with the Everest Collection, where modern design meets natural stone elegance. Inspired by the",
    brand: "HF Tiles",
    colours: ["Ivory", "Silver", "Grey"],
    finishes: ["In&Out Solution", "StoneTouch Tec"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Calacatta",
    handle: "calacatta",
    blurb: "Classic Marble, Effortlessly Modern Bring timeless elegance into your space with the Calacatta Collection, a stunning marble-look porcelain tile serie",
    brand: "Muses",
    colours: [],
    finishes: ["Polished", "Satin"],
    sizes: ["700x1500"],
  },
  {
    name: "Caesarstone",
    handle: "caesarstone",
    blurb: "Sleek Stone-Inspired Sophistication Elevate your interior and exterior spaces with the Caesarstone Collection—a refined porcelain tile range inspired ",
    brand: "HF Tiles",
    colours: ["Light", "Medium", "Dark"],
    finishes: ["In&Out Solution", "Lappato", "Soft Matt", "Flute"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Origin",
    handle: "origin",
    blurb: "Modern Minimalism with a Stone Edge Clean lines meet timeless surface texture in the Origin Collection, a versatile tile range designed for modern int",
    brand: "HF Tiles",
    colours: ["White", "Beige", "Grey", "Black"],
    finishes: ["Matt", "Lappato", "Polish", "Flute"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Luxstone",
    handle: "luxstone",
    blurb: "Effortless Stone-Look Sophistication Bring the timeless beauty of natural stone into your space with the Luxstone Collection — a refined, versatile ra",
    brand: "Capital Tiles",
    colours: ["White", "Natural", "Beige"],
    finishes: [],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Aquastone",
    handle: "vienna",
    blurb: "Understated. Natural. Refined. Inspired by the soft textures and organic tones of natural stone, the Aquastone Collection brings effortless elegance t",
    brand: "Capital Tiles",
    colours: ["Ivory"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Zouks",
    handle: "zouks",
    blurb: "Bold. Textured. Modern. Make a strong design statement with the Zouks Collection – a contemporary tile range defined by its bold texture and dramatic ",
    brand: "Muses",
    colours: [],
    finishes: ["3D"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Stazzema Series",
    handle: "stazzema",
    blurb: "Textured Elegance with Natural Depth Inspired by the fine textures of honed limestone, the Stazzema Collection offers a refined balance of elegance, v",
    brand: "Muses",
    colours: ["Ivory", "Smokey Grey"],
    finishes: ["Felltec"],
    sizes: ["300x600mm", "600x600mm", "600x1200mm"],
  },
  {
    name: "Silver Root",
    handle: "silver-root",
    blurb: "Polished Sophistication with Stone Soul Inspired by the intricate veining of high-end marble and the organic movement of natural stone, the Silver Roo",
    brand: "Muses",
    colours: ["Ivory", "Light Grey", "Brown"],
    finishes: ["Satin"],
    sizes: [],
  },
  {
    name: "Roccia Series",
    handle: "roccia",
    blurb: "Earthy Porcelain Tiles with Modern Durability Bring the rugged charm of natural stone into your home with the Roccia Collection . These porcelain tile",
    brand: "Muses",
    colours: ["Greige", "Charcoal"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Picasso",
    handle: "picasso",
    blurb: "Artful Texture Meets Modern Scale Bring bold creativity into your interiors with the Picasso Collection , a porcelain tile range inspired by contempor",
    brand: "Muses",
    colours: [],
    finishes: ["Deep Ink (IK) & 3D"],
    sizes: ["300x600", "600×600", "600×1200", "750×1500"],
  },
  {
    name: "Onyx Series",
    handle: "onyx",
    blurb: "Polished Perfection in Stone-Inspired Style Elevate your interiors with the Onyx Collection — a porcelain tile range inspired by the depth and veining",
    brand: "Muses",
    colours: ["Ivory", "Beige", "Light Grey", "Brown"],
    finishes: ["Polished", "Satin"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Calacatta Gold",
    handle: "calacatta-gold",
    blurb: "Timeless Elegance with a Golden Touch Inspired by the luxurious veining of Italian Calacatta marble, the Calacatta Gold Collection brings soft opulenc",
    brand: "Muses",
    colours: ["Gold"],
    finishes: ["Polished", "Satin"],
    sizes: ["600x1200mm", "750x1500mm"],
  },
  {
    name: "Kolor Series",
    handle: "kolor",
    blurb: "Contemporary Concrete-Inspired Minimalism Refined, architectural, and effortlessly modern, the Kolor Collection brings the understated beauty of concr",
    brand: "Muses",
    colours: ["White", "Ivory", "Light Grey", "Medium Grey"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Alhambra Collection",
    handle: "alhambra",
    blurb: "Elegant Embossed Tiles for Walls & Floors Bring European sophistication to your home with the Alhambra Collection . These decor tiles feature delicate",
    brand: "Capital Tiles",
    colours: ["Rojo", "Negro", "Gris", "Azul", "Arena", "Barcelona"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Aqua",
    handle: "aqua-collection",
    blurb: "Modern Coastal Finish Bring a refreshing, contemporary look to your interiors with the Aqua 60x240mm polished tile. Its sleek finish is ideal for brig",
    brand: "Muses",
    colours: ["Crystal", "Opal", "Rune", "Jade", "Berry", "Core"],
    finishes: ["Polished"],
    sizes: [],
  },
  {
    name: "Altea Collection",
    handle: "altea-collection",
    blurb: "Spanish Subway Tiles with Glossy Character The Altea Collection brings a fresh twist to classic subway tiles, with a wavy structured finish and a rich",
    brand: "Capital Tiles",
    colours: ["Dusty Pink", "Matcha", "Ash Blue", "Black", "Smoke", "Pine Green", "White"],
    finishes: [],
    sizes: ["75 x 150", "100 x 100"],
  },
  {
    name: "Aroma Collection",
    handle: "aroma-collection",
    blurb: "Italian Subway Tiles with Glossy Texture The Aroma Collection brings Italian craftsmanship to a modern classic. These elongated 60x240 mm subway tiles",
    brand: "Capital Tiles",
    colours: ["Verde", "Verde Scuro", "Rosa Scuro", "Blu", "Turchese", "Sabbia", "Bianco"],
    finishes: [],
    sizes: ["60 x 240"],
  },
  {
    name: "Bari Collection",
    handle: "bari-collection",
    blurb: "The Bari Collection Travertine Tile — Belconnen Timeless elegance meets natural artistry with The Bari Collection . A luxurious travertine-look porcel",
    brand: "Capital Tiles",
    colours: ["Bianco", "Taupe", "Beige"],
    finishes: ["Versa Touch", "P5 20mm", "Cobbles VT", "P5 20mm Pencil Edge"],
    sizes: ["300x600", "600x600", "1200x600", "75x300", "307x307 mm sheets", "Crazy Pave", "French Pattern", "600x400 mm DF", "600x400"],
  },
  {
    name: "UNICO GREY",
    handle: "unico-grey",
    blurb: "Look Tile — Woden Valley Italian-made and effortlessly refined, Unico Grey reimagines classic marble with twenty unique faces and innovative, high-imp",
    brand: "Capital Tiles",
    colours: ["Unico Grey"],
    finishes: ["Matt 3D"],
    sizes: ["600x1200 mm"],
  },
  {
    name: "Cocoon Collection",
    handle: "cocoon-collection",
    blurb: "Cocoon Honed Porcelain Tile — Weston Creek & Molonglo Cocoon is an Italian-made porcelain collection that wraps spaces in calm. With 16 unique faces, ",
    brand: "Capital Tiles",
    colours: ["Hazelnut", "Beige"],
    finishes: ["Honed"],
    sizes: ["600x1200 mm"],
  },
  {
    name: "Ciement",
    handle: "ciement",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["White"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Orobico",
    handle: "orobico",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 Recommended Applications (Glaze",
    brand: "CIE Ceramic",
    colours: ["Bianco", "Grey"],
    finishes: ["Matt"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Republic",
    handle: "republic",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 600*60",
    brand: "CIE Ceramic",
    colours: ["White", "Silver"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200", "400x600"],
  },
  {
    name: "Divine Stone",
    handle: "divine-stone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Simply Stone",
    handle: "simply-stone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "SandStone",
    handle: "sandstone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Bianco"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Polar Ice",
    handle: "polar-ice",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 Recommended Applications (Glaze",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Terrazzo",
    handle: "terrazzo",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 Recommended Applications (Glazed Porcelain) : Interio",
    brand: "CIE Ceramic",
    colours: ["Bianco"],
    finishes: ["Matt"],
    sizes: ["300x300", "300x600", "600x600"],
  },
  {
    name: "Travertine",
    handle: "travertine-1",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Silver", "Bravo"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Dusk",
    handle: "dusk",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Greige", "White"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Millenia",
    handle: "millenia",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm Matt P2 600*1200 1",
    brand: "CIE Ceramic",
    colours: ["White", "Pearl Grey"],
    finishes: ["Matt", "Polished"],
    sizes: ["300x300", "300x600", "600x600", "600x1200", "1200x1200"],
  },
  {
    name: "Shine",
    handle: "shine",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Bianco", "Moon"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Cairo",
    handle: "cairo",
    blurb: "Size Thickness Finish Slip Rating 600*600 20mm External P5 400*600 20mm External Drop Edge Copping P5 Recommended Applications (Glazed Porcelain) : Ex",
    brand: "CIE Ceramic",
    colours: ["Light", "Dark"],
    finishes: ["External"],
    sizes: ["400x600", "600x600"],
  },
  {
    name: "Patrone",
    handle: "patrone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P4 300*600 10mm Matt P4 600*600 10mm Matt P4 600*600 20mm External P5 400*600 20mm External P5 Not",
    brand: "CIE Ceramic",
    colours: ["Beige", "Silver", "Ebony"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "400x600"],
  },
  {
    name: "Pool Glass mosaic",
    handle: "pool-glass-mosaic",
    blurb: "Available. Floor and wall rated, supplied and installed across Canberra.",
    brand: "CIE Ceramic",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Kit Kat Mosaic",
    handle: "kit-kat-mosaic",
    blurb: "Colour: Gloss White Concave 20mm, Gloss Grey Concave 20mm, Plain Matt White 20mm, Plain Matt White 12mm Size: Sheet Size 12mm 293*298 Sheet Size 20mm ",
    brand: "CIE Ceramic",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Stone Cobblestone",
    handle: "stone-cobblestone",
    blurb: "Colour: Bali, Luna, Imperial Packaging: Sold Per Square Metre, Sheet Size Meshed 300*300 Full Crates Hold 20.25m² Recommended Applications (Natural St",
    brand: "CIE Ceramic",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Milano",
    handle: "milano",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 1200*1200 10mm Matt P2 600*600 ",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200", "1200x1200", "400x600"],
  },
  {
    name: "Calacatta Pro",
    handle: "calacatta-pro",
    blurb: "The Calacatta Pro Marble collection delivers the timeless elegance of classic Calacatta with a modern twist. Featuring a bright white base enriched by",
    brand: "Muses",
    colours: [],
    finishes: ["Felltec", "Polished"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Find Honed",
    handle: "find-honed",
    blurb: "Available in 2 colours and 1 finish, in 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Cool Grey", "Light Grey"],
    finishes: ["Honed"],
    sizes: ["600x1200"],
  },
  {
    name: "Mistery Dark Grey",
    handle: "mistery-dark-grey",
    blurb: "Available in 2 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Light Grey", "Dark Grey"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Vutton Series",
    handle: "vutton-series",
    blurb: "The VUTTON collection combines refined elegance with contemporary style, making it the perfect choice for sophisticated interiors. Inspired by natural",
    brand: "Muses",
    colours: ["Ash", "Ice", "Night", "Pearl", "Sage"],
    finishes: [],
    sizes: ["Mosaic Sheets (275.2×275.2mm)"],
  },
  {
    name: "Blaze Paver",
    handle: "blaze-paver",
    blurb: "Color Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Crest Paver",
    handle: "crest-paver",
    blurb: "Available in 3 colours and 1 finish, in 600 x 600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Light Grey", "Ivory", "Dark Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Imperial Stone Paver",
    handle: "imperial-stone-paver",
    blurb: "Sizes : 600×600 (20mm Thick) Color Ivory, Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Light Grey", "Ivory"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Petra Mix Paver",
    handle: "petra-mix-paver",
    blurb: "Sizes : 600×600 (20mm Thick) Color Beige, Ivory, Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Quartzite Paver",
    handle: "quartzite-paver",
    blurb: "Available in 2 colours and 1 finish, in 600 x 600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Charcoal", "Grigio"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Trav Cross Cut",
    handle: "trav-cross-cut",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Trav Vein Cut",
    handle: "trav-vein-cut",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Starry",
    handle: "starry",
    blurb: "Starry is a premium porcelain tile offered by Muses Australia that combines understated elegance with everyday performance. Designed to bring a warm a",
    brand: "Muses",
    colours: ["Beige", "Light Grey", "Black"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Find",
    handle: "find",
    blurb: "Available in 2 colours and 1 finish, in 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Cool Grey", "Light Grey"],
    finishes: ["Felltec"],
    sizes: ["600x1200"],
  },
  {
    name: "Limestone",
    handle: "limestone",
    blurb: "Available in 4 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Beige Fluted", "Ivory Fluted", "Ivory"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Port Travertino",
    handle: "port-travertino",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Balcan",
    handle: "balcan",
    blurb: "quality ceramic wall and floor tile offered by Muses Ceramics Australia, designed to elevate interiors with a refined aesthetic and reliable performan",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Ferragamo",
    handle: "ferragamo",
    blurb: "The Ferragamo tile from Muses Australia is a premium glazed porcelain tile crafted to bring a refined, modern look to interior and exterior spaces. It",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Karzai Green",
    handle: "karzai-green",
    blurb: "The Karzai Green tile offers a striking combination of elegance and durability, featuring a 600 × 1200 mm size and a high-quality 4D Glue & Grit Full ",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Pandora Elegance",
    handle: "pandora",
    blurb: "The Pandora tile from Muses Australia is a stylish glazed porcelain tile in a 600 × 1200 mm size with a 4D Glue & Grit Full Body finish. It delivers a",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Ionic",
    handle: "origin-copy",
    blurb: "Available in 2 colours and 3 finishes, in 600x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Grey", "Silver"],
    finishes: ["Matt", "Polish", "Soft Matt"],
    sizes: ["600x600", "300x600", "600x1200"],
  },
  {
    name: "Monash",
    handle: "monash",
    blurb: "Available in 1 colour and 1 finish, in 600x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Black"],
    finishes: ["Matt"],
    sizes: ["600x600", "600x1200"],
  },
  {
    name: "Apex",
    handle: "apex",
    blurb: "Available in 1 colour and 2 finishes, in 300x600 to 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Silver"],
    finishes: ["Matt", "Polish"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Vienna",
    handle: "vienna-1",
    blurb: "Available in 2 colours and 3 finishes, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Grey", "Ivory"],
    finishes: ["Matt", "Polish", "Soft Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Limestone Dark",
    handle: "limestone-dark",
    blurb: "Available in 1 finish, in 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Loft Dark",
    handle: "loft-dark",
    blurb: "Available in 2 finishes, in 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["600x600"],
  },
  {
    name: "Terrazzo Grey",
    handle: "terrazzo-grey",
    blurb: "Available in 1 finish, in 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Vista",
    handle: "vista",
    blurb: "Available in 2 colours and 1 finish, in 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Ivory", "Silver"],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Fg Grey",
    handle: "fg-grey",
    blurb: "Available in 2 finishes, in 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt", "Polish"],
    sizes: ["600x600"],
  },
  {
    name: "Gelato",
    handle: "gelato",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Light", "Medium", "Dark"],
    finishes: ["In&Out Solution"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Flat-Alps",
    handle: "flat-alps",
    blurb: "Available in 4 colours and 4 finishes, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Silver", "Grey", "White", "Beige"],
    finishes: ["In&Out Solution", "StoneTouch Tec", "Paver", "Flute"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Taj Mahal",
    handle: "taj-mahal",
    blurb: "Available in 3 colours and 4 finishes, in 600x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Natural", "Ivory", "Silver"],
    finishes: ["Matt", "StoneTouch Tec", "Soft Matt", "Flute"],
    sizes: ["600x600", "600x1200"],
  },
  {
    name: "Tundra",
    handle: "tundra",
    blurb: "Available in 1 colour and 1 finish, in 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["White"],
    finishes: ["Matt"],
    sizes: ["600x1200"],
  },
  {
    name: "Iceland",
    handle: "iceland",
    blurb: "Available in 1 colour and 1 finish, in 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Gold"],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Carrara",
    handle: "carrara",
    blurb: "Available in 1 colour and 1 finish, in 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["White"],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
]
