/* Carpet — the full range, taken from the live capitaltiles.com.au carpet
   collection: names, blurbs, brands and the colour / finish / size options each
   product actually ships with. */

export const CARPET = [
  {
    name: "Sky Bridge",
    handle: "sky-bridge",
    blurb: "Sky Bridge is a stylish loop pile carpet, ideal for those seeking a sophisticated look at a cost-effective price. Its chunky, textured loops offer a c",
    brand: "EC carpets",
    colours: ["Bowen 8105", "Tasman 8107", "Harbour 8101", "Hampden 8108", "Webb 8103", "Macleay 8106", "Paringa 8102", "Marlow 8104"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Dolomites",
    handle: "dolomites",
    blurb: "Dolomites is a stylish loop pile carpet, ideal for those seeking a sophisticated look at a cost-effective price. Its chunky, textured loops offer a co",
    brand: "EC carpets",
    colours: ["Stelvio 8005", "Rosa 8007", "Gavia 8001", "Cervino 8008", "Brenta 8003", "Bianco 8006", "Corvara 8002", "Madonna 8104"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Woodchester",
    handle: "woodchester",
    blurb: "Woodchester offers stylish and budget-friendly polypropylene carpeting, combining contemporary design with affordability for homeowners, landlords, bu",
    brand: "EC carpets",
    colours: ["Callington 3504", "Meechi 3508", "Tinpot 3509", "Rodwell 3516", "Dalveen 3511", "Macallan 3525"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Summit Point",
    handle: "summit-point",
    blurb: "Summit Point is a medium-duty, tough stain-resistant carpet ideal for active families, raising the bar for premium polypropylene carpets by providing ",
    brand: "EC carpets",
    colours: ["Feathertop+2922", "Selwyn+2921", "Howitt+2923", "Townsend+2928", "Riverina+2927", "Hotham+2925", "Franklin+2926"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Savanna",
    handle: "savanna",
    blurb: "Savanna is a medium-duty, tough stain-resistant carpet ideal for active families, raising the bar for premium polypropylene carpets by providing outst",
    brand: "EC carpets",
    colours: ["Rivergum 2932", "Candlebark 2931", "Coolibah 2933", "Cottonwood 2938", "Wattle 2937", "Applebush 2935", "Copperburr 2936"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Montrosa",
    handle: "montrosa",
    blurb: "Montrosa is a stain-resistant carpet designed for active families, combining stylish design and affordability for homeowners, landlords, builders, and",
    brand: "EC carpets",
    colours: ["Spire 2504", "Faber 2506", "Hillford 2508", "Vistron 2509", "Bottania 2516", "Leedon 2511", "Avila 2525", "Chantilly 2515"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Encounter",
    handle: "encounter",
    blurb: "Encounter is a trendy and budget-friendly, tough, stain-resistant carpet ideal for active families, offering easy maintenance and exceptional affordab",
    brand: "EC carpets",
    colours: ["Sandbar 7574", "Shorebird 7579", "Spice 7585", "Anchorage 7576", "Newland 7577", "Pontoon 7575", "Botany 7578", "Storm 7589"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Tunes",
    handle: "tunes",
    blurb: "Experience the appeal of beautiful organic tones, twisted in a striated pattern. Displaying unrivalled durability, this combination of nature-inspired",
    brand: "EC carpets",
    colours: ["Classical 9719", "Country 9741", "Legato 9728", "Jazz 9738", "Scalar 9704", "Pop 9726", "Blues 9737", "Disco 9732", "Chromatic 9707"],
    finishes: ["Twist"],
    sizes: [],
  },
  {
    name: "Orchard",
    handle: "orchard",
    blurb: "Orchards’ combination of chic design with durability, elevates spaces with earthy colours and a striated pattern. Its construction mirrors the eleganc",
    brand: "EC carpets",
    colours: ["Akane 2619", "Calville 2641", "Sansa 2628", "Melrose 2638", "Cortland 2604", "Cameo 2626", "Ida 2637", "Jonamac 2632", "Ashmead 2607"],
    finishes: ["Plush"],
    sizes: [],
  },
  {
    name: "Flinders Gorge",
    handle: "flinders-gorge",
    blurb: "Flinders Gorge offers high-quality and affordability with a rich texture resembling wool. Its neutral palette blends seamlessly with modern interiors,",
    brand: "EC carpets",
    colours: ["Blanche 3404", "Beltana 3406", "Olary 3433", "Warren 3421", "Calla 3403", "Hawker 3455", "Havelock 3451", "Tanderra 3458", "Leigh 3425", "Copley 3419", "Amyton 3416", "Rawnsley 3422"],
    finishes: [],
    sizes: [],
  },
  {
    name: "District Loft",
    handle: "district-loft",
    blurb: "District Loft tis a modern entry-level cut pile carpet offering comfort and dependable performance in a practical 30oz construction. Its 1/10 gauge co",
    brand: "EC carpets",
    colours: ["Quarter 9242", "Precinct 9243", "Local 9237", "Bureau 9231", "Foundry 9212", "Urban 9225", "City 9224", "Metro 9223", "Assembly 9228", "Forge 9218"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Comfort Touch",
    handle: "comfort-touch",
    blurb: "Comfort Touch is a luxurious twist pile carpet designed for ultimate comfort and softness underfoot. Its plush texture offers exceptional durability y",
    brand: "EC carpets",
    colours: ["Humble 9142", "Relax 9143", "Zen 9137", "Warmth 9131", "Ease 9112", "Charm 9125", "Peace 9124", "Quiet 9123", "Mood 9128", "Snug 9118"],
    finishes: ["Twist", "Plush"],
    sizes: [],
  },
  {
    name: "Coco Bliss",
    handle: "coco-bliss",
    blurb: "Coco Bliss is a premium twist pile carpet designed for style and performance. Its resilient and dense construction offers exceptional durability, maki",
    brand: "EC carpets",
    colours: ["Felicity 9042", "Joy 9043", "Happiness+9037", "Epiphany+9031", "Euphoria+9012", "Delight+9025", "Elation+9024", "Nostalgia+9023", "Gratitude+9028", "Contentment+9018"],
    finishes: ["Twist"],
    sizes: [],
  },
  {
    name: "Bourkesgate",
    handle: "bourkesgate",
    blurb: "Experience unparalleled appearance longevity with our Bourkesgate range, crafted to preserve its flawless allure every day. Combining the aesthetic of",
    brand: "EC carpets",
    colours: ["Kidman 1962", "Kamila 1961", "Cobb 1952", "Lawson 1955", "Paroo 1953", "Jandra 1963", "Namoi 1964", "Louth 1965"],
    finishes: ["Loop Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Bouclé",
    handle: "boucle",
    blurb: "Bouclé offers a touch of wool-like elegance, reminiscent of the European textile texture, bouclé. Combined with a beautiful colour palette, it provide",
    brand: "EC carpets",
    colours: ["Ovie+4304", "Sarinen+4303", "Jacqueline+4342", "Mokum+4347", "Fredrik+4348", "Shu+4315", "Atticus+4318", "Maymo+4308", "Coco+4336"],
    finishes: ["Boucle"],
    sizes: [],
  },
  {
    name: "Ayrton",
    handle: "ayrton",
    blurb: "The striated pattern and earthy tones of Ayrton go beyond mere functionality. Its design not only withstands abrasion but also displays a luxurious ae",
    brand: "EC carpets",
    colours: ["Monaco 4619", "Montreal 4641", "Silverstone 4628", "Francor 4638", "Quebec 4604", "Monza 4626", "Emilia 4637", "Suzuka 4632", "Toleman 4607"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Avenue",
    handle: "avenue",
    blurb: "Avenue combines nylon’s practicality with the aesthetic qualities of natural fibres. Its rich texture hides stains effectively and with modern colours",
    brand: "EC carpets",
    colours: ["Milton 1149", "Rayne 1150", "Rothbury 1153", "Sherwood 1151", "Bevington 1155", "Ashbourne 1152", "Cudmore 1154", "Moorhouse 1156", "Morland 1148"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Andes Peak",
    handle: "andes-peak",
    blurb: "Andes Peak offers wool-like elegance featuring a subtly heathered texture. Its neutral colour palette complements any interior design, while its durab",
    brand: "EC carpets",
    colours: ["Olca 2404", "Patilla 2406", "Serena 2433", "Merida 2421", "Isabel 2403", "Valera 2455", "Rio 2451", "Rubio 2458", "Hudson 2425", "Mendoza 2419", "Morado 2416", "Patagonia 2422"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Acacia Hill",
    handle: "acacia-hill",
    blurb: "Discover the combination of practicality and sophistication with Acacia Hill. This nylon soft flooring has a natural look and rich texture which is ea",
    brand: "EC carpets",
    colours: ["Alton 1249", "Kennedy 1250", "Atkins 1253", "Mawson 1251", "Millrose 1255", "Longford 1252", "Karson 1254", "Myrtle 1256", "Magnolia 1248"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Sirocco",
    handle: "sirocco",
    blurb: "Sirocco is an entry-level wool loop pile carpet crafted from 100% pure wool, offering natural comfort and everyday practicality. Inspired by the class",
    brand: "EC carpets",
    colours: ["Desert Clay 5917", "Barley Sand 5954", "Argan Spice 5947", "Market Bazaar 5945", "Quarry Mist 5923", "Cinder Stone 5928", "Basalt Dune 5988"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Hause",
    handle: "hause",
    blurb: "A modern take on classic Berber, this premium 100% New Zealand wool carpet offers elegance and practicality with its neutral heathered colours effortl",
    brand: "EC carpets",
    colours: ["Three 5003", "Seventeen 5017", "Fifty Four 5054", "Forty Seven 5047", "Forty Five 5045", "Twenty Three 5023", "Twenty EIGHT 5028", "Eighty Eight 5088", "Eleven 5011"],
    finishes: ["Twist"],
    sizes: [],
  },
  {
    name: "Elmsford",
    handle: "elmsford",
    blurb: "Elmsford is a premium 100% New Zealand wool loop carpet, where natural warmth meets considered design. Its offset, organic pattern introduces a quiet,",
    brand: "EC carpets",
    colours: ["Clara 5801", "Birley 5802", "Rowden 5803", "Caden 5804", "Magnor 5805", "Nox 5806", "Solmorra 5807", "Oakmere 5808", "Garnet 5809"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Dawson Falls",
    handle: "dawson-falls",
    blurb: "Dawson Falls, our luxurious pure wool carpet, redefines elegance with its refined linear pattern and stunning colour palette, bringing timeless style ",
    brand: "EC carpets",
    colours: ["Meadow 5403", "Canyon 5417", "Sunlit 5454", "Serenity 5447", "Summit 5445", "Cascade 5423", "Mist 5428", "Frosted 5488", "Harmony 5411"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Cotswolds",
    handle: "cotswolds",
    blurb: "Cotswolds is a premium 100% New Zealand wool loop carpet that brings architectural confidence to the floor. Its geometric loop pattern delivers a stru",
    brand: "EC carpets",
    colours: ["Willowby 6001", "Alderwick 6002", "Fallow 6003", "Thornleigh 6004", "Millthorpe 6005", "Hollowmere 6006", "Kingswell 6007", "Hazelwood 6008", "Maplehurst 6009"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Bahamas",
    handle: "bahamas",
    blurb: "rafted from 100% New Zealand Wool, Bahamas offers a rustic, sisal-inspired loop. This timeless colour palette comes in natural earthy tones, suitable ",
    brand: "EC carpets",
    colours: ["Caribbean 5705", "Grenada 5706", "Barbados 5707", "Cayman 5704", "Cuba 5701", "Jamaica 5703", "Nevis 5702"],
    finishes: ["Loop Pile", "Rustic"],
    sizes: [],
  },
  {
    name: "Covent Garden",
    handle: "covent-garden",
    blurb: "Covent Garden will bring luxurious softness and style to your home. A cut pile twist carpet with a palette of natural earthy tones, Covent Garden is d",
    brand: "God Freyhirst",
    colours: ["Soft Leather", "Kenya Blend", "Sun Dew", "Lotus Petal", "Claystone", "Sandrock", "Ice Grey", "Stone Pillar", "Steel Facade", "Seal"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Cool Charm",
    handle: "cool-charm",
    blurb: "Cool Charm is a solution dyed nylon carpet in a stylish cut pile twist style. Soft, resilient and durable, this is a neutral and affordable flooring o",
    brand: "God Freyhirst",
    colours: ["Braid", "Amulet Stipple", "Celtic Brown", "Tribal Stipple", "Porcelain", "Chalkstone", "Stone Pillar", "Atmosphere", "Andriod", "Stonewashed", "Steel Mesh", "Seal Fur"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Penny Lane",
    handle: "penny-lane",
    blurb: "Create a comfortable and stylish home with Penny Lane. This soft and affordable polyester cut pile twist carpet is well suited to low traffic areas. C",
    brand: "God Freyhirst",
    colours: ["Snow Blossom", "Ecru", "Sandalwood", "Vintage", "Hearthstone", "Calm Grey", "Dove", "Stone Stipple", "Suede", "Rhino", "Greystone", "Urban Stipple", "Tempest", "Android", "Onyx", "Cobalt"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Country Lane",
    handle: "country-lane",
    blurb: "Country Lane is a classic textured loop pile carpet that combines style and performance. This range is Declare LBC Red List Free and features five tim",
    brand: "God Freyhirst",
    colours: ["Fresh Linen", "Daisy", "Meadow", "Province", "Iron Gate"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Enchant",
    handle: "enchant",
    blurb: "Indulge in luxury with our exquisite 100% wool carpet, Enchant. Crafted for unparalleled comfort and durability, its plush texture and timeless design",
    brand: "God Freyhirst",
    colours: ["Raw Cotton", "Almond Beige", "Puddle", "Dusty Plain", "Woodland", "Pelaco", "Stonewashed", "Concrete", "Midnight Blue", "Greywacke"],
    finishes: ["Cut Pile", "Twist", "Plush"],
    sizes: [],
  },
  {
    name: "Elegant Reflections",
    handle: "elegant-reflections",
    blurb: "With a couple of stippled colours in the palette for added interest, Elegant Reflections is wonderfully soft and comfortable underfoot. Details Style:",
    brand: "God Freyhirst",
    colours: ["Brown Tweed", "Cargo Stipple", "Ironstone", "Shale Stipple", "Ceramic", "Sandrock", "Warm Beige", "Wind Spray", "Cloudy Day", "Cobblestone", "Cold Mountain", "Dark Shadow"],
    finishes: ["Cut Pile", "Twist", "Stipple"],
    sizes: [],
  },
  {
    name: "Apollo Ridge",
    handle: "apollo-ridge",
    blurb: "Apollo Ridge is a 100% Solution Dyed PET Polyester carpet, designed to created a comfortable and stylish home with affordability in mind. Its combinat",
    brand: "God Freyhirst",
    colours: ["Sandstone", "Vintage", "Silver Haze", "Mineral Stipple", "Slate", "Storm Grey", "Charcoal"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Regency Twist",
    handle: "regency-twist",
    blurb: "The soft wool fibres of Regency Twist provide luxury underfoot with its luxurious texture, adding elegance and warmth while elevating the overall ambi",
    brand: "God Freyhirst",
    colours: ["Almond", "Vintage Stone", "Linen", "Fur", "Montego", "Obelisk", "Steel", "Zinc", "Enchanted", "Cashmere"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Timeless",
    handle: "timeless",
    blurb: "Timeless is the perfect way to bring luxurious softness to any home interior. A cut pile twist carpet with a natural stony palette, it's exquisitely s",
    brand: "God Freyhirst",
    colours: ["Moonrock Stipple", "Fudge", "Oakheart Stipple", "Brushed Cotton", "Old Parchment", "Stone Beige", "Tan", "Barley", "Meadow", "Dawn", "Glacier Grey", "Light Shadow", "Urban Grey"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Venture",
    handle: "venture",
    blurb: "Venture is a solution dyed nylon carpet in a stylish cut pile twist style. Soft, resilient and durable, this neutral and affordable flooring option is",
    brand: "God Freyhirst",
    colours: ["Chamois", "Neutral", "Soft Leather", "Grey Haze", "Magma", "Paving", "Gravel", "Tundra"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Astra",
    handle: "astra",
    blurb: "Australian Made, versatile and stylish, Astra is an on-trend, chunky loop pile carpet that adds value to your home. Details Fibre : Polypropylene Carp",
    brand: "God Freyhirst",
    colours: ["Palatial", "Plateau", "Mirage", "Beyond", "Affinity", "Ornate"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Riviera",
    handle: "riviera",
    blurb: "Riviera is a versatile and affordable high low loop patterned carpet that is sure to add style and value to your home. Details Fibre : Polypropylene C",
    brand: "God Freyhirst",
    colours: ["Claystone", "Vapour", "Sea Fog", "Nimbus", "Masonry", "Gravel", "Storm Grey", "Gunmetal"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Callisto",
    handle: "callisto",
    blurb: "An economical flooring solution for the cost conscious buyer, this high low loop pile carpet is a great option for your first home or investment prope",
    brand: "God Freyhirst",
    colours: ["Light Brown", "Grey", "Charcoal", "Panther"],
    finishes: ["Level Loop", "Loop Pile"],
    sizes: [],
  },
  {
    name: "Campaspe",
    handle: "campaspe",
    blurb: "An economical flooring solution for the cost conscious buyer, this high low loop pile carpet is a great option for your first home or investment prope",
    brand: "God Freyhirst",
    colours: ["China Clay", "Mortar", "Glacial", "Siltstone", "Overcast", "Boulder", "Storm Grey", "Cinders"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Forest Park",
    handle: "forest-park",
    blurb: "Versatile and stylish, Forest Park is a textured loop carpet that is sure to add value to your home. Details Fibre : Polypropylene Carpet Brand: Yarn:",
    brand: "God Freyhirst",
    colours: ["Waterfall", "Sandstone", "Clay Stone", "Beacon", "Smoke", "Bedrock", "Cloud", "Forge"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Ovation",
    handle: "ovation",
    blurb: "Ovation is a versatile and affordable Textured Loop Pile carpet that is sure to add style and value to your home. Details Fibre : Polypropylene Carpet",
    brand: "God Freyhirst",
    colours: ["Doeskin", "Oyster", "Heron", "Pumice", "Woodland", "Folkstone", "Caviar", "Blacksmith"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Enforcer 4M",
    handle: "enforcer-4m",
    blurb: "An economical flooring solution for the cost conscious buyer, this high low loop pile carpet is a great option for your first home or investment prope",
    brand: "God Freyhirst",
    colours: ["Warmstone", "Windspray", "Smoke", "Lava", "Aggregate", "Basalt", "Mineral", "Monolith"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Odyssey",
    handle: "odyssey",
    blurb: "Odyssey seamlessly blends style with practicality, acting as a natural insulator for any living space. Beyond its captivating design, the inherent qua",
    brand: "God Freyhirst",
    colours: ["Argos", "Penelope", "Trojan", "Sparta", "Stella"],
    finishes: ["Cut Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Supreme Touch",
    handle: "supreme-touch",
    blurb: "Supreme Touch is a cut pile twist offering a natural colour palette of carpet colours from light sands to deep stones. As part of the Luxury collectio",
    brand: "God Freyhirst",
    colours: ["Mushroom Stipple", "Chestnut", "Boulder Stipple", "Fawn", "Sand Dune", "Quartz", "Stoneware", "Fog", "Abalone", "Silverado", "Concrete", "Beacon", "Winter Grey", "Dark Mood"],
    finishes: ["Cut Pile", "Twist", "Textured"],
    sizes: [],
  },
  {
    name: "Modern Texture",
    handle: "modern-texture",
    blurb: "With durability, stain and fade resistance, Modern Texture is a solution dyed nylon carpet that will last. Details Fibre : Solution Dyed Nylon Carpet ",
    brand: "God Freyhirst",
    colours: ["Ivory", "Bamboo", "Light Smoke", "Morning Fog", "Claystone", "Silver Drop", "Zinc", "Dark Granite"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Bayside",
    handle: "bayside",
    blurb: "Mixing comfort and durability, Bayside is a solution dyed nylon carpet, in a cut pile twist style. Feel peace of mind with this carpet’s resistance to",
    brand: "God Freyhirst",
    colours: ["Ivory Coast", "Beach Shell", "Canvas Wash", "Cork", "Tumbleweed", "Ghost Grey", "Overcast", "Mist", "Cloud", "Blue Fox", "Pewter", "Granite"],
    finishes: ["Cut Pile", "Twist", "Stipple"],
    sizes: [],
  },
  {
    name: "Fiesta",
    handle: "fiesta",
    blurb: "Fiesta is a practical solution dyed nylon carpet in a stylish cut pile twist style. Soft, resilient and durable, this is a great, affordable flooring ",
    brand: "God Freyhirst",
    colours: ["Earthston", "Mosaic", "Lanolin", "Chalk", "Amulet", "Agate", "Oyster", "Grey Haze", "Lexington", "Urban"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Refined Appeal",
    handle: "refined-appeal",
    blurb: "Refined Appeal is a solution dyed nylon carpet in a stylish cut pile twist construction. Soft, resilient and durable, this is a neutral and affordable",
    brand: "God Freyhirst",
    colours: ["Amulet Stipple", "Saddle Stipple", "Quartz", "Sand", "Soft Taupe", "Silver Mist", "Mushroom", "Pewter", "Dark Cloud", "Thunder", "Slate"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Kensington",
    handle: "kensington",
    blurb: "Kensington has a lush pile density and tailored finished to give you the look you want from less. Select from on-trend, neutral colours for an elegant",
    brand: "God Freyhirst",
    colours: ["Amulet Stipple", "Chalkstone", "Oyster", "Silver", "Grey Horizon", "Deep Grey", "Dark Matter"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Velvet Appeal",
    handle: "velvet-appeal",
    blurb: "Wake up to luxury every day with Velvet Appeal. Made in Australia from our incredibly soft triexta fibre, this carpet features permanent built-in stai",
    brand: "God Freyhirst",
    colours: ["Coconut", "Aged Paper", "Manuscript", "Sand Glass", "Harpe", "Alpaca", "Clean Vapour", "Ocean Air", "Silk Grey", "Silver Drop", "Frosty Touch", "Silverton", "Flooded Gum", "Soothing Grey", "Grey Concrete", "Tuscan Path", "Pond Pebble", "Grey Calm", "Night Horizon", "Metal Links", "Dark Whale", "Cornflower", "Stone Blue", "Green Crystal"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Winter Flair",
    handle: "winter-flair",
    blurb: "Perfect your interior vision with the incredibly stylish Winter Flair. Crafted from our extremely durable and stain resistant triexta fibre, this high",
    brand: "God Freyhirst",
    colours: ["Fawn Pink", "Powder White", "Cargo Beige", "Honey Glow", "Smoked Pearl", "Tapestry Beige", "Ash Grey", "Morning Grey", "Bedrock", "Dark Mushroom", "Charcoal", "Obsidian", "Blue Print", "Deep Sea", "Ocean View", "Everglades"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Luxury Appeal",
    handle: "luxury-appeal",
    blurb: "Indulge in luxuriously soft carpet every day with Luxury Appeal. Meticulously crafted in Australia from our extremely durable and stain resistant trie",
    brand: "God Freyhirst",
    colours: ["Cream Cloak", "Champagne", "Silk Paper", "Shortbread", "Stone House", "Bagel", "Elusion", "Grey Fog", "Urban Chic", "City Shadow", "Smoke Stack", "Stonehenge", "Stone Partition", "Tinsmith", "Blue Iris", "Mint Slice"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Unwind",
    handle: "unwind",
    blurb: "You can live worry-free with this soft, high-performing triexta carpet that is ideal for busy family households. With less time spent cleaning, you’ll",
    brand: "God Freyhirst",
    colours: ["Blush", "Pearl Blush", "Cottonseed", "Ambrosia", "Feldspar", "Red Engine", "Dahlia", "Tradewind", "Light Grey", "Grey Mood", "Steel", "Seal", "Tranquility", "Pewter", "Charcoal", "Wrought Iron", "Stormy Blue", "Cobalt", "Green Haze"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Royal Charm",
    handle: "royal-charm",
    blurb: "Made in Australia from our incredibly soft triexta fibre, this carpet features permanent built-in stain resistance and excellent durability. This luxu",
    brand: "God Freyhirst",
    colours: ["Dusky Pink", "White Feather", "Moonlight", "Biscotti", "Arctic Mist", "Glacier Grey", "Grey Haze", "Cloud Grey", "Grey Crystal", "Smoke", "Cool Grey", "Ash Grey", "Night Storm", "Sierra Night", "Dark Slate", "Dark Shadow", "Blue Charm", "Dark Denim"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Natural Artistry",
    handle: "natural-artistry",
    blurb: "Make a design statement with this stunning textured cut and loop carpet, Natural Artistry. This unique highlighted design is formed by the inimitable ",
    brand: "God Freyhirst",
    colours: ["Arctic", "Moon Shine", "Vintage", "Bazar", "Mist", "Mineral"],
    finishes: ["Loop Pile", "Cut & Loop", "Textured"],
    sizes: [],
  },
  {
    name: "Bellavista",
    handle: "bellavista",
    blurb: "Create your own beautiful interior view with Bellavista, a sumptuously soft wool carpet. A cut pile twist with random textured finish, the natural woo",
    brand: "God Freyhirst",
    colours: ["Bohemia", "Pebble Bay", "Murray River", "Satay", "Market Place", "Asteroid", "School Grey", "Pewter", "Deep Space", "Stone Age"],
    finishes: ["Cut Pile", "Twist", "Textured"],
    sizes: [],
  },
  {
    name: "Monte Bello",
    handle: "monte-bello",
    blurb: "Monte Bello is a supremly soft solution dyed nylon carpet. With colours inspired by nature's palette, this cut pile twist is one of the best carpets f",
    brand: "God Freyhirst",
    colours: ["Curlew", "Seagrass", "Cascade", "Limestone", "Channel", "Acacia", "Harbour", "Cove", "Mangrove", "Sheltered Bay", "Sea Eagle", "Mineral", "Oyster", "Dock"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Beaucastle",
    handle: "beaucastle",
    blurb: "Inspired by the hand-crafted rooftops of renaissance French chateaus, Beaucastle promises raw beauty and earthy charm. The patterned textured loop pil",
    brand: "God Freyhirst",
    colours: ["Timber", "Sandstone", "Asteroid", "Arctic Mist", "Woodash", "Sable"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Classic City",
    handle: "classic-city",
    blurb: "Classic City is a polyester cut pile twist carpet bringing comfort and practicality at an affordable price. Beautifully soft, this carpet is perfect f",
    brand: "God Freyhirst",
    colours: ["Rice Paper", "Amaretti", "Pebble Bay", "Hazelnut", "Bolero", "Drizzle", "Whisper", "Ashville", "Deep Grey", "Mouse Grey", "Cloud Stipple", "Grey Pebble", "Urban Grey", "Night Sky", "Lobelia"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Highbury Place",
    handle: "highbury-place",
    blurb: "Highbury Place has been designed to bring the perfect balance of comfort and durability to your floor. Wear, stain and fade resistance combines with s",
    brand: "God Freyhirst",
    colours: ["Bone Stipple", "Soft Petal", "Almond Milk", "Whisper Grey", "Flintstone", "Grey Haze", "Steel", "Classic Grey", "Dolomite", "Gothic Arch"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Murano",
    handle: "murano",
    blurb: "Just like its namesake, Murano, a new cloud soft carpet from Godfrey Hirst, honours the marriage of craftsmanship and innovation. Made in Australia fr",
    brand: "God Freyhirst",
    colours: ["Pendant", "Liquid Light", "Sculpture", "Glass Bowl", "Florentino", "Milk Glass", "Mirror", "Chandelier", "Smalto", "Palazzo", "Aventurine", "Furnace"],
    finishes: ["Cut Pile", "Twist", "Textured"],
    sizes: [],
  },
  {
    name: "Marylebone",
    handle: "marylebone",
    blurb: "Marylebone is a divinely soft and durable carpet that can handle the demands of a busy family home. This soft solution dyed nylon carpet is finished i",
    brand: "God Freyhirst",
    colours: ["West End", "Baker Street", "Portman Estate", "Westminster", "Spanish Place", "Nottingham Place", "Chandos House", "Upper Wimpole", "Cavendish Square", "Fitzrovia", "Tyburn", "Wigmore Hall"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Ravine 4M",
    handle: "ravine-4m",
    blurb: "A stunning and versatile range of carpet for all seasons, Ravine 4M will sustain luxurious comfort all year round. This textured loop pile carpet enha",
    brand: "God Freyhirst",
    colours: ["Oatmeal", "Crevice", "Cobblestone", "Stonewall", "Smokey Ash", "Fissure", "Pewter", "Tussock", "Stone Haze"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Pebble Grid 4M",
    handle: "pebble-grid-4m",
    blurb: "Our ever popular Pebble Grid is now available in a practical 4 metre width. Pebble Grid’s sophisticated latticed pattern draws the eye, creating an il",
    brand: "God Freyhirst",
    colours: ["Calcite", "Sandstone", "Gypsum", "Borax", "Fieldspace", "Kimberlite", "Shale", "Basalt", "Dolomite", "Bauxite"],
    finishes: ["Level Loop", "Loop Pile"],
    sizes: [],
  },
  {
    name: "Grand Luxury",
    handle: "grand-luxury",
    blurb: "Making a design statement has never been easier with magnificent Grand Luxury carpet. Created from gorgeous wool in a classic cut pile twist with subt",
    brand: "God Freyhirst",
    colours: ["Raw Cotton", "Almond Beige", "Savannah", "Dusty Plain", "Grainger", "Stonewashed", "Gun Metal", "Greywacke"],
    finishes: ["Polished", "Cut Pile", "Twist", "Textured"],
    sizes: [],
  },
  {
    name: "Montrose",
    handle: "montrose",
    blurb: "Montrose features a rustic chunky textured loop pile, creating a pebbled effect that adds handcrafted charm and character to contemporary living space",
    brand: "God Freyhirst",
    colours: ["Saratoga", "Gindera", "Mallard", "Borrowfield", "Del Mar", "Langley", "Belmont", "Rosehill"],
    finishes: ["Loop Pile", "Textured", "Rustic"],
    sizes: [],
  },
  {
    name: "Mystic Charm II",
    handle: "mystic-charm-ii",
    blurb: "Designed with durability in mind, Mystic Charm II by Godfrey Hirst is a cut pile twist that adds subtle texture to the floor. This Australian Made Sol",
    brand: "God Freyhirst",
    colours: ["Bone", "Canvas", "Mushroom", "Grey Haze", "Tin", "Battleship", "Metallic", "Sable", "Earthstone", "Dolomite"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Tranquil Texture",
    handle: "tranquil-texture",
    blurb: "Tranquil Texture, a stylish artisan wool carpet from Hycraft, takes inspiration from the places that bring us peace and happiness. The chunky textured",
    brand: "God Freyhirst",
    colours: ["Ocean Sand", "Mountain Ranges", "Tropical Oasis", "Springtime", "Summer Rain", "Country Retreat", "Lake House"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Luxury Living",
    handle: "luxury-living",
    blurb: "Encapsulating the hallmarks of an aspirational lifestyle, Luxury Living, a new, elegantly textured 100% wool carpet from Hycraft, teams quality, comfo",
    brand: "God Freyhirst",
    colours: ["Lavish", "Classic", "Sumptious", "Marble", "Ornate", "Modern", "Silhouette"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Carramar 4M",
    handle: "carramar-4m",
    blurb: "This luxury designer wool carpet delivers a superb modern foundation for contemporary styling. Crafted from beautiful wool, this 4 metre wide close te",
    brand: "God Freyhirst",
    colours: ["Sea Pearl", "Coastal Dune", "Buckwheat", "Avalanche", "Oyster Shell", "Dove Grey", "Winter Mist", "Evening Grey", "Coal Ash", "Aged Pewter", "Mulch", "Industrial Grey"],
    finishes: ["Level Loop", "Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Trinidad",
    handle: "trinidad",
    blurb: "Enjoy this beautiful textured level loop carpet. Trinidad is beautifully soft underfoot and the wool properties help to keep your space cooler in summ",
    brand: "God Freyhirst",
    colours: ["Matelot", "Maracas Bay", "La Brea"],
    finishes: ["Level Loop", "Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Beechmont",
    handle: "beechmont",
    blurb: "Settle in with Beechmont, a solution dyed nylon carpet, that combines durability and comfort. With a textured level loop design and a neutral colour r",
    brand: "God Freyhirst",
    colours: ["White Beech", "Scenic Rim", "Graceleigh Park", "Mountain Soil", "Nerang River"],
    finishes: ["Level Loop", "Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Queenstwist",
    handle: "queenstwist",
    blurb: "A stunning range of cut pile twist wool carpet for all seasons. Its twisted yarns create a textured surface, enhancing comfort and resilience. This ca",
    brand: "God Freyhirst",
    colours: ["Ecru", "Riversand", "Balsa Stone", "Jarrah", "Merbau", "Silver", "Dove Grey", "Zodiac", "Michelin", "Nightsky", "Musket"],
    finishes: ["Cut Pile", "Twist", "Textured"],
    sizes: [],
  },
  {
    name: "Winter Charm",
    handle: "winter-charm",
    blurb: "Sink your toes into sumptuously soft Winter Charm. With built-in stain protection from household spills and pet mishaps, as well as excellent durabili",
    brand: "God Freyhirst",
    colours: ["Pressed Rose", "Bleached Shell", "Sandy Day", "Beige Royal", "Papyrus", "Pebblestone", "Light Clay", "Vapour", "Silver Wheel", "Wood Ash", "City Grey", "Industrial Grey", "Coalmine", "Dolomite", "Seafront", "Fern"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Vintage Grace",
    handle: "vintage-grace",
    blurb: "Superbly crafted from wool and proudly Australian Made, Vintage Grace is a stunning new release from Hycraft. The rustic and highly textural chunky lo",
    brand: "God Freyhirst",
    colours: ["Tweed", "Suede", "Calico", "Pearl", "Taffeta", "Burlap", "Ticking", "Ebony"],
    finishes: ["Loop Pile", "Textured", "Rustic"],
    sizes: [],
  },
  {
    name: "Bridgeport",
    handle: "bridgeport",
    blurb: "Bridgeport offers a versatile palette to suit any décor with a range of on trend colours including beautiful neutrals and moody rich tones. This soft,",
    brand: "God Freyhirst",
    colours: ["Cloud", "Porcelain", "Surfmist", "Smokehaze", "Vapour", "Starling", "Mineral", "Steeple", "Truffle", "Carbon"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Capri",
    handle: "capri",
    blurb: "Evoking lush images of beauty and warmth, Capri, the densely luxuriant new carpet from Godfrey Hirst, adds style and comfort to every home. A cut pile",
    brand: "God Freyhirst",
    colours: ["Casa Rossa", "Sea Stacks", "Positano", "Limestone Crags", "Roman Villa", "Sea Ferry", "Piazzetta", "Amalfi Coast", "Sea Palace", "Marina Grande", "Peninsula", "Sorrento"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Inspirational",
    handle: "inspirational",
    blurb: "If you are looking for a wonderfully soft, dependable carpet then you have found it – meet Inspirational! This durable, soft and easy to clean triexta",
    brand: "God Freyhirst",
    colours: ["Deep Purple", "Dover White", "Birchwood", "Acorn", "Super Nova", "Cygnet", "Dove", "Glacier", "Limestone", "Cloudy Day", "Silver Berry", "Argent", "Sharkskin", "Dolphin", "Greystone", "Driftwood", "Arctic Grey", "Manatee", "Dark Grey", "Mica", "Dark Shadow", "Fresh Breeze", "Ice Blue", "Smokey Blue", "Deep Sky", "Blue Shadow", "Mountain Blue", "Ice Green", "Greendale", "Cameo"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Soft Sunrise",
    handle: "soft-sunrise",
    blurb: "If you are looking for a wonderfully soft yet practical carpet then look no further! Made in Australia, Soft Sunrise is durable and stain resistant tr",
    brand: "God Freyhirst",
    colours: ["Earthen", "Cloud", "Angora", "Sandshell", "Oatmeal", "Overcast", "Dove", "Stormy", "Canyon", "Vapour", "Haze", "Aluminium", "Alloy", "Summit", "Fog", "Fieldstone", "Cavern", "Cameo", "Lake", "Meadow"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Petra",
    handle: "petra",
    blurb: "Inspired by the hand-hewn caves and temples carved from ancient Jordanian desert sandstone, Petra promises raw beauty and earthy charm. The wool low-l",
    brand: "God Freyhirst",
    colours: ["Corinthian", "Damascus", "Bedouin", "Renaissance", "Obelisk", "Parapet", "Jordan", "Fortress"],
    finishes: ["Level Loop", "Loop Pile"],
    sizes: [],
  },
  {
    name: "Chatsworth",
    handle: "chatsworth",
    blurb: "Chatsworth is a beautiful chunky loop pile carpet in natural earthy tone shades, making it a focal point in your home. Made in Australia, its tactile ",
    brand: "God Freyhirst",
    colours: ["Talman", "Bakewell", "Devonshire", "Cavendish", "Shrewsbury", "Thompson", "Sir William", "Derwent", "Archer"],
    finishes: ["Level Loop", "Loop Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Otway Lodge",
    handle: "otway-lodge",
    blurb: "Otway Lodge is a solution dyed nylon carpet with a textured loop pile design. This carpet instantly provides a peaceful ambience to any room, with a l",
    brand: "God Freyhirst",
    colours: ["Cascade", "Beachside", "Haven", "Ocean View", "Lakeshore", "Kookaburra", "Riverbed", "Coastline", "Creek", "Koala", "Gorge"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Soft Glow",
    handle: "soft-glow",
    blurb: "Australian Made Soft Glow features permanent built-in stain resistance, excellent durability and it cleans with just water. This beautifully soft trie",
    brand: "God Freyhirst",
    colours: ["Luminous", "Serene", "Glimmer", "Radiance", "Dazzling", "Yoga", "Iridescent", "Lucent", "Shimmer", "Vivid", "Ablaze", "Karma", "Twinkle", "Sunrise", "Ray", "Nightlight"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Westpoint",
    handle: "westpoint",
    blurb: "Westpoint has been designed with durability in mind. This beautifully soft range comes in a wide colour palette that will add style and texture to you",
    brand: "God Freyhirst",
    colours: ["Lieutenant", "Union", "Colonial", "Officer", "Defence", "Cadet", "General", "Captain", "Academy", "Fort"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Pegasus",
    handle: "pegasus",
    blurb: "Pegasus seamlessly combines aesthetic appeal with functional excellence, serving as a natural insulator for any space. Beyond its visually striking de",
    brand: "God Freyhirst",
    colours: ["Orpheus", "Medusa", "Perseus", "Ares", "Zeus"],
    finishes: ["Cut Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Caribbean",
    handle: "caribbean",
    blurb: "Caribbean is a level loop wool carpet that provides style, durability and stain resistance to your floor. This level loop pile carpet's intricate desi",
    brand: "God Freyhirst",
    colours: ["Havana", "Bahamas", "Aruba", "San Juan", "Santiago"],
    finishes: ["Level Loop", "Loop Pile"],
    sizes: [],
  },
  {
    name: "Balmain",
    handle: "balmain",
    blurb: "Balmain is a solution dyed nylon carpet featuring a chunky loop pile design that brings both comfort and character to your space. Its distinctive text",
    brand: "God Freyhirst",
    colours: ["Beechwood", "Rye", "Lotus", "Pebble Bay", "Riversand", "Ashwood", "Boulevard", "Grey Beam"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Modern Appeal",
    handle: "modern-appeal",
    blurb: "Bring home timeless elegance with Modern Appeal, a beautifully soft carpet from Godfrey Hirst. Crafted from DuraTuft® Soft PET, this cut pile twist st",
    brand: "God Freyhirst",
    colours: ["Aesthetic", "Lifestyle", "Curated", "Contemporary", "Flawless", "Society", "Generational", "Sustainable", "Minimalist", "Nature", "Serene", "Effortless", "Cultural"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Serina",
    handle: "serina",
    blurb: "Bring home effortless comfort with Serina from Godfrey Hirst, a beautifully soft and durable carpet designed for modern Australian homes. Ideal for li",
    brand: "God Freyhirst",
    colours: ["505 Aesthetic", "506 Lifestyle", "510 Curated", "514 Contemporary", "542 Flawless", "715 Society", "718 Generational", "725 Sustainable", "736 Minimalist", "742 Nature", "750 Serene", "760 Effortless", "770 Cultural"],
    finishes: [],
    sizes: [],
  },
]
