/* Duratuft Carpet product detail data.

   Style, fibre, roll width, thickness, ratings and the descriptions come
   from the live capitaltiles.com.au feed for this collection. Generated —
   edit the source data, not this file.
*/

export const DURATUFT_PRODUCTS = [
  {
    handle: "serina",
    name: "Serina",
    brand: "Godfrey Hirst",
    card: "/img/duratuft/serina.jpg",
    images: [
      "/img/duratuft/serina/1.jpg",
      "/img/duratuft/serina/2.jpg",
      "/img/duratuft/serina/3.jpg",
      "/img/duratuft/serina/4.jpg",
      "/img/duratuft/serina/5.jpg",
      "/img/duratuft/serina/6.jpg",
      "/img/duratuft/serina/7.jpg",
      "/img/duratuft/serina/8.jpg",
      "/img/duratuft/serina/9.jpg",
      "/img/duratuft/serina/10.jpg",
      "/img/duratuft/serina/11.jpg",
      "/img/duratuft/serina/12.jpg",
      "/img/duratuft/serina/13.jpg",
      "/img/duratuft/serina/14.jpg",
    ],
    tagline: "Duratuft carpet in 13 colours",
    short: "Serina Duratuft carpet by Godfrey Hirst. 3.66m roll width and 13 colours. Supplied and laid across Canberra.",
    overview: [
      "Bring home effortless comfort with Serina from Godfrey Hirst, a beautifully soft and durable carpet designed for modern Australian homes. Ideal for living rooms, bedrooms and family spaces, Serina carpet is designed for relaxed, everyday living. Australian Made and stain and fade resistant, it delivers long-lasting performance, easy maintenance and timeless style, making it a practical and elegant choice for your home.",
      "Australian Made Declare Red List Free Wear Resistance Fade Resistance Mid Range Extra Soft 7 Year Premium Limited Residential Warranty",
    ],
    features: ["Australian Made", "Declare Red List Free", "Wear Resistance", "Fade Resistance", "Mid Range", "Extra Soft"],
    seoTitle: "Serina | Capital Tiles",
    seoDesc: "Serina, 13 colours. Duratuft carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "505 Aesthetic",
      "506 Lifestyle",
      "510 Curated",
      "514 Contemporary",
      "542 Flawless",
      "715 Society",
      "718 Generational",
      "725 Sustainable",
      "736 Minimalist",
      "742 Nature",
      "750 Serene",
      "760 Effortless",
      "770 Cultural",
    ],
    sizes: ["3.66m"],
    finishes: [],
    thickness: ["9 (+/-1.0)mm"],
    slip: [],
    material: ["DuraTuft Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "DuraTuft Carpet"],
      ["Yarn", "100% DuraTuft Soft SD P.E.T."],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "9 (+/-1.0)mm"],
      ["Pile Height", "7 (+/-1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "modern-appeal",
    name: "Modern Appeal",
    brand: "Godfrey Hirst",
    card: "/img/duratuft/modern-appeal.jpg",
    images: [
      "/img/duratuft/modern-appeal/1.jpg",
      "/img/duratuft/modern-appeal/2.jpg",
      "/img/duratuft/modern-appeal/3.jpg",
      "/img/duratuft/modern-appeal/4.jpg",
      "/img/duratuft/modern-appeal/5.jpg",
      "/img/duratuft/modern-appeal/6.jpg",
      "/img/duratuft/modern-appeal/7.jpg",
      "/img/duratuft/modern-appeal/8.jpg",
      "/img/duratuft/modern-appeal/9.jpg",
      "/img/duratuft/modern-appeal/10.jpg",
      "/img/duratuft/modern-appeal/11.jpg",
      "/img/duratuft/modern-appeal/12.jpg",
      "/img/duratuft/modern-appeal/13.jpg",
      "/img/duratuft/modern-appeal/14.jpg",
    ],
    tagline: "Duratuft carpet in 13 colours",
    short: "Modern Appeal Duratuft carpet by Godfrey Hirst. 3.66m roll width and 13 colours. Supplied and laid across Canberra.",
    overview: [
      "Bring home timeless elegance with Modern Appeal, a beautifully soft carpet from Godfrey Hirst. Crafted from DuraTuft® Soft PET, this cut pile twist style invites you to relax into its gentle texture, with light-reflecting fibres that add depth and warmth to your space. Designed for everyday comfort and calm, Modern Appeal softens both the look and feel of your home. Australian Made and stain and fade resistant, it offers a practical touch of indulgence — proving that luxury can be both affordable and lasting.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs 5 Star Contract Light Duty - 1 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty^ Wear Resistance Fade Resistance Mid Range Extra Soft",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs 5 Star",
      "Contract Light Duty - 1 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty^",
    ],
    seoTitle: "Modern Appeal | Capital Tiles",
    seoDesc: "Modern Appeal, 13 colours. Duratuft carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Aesthetic",
      "Lifestyle",
      "Curated",
      "Contemporary",
      "Flawless",
      "Society",
      "Generational",
      "Sustainable",
      "Minimalist",
      "Nature",
      "Serene",
      "Effortless",
      "Cultural",
    ],
    sizes: ["3.66m"],
    finishes: [],
    thickness: ["12 (+/-1.0)mm"],
    slip: [],
    material: ["DuraTuft Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "DuraTuft Carpet"],
      ["Yarn", "100% DuraTuft Soft SD P.E.T."],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "12 (+/-1.0)mm"],
      ["Pile Height", "10 (+/-1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "13"],
    ],
    rooms: [],
  },
  {
    handle: "capri",
    name: "Capri",
    brand: "Godfrey Hirst",
    card: "/img/duratuft/capri.jpg",
    images: [
      "/img/duratuft/capri/1.jpg",
      "/img/duratuft/capri/2.jpg",
      "/img/duratuft/capri/3.jpg",
      "/img/duratuft/capri/4.jpg",
      "/img/duratuft/capri/5.jpg",
      "/img/duratuft/capri/6.jpg",
      "/img/duratuft/capri/7.jpg",
      "/img/duratuft/capri/8.jpg",
      "/img/duratuft/capri/9.jpg",
      "/img/duratuft/capri/10.jpg",
      "/img/duratuft/capri/11.jpg",
      "/img/duratuft/capri/12.jpg",
      "/img/duratuft/capri/13.jpg",
    ],
    tagline: "Duratuft carpet in 12 colours",
    short: "Capri Duratuft carpet by Godfrey Hirst. 3.66m roll width and 12 colours. Supplied and laid across Canberra.",
    overview: [
      "Evoking lush images of beauty and warmth, Capri, the densely luxuriant new carpet from Godfrey Hirst, adds style and comfort to every home. A cut pile twist with light reflecting contrast, Capri is crafted from DuraTuft Soft PET, an advanced carpet fibre boasting an ACCS Residential Extra Heavy Duty 5 star rating that's ideal for high traffic spaces and stairs. Stain, fade and wear resistant, the softly textural surface also helps to insulate against household noise. Styling a home interior with this exceptionally performing Australian Made carpet, is an accessible luxury.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Wear Resistance Fade Resistance Mid Range Extra Soft",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Capri | Capital Tiles",
    seoDesc: "Capri, 12 colours. Duratuft carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Casa Rossa",
      "Sea Stacks",
      "Positano",
      "Limestone Crags",
      "Roman Villa",
      "Sea Ferry",
      "Piazzetta",
      "Amalfi Coast",
      "Sea Palace",
      "Marina Grande",
      "Peninsula",
      "Sorrento",
    ],
    sizes: ["3.66m"],
    finishes: [],
    thickness: ["16 (+/-1.0)mm"],
    slip: [],
    material: ["DuraTuft Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "DuraTuft Carpet"],
      ["Yarn", "100% DuraTuft Soft SD P.E.T."],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "16 (+/-1.0)mm"],
      ["Pile Height", "14 (+/-1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "12"],
    ],
    rooms: [],
  },
  {
    handle: "murano",
    name: "Murano",
    brand: "Godfrey Hirst",
    card: "/img/duratuft/murano.jpg",
    images: [
      "/img/duratuft/murano/1.jpg",
      "/img/duratuft/murano/2.jpg",
      "/img/duratuft/murano/3.jpg",
      "/img/duratuft/murano/4.jpg",
      "/img/duratuft/murano/5.jpg",
      "/img/duratuft/murano/6.jpg",
      "/img/duratuft/murano/7.jpg",
      "/img/duratuft/murano/8.jpg",
      "/img/duratuft/murano/9.jpg",
      "/img/duratuft/murano/10.jpg",
      "/img/duratuft/murano/11.jpg",
      "/img/duratuft/murano/12.jpg",
    ],
    tagline: "Duratuft carpet in 12 colours",
    short: "Murano Duratuft carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 12 colours. Supplied and laid across Canberra.",
    overview: [
      "Just like its namesake, Murano, a new cloud soft carpet from Godfrey Hirst, honours the marriage of craftsmanship and innovation. Made in Australia from DuraTuft Soft PET, this twisted cut pile carpet comes with a Residential Extra Heavy Duty 5 star rating, delivering a durable, textured finish perfect for busy living areas. Complete with stain and fade resistance , the artistry of Murano rests on its combination of high performance and smooth, cushiony underfoot feel to create a premium flooring product.",
      "Godfrey Hirst Best Seller Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Wear Resistance Fade Resistance Mid Range Extra Soft",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
    ],
    seoTitle: "Murano | Capital Tiles",
    seoDesc: "Murano, Cut Pile Twist, 12 colours. Duratuft carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Pendant",
      "Liquid Light",
      "Sculpture",
      "Glass Bowl",
      "Florentino",
      "Milk Glass",
      "Mirror",
      "Chandelier",
      "Smalto",
      "Palazzo",
      "Aventurine",
      "Furnace",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["DuraTuft Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "DuraTuft Carpet"],
      ["Yarn", "100% DuraTuft Soft SD P.E.T."],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "12 (+/-1.0)mm"],
      ["Pile Height", "10 (+/-1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "12"],
    ],
    rooms: [],
  },
  {
    handle: "highbury-place",
    name: "Highbury Place",
    brand: "Godfrey Hirst",
    card: "/img/duratuft/highbury-place.jpg",
    images: [
      "/img/duratuft/highbury-place/1.jpg",
      "/img/duratuft/highbury-place/2.jpg",
      "/img/duratuft/highbury-place/3.jpg",
      "/img/duratuft/highbury-place/4.jpg",
      "/img/duratuft/highbury-place/5.jpg",
      "/img/duratuft/highbury-place/6.jpg",
      "/img/duratuft/highbury-place/7.jpg",
      "/img/duratuft/highbury-place/8.jpg",
      "/img/duratuft/highbury-place/9.jpg",
      "/img/duratuft/highbury-place/10.jpg",
    ],
    tagline: "Duratuft carpet in 10 colours",
    short: "Highbury Place Duratuft carpet by Godfrey Hirst. 3.66m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Highbury Place has been designed to bring the perfect balance of comfort and durability to your floor. Wear, stain and fade resistance combines with softness for a practical and stylish carpet.",
      "Godfrey Hirst Best Seller Australian Made 10 Year Standard Limited Residential Warranty* Wear Resistance Fade Resistance Mid Range",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "10 Year Standard Limited Residential Warranty*",
      "Wear Resistance",
      "Fade Resistance",
      "Mid Range",
    ],
    seoTitle: "Highbury Place | Capital Tiles",
    seoDesc: "Highbury Place, 10 colours. Duratuft carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Bone Stipple",
      "Soft Petal",
      "Almond Milk",
      "Whisper Grey",
      "Flintstone",
      "Grey Haze",
      "Steel",
      "Classic Grey",
      "Dolomite",
      "Gothic Arch",
    ],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["DuraTuft Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "DuraTuft Carpet"],
      ["Yarn", "100% DuraTuft SD P.E.T."],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "11.5 (+/- 1.0)mm"],
      ["Pile Height", "9.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "kensington",
    name: "Kensington",
    brand: "Godfrey Hirst",
    card: "/img/duratuft/kensington.jpg",
    images: [
      "/img/duratuft/kensington/1.jpg",
      "/img/duratuft/kensington/2.jpg",
      "/img/duratuft/kensington/3.jpg",
      "/img/duratuft/kensington/4.jpg",
      "/img/duratuft/kensington/5.jpg",
      "/img/duratuft/kensington/6.jpg",
    ],
    tagline: "Duratuft carpet in 7 colours",
    short: "Kensington Duratuft carpet by Godfrey Hirst. 3.66m roll width and 7 colours. Supplied and laid across Canberra.",
    overview: [
      "Kensington has a lush pile density and tailored finished to give you the look you want from less. Select from on-trend, neutral colours for an elegant carpet that will suit your home for many years to come.",
      "Australian Made Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Premium Limited Residential Warranty* Wear Resistance Fade Resistance Mid Range",
    ],
    features: [
      "Australian Made",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Premium Limited Residential Warranty*",
      "Wear Resistance",
    ],
    seoTitle: "Kensington | Capital Tiles",
    seoDesc: "Kensington, 7 colours. Duratuft carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Amulet Stipple", "Chalkstone", "Oyster", "Silver", "Grey Horizon", "Deep Grey", "Dark Matter"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["DuraTuft Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "DuraTuft Carpet"],
      ["Yarn", "100% DuraTuft SD P.E.T."],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "15.5 (+/- 1.0)mm"],
      ["Pile Height", "13.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "7"],
    ],
    rooms: [],
  },
]

export function byHandle(handle) {
  return DURATUFT_PRODUCTS.find((p) => p.handle === handle)
}
