/* Engineered Timber product detail data.

   Specs, colours, sizes and the descriptions come from the live
   capitaltiles.com.au feed for this collection. Generated — edit the
   source data, not this file.
*/

export const ENGINEERED_TIMBER_PRODUCTS = [
  {
    handle: "scenic-rim-12mm",
    name: "Scenic Rim 12mm",
    brand: "National Flooring Distributors",
    card: "/img/timber/scenic-rim-12mm.jpg",
    images: [
      "/img/timber/scenic-rim-12mm/1.jpg",
      "/img/timber/scenic-rim-12mm/2.jpg",
      "/img/timber/scenic-rim-12mm/3.jpg",
      "/img/timber/scenic-rim-12mm/4.jpg",
      "/img/timber/scenic-rim-12mm/5.jpg",
      "/img/timber/scenic-rim-12mm/6.jpg",
      "/img/timber/scenic-rim-12mm/7.jpg",
      "/img/timber/scenic-rim-12mm/8.jpg",
    ],
    tagline: "Engineered timber flooring in 8 colours",
    short: "Scenic Rim 12mm engineered timber flooring by National Flooring Distributors. 190mm x 1900mm planks, 12mm thick and 8 colours. Supplied and installed across Canberra.",
    overview: [
      "Scenic Rim engineered timber flooring offers the perfect balance of elegance and durability. Featuring a cross-laminated core for enhanced stability, each plank is finished with seven layers of premium German Treffert Lacquer for lasting protection.",
      "Available in eight stunning European Oak veneers, this collection brings warmth, character, and sophistication to any space.",
    ],
    features: [
      "Plank size: 190mm x 1900mm",
      "Thickness: 12mm",
      "Wear layer: 1.2mm",
      "Surface: Brushed",
      "8 colours in the range",
      "Full boards on display in the Mitchell showroom",
    ],
    seoTitle: "Scenic Rim 12mm | Capital Tiles",
    seoDesc: "Scenic Rim 12mm, 190mm x 1900mm, 12mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Almond Oak 722",
      "Danish Oak 708",
      "Harvest Oak 706",
      "Milky Oak 711",
      "Mocha 721",
      "Pale Oak 701",
      "Revlon Oak 705",
      "Vintage Oak 703",
    ],
    sizes: ["190mm x 1900mm"],
    finishes: ["Brushed"],
    thickness: ["12mm"],
    slip: [],
    material: ["1.2mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Plank Size", "190mm x 1900mm"],
      ["Total Thickness", "12mm"],
      ["VENEER THICKNESS", "1.2mm"],
      ["SURFACE", "Brushed"],
      ["QTY PER CARTON", "8 Planks"],
      ["AREA PER CARTON", "2.09m²"],
      ["CLICK SYSTEM", "Uniclic"],
    ],
    rooms: [],
  },
  {
    handle: "daintree-xl-15mm",
    name: "Daintree XL 15mm",
    brand: "National Flooring Distributors",
    card: "/img/timber/daintree-xl-15mm.jpg",
    images: [
      "/img/timber/daintree-xl-15mm/1.jpg",
      "/img/timber/daintree-xl-15mm/2.jpg",
      "/img/timber/daintree-xl-15mm/3.jpg",
    ],
    tagline: "Engineered timber flooring in 3 colours",
    short: "Daintree XL 15mm engineered timber flooring by National Flooring Distributors. 190mm x 1900mm planks, 15mm thick and 3 colours. Supplied and installed across Canberra.",
    overview: [
      "Elevate your space with the grandeur of Daintree XL Engineered Timber. Designed with extra-large planks for a more expansive and seamless look, this premium flooring solution brings the timeless beauty of real timber to modern interiors.",
      "Crafted for both style and durability, Daintree XL offers a refined natural aesthetic while delivering superior resilience to withstand daily life. The wide, long planks create a sophisticated flow, making them ideal for open-plan homes, commercial spaces, and high-end retail environments.",
      "With a resilient, low-maintenance surface, Daintree XL ensures lasting beauty with minimal effort, allowing you to enjoy luxurious timber flooring without compromise.",
    ],
    features: [
      "Eco Friendly",
      "Durable",
      "Family Friendly",
      "Recoating Approved",
      "Sawn Quality Veneer",
      "Real Timber Unlimited Pattern Repeat",
    ],
    seoTitle: "Daintree XL 15mm | Capital Tiles",
    seoDesc: "Daintree XL 15mm, 190mm x 1900mm, 15mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: ["Blackbutt", "Spotted Gum", "Tasmanian Oak"],
    sizes: ["190mm x 1900mm"],
    finishes: ["Brushed"],
    thickness: ["15mm"],
    slip: [],
    material: ["2mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Plank Size", "190mm x 1900mm"],
      ["Total Thickness", "15mm"],
      ["VENEER THICKNESS", "2mm"],
      ["SURFACE", "Brushed"],
      ["QTY PER CARTON", "6 Planks"],
      ["AREA PER CARTON", "2.166m²"],
      ["CLICK SYSTEM", "5G or T&G"],
    ],
    rooms: [],
  },
  {
    handle: "eternity-european-oaks-14mm",
    name: "Eternity - European Oaks 14mm",
    brand: "National Flooring Distributors",
    card: "/img/timber/eternity-european-oaks-14mm.jpg",
    images: [
      "/img/timber/eternity-european-oaks-14mm/1.jpg",
      "/img/timber/eternity-european-oaks-14mm/2.jpg",
      "/img/timber/eternity-european-oaks-14mm/3.jpg",
      "/img/timber/eternity-european-oaks-14mm/4.jpg",
      "/img/timber/eternity-european-oaks-14mm/5.jpg",
      "/img/timber/eternity-european-oaks-14mm/6.jpg",
      "/img/timber/eternity-european-oaks-14mm/7.jpg",
      "/img/timber/eternity-european-oaks-14mm/8.jpg",
      "/img/timber/eternity-european-oaks-14mm/9.jpg",
      "/img/timber/eternity-european-oaks-14mm/10.jpg",
    ],
    tagline: "Engineered timber flooring in 10 colours",
    short: "Eternity - European Oaks 14mm engineered timber flooring by National Flooring Distributors. 190mm x 1900mm planks, 14mm thick and 10 colours. Supplied and installed across Canberra.",
    overview: [
      "Transform your space with the premium look and feel of Eternity European Oaks Engineered Timber flooring. Combining the natural elegance of real timber with a cross-laminated core for enhanced strength and stability, Eternity is built to last.",
      "Available in 10 nature-inspired colours, it's the perfect way to add timeless sophistication to any interior.",
    ],
    features: [
      "9 Coats German Technology Coating",
      "European Oak Quality",
      "Pet & Family Friendly",
      "Real Timber Unlimited Pattern",
      "Durable",
      "Water Resistant",
    ],
    seoTitle: "Eternity - European Oaks 14mm | Capital Tiles",
    seoDesc: "Eternity - European Oaks 14mm, 190mm x 1900mm, 14mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Beachwood 811",
      "Blonde Oak 808",
      "Cashew Oak 803",
      "Celtic Snow 801",
      "Chestnut 804",
      "Chocolate Oak 809",
      "Fawn Oak 805",
      "Haven 807",
      "Natural Oak 806",
      "River Oak 802",
    ],
    sizes: ["190mm x 1900mm"],
    finishes: [],
    thickness: ["14mm"],
    slip: ["P3"],
    material: ["3mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Plank Size", "190mm x 1900mm"],
      ["Total Thickness", "14mm"],
      ["VENEER THICKNESS", "3mm"],
      ["SLIP RATING", "P3"],
      ["QTY PER CARTON", "6 Planks"],
      ["M 2 PER CARTON", "2.166m²"],
      ["SURFACE FINISH", "Brushed"],
      ["QTY PER CARTON", "6 Planks"],
    ],
    rooms: [],
  },
  {
    handle: "daintree-15mm",
    name: "Daintree 15mm",
    brand: "National Flooring Distributors",
    card: "/img/timber/daintree-15mm.jpg",
    images: [
      "/img/timber/daintree-15mm/1.jpg",
      "/img/timber/daintree-15mm/2.jpg",
      "/img/timber/daintree-15mm/3.jpg",
    ],
    tagline: "Engineered timber flooring in 3 colours",
    short: "Daintree 15mm engineered timber flooring by National Flooring Distributors. 136mm x 1900mm planks, 15mm thick and 3 colours. Supplied and installed across Canberra.",
    overview: [
      "Embrace the warmth of nature with Daintree, our premium engineered timber collection designed to bring comfort and timeless beauty to any space. Featuring natural wood textures and rich tones, Daintree creates an inviting atmosphere.",
      "Perfect for both homes and commercial spaces that value style and functionality, Daintree offers a seamless blend of charm and strength.",
    ],
    features: [
      "Pet + Family Friendly",
      "Durable",
      "Easy to Clean",
      "Water Resistant",
      "Real Timber Unlimited Pattern Repeat",
      "20 yrs Residential & 5 yrs Commercial Warranty",
    ],
    seoTitle: "Daintree 15mm | Capital Tiles",
    seoDesc: "Daintree 15mm, 136mm x 1900mm, 15mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: ["Blackbutt", "Spotted Gum", "Tasmanian Oak"],
    sizes: ["136mm x 1900mm"],
    finishes: ["Brushed"],
    thickness: ["15mm"],
    slip: [],
    material: ["2mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Plank Size", "136mm x 1900mm"],
      ["Total Thickness", "15mm"],
      ["VENEER THICKNESS", "2mm"],
      ["SURFACE", "Brushed"],
      ["QTY PER CARTON", "6 Planks"],
      ["AREA PER CARTON", "2.06m²"],
      ["CLICK SYSTEM", "5G or T&G"],
    ],
    rooms: [],
  },
  {
    handle: "rustic-blackbutt",
    name: "Rustic Blackbutt",
    brand: "Capital Tiles",
    card: "/img/timber/rustic-blackbutt.jpg",
    images: ["/img/timber/rustic-blackbutt/1.jpg", "/img/timber/rustic-blackbutt/2.jpg"],
    tagline: "Engineered timber flooring in 1845 x 194 x 12 mm",
    short: "Rustic Blackbutt engineered timber flooring. 1845 x 194 x 12 mm planks. Supplied and installed across Canberra.",
    overview: [
      "Bring the timeless charm of Australian hardwood into your home with Rustic Blackbutt laminate planks. Expertly designed for modern living, this flooring combines authentic timber tones with advanced performance features, including 72-hour water resistance, a durable AC5-rated surface finish, and integrated acoustic protection for a quieter environment. The Licensed Click System ensures a fast, hassle-free installation, while 4 Sided Micro Bevel edges create a realistic plank look across interiors.",
    ],
    features: [
      "Plank size: 1845 x 194 x 12 mm",
      "Surface: AC5 Surface Finish",
      "Slip rating: P3",
      "Full boards on display in the Mitchell showroom",
    ],
    seoTitle: "Rustic Blackbutt | Capital Tiles",
    seoDesc: "Rustic Blackbutt, 1845 x 194 x 12 mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [],
    sizes: ["1845 x 194 x 12 mm"],
    finishes: ["AC5 Surface Finish"],
    thickness: [],
    slip: ["P3"],
    material: [],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Dimension", "1845 x 194 x 12 mm"],
      ["Surface Finish", "AC5"],
      ["Edges", "4 Sided Micro Bevel"],
      ["Joining System", "Licensed Click System"],
      ["Water Resistance", "72 Hours"],
      ["Slip Resistance", "P3"],
      ["CHF Value", "–"],
      ["Smoke Value", "–"],
      ["Pack Size", "1.7897 m² (5 Boards)"],
      ["Weight", "18.5 kg"],
    ],
    rooms: [],
  },
  {
    handle: "cream-oak",
    name: "Cream Oak",
    brand: "Capital Tiles",
    card: "/img/timber/cream-oak.jpg",
    images: ["/img/timber/cream-oak/1.jpg", "/img/timber/cream-oak/2.jpg"],
    tagline: "Engineered timber flooring in 1516 x 238 x 12 mm",
    short: "Cream Oak engineered timber flooring. 1516 x 238 x 12 mm planks. Supplied and installed across Canberra.",
    overview: [
      "The Cream Oak laminate plank delivers a soft, neutral timber look that enhances both contemporary and classic interiors. Built for everyday living, this flooring offers 48-hour water resistance, a durable AC4 surface finish, and built-in acoustic properties for a quieter, more comfortable home. Featuring the Licensed Click System and 4 Sided Micro Bevel edges, installation is seamless and planks lock tightly for a natural timber aesthetic in any room.",
    ],
    features: [
      "48-hour water resistance – protection against spills and splashes in kitchens, living areas.",
      "Soft, neutral oak tone – complements a wide range of interior styles and furnishings.",
      "AC4 surface finish – durable enough for everyday wear in busy households.",
      "Licensed Click System – fast, glue-free installation.",
      "P3 slip resistance – safe for residential and light commercial spaces.",
      "4 Sided Micro Bevel edges – authentic timber plank definition.",
    ],
    seoTitle: "Cream Oak | Capital Tiles",
    seoDesc: "Cream Oak, 1516 x 238 x 12 mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [],
    sizes: ["1516 x 238 x 12 mm"],
    finishes: ["AC4 Surface Finish"],
    thickness: [],
    slip: ["P3"],
    material: [],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Dimension", "1516 x 238 x 12 mm"],
      ["Surface Finish", "AC4"],
      ["Edges", "4 Sided Micro Bevel"],
      ["Joining System", "Licensed Click System"],
      ["Water Resistance", "48 Hours"],
      ["Slip Resistance", "P3"],
      ["CHF Value", "6.1 kW/m²"],
      ["Smoke Value", "4 %.min"],
      ["Pack Size", "2.1648 m² (6 Boards)"],
      ["Weight", "21.8 kg"],
    ],
    rooms: [],
  },
  {
    handle: "spotted-gum",
    name: "Spotted Gum",
    brand: "Capital Tiles",
    card: "/img/timber/spotted-gum.jpg",
    images: [
      "/img/timber/spotted-gum/1.jpg",
      "/img/timber/spotted-gum/2.jpg",
      "/img/timber/spotted-gum/3.jpg",
      "/img/timber/spotted-gum/4.jpg",
      "/img/timber/spotted-gum/5.jpg",
    ],
    tagline: "Engineered timber flooring in 1516 x 238 x 12 mm",
    short: "Spotted Gum engineered timber flooring. 1516 x 238 x 12 mm planks and a – wear layer. Supplied and installed across Canberra.",
    overview: [
      "The Spotted Gum collection brings the rich, earthy character of native Australian hardwood into contemporary homes. Designed for family living, this hybrid and engineered timber flooring range delivers waterproof performance for everyday spills, exceptional acoustic comfort, and a warm, authentic timber aesthetic. Installation is effortless with the Licensed Click System, making it ideal for kitchens, living areas, and bedrooms in both Canberra and nearby Queanbeyan and Yass residences.",
      "With a focus on durability and low maintenance, Spotted Gum flooring provides a stylish solution for modern interiors while supporting busy households. The natural grain patterns, brushed UV lacquer finish, and P3 slip rating make it a practical yet visually stunning choice for high-traffic areas.",
    ],
    features: [
      "Available in laminate & hybrid formats – choose the perfect fit for your Canberra home.",
      "Waterproof performance – ideal for kitchens, living areas, and open-plan family spaces.",
      "Exceptional durability – AC4 laminate or UV-coated hybrid surface for long-lasting wear.",
      "Licensed Click System – fast, glue-free installation suitable for Tuggeranong and Queanbeyan.",
      "Acoustic benefits – built-in hybrid underlay reduces noise for quiet, comfortable interiors.",
      "Slip resistance up to P4 – safe for residential use, including busy family living areas.",
    ],
    seoTitle: "Spotted Gum | Capital Tiles",
    seoDesc: "Spotted Gum, 1516 x 238 x 12 mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [],
    sizes: ["1516 x 238 x 12 mm", "1800 x 228 x 9 mm"],
    finishes: ["AC4 Brushed", "UV Coating"],
    thickness: [],
    slip: ["P3", "P4"],
    material: ["– top layer"],
    specCols: ["Specification", "Laminate", "Hybrid"],
    specRows: [
      ["Dimension", "1516 x 238 x 12 mm", "1800 x 228 x 9 mm"],
      ["Surface Finish", "AC4 Brushed", "UV Coating"],
      ["Top Layer", "–", "0.5 mm European Oak"],
      ["Built-In Underlay", "–", "2 mm"],
      ["Edges", "4 Sided Micro Bevel", "–"],
      ["Joining System", "Licensed Click System", "Licensed Click System"],
      ["Water Resistance", "48 Hours", "–"],
      ["Slip Resistance", "P3", "P4"],
      ["CHF Value", "6.1 kW/m²", "–"],
      ["Smoke Value", "4 %.min", "–"],
      ["Acoustic Rating", "–", "L'nT,w: 36"],
      ["Pack Size", "2.1648 m² (6 Boards)", "1.6416 m² (4 Boards)"],
      ["Weight", "21.8 kg", "24 kg"],
    ],
    rooms: [],
  },
  {
    handle: "lime-wash",
    name: "Lime Wash",
    brand: "Capital Tiles",
    card: "/img/timber/lime-wash.jpg",
    images: [
      "/img/timber/lime-wash/1.jpg",
      "/img/timber/lime-wash/2.jpg",
      "/img/timber/lime-wash/3.jpg",
      "/img/timber/lime-wash/4.jpg",
      "/img/timber/lime-wash/5.jpg",
    ],
    tagline: "Engineered timber flooring in 1900 x 190 x 14 mm",
    short: "Lime Wash engineered timber flooring. 1900 x 190 x 14 mm planks and a 2 mm european oak wear layer. Supplied and installed across Canberra.",
    overview: [
      "The Lime Wash collection combines the calming elegance of a soft whitewashed European oak veneer with the practical benefits of engineered timber. Designed for family living, this flooring is water-resistant for everyday spills and features a built-in acoustic layer for quiet, comfortable spaces. Perfect for kitchens, living rooms, bedrooms, and open-plan interiors, Lime Wash enhances homes.",
      "Note: Always check samples in your intended space before installation to ensure finish and colour selection meet your design goals.",
    ],
    features: [
      "Natural European Oak veneer – 2 mm top layer for authentic timber appearance.",
      "Water-resistant core – ideal for everyday spills in busy households.",
      "Brushed UV lacquer finish – protects against wear, fading, and stains.",
      "Built-in acoustic layer – provides warmth underfoot and noise reduction.",
      "Flexible installation – supports both floating and direct stick methods.",
      "Tongue & Groove system – ensures tight, secure joints.",
    ],
    seoTitle: "Lime Wash | Capital Tiles",
    seoDesc: "Lime Wash, 1900 x 190 x 14 mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [],
    sizes: ["1900 x 190 x 14 mm"],
    finishes: ["Brushed UV Lacquer"],
    thickness: [],
    slip: ["P3"],
    material: ["2 mm European Oak top layer"],
    specCols: ["Specification", "Lime Wash"],
    specRows: [
      ["Dimension", "1900 x 190 x 14 mm"],
      ["Top Layer", "2 mm European Oak"],
      ["Surface Finish", "Brushed UV Lacquer"],
      ["Edges", "4 Sided Micro Bevel"],
      ["Joining System", "Tongue & Groove"],
      ["Moisture Content", "8–12%"],
      ["Installation Method", "Floating / Direct Stick"],
      ["Slip Resistance", "P3"],
      ["CHF Value", "4.1 kW/m²"],
      ["Smoke Value", "44 %.min"],
      ["Pack Size", "2.888 m² (8 Boards, 26 kg) / 2.166 m² (6 Boards, 20.5 kg)"],
      ["Nesting", "<25% Random Short Boards"],
    ],
    rooms: [],
  },
  {
    handle: "classic-oak",
    name: "Classic Oak",
    brand: "Capital Tiles",
    card: "/img/timber/classic-oak.jpg",
    images: ["/img/timber/classic-oak/1.jpg", "/img/timber/classic-oak/2.jpg", "/img/timber/classic-oak/3.jpg"],
    tagline: "Engineered timber flooring in 1900 x 190 x 14 mm",
    short: "Classic Oak engineered timber flooring. 1900 x 190 x 14 mm planks and a 2 mm european oak wear layer. Supplied and installed across Canberra.",
    overview: [
      "Classic Oak engineered timber flooring brings the warmth of natural oak together with the durability of today's construction technology. With a brushed UV lacquer finish that highlights the natural grain and a water-resistant core, it's designed for timeless appeal and everyday practicality. Perfect for family homes, Classic Oak delivers enduring charm and comfort to kitchens, hallways, living areas and open-plan spaces.",
      "With acoustic comfort built-in, this flooring reduces noise for quieter living, while the floating or direct stick installation methods provide flexibility across a range of subfloors. Classic Oak combines traditional style with dependable performance for long-lasting results in both residential and light commercial settings.",
    ],
    features: [
      "Natural oak timber – authentic texture with a warm, classic tone.",
      "Brushed UV lacquer finish – durable and low-maintenance surface.",
      "Water-resistant core – ideal for kitchens, hallways and living spaces.",
      "Acoustic comfort – reduces footfall noise for quieter homes.",
      "Flexible installation – floating or direct stick methods to suit your project.",
      "Tongue & groove system – reliable and secure plank connection.",
    ],
    seoTitle: "Classic Oak | Capital Tiles",
    seoDesc: "Classic Oak, 1900 x 190 x 14 mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [],
    sizes: ["1900 x 190 x 14 mm"],
    finishes: ["Brushed UV Lacquer"],
    thickness: [],
    slip: ["P3"],
    material: ["2 mm European Oak top layer"],
    specCols: ["Attribute", "Classic Oak"],
    specRows: [
      ["Timber Grade", "Natural"],
      ["Dimension", "1900 x 190 x 14 mm"],
      ["Top Layer", "2 mm European Oak"],
      ["Surface Finish", "Brushed UV Lacquer"],
      ["Edges", "4 Sided Micro Bevel"],
      ["Joining System", "Tongue and Groove"],
      ["Moisture Content", "8–12%"],
      ["Installation Method", "Floating / Direct Stick"],
      ["Slip Resistance", "P3"],
      ["CHF Value", "4.1 kW/m²"],
      ["Smoke Value", "44 %.min"],
      ["Pack Size", "2.888 m² (8 Boards, 26 kg)"],
      ["Alternate Pack Size", "2.166 m² (6 Boards, 20.5 kg)"],
      ["Nesting", "<25% Random Short Boards"],
    ],
    rooms: [],
  },
  {
    handle: "cream-white",
    name: "Cream White",
    brand: "Capital Tiles",
    card: "/img/timber/cream-white.jpg",
    images: [
      "/img/timber/cream-white/1.jpg",
      "/img/timber/cream-white/2.jpg",
      "/img/timber/cream-white/3.jpg",
      "/img/timber/cream-white/4.jpg",
    ],
    tagline: "Engineered timber flooring in 1900 x 190 x 14 mm",
    short: "Cream White engineered timber flooring. 1900 x 190 x 14 mm planks and a 2 mm european oak wear layer. Supplied and installed across Canberra.",
    overview: [
      "Cream White engineered timber flooring blends the elegance of European oak with the durability of modern technology. With its natural oak top layer and brushed UV lacquer finish, it brings warmth and sophistication into homes. Designed for everyday living, Cream White offers acoustic comfort, water resistance for daily spills, and versatile installation options.",
      "Whether you're upgrading a family home in Holt, modernising an apartment in Bruce, or renovating a townhouse in Aranda, this flooring delivers a seamless balance of timeless timber beauty with lasting performance. Its floating or direct stick install flexibility ensures a reliable fit in both residential and light commercial spaces.",
    ],
    features: [
      "Natural European Oak veneer – timeless warmth and authentic grain appeal.",
      "Brushed UV lacquer finish – durable, low-maintenance and resilient surface.",
      "Water-resistant core – handles everyday spills and seasonal humidity.",
      "Acoustic comfort – reduces noise for quieter, more comfortable homes.",
      "Flexible installation – floating or direct stick options for any project.",
      "Tongue & groove joining – secure and reliable plank connection.",
    ],
    seoTitle: "Cream White | Capital Tiles",
    seoDesc: "Cream White, 1900 x 190 x 14 mm. Engineered timber flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [],
    sizes: ["1900 x 190 x 14 mm"],
    finishes: ["Brushed UV Lacquer"],
    thickness: [],
    slip: ["P3"],
    material: ["2 mm European Oak top layer"],
    specCols: ["Attribute", "Cream White"],
    specRows: [
      ["Timber Grade", "Natural"],
      ["Dimension", "1900 x 190 x 14 mm"],
      ["Top Layer", "2 mm European Oak"],
      ["Surface Finish", "Brushed UV Lacquer"],
      ["Edges", "4 Sided Micro Bevel"],
      ["Joining System", "Tongue and Groove"],
      ["Moisture Content", "8–12%"],
      ["Installation Method", "Floating / Direct Stick"],
      ["Slip Resistance", "P3"],
      ["CHF Value", "4.1 kW/m²"],
      ["Smoke Value", "44 %.min"],
      ["Pack Size", "2.888 m² (8 Boards, 26 kg)"],
      ["Alternate Pack Size", "2.166 m² (6 Boards, 20.5 kg)"],
      ["Nesting", "<25% Random Short Boards"],
    ],
    rooms: [],
  },
]

export function byHandle(handle) {
  return ENGINEERED_TIMBER_PRODUCTS.find((p) => p.handle === handle)
}
