/* Flooring — the full range, taken from the live capitaltiles.com.au flooring
   collection: names, blurbs, brands and the colour / finish / size options each
   product actually ships with. */

export const FLOORING = [
  {
    name: "Tranquility 5.0mm",
    handle: "tranquility-5-0mm",
    blurb: "Transform your space with Tranquility Luxury Vinyl Planks, designed to bring elegance, durability, and peace of mind to any environment. Whether in a ",
    brand: "National Flooring Distributors",
    colours: ["Tranquility - Ashen Mist", "Tranquility - Bristle Oak", "Tranquility - Classic Teak", "Tranquility - Coastline Oak", "Tranquility -Ernest Spotted Gum", "Tranquility - Eucalypti Gum", "Tranquility - Field Oak", "Tranquility - Florence Oak", "Tranquility - Ghost Gum", "Tranquility - Hazel Oak", "Tranquility - Ivory Oak", "Tranquility - Limed Oak", "Tranquility - Magnolia Oak", "Tranquility - Pewter Oak", "Tranquility - Phantom Oak", "Tranquility - Rover Spotted Gum", "Tranquility - Samford Oak", "Tranquility - Smokey Blackbutt", "Tranquility - Stanley Oak", "Tranquility - Sterling Oak", "Tranquility - Village Blackbutt", "Tranquility - Weathered Blackbutt"],
    finishes: ["Limed"],
    sizes: [],
  },
  {
    name: "Tempess 4.5mm",
    handle: "tempess",
    blurb: "Introducing Tempess Luxury Vinyl Plank, the epitome of elegance and empowerment. Tempess is an industry-leading range creating sophisticated spaces yo",
    brand: "National Flooring Distributors",
    colours: ["Brighton Oak B1", "Dawn Oak D1", "Mature Oak M2", "Meadow Blackbutt M4", "Merryland Oak M3", "Moonlight Oak M1", "Nickle Oak N1", "Odyssey Tassie Oak O1", "Rainy Oak R1", "Riverstone R2", "Tamsyn Oak T1", "Western Spotted Gum W1"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Sunvista 4.5mm",
    handle: "sunvista-4-5mm",
    blurb: "Create a welcoming space you’ll love to come home to. With effortless style, Sunvista offers excellence in artistry and design. Available in 12 of the",
    brand: "National Flooring Distributors",
    colours: ["Sunvista - 13", "Sunvista - 17", "Sunvista - 18", "Sunvista - 19", "Sunvista - 73", "Sunvista - 79", "Sunvista - 111", "Sunvista - 113", "Sunvista - 131", "Sunvista - 207", "Sunvista - 312", "Sunvista - 715"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Stella 4.5mm",
    handle: "stella-4-5mm",
    blurb: "Experience the warmth and comfort of natural timber with the resilience of Stella Luxury Vinyl Planks. Designed for families and pets, Stella withstan",
    brand: "National Flooring Distributors",
    colours: ["Ashen Oak 573", "Coastal Oak 552", "Earl Oak 553", "Mellow Blackbutt 557", "Oasis Oak 555", "Oyster Grey 570", "Regal Oak 556", "Seaside Oak 571", "Tidal Grey 561", "Warm Spotted Gum 572"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Spellbound 3.0mm",
    handle: "spellbound-3-0mm",
    blurb: "Create a sense of wonder with Spellbound Luxury Vinyl Plank. With a colour palette ranging from mythical greys to warm honeys and deep earthy tones, y",
    brand: "National Flooring Distributors",
    colours: ["Amulet", "Aura", "Bewitch", "Charm", "Crystal", "Divine", "Enchant", "Magic", "Merlin", "Myth", "Rune", "Wonder"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Reaction 2.5mm",
    handle: "reaction",
    blurb: "Evoke the ultimate reaction from guests with this stylish choice in flooring. The natural embossed wood grain and matte surface finish gives an authen",
    brand: "National Flooring Distributors",
    colours: ["Coastal Blackbutt", "Highland Silver Oak", "Natural Oak", "Spotted Gum", "Tasmanian Oak", "White Rustic Oak"],
    finishes: ["Matt", "Embossed", "Rustic"],
    sizes: [],
  },
  {
    name: "Illusions 5mm",
    handle: "illusions-5mm",
    blurb: "The ever-popular Illusions Vinyl Plank now comes in 12 fresh, new colours, ensuring the utmost in style for your home. From cool pearl tones to warm h",
    brand: "National Flooring Distributors",
    colours: ["Ambush", "Ashwood", "Aspen", "Blackbutt", "Cinnamon Oak", "Dune", "Grey Gum", "Mahogany", "Native Spotted Gum", "Natural Pearl", "NSW Spotted Gum", "Urban Grey"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Cascade 4.5mm",
    handle: "cascade",
    blurb: "Create stunning spaces with the luxurious Cascade range. Our expertly designed 'longboards' perfectly accommodate the 'less is more' trend that is swe",
    brand: "National Flooring Distributors",
    colours: ["Belmore", "Chandler", "Edith", "Gordon", "Kearney", "Murray", "Niagara", "Oaky", "Rawson", "Teviot", "Trinity", "Tully"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Calloway 2.0mm",
    handle: "calloway",
    blurb: "Elevate your interiors with the sleek, sophisticated appeal of Calloway Luxury Vinyl Planks. Designed for both beauty and durability, these planks are",
    brand: "National Flooring Distributors",
    colours: ["Frontier Blackbutt", "Hudson Oak", "Isle Oak", "Junction Spotted Gum"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Oakridge 6.5mm",
    handle: "oakridge",
    blurb: "Engineered with the latest hybrid technology, Oakridge combines superior strength and long-lasting performance, making it the ideal choice for every m",
    brand: "National Flooring Distributors",
    colours: ["Antique Walnut", "Coraki Blackbutt", "Hillside Oak", "Limed Oak", "Northern Spotted Gum", "Oyster Driftwood", "Sandy Oak", "Tassie Oak"],
    finishes: ["Limed"],
    sizes: [],
  },
  {
    name: "Daybreak 7mm",
    handle: "daybreak",
    blurb: "Daybreak is designed for living and made to impress, bringing effortless style to your floors. Whether you’re building a new space or refreshing an ol",
    brand: "National Flooring Distributors",
    colours: ["Brushed Honey Oak 7002", "Country Oak 7001", "Mountain Misty Oak 7003", "Natural Spotted Gum 7009", "Refined Blackbutt 7010", "Riverstone Oak 7006", "Snowy Oak 7004", "Tasmanian Oak 7008", "Wild Valley Oak 7007", "Winter Fawn Oak 7005"],
    finishes: ["Brushed", "Matt"],
    sizes: [],
  },
  {
    name: "Bespoke 9mm",
    handle: "bespoke",
    blurb: "Bespoke Hybrid Flooring delivers the perfect balance of luxury, durability and acoustic comfort for modern Australian homes and commercial spaces. Ins",
    brand: "National Flooring Distributors",
    colours: ["Ashen Mist", "Classic Teak", "Coastline Oak", "Ernest Spotted Gum", "Field Oak", "Hazel Oak", "Stanley Oak", "Sterline Oak", "Village Blackbutt", "Weathered Blackbutt"],
    finishes: ["Matt"],
    sizes: [],
  },
  {
    name: "Lime Wash",
    handle: "lime-wash",
    blurb: "Lime Wash Engineered Timber – Water-Resistant European Oak Flooring for Canberra Homes The Lime Wash collection combines the calming elegance of a sof",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed"],
    sizes: [],
  },
  {
    name: "Classic Oak",
    handle: "classic-oak",
    blurb: "Classic Oak – Traditional Timber Elegance with Modern Performance Classic Oak engineered timber flooring brings the warmth of natural oak together wit",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed", "Rustic"],
    sizes: [],
  },
  {
    name: "Cream White",
    handle: "cream-white",
    blurb: "Cream White – Timeless Oak with Modern Strength Cream White engineered timber flooring blends the elegance of European oak with the durability of mode",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed", "Rustic"],
    sizes: [],
  },
  {
    name: "Grey Ironbark",
    handle: "grey-ironbark",
    blurb: "Grey Ironbark – Modern Durability with Everyday Style Grey Ironbark hybrid flooring strikes the perfect balance of durability, comfort and contemporar",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Textured"],
    sizes: [],
  },
  {
    name: "Stone Grey",
    handle: "stone-grey",
    blurb: "Stone Grey – Contemporary Strength with Quiet Comfort Stone Grey hybrid flooring is built for modern family living. Its 100% waterproof core handles e",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Carbon",
    handle: "carbon",
    blurb: "Carbon – Performance Flooring for Everyday Living Carbon hybrid flooring is designed to handle the demands of modern family life. With a 100% waterpro",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Spotted Gum",
    handle: "spotted-gum",
    blurb: "Spotted Gum Engineered & Hybrid Flooring – Durable, Waterproof, Acoustic Timber Floors for Canberra Homes The Spotted Gum collection brings the rich, ",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed"],
    sizes: ["1800 x 228 x 9mm", "1516 x 238 x 12mm"],
  },
  {
    name: "Cream Oak",
    handle: "cream-oak",
    blurb: "Durable, Waterproof, and Quiet – Cream Oak Laminate Flooring The Cream Oak laminate plank delivers a soft, neutral timber look that enhances both cont",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Rustic Blackbutt",
    handle: "rustic-blackbutt",
    blurb: "Rustic Blackbutt Laminate Flooring – Stylish, Resilient & Whisper-Quiet Bring the timeless charm of Australian hardwood into your home with Rustic Bla",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Rustic"],
    sizes: [],
  },
  {
    name: "Grey Oak",
    handle: "grey-oak",
    blurb: "Grey Oak Laminate Flooring – Modern, Durable & Whisper-Quiet Elevate your interiors with the sophisticated tones of Grey Oak laminate planks. Designed",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Polished"],
    sizes: [],
  },
  {
    name: "Rustic Spotted Gum",
    handle: "rustic-spotted-gum",
    blurb: "Rustic Spotted Gum Laminate Flooring – Rich, Durable & Comfortable Bring the natural elegance of Australian hardwood into your home with Rustic Spotte",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Rustic"],
    sizes: [],
  },
  {
    name: "Ironbark",
    handle: "ironbark",
    blurb: "Ironbark Laminate Flooring – Robust, Stylish & Sound-Reducing Experience the rugged elegance of Ironbark laminate planks. Combining striking Australia",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Kensington Brown",
    handle: "kensington-brown",
    blurb: "Kensington Brown Laminate Flooring – Warm, Durable & Family-Friendly Enhance your interiors with the rich, earthy tones of Kensington Brown laminate f",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Regent Beige",
    handle: "regent-beige",
    blurb: "Regent Beige Laminate Flooring – Elegant, Strong & Family-Ready Bring understated luxury into your home with the warm, neutral tones of Regent Beige l",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Botany Beige",
    handle: "botany-beige",
    blurb: "Botany Beige Laminate Flooring – Soft, Versatile & Built to Last Transform your interiors with the warm, calming tones of Botany Beige laminate floori",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Oxford Cream",
    handle: "oxford-cream",
    blurb: "Oxford Cream Laminate Flooring – Elegant Warmth & Everyday Strength Brighten your space with the soft, sunlit tones of Oxford Cream . This versatile l",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Chelsea Ivory",
    handle: "chelsea-ivory",
    blurb: "Chelsea Ivory Laminate Flooring – Light Oak Elegance & Lasting Strength Transform your interiors with the refined beauty of Chelsea Ivory , a pale oak",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Coventry Sand",
    handle: "coventry-sand",
    blurb: "Coventry Sand – Soft Sand Tones with Waterproof Strength Refresh your space with Coventry Sand laminate flooring , blending natural warmth with a cont",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Blackbutt",
    handle: "blackbutt",
    blurb: "Blackbutt Flooring – Authentic Timber Style in Laminate & Hybrid Options Bring the natural warmth of Australian hardwood into your home with Blackbutt",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: ["1516 x 238 x 12mm", "1540 x 182 x 6.5mm"],
  },
  {
    name: "Natural Oak",
    handle: "natural-oak",
    blurb: "Natural Oak – Classic Timber Look with Everyday Practicality Enhance your interiors with the timeless appeal of Natural Oak laminate flooring . Featur",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "White Oak",
    handle: "white-oak",
    blurb: "White Oak – Bright, Waterproof & Built for Comfort Lift the light in your home with White Oak laminate flooring . Its fresh, airy palette opens up roo",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Beige Oak",
    handle: "beige-oak",
    blurb: "Beige Oak – Natural Warmth & Lasting Performance Bring timeless elegance into your project with Beige Oak laminate flooring . Its neutral, warm oak to",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Charcoal Grey",
    handle: "charcoal-grey",
    blurb: "Charcoal Grey brings modern depth and texture to any interior while delivering premium performance. With a water-resistant core, natural oak veneer, a",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed", "Matt"],
    sizes: [],
  },
  {
    name: "Pacific Spotted Gum",
    handle: "pacific-spotted-gum",
    blurb: "Pacific Spotted Gum – Natural Timber Appeal with Next-Gen Performance Bring timeless Australian character into your space with Pacific Spotted Gum 6.5",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Matt"],
    sizes: [],
  },
]
