/* Hybrid flooring range, taken from the live capitaltiles.com.au hybrid-flooring
   collection: names, blurbs, brands and the colour / finish / size options
   each product actually ships with. */

export const HYBRID = [
  {
    name: "Oakridge 6.5mm",
    handle: "oakridge",
    blurb: "Engineered with the latest hybrid technology, Oakridge combines superior strength and long-lasting performance, making it the ideal choice for every m",
    brand: "National Flooring Distributors",
    colours: ["Antique Walnut", "Coraki Blackbutt", "Hillside Oak", "Limed Oak", "Northern Spotted Gum", "Oyster Driftwood", "Sandy Oak", "Tassie Oak"],
    finishes: ["Limed"],
    sizes: ["6.5mm"],
  },
  {
    name: "Daybreak 7mm",
    handle: "daybreak",
    blurb: "Daybreak is designed for living and made to impress, bringing effortless style to your floors. Whether you’re building a new space or refreshing an ol",
    brand: "National Flooring Distributors",
    colours: ["Brushed Honey Oak 7002", "Country Oak 7001", "Mountain Misty Oak 7003", "Natural Spotted Gum 7009", "Refined Blackbutt 7010", "Riverstone Oak 7006", "Snowy Oak 7004", "Tasmanian Oak 7008", "Wild Valley Oak 7007", "Winter Fawn Oak 7005"],
    finishes: ["Brushed", "Matt"],
    sizes: ["7mm"],
  },
  {
    name: "Bespoke 9mm",
    handle: "bespoke",
    blurb: "Bespoke Hybrid Flooring delivers the perfect balance of luxury, durability and acoustic comfort for modern Australian homes and commercial spaces. Ins",
    brand: "National Flooring Distributors",
    colours: ["Ashen Mist", "Classic Teak", "Coastline Oak", "Ernest Spotted Gum", "Field Oak", "Hazel Oak", "Stanley Oak", "Sterline Oak", "Village Blackbutt", "Weathered Blackbutt"],
    finishes: ["Matt"],
    sizes: ["9mm"],
  },
  {
    name: "Tawny Brown",
    handle: "tawny-brown",
    blurb: "Warm Timber Aesthetics with Everyday Performance Tawny Brown hybrid flooring combines the natural beauty of timber with the resilience of next-gen wat",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Grey Ironbark",
    handle: "grey-ironbark",
    blurb: "Modern Durability with Everyday Style Grey Ironbark hybrid flooring strikes the perfect balance of durability, comfort and contemporary design. With i",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Textured"],
    sizes: [],
  },
  {
    name: "Stone Grey",
    handle: "stone-grey",
    blurb: "Contemporary Strength with Quiet Comfort Stone Grey hybrid flooring is built for modern family living. Its 100% waterproof core handles everyday spill",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Carbon",
    handle: "carbon",
    blurb: "Performance Flooring for Everyday Living Carbon hybrid flooring is designed to handle the demands of modern family life. With a 100% waterproof surfac",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Spotted Gum",
    handle: "spotted-gum",
    blurb: "Durable, Waterproof, Acoustic Timber Floors for Canberra Homes The Spotted Gum collection brings the rich, earthy character of native Australian hardw",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed"],
    sizes: [],
  },
  {
    name: "Rustic Blackbutt",
    handle: "rustic-blackbutt",
    blurb: "Stylish, Resilient & Whisper-Quiet Bring the timeless charm of Australian hardwood into your home with Rustic Blackbutt laminate planks. Expertly desi",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Grey Oak",
    handle: "grey-oak",
    blurb: "Modern, Durable & Whisper-Quiet Elevate your interiors with the sophisticated tones of Grey Oak laminate planks. Designed for contemporary living, thi",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Rustic Spotted Gum",
    handle: "rustic-spotted-gum",
    blurb: "Rich, Durable & Comfortable Bring the natural elegance of Australian hardwood into your home with Rustic Spotted Gum laminate planks. Combining multi-",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Oxford Cream",
    handle: "oxford-cream",
    blurb: "Elegant Warmth & Everyday Strength Brighten your space with the soft, sunlit tones of Oxford Cream . This versatile laminate lifts interiors across Gu",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Blackbutt",
    handle: "blackbutt",
    blurb: "Authentic Timber Style in Laminate & Hybrid Options Bring the natural warmth of Australian hardwood into your home with Blackbutt timber-look flooring",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Beige Oak",
    handle: "beige-oak",
    blurb: "Natural Warmth & Lasting Performance Bring timeless elegance into your project with Beige Oak laminate flooring . Its neutral, warm oak tones add comf",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Cream Oak",
    handle: "cream-oak",
    blurb: "Cream Oak Laminate Flooring The Cream Oak laminate plank delivers a soft, neutral timber look that enhances both contemporary and classic interiors. B",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Charcoal Grey",
    handle: "charcoal-grey",
    blurb: "Charcoal Grey brings modern depth and texture to any interior while delivering premium performance. With a water-resistant core, natural oak veneer, a",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed", "Matt"],
    sizes: [],
  },
  {
    name: "Pacific Spotted Gum",
    handle: "pacific-spotted-gum",
    blurb: "Natural Timber Appeal with Next-Gen Performance Bring timeless Australian character into your space with Pacific Spotted Gum 6.5 mm Hybrid Flooring — ",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Matt"],
    sizes: ["6.5mm"],
  },
]
