/* Laminate flooring range, taken from the live capitaltiles.com.au laminate-flooring collection:
   names, blurbs, brands and the colour / finish / size options each product
   actually ships with. */

export const LAMINATE = [
  {
    name: "Roccia Series",
    handle: "roccia",
    blurb: "Roccia Collection – Earthy Porcelain Tiles with Modern Durability Bring the rugged charm of natural stone into your home with the Roccia Collection . ",
    brand: "Muses",
    colours: ["Greige", "Charcoal"],
    finishes: ["Matt"],
    sizes: [],
  },
  {
    name: "Coventry Sand",
    handle: "coventry-sand",
    blurb: "Coventry Sand – Soft Sand Tones with Waterproof Strength Refresh your space with Coventry Sand laminate flooring , blending natural warmth with a cont",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Carbon",
    handle: "carbon",
    blurb: "Carbon – Performance Flooring for Everyday Living Carbon hybrid flooring is designed to handle the demands of modern family life. With a 100% waterpro",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Spotted Gum",
    handle: "spotted-gum",
    blurb: "Spotted Gum Engineered & Hybrid Flooring – Durable, Waterproof, Acoustic Timber Floors for Canberra Homes The Spotted Gum collection brings the rich, ",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed"],
    sizes: [],
  },
  {
    name: "Rustic Blackbutt",
    handle: "rustic-blackbutt",
    blurb: "Rustic Blackbutt Laminate Flooring – Stylish, Resilient & Whisper-Quiet Bring the timeless charm of Australian hardwood into your home with Rustic Bla",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Grey Oak",
    handle: "grey-oak",
    blurb: "Grey Oak Laminate Flooring – Modern, Durable & Whisper-Quiet Elevate your interiors with the sophisticated tones of Grey Oak laminate planks. Designed",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Rustic Spotted Gum",
    handle: "rustic-spotted-gum",
    blurb: "Rustic Spotted Gum Laminate Flooring – Rich, Durable & Comfortable Bring the natural elegance of Australian hardwood into your home with Rustic Spotte",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Ironbark",
    handle: "ironbark",
    blurb: "Ironbark Laminate Flooring – Robust, Stylish & Sound-Reducing Experience the rugged elegance of Ironbark laminate planks. Combining striking Australia",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Kensington Brown",
    handle: "kensington-brown",
    blurb: "Kensington Brown Laminate Flooring – Warm, Durable & Family-Friendly Enhance your interiors with the rich, earthy tones of Kensington Brown laminate f",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Regent Beige",
    handle: "regent-beige",
    blurb: "Regent Beige Laminate Flooring – Elegant, Strong & Family-Ready Bring understated luxury into your home with the warm, neutral tones of Regent Beige l",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Botany Beige",
    handle: "botany-beige",
    blurb: "Botany Beige Laminate Flooring – Soft, Versatile & Built to Last Transform your interiors with the warm, calming tones of Botany Beige laminate floori",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Oxford Cream",
    handle: "oxford-cream",
    blurb: "Oxford Cream Laminate Flooring – Elegant Warmth & Everyday Strength Brighten your space with the soft, sunlit tones of Oxford Cream . This versatile l",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Chelsea Ivory",
    handle: "chelsea-ivory",
    blurb: "Chelsea Ivory Laminate Flooring – Light Oak Elegance & Lasting Strength Transform your interiors with the refined beauty of Chelsea Ivory , a pale oak",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Blackbutt",
    handle: "blackbutt",
    blurb: "Blackbutt Flooring – Authentic Timber Style in Laminate & Hybrid Options Bring the natural warmth of Australian hardwood into your home with Blackbutt",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Natural Oak",
    handle: "natural-oak",
    blurb: "Natural Oak – Classic Timber Look with Everyday Practicality Enhance your interiors with the timeless appeal of Natural Oak laminate flooring . Featur",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "White Oak",
    handle: "white-oak",
    blurb: "White Oak – Bright, Waterproof & Built for Comfort Lift the light in your home with White Oak laminate flooring . Its fresh, airy palette opens up roo",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Beige Oak",
    handle: "beige-oak",
    blurb: "Beige Oak – Natural Warmth & Lasting Performance Bring timeless elegance into your project with Beige Oak laminate flooring . Its neutral, warm oak to",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
]
