/* Mosaic Tiles product detail data.

   Specs, colours, sizes and the copy are the same records already built
   for the ranges shared with our other tile collections, so no product is
   described twice and no image is stored twice. Generated — edit the
   source data, not this file.
*/

export const MOSAIC_PRODUCTS = [
  {
    handle: "carrara-mosaic",
    name: "Carrara Mosaic",
    brand: "HF Tiles",
    card: "/img/mosaic/carrara-mosaic.jpg",
    images: [
      "/img/mosaic/carrara-mosaic/1.jpg",
      "/img/mosaic/carrara-mosaic/2.jpg",
      "/img/mosaic/carrara-mosaic/3.jpg",
      "/img/mosaic/carrara-mosaic/4.jpg",
    ],
    tagline: "Soft matt in 4 colours",
    short: "Carrara Mosaic by HF Tiles. 4 colours and Soft Matt finish. On display in our Mitchell showroom.",
    overview: [
      "Carrara Mosaic is part of the mosaic tiles range we hold at Capital Tiles, supplied by HF Tiles. It runs in herringbone, kitKat, convex and concave, so there is a tone here for a light room and for a darker, more grounded one.",
      "It is offered in Soft Matt finish. Thickness is 10mm. We list it under Mosaic Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Herringbone, kitKat, Convex and Concave",
      "Finish: Soft Matt",
      "Thickness: 10mm",
      "Listed under Mosaic Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Carrara Mosaic Mosaic Tiles | Capital Tiles",
    seoDesc: "Carrara Mosaic in Soft Matt. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["Herringbone", "kitKat", "Convex", "Concave"],
    sizes: [],
    finishes: ["Soft Matt"],
    thickness: ["10mm"],
    slip: ["None"],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Mosaic Tiles", href: "/tiles/mosaic" },
    ],
  },
  {
    handle: "aroma-collection",
    name: "Aroma Collection",
    brand: "Capital Tiles",
    card: "/img/mosaic/aroma-collection.jpg",
    images: [
      "/img/bathroom/aroma-collection/1.jpg",
      "/img/bathroom/aroma-collection/2.jpg",
      "/img/bathroom/aroma-collection/3.jpg",
      "/img/bathroom/aroma-collection/4.jpg",
      "/img/bathroom/aroma-collection/5.jpg",
      "/img/bathroom/aroma-collection/6.jpg",
      "/img/bathroom/aroma-collection/7.jpg",
      "/img/bathroom/aroma-collection/8.jpg",
      "/img/bathroom/aroma-collection/9.jpg",
      "/img/bathroom/aroma-collection/10.jpg",
      "/img/bathroom/aroma-collection/11.jpg",
      "/img/bathroom/aroma-collection/12.jpg",
      "/img/bathroom/aroma-collection/13.jpg",
      "/img/bathroom/aroma-collection/14.jpg",
      "/img/bathroom/aroma-collection/15.jpg",
      "/img/bathroom/aroma-collection/16.jpg",
      "/img/bathroom/aroma-collection/17.jpg",
      "/img/bathroom/aroma-collection/18.jpg",
      "/img/bathroom/aroma-collection/19.jpg",
      "/img/bathroom/aroma-collection/20.jpg",
      "/img/bathroom/aroma-collection/21.jpg",
    ],
    tagline: "Structured gloss in 7 colours",
    short: "Aroma Collection. 7 colours, Structured Gloss finish and a single 60 x 240 format. On display in our Mitchell showroom.",
    overview: [
      "Aroma Collection is part of the bathroom range we hold at Capital Tiles. It runs in verde, Verde Scuro, Rosa Scuro, blu, turchese, sabbia and bianco, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 60 x 240. It is offered in Structured Gloss finish. We list it under Bathroom Tiles, Kitchen Tiles, Wall Tiles and Mosaic Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Verde, Verde Scuro, Rosa Scuro, Blu, Turchese, Sabbia and Bianco",
      "Finish: Structured Gloss",
      "Size: 60 x 240",
      "Listed under Bathroom Tiles, Kitchen Tiles and Wall Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Aroma Collection Bathroom Tiles | Capital Tiles",
    seoDesc: "Aroma Collection in Structured Gloss, 60 x 240. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["Verde", "Verde Scuro", "Rosa Scuro", "Blu", "Turchese", "Sabbia", "Bianco"],
    sizes: ["60 x 240"],
    finishes: ["Structured Gloss"],
    thickness: [],
    slip: [],
    material: [],
    specCols: ["Size (mm)", "Finish", "PCS/CTN", "m²/CTN", "KG/CTN", "CTNS/PLT", "KG/PLT", "m²/PLT"],
    specRows: [
      ["60 x 240", "Structured Gloss", "50", "0.72", "10", "60", "600", "43.2"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Mosaic Tiles", href: "/tiles/mosaic" },
    ],
  },
  {
    handle: "altea-collection",
    name: "Altea Collection",
    brand: "Capital Tiles",
    card: "/img/mosaic/altea-collection.jpg",
    images: [
      "/img/bathroom/altea-collection/1.jpg",
      "/img/bathroom/altea-collection/2.jpg",
      "/img/bathroom/altea-collection/3.jpg",
      "/img/bathroom/altea-collection/4.jpg",
      "/img/bathroom/altea-collection/5.jpg",
      "/img/bathroom/altea-collection/6.jpg",
      "/img/bathroom/altea-collection/7.jpg",
      "/img/bathroom/altea-collection/8.jpg",
      "/img/bathroom/altea-collection/9.jpg",
      "/img/bathroom/altea-collection/10.jpg",
      "/img/bathroom/altea-collection/11.jpg",
      "/img/bathroom/altea-collection/12.jpg",
      "/img/bathroom/altea-collection/13.jpg",
      "/img/bathroom/altea-collection/14.jpg",
      "/img/bathroom/altea-collection/15.jpg",
      "/img/bathroom/altea-collection/16.jpg",
      "/img/bathroom/altea-collection/17.jpg",
      "/img/bathroom/altea-collection/18.jpg",
      "/img/bathroom/altea-collection/19.jpg",
      "/img/bathroom/altea-collection/20.jpg",
      "/img/bathroom/altea-collection/21.jpg",
      "/img/bathroom/altea-collection/22.jpg",
    ],
    tagline: "Structured gloss in 7 colours",
    short: "Altea Collection. 7 colours, Structured Gloss finish and 2 formats from 75 x 150 to 100 x 100. On display in our Mitchell showroom.",
    overview: [
      "Altea Collection is part of the bathroom range we hold at Capital Tiles. It runs in Dusty Pink, matcha, Ash Blue, black, smoke, Pine Green and white, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 75 x 150 and 100 x 100. It is offered in Structured Gloss finish. We list it under Bathroom Tiles, Kitchen Tiles, Wall Tiles and Mosaic Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Dusty Pink, Matcha, Ash Blue, Black, Smoke, Pine Green and White",
      "Finish: Structured Gloss",
      "Sizes: 75 x 150, 100 x 100",
      "Listed under Bathroom Tiles, Kitchen Tiles and Wall Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Altea Collection Bathroom Tiles | Capital Tiles",
    seoDesc: "Altea Collection in Structured Gloss, 75 x 150, 100 x 100. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["Dusty Pink", "Matcha", "Ash Blue", "Black", "Smoke", "Pine Green", "White"],
    sizes: ["75 x 150", "100 x 100"],
    finishes: ["Structured Gloss"],
    thickness: [],
    slip: [],
    material: [],
    specCols: ["Size (mm)", "Finish", "PCS/CTN", "m²/CTN", "KG/CTN"],
    specRows: [
      ["75 x 150", "Structured Gloss", "44", "0.5", "6.8"],
      ["100 x 100", "Structured Gloss", "50", "0.5", "7.5"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Mosaic Tiles", href: "/tiles/mosaic" },
    ],
  },
  {
    handle: "aqua-collection",
    name: "Aqua",
    brand: "Muses",
    card: "/img/mosaic/aqua-collection.jpg",
    images: [
      "/img/bathroom/aqua-collection/1.png",
      "/img/bathroom/aqua-collection/2.png",
      "/img/bathroom/aqua-collection/3.png",
      "/img/bathroom/aqua-collection/4.png",
      "/img/bathroom/aqua-collection/5.png",
      "/img/bathroom/aqua-collection/6.png",
      "/img/bathroom/aqua-collection/7.png",
      "/img/bathroom/aqua-collection/8.png",
      "/img/bathroom/aqua-collection/9.png",
      "/img/bathroom/aqua-collection/10.png",
      "/img/bathroom/aqua-collection/11.png",
      "/img/bathroom/aqua-collection/12.png",
      "/img/bathroom/aqua-collection/13.jpg",
      "/img/bathroom/aqua-collection/14.png",
      "/img/bathroom/aqua-collection/15.png",
      "/img/bathroom/aqua-collection/16.png",
      "/img/bathroom/aqua-collection/17.jpg",
      "/img/bathroom/aqua-collection/18.png",
    ],
    tagline: "Polished in 6 colours",
    short: "Aqua by Muses. 6 colours, polished finish and a single 60 x 240 mm format. On display in our Mitchell showroom.",
    overview: [
      "Aqua is part of the bathroom range we hold at Capital Tiles, supplied by Muses. It runs in crystal, opal, rune, jade, berry and core, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 60 x 240 mm. It is offered in polished finish. Thickness is 6 mm. We list it under Bathroom Tiles, Kitchen Tiles, Wall Tiles, Floor Tiles and Mosaic Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Crystal, Opal, Rune, Jade, Berry and Core",
      "Finish: Polished",
      "Size: 60 x 240 mm",
      "Thickness: 6 mm",
      "Listed under Bathroom Tiles, Kitchen Tiles and Wall Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Aqua Bathroom Tiles | Capital Tiles",
    seoDesc: "Aqua in polished, 60 x 240 mm. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["Crystal", "Opal", "Rune", "Jade", "Berry", "Core"],
    sizes: ["60 x 240 mm"],
    finishes: ["Polished"],
    thickness: ["6 mm"],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
      { label: "Mosaic Tiles", href: "/tiles/mosaic" },
    ],
  },
  {
    handle: "alhambra",
    name: "Alhambra Collection",
    brand: "Capital Tiles",
    card: "/img/mosaic/alhambra.jpg",
    images: [
      "/img/bathroom/alhambra/1.jpg",
      "/img/bathroom/alhambra/2.jpg",
      "/img/bathroom/alhambra/3.jpg",
      "/img/bathroom/alhambra/4.jpg",
      "/img/bathroom/alhambra/5.jpg",
      "/img/bathroom/alhambra/6.jpg",
      "/img/bathroom/alhambra/7.jpg",
      "/img/bathroom/alhambra/8.jpg",
    ],
    tagline: "Matt in 6 colours",
    short: "Alhambra Collection. 6 colours, matt finish and a single 250x250 format. On display in our Mitchell showroom.",
    overview: [
      "Alhambra Collection is part of the bathroom range we hold at Capital Tiles. It runs in rojo, negro, gris, azul, arena and barcelona, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 250x250. It is offered in matt finish. We list it under Bathroom Tiles, Kitchen Tiles, Wall Tiles, Floor Tiles and Mosaic Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Rojo, Negro, Gris, Azul, Arena and Barcelona",
      "Finish: Matt",
      "Size: 250x250",
      "Listed under Bathroom Tiles, Kitchen Tiles and Wall Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Alhambra Collection Bathroom Tiles | Capital Tiles",
    seoDesc: "Alhambra Collection in matt, 250x250. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["Rojo", "Negro", "Gris", "Azul", "Arena", "Barcelona"],
    sizes: ["250x250"],
    finishes: ["Matt"],
    thickness: [],
    slip: [],
    material: [],
    specCols: ["Colour / Look", "Size (mm)", "Finish", "PCS/CTN", "m²/CTN", "KG/CTN", "CTNS/PLT", "KG/PLT", "m²/PLT"],
    specRows: [
      ["Rojo", "250x250", "Matt", "16", "1", "19.2", "44", "848", "44"],
      ["Negro", "250x250", "Matt", "16", "1", "19.2", "44", "848", "44"],
      ["Gris", "250x250", "Matt", "16", "1", "19.2", "44", "848", "44"],
      ["Azul", "250x250", "Matt", "16", "1", "19.2", "44", "848", "44"],
      ["Arena", "250x250", "Matt", "16", "1", "19.2", "44", "848", "44"],
      ["Barcelona Blanco", "250x250", "Matt", "16", "1", "19.2", "44", "848", "44"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
      { label: "Mosaic Tiles", href: "/tiles/mosaic" },
    ],
  },
  {
    handle: "picasso",
    name: "Picasso",
    brand: "Muses",
    card: "/img/mosaic/picasso.jpg",
    images: [
      "/img/bathroom/picasso/1.png",
      "/img/bathroom/picasso/2.png",
      "/img/bathroom/picasso/3.png",
      "/img/bathroom/picasso/4.png",
      "/img/bathroom/picasso/5.png",
      "/img/bathroom/picasso/6.png",
      "/img/bathroom/picasso/7.png",
    ],
    tagline: "Abstract-art porcelain with sculptural texture",
    short: "Drawn from contemporary abstract art rather than stone, Picasso pairs Deep Ink colour with a sculptural 3D face. Sizes run up to 750 x 1500.",
    overview: [
      "Picasso does not pretend to be a rock. The range takes its cues from contemporary abstract art, with layered surface work in place of veining or grain. Deep Ink delivers dramatic contrast and depth of colour. The 3D finish adds physical relief, so the face casts its own shadows and the pattern shifts as you move past it. The body is porcelain, built for heavy foot traffic.",
      "Four sizes: 750 x 1500, 600 x 1200, 600 x 600 and 300 x 600. The largest goes on commercial walls, hotel lobbies and large-format flooring. 600 x 1200 suits open-plan interiors, offices and retail spaces, 600 x 600 works on living areas and upscale residential floors, and 300 x 600 handles feature walls, splashbacks and bathroom accents. The 3D textures are recommended for vertical applications, where the sculptural effect actually reads.",
      "Worth checking under the light it will live in, because both finishes behave differently in daylight and under downlights. We keep the range at the Mitchell showroom in full tiles. Capital Tiles supplies trade and homeowners, and our installers handle removal, substrate prep, laying, grouting and sealing on Canberra and Queanbeyan jobs, with a free measure and quote first.",
    ],
    features: [
      "Deep Ink (IK) and 3D finishes for contrast and relief",
      "Porcelain construction built for heavy foot traffic",
      "Sizes: 300x600, 600x600, 600x1200 and 750x1500",
      "3D texture is recommended for vertical applications",
      "Large formats suit commercial walls and hotel lobbies",
      "300x600 for feature walls, splashbacks and bathroom accents",
    ],
    seoTitle: "Picasso Textured Porcelain | Capital Tiles",
    seoDesc: "Picasso by Muses: Deep Ink and 3D textured porcelain from 300x600 to 750x1500. Feature walls, lobbies and large-format floors. See it in Mitchell.",
    colours: [],
    sizes: ["300x600", "600×600", "600×1200", "750×1500"],
    finishes: ["Deep Ink (IK) & 3D"],
    thickness: [],
    slip: ["None"],
    material: [],
    specCols: ["Size (mm)", "Finish", "Slip Rating", "Pieces/Box", "m²/Box", "Recommended Use"],
    specRows: [
      ["750 x 1500", "Deep Ink / 3D", "None", "2", "2.25", "Commercial walls, hotel lobbies, large-format flooring"],
      ["600 x 1200", "Deep Ink / 3D", "None", "2", "1.44", "Open-plan interiors, offices, retail spaces"],
      ["600 x 600", "Deep Ink / 3D", "None", "4", "1.44", "Living areas, upscale residential floors"],
      ["300 x 600", "Deep Ink / 3D", "None", "6", "1.08", "Feature walls, splashbacks, bathroom accents"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
      { label: "Mosaic Tiles", href: "/tiles/mosaic" },
    ],
  },
]

export function byHandle(handle) {
  return MOSAIC_PRODUCTS.find((p) => p.handle === handle)
}
