/* Natural timber range, taken from the live capitaltiles.com.au timber
   collection: names, blurbs, brands and the colour / finish / size options
   each product actually ships with. */

export const NATURAL_TIMBER = [
  {
    name: "Rustic Spotted Gum",
    handle: "rustic-spotted-gum",
    blurb: "Rustic Spotted Gum Laminate Flooring – Rich, Durable & Comfortable Bring the natural elegance of Australian hardwood into your home with Rustic Spotte",
    brand: "Capital Tiles",
    colours: ["Spotted Gum"],
    finishes: ["Rustic", "Natural"],
    sizes: [],
  },
  {
    name: "Coventry Sand",
    handle: "coventry-sand",
    blurb: "Coventry Sand – Soft Sand Tones with Waterproof Strength Refresh your space with Coventry Sand laminate flooring , blending natural warmth with a cont",
    brand: "Capital Tiles",
    colours: ["Sand"],
    finishes: ["Natural"],
    sizes: [],
  },
  {
    name: "White Oak",
    handle: "white-oak",
    blurb: "White Oak – Bright, Waterproof & Built for Comfort Lift the light in your home with White Oak laminate flooring . Its fresh, airy palette opens up roo",
    brand: "Capital Tiles",
    colours: ["White", "Oak"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Beige Oak",
    handle: "beige-oak",
    blurb: "Beige Oak – Natural Warmth & Lasting Performance Bring timeless elegance into your project with Beige Oak laminate flooring . Its neutral, warm oak to",
    brand: "Capital Tiles",
    colours: ["Beige", "Oak"],
    finishes: ["Natural"],
    sizes: [],
  },
  {
    name: "Wood Brown",
    handle: "wood-brown",
    blurb: "Wood Brown is a refined flooring solution that brings together natural warmth, acoustic comfort, and modern resilience. With water-resistant propertie",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Brushed", "Natural"],
    sizes: [],
  },
  {
    name: "Vintage Natural",
    handle: "vintage-natural",
    blurb: "Vintage Natural brings together classic European oak charm with the performance and convenience of modern engineered timber flooring. It’s water-resis",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed", "Smooth", "Natural"],
    sizes: [],
  },
  {
    name: "Tuscan Brown",
    handle: "tuscan-brown",
    blurb: "Tuscan Brown offers timeless charm and outstanding performance, blending the classic appeal of wide-plank engineered oak with practical benefits. Its ",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Brushed", "Rustic", "Natural"],
    sizes: [],
  },
  {
    name: "Tinge Clay",
    handle: "tinge-clay",
    blurb: "Tinge Clay combines elegant earth tones with waterproof durability, acoustic comfort, and effortless installation. Its brushed UV lacquer finish enhan",
    brand: "Capital Tiles",
    colours: ["Clay"],
    finishes: ["Brushed", "Natural"],
    sizes: ["1900 x 190 x 15mm", "600 x 120 x 15mm", "2200 x 240 x 20mm"],
  },
  {
    name: "Tortilla Brown",
    handle: "tortilla-brown",
    blurb: "Tortilla Brown combines natural beauty with superior functionality. Its water-resistant properties and tongue & groove joining system make it ideal fo",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Brushed", "Rustic", "Natural"],
    sizes: [],
  },
  {
    name: "Terrace Grey",
    handle: "terrace-grey",
    blurb: "Terrace Grey blends premium design with practical performance. Engineered to withstand everyday living, it features a water-resistant core, warm timbe",
    brand: "Capital Tiles",
    colours: ["Grey"],
    finishes: ["Brushed"],
    sizes: ["600 x 90 x 15mm", "600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Tawny Brown",
    handle: "tawny-brown",
    blurb: "Tawny Brown – Warm Timber Aesthetics with Everyday Performance Tawny Brown hybrid flooring combines the natural beauty of timber with the resilience o",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Smooth", "Rustic", "Natural"],
    sizes: [],
  },
  {
    name: "Tan Brown",
    handle: "tan-brown",
    blurb: "Tan Brown is the perfect fusion of beauty and performance, offering a durable timber floor that thrives in everyday living spaces. With its water-resi",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Brushed", "Natural"],
    sizes: ["600 x 90 x 15mm", "600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Smoked Brown",
    handle: "smoked-brown",
    blurb: "Smoked Brown offers the perfect balance between classic style and functional performance. With water-resistant construction, warm underfoot feel, and ",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Brushed", "Smooth", "Natural"],
    sizes: ["600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Royal Beige",
    handle: "royal-beige",
    blurb: "Royal Beige combines timeless elegance with modern performance. Designed to be both water-resistant and acoustically enhanced, this wide-plank timber ",
    brand: "Capital Tiles",
    colours: ["Beige"],
    finishes: ["Brushed", "Rustic", "Natural"],
    sizes: [],
  },
  {
    name: "Raw Neutral",
    handle: "raw-neutral",
    blurb: "Raw Neutral is a celebration of subtle elegance and high performance. Designed for spaces that demand both sophistication and practicality, it offers ",
    brand: "Capital Tiles",
    colours: ["Neutral"],
    finishes: ["Brushed", "Rustic", "Natural"],
    sizes: ["1900 x 190 x 15mm", "600 x 120 x 15mm", "2200 x 240 x 20mm"],
  },
  {
    name: "Pecan Brown",
    handle: "pecan-brown",
    blurb: "Pecan Brown combines natural elegance with modern performance, offering a durable, water-resistant timber floor that brings warmth and quiet comfort t",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Brushed", "Natural"],
    sizes: [],
  },
  {
    name: "Natural Limed",
    handle: "natural-limed",
    blurb: "Discover the elegance and performance of Natural Limed — engineered to offer waterproof protection, natural warmth, and acoustic comfort. Designed wit",
    brand: "Capital Tiles",
    colours: ["Limed"],
    finishes: ["Brushed", "Limed", "Natural"],
    sizes: ["1900 x 190 x 15mm", "600 x 120 x 15mm", "2200 x 240 x 20mm"],
  },
  {
    name: "Moss Grey",
    handle: "moss-grey",
    blurb: "Moss Grey brings subtle sophistication and durable performance to modern interiors. With a water-resistant engineered core and 3 mm European Oak surfa",
    brand: "Capital Tiles",
    colours: ["Grey"],
    finishes: ["Brushed", "Textured", "Natural"],
    sizes: ["600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Midnight Grey",
    handle: "midnight-grey",
    blurb: "Midnight Grey is a bold and sophisticated engineered timber flooring option designed for performance and aesthetics. Featuring a water-resistant core,",
    brand: "Capital Tiles",
    colours: ["Grey"],
    finishes: ["Brushed", "Matt", "Natural"],
    sizes: ["600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Mellow Beige",
    handle: "mellow-beige",
    blurb: "Mellow Beige offers the perfect fusion of beauty and performance. With waterproofing advantages, natural warmth underfoot, and acoustic comfort, it's ",
    brand: "Capital Tiles",
    colours: ["Beige"],
    finishes: ["Brushed", "Natural"],
    sizes: ["600 x 90 x 15mm", "600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Light Neutral",
    handle: "light-neutral",
    blurb: "The Light Neutral collection offers the perfect blend of timeless beauty and modern performance. Designed with waterproof technology, it provides exce",
    brand: "Capital Tiles",
    colours: ["Neutral"],
    finishes: ["Brushed", "Natural"],
    sizes: ["600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Light Ash",
    handle: "light-ash",
    blurb: "Light Ash brings subtle elegance and exceptional performance to any interior. Designed with a water-resistant core, it’s ideal for family homes and bu",
    brand: "Capital Tiles",
    colours: ["Ash"],
    finishes: ["Brushed", "Gloss", "Natural"],
    sizes: [],
  },
  {
    name: "Granite Grey",
    handle: "granite-grey",
    blurb: "Granite Grey delivers a bold and contemporary finish with exceptional structural strength and comfort. Its water-resistant engineered core, thick 4 mm",
    brand: "Capital Tiles",
    colours: ["Grey"],
    finishes: ["Brushed", "Rustic", "Natural"],
    sizes: [],
  },
  {
    name: "Grey Ironbark",
    handle: "grey-ironbark",
    blurb: "Grey Ironbark – Modern Durability with Everyday Style Grey Ironbark hybrid flooring strikes the perfect balance of durability, comfort and contemporar",
    brand: "Capital Tiles",
    colours: ["Ironbark", "Grey"],
    finishes: ["Smooth", "Textured"],
    sizes: [],
  },
  {
    name: "French Beige",
    handle: "french-beige",
    blurb: "French Beige combines elegant aesthetics with high-performance features designed for modern living. With its waterproof properties, natural warmth, ac",
    brand: "Capital Tiles",
    colours: ["Beige"],
    finishes: ["Brushed", "Natural"],
    sizes: [],
  },
  {
    name: "Flannel Grey",
    handle: "flannel-grey",
    blurb: "Flannel Grey is a versatile and durable hybrid flooring solution that combines modern aesthetics with everyday practicality. Its waterproof constructi",
    brand: "Capital Tiles",
    colours: ["Grey"],
    finishes: ["Matt", "Natural"],
    sizes: [],
  },
  {
    name: "Coral Sand",
    handle: "coral-sand",
    blurb: "Coral Sand is where modern performance meets natural elegance. With exceptional waterproofing and warm timber underfoot, it enhances comfort in any sp",
    brand: "Capital Tiles",
    colours: ["Sand"],
    finishes: ["Brushed", "Natural"],
    sizes: ["600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Classic Oak",
    handle: "classic-oak",
    blurb: "Classic Oak – Traditional Timber Elegance with Modern Performance Classic Oak engineered timber flooring brings the warmth of natural oak together wit",
    brand: "Capital Tiles",
    colours: ["Oak"],
    finishes: ["Brushed", "Rustic", "Natural"],
    sizes: [],
  },
  {
    name: "Casper White",
    handle: "casper-white",
    blurb: "Timeless Elegance Meets Everyday Performance Casper White is a premium engineered timber floor designed to bring refined beauty and durable performanc",
    brand: "Capital Tiles",
    colours: ["White"],
    finishes: ["Brushed", "Natural"],
    sizes: ["600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Beige Ash",
    handle: "beige-ash",
    blurb: "Beige Ash combines timeless elegance with reliable performance. With its waterproof surface, warm natural timber feel, and acoustic benefits, it's a p",
    brand: "Capital Tiles",
    colours: ["Beige", "Ash"],
    finishes: ["Brushed", "Natural"],
    sizes: ["1900 x 190 x 15mm", "600 x 120 x 15mm"],
  },
  {
    name: "Basset Brown",
    handle: "basset-brown",
    blurb: "Basset Brown offers timeless elegance with the strength and performance of engineered timber. Designed for real-world living, it features a water-resi",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Brushed", "Natural"],
    sizes: [],
  },
  {
    name: "Antique White",
    handle: "antique-white",
    blurb: "Antique White offers a perfect blend of timeless charm and practical innovation. Its waterproof construction and natural warmth make it ideal for cozy",
    brand: "Capital Tiles",
    colours: ["White"],
    finishes: ["Brushed", "Matt", "Natural"],
    sizes: ["1900 x 190 x 15mm", "600 x 90 x 15mm", "600 x 120 x 15mm"],
  },
  {
    name: "Antique Brown",
    handle: "antique-brown",
    blurb: "Antique Brown delivers timeless character with engineered performance. Crafted for modern living, it features water-resistant timber construction, war",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Brushed", "Natural"],
    sizes: [],
  },
  {
    name: "Almond White",
    handle: "almond-white",
    blurb: "Almond White delivers timeless elegance and practical performance in one beautiful flooring solution. Its waterproof core makes it ideal for wet areas",
    brand: "Capital Tiles",
    colours: ["White"],
    finishes: ["Natural"],
    sizes: [],
  },
  {
    name: "Acorn Brown",
    handle: "acorn-brown",
    blurb: "Acorn Brown offers a luxurious timber flooring experience with the benefits of waterproof durability, natural warmth, and enhanced acoustic comfort. A",
    brand: "Capital Tiles",
    colours: ["Brown"],
    finishes: ["Brushed", "Rustic", "Natural"],
    sizes: ["600 x 90 x 15mm", "600 x 120 x 15mm", "1900 x 190 x 15mm"],
  },
  {
    name: "Charcoal Grey",
    handle: "charcoal-grey",
    blurb: "Charcoal Grey brings modern depth and texture to any interior while delivering premium performance. With a water-resistant core, natural oak veneer, a",
    brand: "Capital Tiles",
    colours: ["Charcoal", "Grey"],
    finishes: ["Brushed", "Matt", "Natural"],
    sizes: [],
  },
  {
    name: "Pacific Spotted Gum",
    handle: "pacific-spotted-gum",
    blurb: "Pacific Spotted Gum – Natural Timber Appeal with Next-Gen Performance Bring timeless Australian character into your space with Pacific Spotted Gum 6.5",
    brand: "Capital Tiles",
    colours: ["Spotted Gum"],
    finishes: ["Matt", "Natural"],
    sizes: [],
  },
]
