/* Solution dyed nylon carpet range, taken from the live capitaltiles.com.au solution-dyed-nylon collection:
   names, blurbs, brands and the colour / finish / size options each product
   actually ships with. */

export const NYLON = [
  {
    name: "Balmain",
    handle: "balmain",
    blurb: "Balmain is a solution dyed nylon carpet featuring a chunky loop pile design that brings both comfort and character to your space. Its distinctive text",
    brand: "God Freyhirst",
    colours: ["Beechwood", "Rye", "Lotus", "Pebble Bay", "Riversand", "Ashwood", "Boulevard", "Grey Beam"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Westpoint",
    handle: "westpoint",
    blurb: "Westpoint has been designed with durability in mind. This beautifully soft range comes in a wide colour palette that will add style and texture to you",
    brand: "God Freyhirst",
    colours: ["Lieutenant", "Union", "Colonial", "Officer", "Defence", "Cadet", "General", "Captain", "Academy", "Fort"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Otway Lodge",
    handle: "otway-lodge",
    blurb: "Otway Lodge is a solution dyed nylon carpet with a textured loop pile design. This carpet instantly provides a peaceful ambience to any room, with a l",
    brand: "God Freyhirst",
    colours: ["Cascade", "Beachside", "Haven", "Ocean View", "Lakeshore", "Kookaburra", "Riverbed", "Coastline", "Creek", "Koala", "Gorge"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Bridgeport",
    handle: "bridgeport",
    blurb: "Bridgeport offers a versatile palette to suit any décor with a range of on trend colours including beautiful neutrals and moody rich tones. This soft,",
    brand: "God Freyhirst",
    colours: ["Cloud", "Porcelain", "Surfmist", "Smokehaze", "Vapour", "Starling", "Mineral", "Steeple", "Truffle", "Carbon"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Beechmont",
    handle: "beechmont",
    blurb: "Settle in with Beechmont, a solution dyed nylon carpet, that combines durability and comfort. With a textured level loop design and a neutral colour r",
    brand: "God Freyhirst",
    colours: ["White Beech", "Scenic Rim", "Graceleigh Park", "Mountain Soil", "Nerang River"],
    finishes: ["Level Loop", "Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Mystic Charm II",
    handle: "mystic-charm-ii",
    blurb: "Designed with durability in mind, Mystic Charm II by Godfrey Hirst is a cut pile twist that adds subtle texture to the floor. This Australian Made Sol",
    brand: "God Freyhirst",
    colours: ["Bone", "Canvas", "Mushroom", "Grey Haze", "Tin", "Battleship", "Metallic", "Sable", "Earthstone", "Dolomite"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Marylebone",
    handle: "marylebone",
    blurb: "Marylebone is a divinely soft and durable carpet that can handle the demands of a busy family home. This soft solution dyed nylon carpet is finished i",
    brand: "God Freyhirst",
    colours: ["West End", "Baker Street", "Portman Estate", "Westminster", "Spanish Place", "Nottingham Place", "Chandos House", "Upper Wimpole", "Cavendish Square", "Fitzrovia", "Tyburn", "Wigmore Hall"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Beaucastle",
    handle: "beaucastle",
    blurb: "Inspired by the hand-crafted rooftops of renaissance French chateaus, Beaucastle promises raw beauty and earthy charm. The patterned textured loop pil",
    brand: "God Freyhirst",
    colours: ["Timber", "Sandstone", "Asteroid", "Arctic Mist", "Woodash", "Sable"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Monte Bello",
    handle: "monte-bello",
    blurb: "Monte Bello is a supremly soft solution dyed nylon carpet. With colours inspired by nature's palette, this cut pile twist is one of the best carpets f",
    brand: "God Freyhirst",
    colours: ["Curlew", "Seagrass", "Cascade", "Limestone", "Channel", "Acacia", "Harbour", "Cove", "Mangrove", "Sheltered Bay", "Sea Eagle", "Mineral", "Oyster", "Dock"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Refined Appeal",
    handle: "refined-appeal",
    blurb: "Refined Appeal is a solution dyed nylon carpet in a stylish cut pile twist construction. Soft, resilient and durable, this is a neutral and affordable",
    brand: "God Freyhirst",
    colours: ["Amulet Stipple", "Saddle Stipple", "Quartz", "Sand", "Soft Taupe", "Silver Mist", "Mushroom", "Pewter", "Dark Cloud", "Thunder", "Slate"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Fiesta",
    handle: "fiesta",
    blurb: "Fiesta is a practical solution dyed nylon carpet in a stylish cut pile twist style. Soft, resilient and durable, this is a great, affordable flooring ",
    brand: "God Freyhirst",
    colours: ["Earthston", "Mosaic", "Lanolin", "Chalk", "Amulet", "Agate", "Oyster", "Grey Haze", "Lexington", "Urban"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Bayside",
    handle: "bayside",
    blurb: "Mixing comfort and durability, Bayside is a solution dyed nylon carpet, in a cut pile twist style. Feel peace of mind with this carpet’s resistance to",
    brand: "God Freyhirst",
    colours: ["Ivory Coast", "Beach Shell", "Canvas Wash", "Cork", "Tumbleweed", "Ghost Grey", "Overcast", "Mist", "Cloud", "Blue Fox", "Pewter", "Granite"],
    finishes: ["Cut Pile", "Twist", "Stipple"],
    sizes: [],
  },
  {
    name: "Modern Texture",
    handle: "modern-texture",
    blurb: "With durability, stain and fade resistance, Modern Texture is a solution dyed nylon carpet that will last. Details Fibre : Solution Dyed Nylon Carpet ",
    brand: "God Freyhirst",
    colours: ["Ivory", "Bamboo", "Light Smoke", "Morning Fog", "Claystone", "Silver Drop", "Zinc", "Dark Granite"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Supreme Touch",
    handle: "supreme-touch",
    blurb: "Supreme Touch is a cut pile twist offering a natural colour palette of carpet colours from light sands to deep stones. As part of the Luxury collectio",
    brand: "God Freyhirst",
    colours: ["Mushroom Stipple", "Chestnut", "Boulder Stipple", "Fawn", "Sand Dune", "Quartz", "Stoneware", "Fog", "Abalone", "Silverado", "Concrete", "Beacon", "Winter Grey", "Dark Mood"],
    finishes: ["Cut Pile", "Twist", "Textured"],
    sizes: [],
  },
  {
    name: "Venture",
    handle: "venture",
    blurb: "Venture is a solution dyed nylon carpet in a stylish cut pile twist style. Soft, resilient and durable, this neutral and affordable flooring option is",
    brand: "God Freyhirst",
    colours: ["Chamois", "Neutral", "Soft Leather", "Grey Haze", "Magma", "Paving", "Gravel", "Tundra"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Timeless",
    handle: "timeless",
    blurb: "Timeless is the perfect way to bring luxurious softness to any home interior. A cut pile twist carpet with a natural stony palette, it's exquisitely s",
    brand: "God Freyhirst",
    colours: ["Moonrock Stipple", "Fudge", "Oakheart Stipple", "Brushed Cotton", "Old Parchment", "Stone Beige", "Tan", "Barley", "Meadow", "Dawn", "Glacier Grey", "Light Shadow", "Urban Grey"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Apollo Ridge",
    handle: "apollo-ridge",
    blurb: "Apollo Ridge is a 100% Solution Dyed PET Polyester carpet, designed to created a comfortable and stylish home with affordability in mind. Its combinat",
    brand: "God Freyhirst",
    colours: ["Sandstone", "Vintage", "Silver Haze", "Mineral Stipple", "Slate", "Storm Grey", "Charcoal"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Elegant Reflections",
    handle: "elegant-reflections",
    blurb: "With a couple of stippled colours in the palette for added interest, Elegant Reflections is wonderfully soft and comfortable underfoot. Details Style:",
    brand: "God Freyhirst",
    colours: ["Brown Tweed", "Cargo Stipple", "Ironstone", "Shale Stipple", "Ceramic", "Sandrock", "Warm Beige", "Wind Spray", "Cloudy Day", "Cobblestone", "Cold Mountain", "Dark Shadow"],
    finishes: ["Cut Pile", "Twist", "Stipple"],
    sizes: [],
  },
  {
    name: "Country Lane",
    handle: "country-lane",
    blurb: "Country Lane is a classic textured loop pile carpet that combines style and performance. This range is Declare LBC Red List Free and features five tim",
    brand: "God Freyhirst",
    colours: ["Fresh Linen", "Daisy", "Meadow", "Province", "Iron Gate"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Cool Charm",
    handle: "cool-charm",
    blurb: "Cool Charm is a solution dyed nylon carpet in a stylish cut pile twist style. Soft, resilient and durable, this is a neutral and affordable flooring o",
    brand: "God Freyhirst",
    colours: ["Braid", "Amulet Stipple", "Celtic Brown", "Tribal Stipple", "Porcelain", "Chalkstone", "Stone Pillar", "Atmosphere", "Andriod", "Stonewashed", "Steel Mesh", "Seal Fur"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Covent Garden",
    handle: "covent-garden",
    blurb: "Covent Garden will bring luxurious softness and style to your home. A cut pile twist carpet with a palette of natural earthy tones, Covent Garden is d",
    brand: "God Freyhirst",
    colours: ["Soft Leather", "Kenya Blend", "Sun Dew", "Lotus Petal", "Claystone", "Sandrock", "Ice Grey", "Stone Pillar", "Steel Facade", "Seal"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Acacia Hill",
    handle: "acacia-hill",
    blurb: "Discover the combination of practicality and sophistication with Acacia Hill. This nylon soft flooring has a natural look and rich texture which is ea",
    brand: "EC carpets",
    colours: ["Alton 1249", "Kennedy 1250", "Atkins 1253", "Mawson 1251", "Millrose 1255", "Longford 1252", "Karson 1254", "Myrtle 1256", "Magnolia 1248"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Andes Peak",
    handle: "andes-peak",
    blurb: "Andes Peak offers wool-like elegance featuring a subtly heathered texture. Its neutral colour palette complements any interior design, while its durab",
    brand: "EC carpets",
    colours: ["Olca 2404", "Patilla 2406", "Serena 2433", "Merida 2421", "Isabel 2403", "Valera 2455", "Rio 2451", "Rubio 2458", "Hudson 2425", "Mendoza 2419", "Morado 2416", "Patagonia 2422"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Avenue",
    handle: "avenue",
    blurb: "Avenue combines nylon’s practicality with the aesthetic qualities of natural fibres. Its rich texture hides stains effectively and with modern colours",
    brand: "EC carpets",
    colours: ["Milton 1149", "Rayne 1150", "Rothbury 1153", "Sherwood 1151", "Bevington 1155", "Ashbourne 1152", "Cudmore 1154", "Moorhouse 1156", "Morland 1148"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Ayrton",
    handle: "ayrton",
    blurb: "The striated pattern and earthy tones of Ayrton go beyond mere functionality. Its design not only withstands abrasion but also displays a luxurious ae",
    brand: "EC carpets",
    colours: ["Monaco 4619", "Montreal 4641", "Silverstone 4628", "Francor 4638", "Quebec 4604", "Monza 4626", "Emilia 4637", "Suzuka 4632", "Toleman 4607"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Birdwood",
    handle: "birdwood",
    blurb: "Experience unparalleled appearance longevity with our Birdwood range, crafted to preserve its flawless allure every day. Combining the aesthetic of a ",
    brand: "EC carpets",
    colours: ["Angas 2962", "Teralinga 2961", "Blumberg 2952", "Cromer 2955", "Hannaford 2953", "Carnell 2963", "Yallam 2964", "Canham 2965"],
    finishes: ["Loop Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Bordeaux",
    handle: "bordeaux",
    blurb: "Experience unparalleled appearance longevity with our Birdwood range, crafted to preserve its flawless allure every day. Combining the aesthetic of a ",
    brand: "EC carpets",
    colours: ["Lorient 4524", "Savinne 4525", "Paulin 4514", "Estera 4550", "Colette 4521", "Pascal 4543", "Pessac 4535", "Berland 4552", "Velmont 4548", "Emilion 4553"],
    finishes: ["Loop Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Bouclé",
    handle: "boucle",
    blurb: "Bouclé offers a touch of wool-like elegance, reminiscent of the European textile texture, bouclé. Combined with a beautiful colour palette, it provide",
    brand: "EC carpets",
    colours: ["Ovie+4304", "Sarinen+4303", "Jacqueline+4342", "Mokum+4347", "Fredrik+4348", "Shu+4315", "Atticus+4318", "Maymo+4308", "Coco+4336"],
    finishes: ["Boucle"],
    sizes: [],
  },
  {
    name: "Bourkesgate",
    handle: "bourkesgate",
    blurb: "Experience unparalleled appearance longevity with our Bourkesgate range, crafted to preserve its flawless allure every day. Combining the aesthetic of",
    brand: "EC carpets",
    colours: ["Kidman 1962", "Kamila 1961", "Cobb 1952", "Lawson 1955", "Paroo 1953", "Jandra 1963", "Namoi 1964", "Louth 1965"],
    finishes: ["Loop Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Coco Bliss",
    handle: "coco-bliss",
    blurb: "Coco Bliss is a premium twist pile carpet designed for style and performance. Its resilient and dense construction offers exceptional durability, maki",
    brand: "EC carpets",
    colours: ["Felicity 9042", "Joy 9043", "Happiness+9037", "Epiphany+9031", "Euphoria+9012", "Delight+9025", "Elation+9024", "Nostalgia+9023", "Gratitude+9028", "Contentment+9018"],
    finishes: ["Twist"],
    sizes: [],
  },
  {
    name: "Comfort Touch",
    handle: "comfort-touch",
    blurb: "Comfort Touch is a luxurious twist pile carpet designed for ultimate comfort and softness underfoot. Its plush texture offers exceptional durability y",
    brand: "EC carpets",
    colours: ["Humble 9142", "Relax 9143", "Zen 9137", "Warmth 9131", "Ease 9112", "Charm 9125", "Peace 9124", "Quiet 9123", "Mood 9128", "Snug 9118"],
    finishes: ["Twist", "Plush"],
    sizes: [],
  },
  {
    name: "District Loft",
    handle: "district-loft",
    blurb: "District Loft tis a modern entry-level cut pile carpet offering comfort and dependable performance in a practical 30oz construction. Its 1/10 gauge co",
    brand: "EC carpets",
    colours: ["Quarter 9242", "Precinct 9243", "Local 9237", "Bureau 9231", "Foundry 9212", "Urban 9225", "City 9224", "Metro 9223", "Assembly 9228", "Forge 9218"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Flinders Gorge",
    handle: "flinders-gorge",
    blurb: "Flinders Gorge offers high-quality and affordability with a rich texture resembling wool. Its neutral palette blends seamlessly with modern interiors,",
    brand: "EC carpets",
    colours: ["Blanche 3404", "Beltana 3406", "Olary 3433", "Warren 3421", "Calla 3403", "Hawker 3455", "Havelock 3451", "Tanderra 3458", "Leigh 3425", "Copley 3419", "Amyton 3416", "Rawnsley 3422"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Langhorne Hut",
    handle: "langhorne-hut",
    blurb: "Langhorne Hut characterises resilience, combining durability with elegance for residential and commercial use. Its tough design retains a modern style",
    brand: "EC carpets",
    colours: ["Chapel 1906", "Bertol 1916", "Arbol 1913", "Hanok 1917", "Orri 1901", "Solvay 1915", "Sheoak 1908", "Borrett 1905"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Orchard",
    handle: "orchard",
    blurb: "Orchards’ combination of chic design with durability, elevates spaces with earthy colours and a striated pattern. Its construction mirrors the eleganc",
    brand: "EC carpets",
    colours: ["Akane 2619", "Calville 2641", "Sansa 2628", "Melrose 2638", "Cortland 2604", "Cameo 2626", "Ida 2637", "Jonamac 2632", "Ashmead 2607"],
    finishes: ["Plush"],
    sizes: [],
  },
  {
    name: "Tunes",
    handle: "tunes",
    blurb: "Experience the appeal of beautiful organic tones, twisted in a striated pattern. Displaying unrivalled durability, this combination of nature-inspired",
    brand: "EC carpets",
    colours: ["Classical 9719", "Country 9741", "Legato 9728", "Jazz 9738", "Scalar 9704", "Pop 9726", "Blues 9737", "Disco 9732", "Chromatic 9707"],
    finishes: ["Twist"],
    sizes: [],
  },
]
