/* Solution Dyed Nylon product detail data.

   Style, fibre, roll width, thickness, ratings and the descriptions come
   from the live capitaltiles.com.au feed for this collection. Generated —
   edit the source data, not this file.
*/

export const NYLON_PRODUCTS = [
  {
    handle: "balmain",
    name: "Balmain",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/balmain.jpg",
    images: [
      "/img/solution-dyed-nylon/balmain/1.jpg",
      "/img/solution-dyed-nylon/balmain/2.jpg",
      "/img/solution-dyed-nylon/balmain/3.jpg",
      "/img/solution-dyed-nylon/balmain/4.jpg",
      "/img/solution-dyed-nylon/balmain/5.jpg",
      "/img/solution-dyed-nylon/balmain/6.jpg",
      "/img/solution-dyed-nylon/balmain/7.jpg",
      "/img/solution-dyed-nylon/balmain/8.jpg",
      "/img/solution-dyed-nylon/balmain/9.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 8 colours",
    short: "Balmain Solution Dyed Nylon Carpet by Godfrey Hirst. 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Balmain is a Solution Dyed Nylon Carpet featuring a chunky loop pile design that brings both comfort and character to your space. Its distinctive texture creates a tactile, grounded feel underfoot, perfect for adding warmth and visual interest to any room. The textured loop construction adds natural depth and works beautifully with raw materials and earthy tones, making it an ideal choice for layered, contemporary interiors. To experience the beautifully textured finish of Balmain for yourself, you can order free samples via the button on the image above.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs 6 Star Contract Light Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty^ Stain Resistance Wear Resistance Fade Resistance Mid Range Textured Loop Pile",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs 6 Star",
      "Contract Light Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty^",
    ],
    seoTitle: "Balmain | Capital Tiles",
    seoDesc: "Balmain, 8 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Beechwood", "Rye", "Lotus", "Pebble Bay", "Riversand", "Ashwood", "Boulevard", "Grey Beam"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: ["9.5 (+/- 1.0)mm"],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed Nylon"],
      ["Gauge", "10.5/10cm (3/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "9.5 (+/- 1.0)mm"],
      ["Pile Height", "7.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "westpoint",
    name: "Westpoint",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/westpoint.jpg",
    images: [
      "/img/solution-dyed-nylon/westpoint/1.jpg",
      "/img/solution-dyed-nylon/westpoint/2.jpg",
      "/img/solution-dyed-nylon/westpoint/3.jpg",
      "/img/solution-dyed-nylon/westpoint/4.jpg",
      "/img/solution-dyed-nylon/westpoint/5.jpg",
      "/img/solution-dyed-nylon/westpoint/6.jpg",
      "/img/solution-dyed-nylon/westpoint/7.jpg",
      "/img/solution-dyed-nylon/westpoint/8.jpg",
      "/img/solution-dyed-nylon/westpoint/9.jpg",
      "/img/solution-dyed-nylon/westpoint/10.jpg",
      "/img/solution-dyed-nylon/westpoint/11.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 10 colours",
    short: "Westpoint Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Westpoint has been designed with durability in mind. This beautifully soft range comes in a wide colour palette that will add style and texture to your floor.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty Stain Resistance Wear Resistance Fade Resistance Fire Rated Carpet Cut Pile Twist $$ Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty",
    ],
    seoTitle: "Westpoint | Capital Tiles",
    seoDesc: "Westpoint, Cut Pile Twist, 10 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Lieutenant", "Union", "Colonial", "Officer", "Defence", "Cadet", "General", "Captain", "Academy", "Fort"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: ["14 (+/- 1.0)mm"],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed Nylon"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "14 (+/- 1.0)mm"],
      ["Pile Height", "12 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "otway-lodge",
    name: "Otway Lodge",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/otway-lodge.jpg",
    images: [
      "/img/solution-dyed-nylon/otway-lodge/1.jpg",
      "/img/solution-dyed-nylon/otway-lodge/2.jpg",
      "/img/solution-dyed-nylon/otway-lodge/3.jpg",
      "/img/solution-dyed-nylon/otway-lodge/4.jpg",
      "/img/solution-dyed-nylon/otway-lodge/5.jpg",
      "/img/solution-dyed-nylon/otway-lodge/6.jpg",
      "/img/solution-dyed-nylon/otway-lodge/7.jpg",
      "/img/solution-dyed-nylon/otway-lodge/8.jpg",
      "/img/solution-dyed-nylon/otway-lodge/9.jpg",
      "/img/solution-dyed-nylon/otway-lodge/10.jpg",
      "/img/solution-dyed-nylon/otway-lodge/11.jpg",
      "/img/solution-dyed-nylon/otway-lodge/12.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 11 colours",
    short: "Otway Lodge Solution Dyed Nylon Carpet by Godfrey Hirst. 3.66m roll width and 11 colours. Supplied and laid across Canberra.",
    overview: [
      "Otway Lodge is a Solution Dyed Nylon Carpet with a textured loop pile design. This carpet instantly provides a peaceful ambience to any room, with a luxurious and cosy feel underfoot. The loop pile's texture adds depth and dimension to your space, complementing organic surfaces, fabrics and furnishings to layer with. To experience the unique feel of Otway Lodge for yourself, you can order free samples via the button on the image above.",
      "Godfrey Hirst Best Seller Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs-6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Textured Loop Pile Mid Range",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs-6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
    ],
    seoTitle: "Otway Lodge | Capital Tiles",
    seoDesc: "Otway Lodge, 11 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Cascade", "Beachside", "Haven", "Ocean View", "Lakeshore", "Kookaburra", "Riverbed", "Coastline", "Creek", "Koala", "Gorge"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: ["11 (+/- 1.0)mm"],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed Nylon"],
      ["Gauge", "10.5/10cm (3/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "11 (+/- 1.0)mm"],
      ["Pile Height", "9 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "11"],
    ],
    rooms: [],
  },
  {
    handle: "bridgeport",
    name: "Bridgeport",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/bridgeport.jpg",
    images: [
      "/img/solution-dyed-nylon/bridgeport/1.jpg",
      "/img/solution-dyed-nylon/bridgeport/2.jpg",
      "/img/solution-dyed-nylon/bridgeport/3.jpg",
      "/img/solution-dyed-nylon/bridgeport/4.jpg",
      "/img/solution-dyed-nylon/bridgeport/5.jpg",
      "/img/solution-dyed-nylon/bridgeport/6.jpg",
      "/img/solution-dyed-nylon/bridgeport/7.jpg",
      "/img/solution-dyed-nylon/bridgeport/8.jpg",
      "/img/solution-dyed-nylon/bridgeport/9.jpg",
      "/img/solution-dyed-nylon/bridgeport/10.jpg",
      "/img/solution-dyed-nylon/bridgeport/11.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 10 colours",
    short: "Bridgeport Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Bridgeport offers a versatile palette to suit any décor with a range of on trend colours including beautiful neutrals and moody rich tones. This soft, hardwearing carpet is durable to withstand everyday life.",
      "Australian Made Declare Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty",
    ],
    seoTitle: "Bridgeport | Capital Tiles",
    seoDesc: "Bridgeport, Cut Pile Twist, 10 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Cloud", "Porcelain", "Surfmist", "Smokehaze", "Vapour", "Starling", "Mineral", "Steeple", "Truffle", "Carbon"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: ["12 (+/- 1.0)mm"],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed Nylon"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "12 (+/- 1.0)mm"],
      ["Pile Height", "10 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "beechmont",
    name: "Beechmont",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/beechmont.jpg",
    images: [
      "/img/solution-dyed-nylon/beechmont/1.jpg",
      "/img/solution-dyed-nylon/beechmont/2.jpg",
      "/img/solution-dyed-nylon/beechmont/3.jpg",
      "/img/solution-dyed-nylon/beechmont/4.jpg",
      "/img/solution-dyed-nylon/beechmont/5.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 5 colours",
    short: "Beechmont Solution Dyed Nylon Carpet by Godfrey Hirst. 3.66m roll width and 5 colours. Supplied and laid across Canberra.",
    overview: [
      "Settle in with Beechmont, a Solution Dyed Nylon Carpet, that combines durability and comfort. With a textured level loop design and a neutral colour range, this carpet provides a stylish foundation to your busy home. Beechmont is resistant to stains, wear and fading, ideal for high traffic hallways and living spaces.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Textured Loop Pile Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Beechmont | Capital Tiles",
    seoDesc: "Beechmont, 5 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["White Beech", "Scenic Rim", "Graceleigh Park", "Mountain Soil", "Nerang River"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed Nylon"],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "8.5 (+/- 1.0)mm"],
      ["Pile Height", "6.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "5"],
    ],
    rooms: [],
  },
  {
    handle: "mystic-charm-ii",
    name: "Mystic Charm II",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/mystic-charm-ii.jpg",
    images: [
      "/img/solution-dyed-nylon/mystic-charm-ii/1.jpg",
      "/img/solution-dyed-nylon/mystic-charm-ii/2.jpg",
      "/img/solution-dyed-nylon/mystic-charm-ii/3.jpg",
      "/img/solution-dyed-nylon/mystic-charm-ii/4.jpg",
      "/img/solution-dyed-nylon/mystic-charm-ii/5.jpg",
      "/img/solution-dyed-nylon/mystic-charm-ii/6.jpg",
      "/img/solution-dyed-nylon/mystic-charm-ii/7.jpg",
      "/img/solution-dyed-nylon/mystic-charm-ii/8.jpg",
      "/img/solution-dyed-nylon/mystic-charm-ii/9.jpg",
      "/img/solution-dyed-nylon/mystic-charm-ii/10.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 10 colours",
    short: "Mystic Charm II Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Designed with durability in mind, Mystic Charm II by Godfrey Hirst is a Cut Pile Twist that adds subtle texture to the floor. This Australian Made Solution Dyed Nylon features a beautiful, yet functional colour palette of light and dark neutrals.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* ISO 9001 Quality Management System ISO 14001 Environment Management System Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Affordable",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Mystic Charm II | Capital Tiles",
    seoDesc: "Mystic Charm II, Cut Pile Twist, 10 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Bone", "Canvas", "Mushroom", "Grey Haze", "Tin", "Battleship", "Metallic", "Sable", "Earthstone", "Dolomite"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed Nylon"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "10 (+/- 1.0)mm"],
      ["Pile Height", "8 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "marylebone",
    name: "Marylebone",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/marylebone.jpg",
    images: [
      "/img/solution-dyed-nylon/marylebone/1.jpg",
      "/img/solution-dyed-nylon/marylebone/2.jpg",
      "/img/solution-dyed-nylon/marylebone/3.jpg",
      "/img/solution-dyed-nylon/marylebone/4.jpg",
      "/img/solution-dyed-nylon/marylebone/5.jpg",
      "/img/solution-dyed-nylon/marylebone/6.jpg",
      "/img/solution-dyed-nylon/marylebone/7.jpg",
      "/img/solution-dyed-nylon/marylebone/8.jpg",
      "/img/solution-dyed-nylon/marylebone/9.jpg",
      "/img/solution-dyed-nylon/marylebone/10.jpg",
      "/img/solution-dyed-nylon/marylebone/11.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 12 colours",
    short: "Marylebone Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 12 colours. Supplied and laid across Canberra.",
    overview: [
      "Marylebone is a divinely soft and durable carpet that can handle the demands of a busy family home. This soft Solution Dyed Nylon Carpet is finished in a delightfully thick cut pile style and is available in range of colours inspired by nature to compliment any interior. Marylebone brings luxury and enduring style into your home, delivering comfort and peace of mind with resistance to wear, stains, soiling and fading.",
    ],
    features: [
      "Style: Cut Pile Twist",
      "Fibre: Solution Dyed Nylon Carpet",
      "Roll width: 3.66m",
      "Pile height: 15 (+/- 1.0)mm",
      "12 colours in the range",
    ],
    seoTitle: "Marylebone | Capital Tiles",
    seoDesc: "Marylebone, Cut Pile Twist, 12 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "West End",
      "Baker Street",
      "Portman Estate",
      "Westminster",
      "Spanish Place",
      "Nottingham Place",
      "Chandos House",
      "Upper Wimpole",
      "Cavendish Square",
      "Fitzrovia",
      "Tyburn",
      "Wigmore Hall",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Soft Solution Dyed Nylon"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "17 (+/- 1.0)mm"],
      ["Pile Height", "15 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "12"],
    ],
    rooms: [],
  },
  {
    handle: "beaucastle",
    name: "Beaucastle",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/beaucastle.jpg",
    images: [
      "/img/solution-dyed-nylon/beaucastle/1.jpg",
      "/img/solution-dyed-nylon/beaucastle/2.jpg",
      "/img/solution-dyed-nylon/beaucastle/3.jpg",
      "/img/solution-dyed-nylon/beaucastle/4.jpg",
      "/img/solution-dyed-nylon/beaucastle/5.jpg",
      "/img/solution-dyed-nylon/beaucastle/6.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 6 colours",
    short: "Beaucastle Solution Dyed Nylon Carpet by Godfrey Hirst. 3.66m roll width and 6 colours. Supplied and laid across Canberra.",
    overview: [
      "Inspired by the hand-crafted rooftops of renaissance French chateaus, Beaucastle promises raw beauty and earthy charm. The patterned textured loop pile creates a distinct uniform texture that won't show tracks, making it an inspired selection for high traffic rooms. Made in Australia from durable solution dyed nylon, Beaucastle is stain resistant, fade resistant and perfect for family homes.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Textured Loop Pile Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Beaucastle | Capital Tiles",
    seoDesc: "Beaucastle, 6 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Timber", "Sandstone", "Asteroid", "Arctic Mist", "Woodash", "Sable"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed Nylon"],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "7.5 (+/- 1.0)mm"],
      ["Pile Height", "5.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "6"],
    ],
    rooms: [],
  },
  {
    handle: "monte-bello",
    name: "Monte Bello",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/monte-bello.jpg",
    images: [
      "/img/solution-dyed-nylon/monte-bello/1.jpg",
      "/img/solution-dyed-nylon/monte-bello/2.jpg",
      "/img/solution-dyed-nylon/monte-bello/3.jpg",
      "/img/solution-dyed-nylon/monte-bello/4.jpg",
      "/img/solution-dyed-nylon/monte-bello/5.jpg",
      "/img/solution-dyed-nylon/monte-bello/6.jpg",
      "/img/solution-dyed-nylon/monte-bello/7.jpg",
      "/img/solution-dyed-nylon/monte-bello/8.jpg",
      "/img/solution-dyed-nylon/monte-bello/9.jpg",
      "/img/solution-dyed-nylon/monte-bello/10.jpg",
      "/img/solution-dyed-nylon/monte-bello/11.jpg",
      "/img/solution-dyed-nylon/monte-bello/12.jpg",
      "/img/solution-dyed-nylon/monte-bello/13.jpg",
      "/img/solution-dyed-nylon/monte-bello/14.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 14 colours",
    short: "Monte Bello Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 14 colours. Supplied and laid across Canberra.",
    overview: [
      "Monte Bello is a supremly soft Solution Dyed Nylon Carpet. With colours inspired by nature's palette, this Cut Pile Twist is one of the best carpets for luxurious living, delivering comfort and peace of mind with resistance to wear, stains, soiling and fading.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Premium",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Monte Bello | Capital Tiles",
    seoDesc: "Monte Bello, Cut Pile Twist, 14 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Curlew",
      "Seagrass",
      "Cascade",
      "Limestone",
      "Channel",
      "Acacia",
      "Harbour",
      "Cove",
      "Mangrove",
      "Sheltered Bay",
      "Sea Eagle",
      "Mineral",
      "Oyster",
      "Dock",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Soft Solution Dyed Nylon"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "14 (+/- 1.0)mm"],
      ["Pile Height", "12 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "14"],
    ],
    rooms: [],
  },
  {
    handle: "refined-appeal",
    name: "Refined Appeal",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/refined-appeal.jpg",
    images: [
      "/img/solution-dyed-nylon/refined-appeal/1.jpg",
      "/img/solution-dyed-nylon/refined-appeal/2.jpg",
      "/img/solution-dyed-nylon/refined-appeal/3.jpg",
      "/img/solution-dyed-nylon/refined-appeal/4.jpg",
      "/img/solution-dyed-nylon/refined-appeal/5.jpg",
      "/img/solution-dyed-nylon/refined-appeal/6.jpg",
      "/img/solution-dyed-nylon/refined-appeal/7.jpg",
      "/img/solution-dyed-nylon/refined-appeal/8.jpg",
      "/img/solution-dyed-nylon/refined-appeal/9.jpg",
      "/img/solution-dyed-nylon/refined-appeal/10.jpg",
      "/img/solution-dyed-nylon/refined-appeal/11.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 11 colours",
    short: "Refined Appeal Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 11 colours. Supplied and laid across Canberra.",
    overview: [
      "Refined Appeal is a Solution Dyed Nylon Carpet in a stylish Cut Pile Twist construction. Soft, resilient and durable, this is a neutral and affordable flooring option.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Refined Appeal | Capital Tiles",
    seoDesc: "Refined Appeal, Cut Pile Twist, 11 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Amulet Stipple",
      "Saddle Stipple",
      "Quartz",
      "Sand",
      "Soft Taupe",
      "Silver Mist",
      "Mushroom",
      "Pewter",
      "Dark Cloud",
      "Thunder",
      "Slate",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Soft Solution Dyed Nylon"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "11.5 (+/- 1.0)mm"],
      ["Pile Height", "9.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "11"],
    ],
    rooms: [],
  },
  {
    handle: "fiesta",
    name: "Fiesta",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/fiesta.jpg",
    images: [
      "/img/solution-dyed-nylon/fiesta/1.jpg",
      "/img/solution-dyed-nylon/fiesta/2.jpg",
      "/img/solution-dyed-nylon/fiesta/3.jpg",
      "/img/solution-dyed-nylon/fiesta/4.jpg",
      "/img/solution-dyed-nylon/fiesta/5.jpg",
      "/img/solution-dyed-nylon/fiesta/6.jpg",
      "/img/solution-dyed-nylon/fiesta/7.jpg",
      "/img/solution-dyed-nylon/fiesta/8.jpg",
      "/img/solution-dyed-nylon/fiesta/9.jpg",
      "/img/solution-dyed-nylon/fiesta/10.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 10 colours",
    short: "Fiesta Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Fiesta is a practical Solution Dyed Nylon Carpet in a stylish Cut Pile Twist style. Soft, resilient and durable, this is a great, affordable flooring option.",
      "Godfrey Hirst Best Seller Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Mid Range",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
    ],
    seoTitle: "Fiesta | Capital Tiles",
    seoDesc: "Fiesta, Cut Pile Twist, 10 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Earthston", "Mosaic", "Lanolin", "Chalk", "Amulet", "Agate", "Oyster", "Grey Haze", "Lexington", "Urban"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Soft Solution Dyed Nylon"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "9.5 (+/- 1.0)mm"],
      ["Pile Height", "7.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "bayside",
    name: "Bayside",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/bayside.jpg",
    images: [
      "/img/solution-dyed-nylon/bayside/1.jpg",
      "/img/solution-dyed-nylon/bayside/2.jpg",
      "/img/solution-dyed-nylon/bayside/3.jpg",
      "/img/solution-dyed-nylon/bayside/4.jpg",
      "/img/solution-dyed-nylon/bayside/5.jpg",
      "/img/solution-dyed-nylon/bayside/6.jpg",
      "/img/solution-dyed-nylon/bayside/7.jpg",
      "/img/solution-dyed-nylon/bayside/8.jpg",
      "/img/solution-dyed-nylon/bayside/9.jpg",
      "/img/solution-dyed-nylon/bayside/10.jpg",
      "/img/solution-dyed-nylon/bayside/11.jpg",
      "/img/solution-dyed-nylon/bayside/12.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 12 colours",
    short: "Bayside Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 12 colours. Supplied and laid across Canberra.",
    overview: [
      "Mixing comfort and durability, Bayside is a Solution Dyed Nylon Carpet, in a Cut Pile Twist style. Feel peace of mind with this carpet's resistance to stains, fading and wear. Bayside's neutral and versatile stippled colour palette makes it the ideal foundation for a variety of interiors.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* ISO 9001 Quality Management System ISO 14001 Environment Management System Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Affordable",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Bayside | Capital Tiles",
    seoDesc: "Bayside, Cut Pile Twist, 12 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Ivory Coast",
      "Beach Shell",
      "Canvas Wash",
      "Cork",
      "Tumbleweed",
      "Ghost Grey",
      "Overcast",
      "Mist",
      "Cloud",
      "Blue Fox",
      "Pewter",
      "Granite",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Soft Solution Dyed Nylon"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "10.5 (+/- 1.0)mm"],
      ["Pile Height", "8.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "12"],
    ],
    rooms: [],
  },
  {
    handle: "modern-texture",
    name: "Modern Texture",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/modern-texture.jpg",
    images: [
      "/img/solution-dyed-nylon/modern-texture/1.jpg",
      "/img/solution-dyed-nylon/modern-texture/2.jpg",
      "/img/solution-dyed-nylon/modern-texture/3.jpg",
      "/img/solution-dyed-nylon/modern-texture/4.jpg",
      "/img/solution-dyed-nylon/modern-texture/5.jpg",
      "/img/solution-dyed-nylon/modern-texture/6.jpg",
      "/img/solution-dyed-nylon/modern-texture/7.jpg",
      "/img/solution-dyed-nylon/modern-texture/8.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 8 colours",
    short: "Modern Texture Solution Dyed Nylon Carpet by Godfrey Hirst. 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "With durability, stain and fade resistance, Modern Texture is a Solution Dyed Nylon Carpet that will last.",
      "Godfrey Hirst Best Seller Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ ISO 9001 Quality Management System 15 Year Premium Limited Residential Warranty* Fire Rated Carpet Stain Resistance Fade Resistance Wear Resistance Textured Loop Pile Affordable",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
    ],
    seoTitle: "Modern Texture | Capital Tiles",
    seoDesc: "Modern Texture, 8 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Ivory", "Bamboo", "Light Smoke", "Morning Fog", "Claystone", "Silver Drop", "Zinc", "Dark Granite"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Soft Solution Dyed Nylon"],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "9.5 (+/- 1.0)mm"],
      ["Pile Height", "7.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "supreme-touch",
    name: "Supreme Touch",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/supreme-touch.jpg",
    images: [
      "/img/solution-dyed-nylon/supreme-touch/1.jpg",
      "/img/solution-dyed-nylon/supreme-touch/2.jpg",
      "/img/solution-dyed-nylon/supreme-touch/3.jpg",
      "/img/solution-dyed-nylon/supreme-touch/4.jpg",
      "/img/solution-dyed-nylon/supreme-touch/5.jpg",
      "/img/solution-dyed-nylon/supreme-touch/6.jpg",
      "/img/solution-dyed-nylon/supreme-touch/7.jpg",
      "/img/solution-dyed-nylon/supreme-touch/8.jpg",
      "/img/solution-dyed-nylon/supreme-touch/9.jpg",
      "/img/solution-dyed-nylon/supreme-touch/10.jpg",
      "/img/solution-dyed-nylon/supreme-touch/11.jpg",
      "/img/solution-dyed-nylon/supreme-touch/12.jpg",
      "/img/solution-dyed-nylon/supreme-touch/13.jpg",
      "/img/solution-dyed-nylon/supreme-touch/14.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 14 colours",
    short: "Supreme Touch Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 14 colours. Supplied and laid across Canberra.",
    overview: [
      "Supreme Touch is a Cut Pile Twist offering a natural colour palette of carpet colours from light sands to deep stones. As part of the Luxury collection, this densely textured carpet is incredibly soft, durable, stain and fade resistant.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* ISO 9001 Quality Management System ISO 14001 Environment Management System Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Affordable",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Supreme Touch | Capital Tiles",
    seoDesc: "Supreme Touch, Cut Pile Twist, 14 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Mushroom Stipple",
      "Chestnut",
      "Boulder Stipple",
      "Fawn",
      "Sand Dune",
      "Quartz",
      "Stoneware",
      "Fog",
      "Abalone",
      "Silverado",
      "Concrete",
      "Beacon",
      "Winter Grey",
      "Dark Mood",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Soft Solution Dyed Nylon"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "12.5 (+/- 1.0)mm"],
      ["Pile Height", "10.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "14"],
    ],
    rooms: [],
  },
  {
    handle: "venture",
    name: "Venture",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/venture.jpg",
    images: [
      "/img/solution-dyed-nylon/venture/1.jpg",
      "/img/solution-dyed-nylon/venture/2.jpg",
      "/img/solution-dyed-nylon/venture/3.jpg",
      "/img/solution-dyed-nylon/venture/4.jpg",
      "/img/solution-dyed-nylon/venture/5.jpg",
      "/img/solution-dyed-nylon/venture/6.jpg",
      "/img/solution-dyed-nylon/venture/7.jpg",
      "/img/solution-dyed-nylon/venture/8.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 8 colours",
    short: "Venture Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Venture is a Solution Dyed Nylon Carpet in a stylish Cut Pile Twist style. Soft, resilient and durable, this neutral and affordable flooring option is perfect for multi-residential / apartment interiors.",
      "Australian Made Declare® Red List Free Residential Heavy Duty & Stairs- 4 Star Contract Light Duty - 1 Star ECS Level 4+ 7 Year Premium Limited Residential Warranty* ISO 9001 Quality Management System ISO 14001 Environment Management System Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Affordable",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Heavy Duty & Stairs- 4 Star",
      "Contract Light Duty - 1 Star",
      "ECS Level 4+",
      "7 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Venture | Capital Tiles",
    seoDesc: "Venture, Cut Pile Twist, 8 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Chamois", "Neutral", "Soft Leather", "Grey Haze", "Magma", "Paving", "Gravel", "Tundra"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Polypropylene"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "9.0 (+/- 1.0)mm"],
      ["Pile Height", "7 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "timeless",
    name: "Timeless",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/timeless.jpg",
    images: [
      "/img/solution-dyed-nylon/timeless/1.jpg",
      "/img/solution-dyed-nylon/timeless/2.jpg",
      "/img/solution-dyed-nylon/timeless/3.jpg",
      "/img/solution-dyed-nylon/timeless/4.jpg",
      "/img/solution-dyed-nylon/timeless/5.jpg",
      "/img/solution-dyed-nylon/timeless/6.jpg",
      "/img/solution-dyed-nylon/timeless/7.jpg",
      "/img/solution-dyed-nylon/timeless/8.jpg",
      "/img/solution-dyed-nylon/timeless/9.jpg",
      "/img/solution-dyed-nylon/timeless/10.jpg",
      "/img/solution-dyed-nylon/timeless/11.jpg",
      "/img/solution-dyed-nylon/timeless/12.jpg",
      "/img/solution-dyed-nylon/timeless/13.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 13 colours",
    short: "Timeless Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 13 colours. Supplied and laid across Canberra.",
    overview: [
      "Timeless is the perfect way to bring luxurious softness to any home interior. A Cut Pile Twist carpet with a natural stony palette, it's exquisitely soft, but it also has excellent durability.",
      "Australian Made Declare® Red List Free ISO 9001 Quality Management System ISO 14001 Environment Management System Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Affordable",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "ISO 9001 Quality Management System",
      "ISO 14001 Environment Management System",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
    ],
    seoTitle: "Timeless | Capital Tiles",
    seoDesc: "Timeless, Cut Pile Twist, 13 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Moonrock Stipple",
      "Fudge",
      "Oakheart Stipple",
      "Brushed Cotton",
      "Old Parchment",
      "Stone Beige",
      "Tan",
      "Barley",
      "Meadow",
      "Dawn",
      "Glacier Grey",
      "Light Shadow",
      "Urban Grey",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Soft Solution Dyed Nylon"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "9.5 (+/- 1.0)mm"],
      ["Pile Height", "7.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "13"],
    ],
    rooms: [],
  },
  {
    handle: "apollo-ridge",
    name: "Apollo Ridge",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/apollo-ridge.jpg",
    images: [
      "/img/solution-dyed-nylon/apollo-ridge/1.jpg",
      "/img/solution-dyed-nylon/apollo-ridge/2.jpg",
      "/img/solution-dyed-nylon/apollo-ridge/3.jpg",
      "/img/solution-dyed-nylon/apollo-ridge/4.jpg",
      "/img/solution-dyed-nylon/apollo-ridge/5.jpg",
      "/img/solution-dyed-nylon/apollo-ridge/6.jpg",
      "/img/solution-dyed-nylon/apollo-ridge/7.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 7 colours",
    short: "Apollo Ridge solution dyed nylon carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 7 colours. Supplied and laid across Canberra.",
    overview: [
      "Apollo Ridge is a 100% Solution Dyed PET Polyester carpet, designed to created a comfortable and stylish home with affordability in mind. Its combination of performance and value is ideal for updating your interior on a budget.",
      "Australian Made Cut Pile Twist 5 Year Standard Limited Residential Warranty* Affordable",
    ],
    features: ["Australian Made", "Cut Pile Twist", "5 Year Standard Limited Residential Warranty*", "Affordable"],
    seoTitle: "Apollo Ridge | Capital Tiles",
    seoDesc: "Apollo Ridge, Cut Pile Twist, 7 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Sandstone", "Vintage", "Silver Haze", "Mineral Stipple", "Slate", "Storm Grey", "Charcoal"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Solution Dyed P.E.T."],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "9 (+/- 1.0)mm"],
      ["Pile Height", "7 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "7"],
    ],
    rooms: [],
  },
  {
    handle: "elegant-reflections",
    name: "Elegant Reflections",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/elegant-reflections.jpg",
    images: [
      "/img/solution-dyed-nylon/elegant-reflections/1.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/2.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/3.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/4.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/5.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/6.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/7.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/8.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/9.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/10.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/11.jpg",
      "/img/solution-dyed-nylon/elegant-reflections/12.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 12 colours",
    short: "Elegant Reflections Solution Dyed Nylon Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 12 colours. Supplied and laid across Canberra.",
    overview: [
      "With a couple of stippled colours in the palette for added interest, Elegant Reflections is wonderfully soft and comfortable underfoot.",
      "Godfrey Hirst Best Seller Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* ISO 9001 Quality Management System ISO 14001 Environment Management System Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Premium",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
    ],
    seoTitle: "Elegant Reflections | Capital Tiles",
    seoDesc: "Elegant Reflections, Cut Pile Twist, 12 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Brown Tweed",
      "Cargo Stipple",
      "Ironstone",
      "Shale Stipple",
      "Ceramic",
      "Sandrock",
      "Warm Beige",
      "Wind Spray",
      "Cloudy Day",
      "Cobblestone",
      "Cold Mountain",
      "Dark Shadow",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed P.E.T."],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "14.5 (+/- 1.0)mm"],
      ["Pile Height", "12.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "12"],
    ],
    rooms: [],
  },
  {
    handle: "country-lane",
    name: "Country Lane",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/country-lane.jpg",
    images: [
      "/img/solution-dyed-nylon/country-lane/1.jpg",
      "/img/solution-dyed-nylon/country-lane/2.jpg",
      "/img/solution-dyed-nylon/country-lane/3.jpg",
      "/img/solution-dyed-nylon/country-lane/4.jpg",
      "/img/solution-dyed-nylon/country-lane/5.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 5 colours",
    short: "Country Lane Solution Dyed Nylon Carpet by Godfrey Hirst. 3.66m roll width and 5 colours. Supplied and laid across Canberra.",
    overview: [
      "Country Lane is a classic textured loop pile carpet that combines style and performance. This range is Declare LBC Red List Free and features five timeless colours.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Stain Resistance Fade Resistance Fire Rated Carpet Textured Loop Pile Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Country Lane | Capital Tiles",
    seoDesc: "Country Lane, 5 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Fresh Linen", "Daisy", "Meadow", "Province", "Iron Gate"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed Nylon"],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "7.5 (+/- 1)mm"],
      ["Pile Height", "5 (+/- 1)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "5"],
    ],
    rooms: [],
  },
  {
    handle: "cool-charm",
    name: "Cool Charm",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/cool-charm.jpg",
    images: [
      "/img/solution-dyed-nylon/cool-charm/1.jpg",
      "/img/solution-dyed-nylon/cool-charm/2.jpg",
      "/img/solution-dyed-nylon/cool-charm/3.jpg",
      "/img/solution-dyed-nylon/cool-charm/4.jpg",
      "/img/solution-dyed-nylon/cool-charm/5.jpg",
      "/img/solution-dyed-nylon/cool-charm/6.jpg",
      "/img/solution-dyed-nylon/cool-charm/7.jpg",
      "/img/solution-dyed-nylon/cool-charm/8.jpg",
      "/img/solution-dyed-nylon/cool-charm/9.jpg",
      "/img/solution-dyed-nylon/cool-charm/10.jpg",
      "/img/solution-dyed-nylon/cool-charm/11.jpg",
      "/img/solution-dyed-nylon/cool-charm/12.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 12 colours",
    short: "Cool Charm Solution Dyed Nylon Carpet by Godfrey Hirst. 3.66m roll width and 12 colours. Supplied and laid across Canberra.",
    overview: [
      "Cool Charm is a Solution Dyed Nylon Carpet in a stylish cut pile twist style. Soft, resilient and durable, this is a neutral and affordable flooring option.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Cool Charm | Capital Tiles",
    seoDesc: "Cool Charm, 12 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Braid",
      "Amulet Stipple",
      "Celtic Brown",
      "Tribal Stipple",
      "Porcelain",
      "Chalkstone",
      "Stone Pillar",
      "Atmosphere",
      "Andriod",
      "Stonewashed",
      "Steel Mesh",
      "Seal Fur",
    ],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "Solution Dyed Nylon"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "10.5 (+/- 1.0)mm"],
      ["Pile Height", "8.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "12"],
    ],
    rooms: [],
  },
  {
    handle: "covent-garden",
    name: "Covent Garden",
    brand: "Godfrey Hirst",
    card: "/img/solution-dyed-nylon/covent-garden.jpg",
    images: [
      "/img/solution-dyed-nylon/covent-garden/1.jpg",
      "/img/solution-dyed-nylon/covent-garden/2.jpg",
      "/img/solution-dyed-nylon/covent-garden/3.jpg",
      "/img/solution-dyed-nylon/covent-garden/4.jpg",
      "/img/solution-dyed-nylon/covent-garden/5.jpg",
      "/img/solution-dyed-nylon/covent-garden/6.jpg",
      "/img/solution-dyed-nylon/covent-garden/7.jpg",
      "/img/solution-dyed-nylon/covent-garden/8.jpg",
      "/img/solution-dyed-nylon/covent-garden/9.jpg",
      "/img/solution-dyed-nylon/covent-garden/10.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 10 colours",
    short: "Covent Garden Solution Dyed Nylon Carpet by Godfrey Hirst. 3.66m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Covent Garden will bring luxurious softness and style to your home. A cut pile twist carpet with a palette of natural earthy tones, Covent Garden is delightfully soft, and also has excellent durability, fade and stain resistance.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Premium Limited Residential Warranty* Stain Resistance Fade Resistance Wear Resistance Fire Rated Carpet Cut Pile Twist Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Premium Limited Residential Warranty*",
    ],
    seoTitle: "Covent Garden | Capital Tiles",
    seoDesc: "Covent Garden, 10 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Soft Leather",
      "Kenya Blend",
      "Sun Dew",
      "Lotus Petal",
      "Claystone",
      "Sandrock",
      "Ice Grey",
      "Stone Pillar",
      "Steel Facade",
      "Seal",
    ],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Soft Solution Dyed Nylon"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "11.5 (+/- 1.0)mm"],
      ["Pile Height", "9.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "acacia-hill",
    name: "Acacia Hill",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/acacia-hill.jpg",
    images: [
      "/img/solution-dyed-nylon/acacia-hill/1.jpg",
      "/img/solution-dyed-nylon/acacia-hill/2.jpg",
      "/img/solution-dyed-nylon/acacia-hill/3.jpg",
      "/img/solution-dyed-nylon/acacia-hill/4.jpg",
      "/img/solution-dyed-nylon/acacia-hill/5.jpg",
      "/img/solution-dyed-nylon/acacia-hill/6.jpg",
      "/img/solution-dyed-nylon/acacia-hill/7.jpg",
      "/img/solution-dyed-nylon/acacia-hill/8.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 9 colours",
    short: "Acacia Hill solution dyed nylon carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "Discover the combination of practicality and sophistication with Acacia Hill. This nylon soft flooring has a natural look and rich texture which is easy to clean while providing exceptional comfort. With contemporary designs and durability in mind, it's an ideal product for both residential and commercial settings.",
      "Acacia Hill expertly blends the practical benefits you expect from nylon with discerning aesthetic qualities traditionally only associated with natural fibres.",
      "Acacia Hill is not only beautiful, but outstandingly effective at concealing soiling.",
    ],
    features: [
      "Sophisticated practicality",
      "Rich, organic texture",
      "Luxurious underfoot",
      "Modern style",
      "Australian quality",
    ],
    seoTitle: "Acacia Hill | Capital Tiles",
    seoDesc: "Acacia Hill, 9 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Alton 1249",
      "Kennedy 1250",
      "Atkins 1253",
      "Mawson 1251",
      "Millrose 1255",
      "Longford 1252",
      "Karson 1254",
      "Myrtle 1256",
      "Magnolia 1248",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "andes-peak",
    name: "Andes Peak",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/andes-peak.jpg",
    images: [
      "/img/solution-dyed-nylon/andes-peak/1.jpg",
      "/img/solution-dyed-nylon/andes-peak/2.jpg",
      "/img/solution-dyed-nylon/andes-peak/3.jpg",
      "/img/solution-dyed-nylon/andes-peak/4.jpg",
      "/img/solution-dyed-nylon/andes-peak/5.jpg",
      "/img/solution-dyed-nylon/andes-peak/6.jpg",
      "/img/solution-dyed-nylon/andes-peak/7.jpg",
      "/img/solution-dyed-nylon/andes-peak/8.jpg",
      "/img/solution-dyed-nylon/andes-peak/9.jpg",
      "/img/solution-dyed-nylon/andes-peak/10.jpg",
      "/img/solution-dyed-nylon/andes-peak/11.jpg",
      "/img/solution-dyed-nylon/andes-peak/12.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 12 colours",
    short: "Andes Peak solution dyed nylon carpet by EC Carpets. 12 colours. Supplied and laid across Canberra.",
    overview: [
      "Andes Peak offers wool-like elegance featuring a subtly heathered texture. Its neutral colour palette complements any interior design, while its durability ensures lasting beauty.",
      "Certified to the highest level under the Environmental Certification Scheme, Andes Peak supports healthier interiors and contributes to Green Star building ratings.",
      "Andes Peak provides an outstanding combination of high-specification quality and affordability, with a rich texture and subtle heather that strongly, and beautifully, resembles wool.",
    ],
    features: [
      "ECS 4+ Accredited",
      "A touch of wool-like class",
      "Durability meets opulence",
      "Stylish simplicity",
      "Colourfast and made to last",
      "Easy to maintain",
    ],
    seoTitle: "Andes Peak | Capital Tiles",
    seoDesc: "Andes Peak, 12 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Olca 2404",
      "Patilla 2406",
      "Serena 2433",
      "Merida 2421",
      "Isabel 2403",
      "Valera 2455",
      "Rio 2451",
      "Rubio 2458",
      "Hudson 2425",
      "Mendoza 2419",
      "Morado 2416",
      "Patagonia 2422",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "avenue",
    name: "Avenue",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/avenue.jpg",
    images: [
      "/img/solution-dyed-nylon/avenue/1.jpg",
      "/img/solution-dyed-nylon/avenue/2.jpg",
      "/img/solution-dyed-nylon/avenue/3.jpg",
      "/img/solution-dyed-nylon/avenue/4.jpg",
      "/img/solution-dyed-nylon/avenue/5.jpg",
      "/img/solution-dyed-nylon/avenue/6.jpg",
      "/img/solution-dyed-nylon/avenue/7.jpg",
      "/img/solution-dyed-nylon/avenue/8.jpg",
      "/img/solution-dyed-nylon/avenue/9.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 9 colours",
    short: "Avenue solution dyed nylon carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "Avenue combines nylon's practicality with the aesthetic qualities of natural fibres. Its rich texture hides stains effectively and with modern colours and geometric patterns, Avenue is an ideal base for contemporary interiors.",
      "Avenue expertly blends the practical benefits you expect from nylon with discerning aesthetic qualities traditionally only associated with natural fibres.",
      "Avenue is not only beautiful, but outstandingly effective at concealing soiling.",
    ],
    features: [
      "Sophisticated practicality",
      "Rich, organic texture",
      "Luxurious underfoot",
      "Modern style",
      "Australian quality",
    ],
    seoTitle: "Avenue | Capital Tiles",
    seoDesc: "Avenue, 9 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Milton 1149",
      "Rayne 1150",
      "Rothbury 1153",
      "Sherwood 1151",
      "Bevington 1155",
      "Ashbourne 1152",
      "Cudmore 1154",
      "Moorhouse 1156",
      "Morland 1148",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "ayrton",
    name: "Ayrton",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/ayrton.jpg",
    images: [
      "/img/solution-dyed-nylon/ayrton/1.jpg",
      "/img/solution-dyed-nylon/ayrton/2.jpg",
      "/img/solution-dyed-nylon/ayrton/3.jpg",
      "/img/solution-dyed-nylon/ayrton/4.jpg",
      "/img/solution-dyed-nylon/ayrton/5.jpg",
      "/img/solution-dyed-nylon/ayrton/6.jpg",
      "/img/solution-dyed-nylon/ayrton/7.jpg",
      "/img/solution-dyed-nylon/ayrton/8.jpg",
      "/img/solution-dyed-nylon/ayrton/9.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 9 colours",
    short: "Ayrton solution dyed nylon carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "The striated pattern and earthy tones of Ayrton go beyond mere functionality. Its design not only withstands abrasion but also displays a luxurious aesthetic, impervious to footprints while embodying the elegance of wool.",
      "No unsightly shading marks left behind by footprints and everyday use.",
      "Ayrton offers an exceptional balance of premium quality and affordability, boasting a luxurious texture that remarkably mimics the elegance of wool.",
    ],
    features: [
      "Track resistant carpet",
      "Luxurious underfoot comfort",
      "Sophisticated colour palette",
      "Durable and luxury",
    ],
    seoTitle: "Ayrton | Capital Tiles",
    seoDesc: "Ayrton, 9 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Monaco 4619",
      "Montreal 4641",
      "Silverstone 4628",
      "Francor 4638",
      "Quebec 4604",
      "Monza 4626",
      "Emilia 4637",
      "Suzuka 4632",
      "Toleman 4607",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "birdwood",
    name: "Birdwood",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/birdwood.jpg",
    images: [
      "/img/solution-dyed-nylon/birdwood/1.jpg",
      "/img/solution-dyed-nylon/birdwood/2.jpg",
      "/img/solution-dyed-nylon/birdwood/3.jpg",
      "/img/solution-dyed-nylon/birdwood/4.jpg",
      "/img/solution-dyed-nylon/birdwood/5.jpg",
      "/img/solution-dyed-nylon/birdwood/6.jpg",
      "/img/solution-dyed-nylon/birdwood/7.jpg",
      "/img/solution-dyed-nylon/birdwood/8.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 8 colours",
    short: "Birdwood solution dyed nylon carpet by EC Carpets. 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Experience unparalleled appearance longevity with our Birdwood range, crafted to preserve its flawless allure every day. Combining the aesthetic of a plush pile with the resilience of a loop pile, revel in the opulence of our flooring.",
      "Engineered to perform day in, day out, and retain its appearance.",
      "A high performing and track resistant loop pile carpet that ensures no shading marks, fluffing, or fading.",
    ],
    features: ["Superior appearance retention", "Track resistant", "Enduring luxury", "Pet friendly"],
    seoTitle: "Birdwood | Capital Tiles",
    seoDesc: "Birdwood, 8 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Angas 2962",
      "Teralinga 2961",
      "Blumberg 2952",
      "Cromer 2955",
      "Hannaford 2953",
      "Carnell 2963",
      "Yallam 2964",
      "Canham 2965",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "bordeaux",
    name: "Bordeaux",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/bordeaux.jpg",
    images: [
      "/img/solution-dyed-nylon/bordeaux/1.jpg",
      "/img/solution-dyed-nylon/bordeaux/2.jpg",
      "/img/solution-dyed-nylon/bordeaux/3.jpg",
      "/img/solution-dyed-nylon/bordeaux/4.jpg",
      "/img/solution-dyed-nylon/bordeaux/5.jpg",
      "/img/solution-dyed-nylon/bordeaux/6.jpg",
      "/img/solution-dyed-nylon/bordeaux/7.jpg",
      "/img/solution-dyed-nylon/bordeaux/8.jpg",
      "/img/solution-dyed-nylon/bordeaux/9.jpg",
      "/img/solution-dyed-nylon/bordeaux/10.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 10 colours",
    short: "Bordeaux solution dyed nylon carpet by EC Carpets. 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Experience unparalleled appearance longevity with our Birdwood range, crafted to preserve its flawless allure every day. Combining the aesthetic of a plush pile with the resilience of a loop pile, revel in the opulence of our flooring.",
      "Certified to the highest level under the Environmental Certification Scheme, Bordeaux supports healthier interiors and contributes to Green Star building ratings.",
      "Bordeaux delivers unparalleled comfort, with an offset chunky loop that feels rich,",
    ],
    features: [
      "ECS 4+ Accredited",
      "Superior Comfort",
      "Classic Style, Contemporary Living",
      "Luxury That Lasts",
      "Timeless Palette",
    ],
    seoTitle: "Bordeaux | Capital Tiles",
    seoDesc: "Bordeaux, 10 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Lorient 4524",
      "Savinne 4525",
      "Paulin 4514",
      "Estera 4550",
      "Colette 4521",
      "Pascal 4543",
      "Pessac 4535",
      "Berland 4552",
      "Velmont 4548",
      "Emilion 4553",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "boucle",
    name: "Bouclé",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/boucle.jpg",
    images: [
      "/img/solution-dyed-nylon/boucle/1.jpg",
      "/img/solution-dyed-nylon/boucle/2.jpg",
      "/img/solution-dyed-nylon/boucle/3.jpg",
      "/img/solution-dyed-nylon/boucle/4.jpg",
      "/img/solution-dyed-nylon/boucle/5.jpg",
      "/img/solution-dyed-nylon/boucle/6.jpg",
      "/img/solution-dyed-nylon/boucle/7.jpg",
      "/img/solution-dyed-nylon/boucle/8.jpg",
      "/img/solution-dyed-nylon/boucle/9.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 9 colours",
    short: "Bouclé solution dyed nylon carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "Bouclé offers a touch of wool-like elegance, reminiscent of the European textile texture, bouclé. Combined with a beautiful colour palette, it provides an elegant foundation for a wide range of interior design themes and furnishings.",
      "Bouclé provides an outstanding combination of high-specification quality and affordability, with a rich texture and subtle heather that strongly, and beautifully, resembles wool.",
      "Although providing a welcome sense of luxury in bedrooms and living areas, Bouclé remains extremely durable to abrasion and flattening. Rated extra heavy duty for residential and medium contract applications, it will perform well in highly active spaces, such as hotel accommodations and apartment living.",
    ],
    features: [
      "A touch of wool-like class",
      "Durability meets opulence",
      "Stylish simplicity",
      "Colourfast and made to last",
      "Easy to maintain",
    ],
    seoTitle: "Bouclé | Capital Tiles",
    seoDesc: "Bouclé, 9 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Ovie+4304",
      "Sarinen+4303",
      "Jacqueline+4342",
      "Mokum+4347",
      "Fredrik+4348",
      "Shu+4315",
      "Atticus+4318",
      "Maymo+4308",
      "Coco+4336",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "bourkesgate",
    name: "Bourkesgate",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/bourkesgate.jpg",
    images: [
      "/img/solution-dyed-nylon/bourkesgate/1.jpg",
      "/img/solution-dyed-nylon/bourkesgate/2.jpg",
      "/img/solution-dyed-nylon/bourkesgate/3.jpg",
      "/img/solution-dyed-nylon/bourkesgate/4.jpg",
      "/img/solution-dyed-nylon/bourkesgate/5.jpg",
      "/img/solution-dyed-nylon/bourkesgate/6.jpg",
      "/img/solution-dyed-nylon/bourkesgate/7.jpg",
      "/img/solution-dyed-nylon/bourkesgate/8.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 8 colours",
    short: "Bourkesgate solution dyed nylon carpet by EC Carpets. 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Experience unparalleled appearance longevity with our Bourkesgate range, crafted to preserve its flawless allure every day. Combining the aesthetic of a plush pile with the resilience of a loop pile, revel in the opulence of our flooring.",
      "Engineered to perform day in, day out and retain its appearance",
      "A high performing and track resistant loop pile carpet that ensures no shading marks, fluffing or fading.",
    ],
    features: ["Superior appearance retention", "Track resistant", "Enduring luxury", "Pet friendly"],
    seoTitle: "Bourkesgate | Capital Tiles",
    seoDesc: "Bourkesgate, 8 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Kidman 1962", "Kamila 1961", "Cobb 1952", "Lawson 1955", "Paroo 1953", "Jandra 1963", "Namoi 1964", "Louth 1965"],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "coco-bliss",
    name: "Coco Bliss",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/coco-bliss.jpg",
    images: [
      "/img/solution-dyed-nylon/coco-bliss/1.jpg",
      "/img/solution-dyed-nylon/coco-bliss/2.jpg",
      "/img/solution-dyed-nylon/coco-bliss/3.jpg",
      "/img/solution-dyed-nylon/coco-bliss/4.jpg",
      "/img/solution-dyed-nylon/coco-bliss/5.jpg",
      "/img/solution-dyed-nylon/coco-bliss/6.jpg",
      "/img/solution-dyed-nylon/coco-bliss/7.jpg",
      "/img/solution-dyed-nylon/coco-bliss/8.jpg",
      "/img/solution-dyed-nylon/coco-bliss/9.jpg",
      "/img/solution-dyed-nylon/coco-bliss/10.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 10 colours",
    short: "Coco Bliss solution dyed nylon carpet by EC Carpets. 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Coco Bliss is a premium twist pile carpet designed for style and performance. Its resilient and dense construction offers exceptional durability, making it perfect for residential and commercial spaces.",
      "Coco Bliss features a stylish twist pile that offers both durability and performance. Available in 10 stunning colours, it brings the perfect combination of sophistication and reliability to any space.",
      "With a high face weight, the carpet resists wear and maintains its look in high-traffic areas, ensuring long-lasting performance.",
    ],
    features: ["Stylish and Elegant", "Durable", "Sound Absorption and Insulation", "Easy Maintenance"],
    seoTitle: "Coco Bliss | Capital Tiles",
    seoDesc: "Coco Bliss, 10 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Felicity 9042",
      "Joy 9043",
      "Happiness+9037",
      "Epiphany+9031",
      "Euphoria+9012",
      "Delight+9025",
      "Elation+9024",
      "Nostalgia+9023",
      "Gratitude+9028",
      "Contentment+9018",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "comfort-touch",
    name: "Comfort Touch",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/comfort-touch.jpg",
    images: [
      "/img/solution-dyed-nylon/comfort-touch/1.jpg",
      "/img/solution-dyed-nylon/comfort-touch/2.jpg",
      "/img/solution-dyed-nylon/comfort-touch/3.jpg",
      "/img/solution-dyed-nylon/comfort-touch/4.jpg",
      "/img/solution-dyed-nylon/comfort-touch/5.jpg",
      "/img/solution-dyed-nylon/comfort-touch/6.jpg",
      "/img/solution-dyed-nylon/comfort-touch/7.jpg",
      "/img/solution-dyed-nylon/comfort-touch/8.jpg",
      "/img/solution-dyed-nylon/comfort-touch/9.jpg",
      "/img/solution-dyed-nylon/comfort-touch/10.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 10 colours",
    short: "Comfort Touch solution dyed nylon carpet by EC Carpets. 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Comfort Touch is a luxurious twist pile carpet designed for ultimate comfort and softness underfoot. Its plush texture offers exceptional durability yet a cosy feel, making it perfect for residential and commercial spaces.",
      "Comfort Touch provides a soft, luxurious feel underfoot, offering both comfort and an elegant appearance.",
      "With a high face weight, the carpet resists wear and maintains its look in high-traffic areas, ensuring long-lasting performance.",
    ],
    features: ["Luxurious", "Durability", "Sound Absorption and Insulation", "Stylish and Versatile"],
    seoTitle: "Comfort Touch | Capital Tiles",
    seoDesc: "Comfort Touch, 10 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Humble 9142",
      "Relax 9143",
      "Zen 9137",
      "Warmth 9131",
      "Ease 9112",
      "Charm 9125",
      "Peace 9124",
      "Quiet 9123",
      "Mood 9128",
      "Snug 9118",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "district-loft",
    name: "District Loft",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/district-loft.jpg",
    images: [
      "/img/solution-dyed-nylon/district-loft/1.jpg",
      "/img/solution-dyed-nylon/district-loft/2.jpg",
      "/img/solution-dyed-nylon/district-loft/3.jpg",
      "/img/solution-dyed-nylon/district-loft/4.jpg",
      "/img/solution-dyed-nylon/district-loft/5.jpg",
      "/img/solution-dyed-nylon/district-loft/6.jpg",
      "/img/solution-dyed-nylon/district-loft/7.jpg",
      "/img/solution-dyed-nylon/district-loft/8.jpg",
      "/img/solution-dyed-nylon/district-loft/9.jpg",
      "/img/solution-dyed-nylon/district-loft/10.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 10 colours",
    short: "District Loft solution dyed nylon carpet by EC Carpets. 10 colours. Supplied and laid across Canberra.",
    overview: [
      "District Loft tis a modern entry-level cut pile carpet offering comfort and dependable performance in a practical 30oz construction. Its 1/10 gauge construction delivers a dense, refined finish, striking the",
      "A stylish finish that brings warmth and timeless elegance to a wide range of interiors.",
      "Constructed with tightly twisted fibres to support resilience and maintain its look",
    ],
    features: ["Refined Appearance", "Everyday Performance", "Low-maintenance Living", "Great Value & Versatility"],
    seoTitle: "District Loft | Capital Tiles",
    seoDesc: "District Loft, 10 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Quarter 9242",
      "Precinct 9243",
      "Local 9237",
      "Bureau 9231",
      "Foundry 9212",
      "Urban 9225",
      "City 9224",
      "Metro 9223",
      "Assembly 9228",
      "Forge 9218",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "flinders-gorge",
    name: "Flinders Gorge",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/flinders-gorge.jpg",
    images: [
      "/img/solution-dyed-nylon/flinders-gorge/1.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/2.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/3.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/4.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/5.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/6.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/7.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/8.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/9.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/10.jpg",
      "/img/solution-dyed-nylon/flinders-gorge/11.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 12 colours",
    short: "Flinders Gorge solution dyed nylon carpet by EC Carpets. 12 colours. Supplied and laid across Canberra.",
    overview: [
      "Flinders Gorge offers high-quality and affordability with a rich texture resembling wool. Its neutral palette blends seamlessly with modern interiors, ensuring long-lasting colour retention and resistance to fading. Easy to maintain, its heathered colours hide dirt and stains effortlessly, while being highly resistant to staining, moisture, mold, and insects.",
      "Certified to the highest level under the Environmental Certification Scheme, Flinders Gorge supports healthier interiors and contributes to Green Star building ratings.",
      "Flinders Gorge provides an outstanding combination of high-specification quality and affordability, with a rich texture and subtle heather that strongly, and beautifully, resembles wool.",
    ],
    features: [
      "ECS 4+ Accredited",
      "A touch of wool-like class",
      "Stylish simplicity",
      "Colourfast and made to last",
      "Easy to maintain",
    ],
    seoTitle: "Flinders Gorge | Capital Tiles",
    seoDesc: "Flinders Gorge, 12 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Blanche 3404",
      "Beltana 3406",
      "Olary 3433",
      "Warren 3421",
      "Calla 3403",
      "Hawker 3455",
      "Havelock 3451",
      "Tanderra 3458",
      "Leigh 3425",
      "Copley 3419",
      "Amyton 3416",
      "Rawnsley 3422",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "langhorne-hut",
    name: "Langhorne Hut",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/langhorne-hut.jpg",
    images: [
      "/img/solution-dyed-nylon/langhorne-hut/1.jpg",
      "/img/solution-dyed-nylon/langhorne-hut/2.jpg",
      "/img/solution-dyed-nylon/langhorne-hut/3.jpg",
      "/img/solution-dyed-nylon/langhorne-hut/4.jpg",
      "/img/solution-dyed-nylon/langhorne-hut/5.jpg",
      "/img/solution-dyed-nylon/langhorne-hut/6.jpg",
      "/img/solution-dyed-nylon/langhorne-hut/7.jpg",
      "/img/solution-dyed-nylon/langhorne-hut/8.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 8 colours",
    short: "Langhorne Hut solution dyed nylon carpet by EC Carpets. 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Langhorne Hut characterises resilience, combining durability with elegance for residential and commercial use. Its tough design retains a modern style, accommodating easy movement for chairs and wheelchairs, while an optional impervious backing suits healthcare needs. With enduring Colours, fire resistance, and a woven look, Langhorne Hut excels in both form and function.",
      "Outstandingly hard-wearing, Langhorne Hut is the ultimate cross-over product, designed to suit the most demanding of residential and commercial applications.",
      "Langhorne Hut combines exceptional durability with style and sophistication. Its modern colour palette and subtle woven design effortlessly complement various interior themes",
    ],
    features: [
      "Ultra-resilient",
      "Style for modern living",
      "Wheel-friendly",
      "Healthcare impervious backing available",
      "Colourfast and made to last",
      "Excellent fire retardance",
    ],
    seoTitle: "Langhorne Hut | Capital Tiles",
    seoDesc: "Langhorne Hut, 8 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Chapel 1906", "Bertol 1916", "Arbol 1913", "Hanok 1917", "Orri 1901", "Solvay 1915", "Sheoak 1908", "Borrett 1905"],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "orchard",
    name: "Orchard",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/orchard.jpg",
    images: [
      "/img/solution-dyed-nylon/orchard/1.jpg",
      "/img/solution-dyed-nylon/orchard/2.jpg",
      "/img/solution-dyed-nylon/orchard/3.jpg",
      "/img/solution-dyed-nylon/orchard/4.jpg",
      "/img/solution-dyed-nylon/orchard/5.jpg",
      "/img/solution-dyed-nylon/orchard/6.jpg",
      "/img/solution-dyed-nylon/orchard/7.jpg",
      "/img/solution-dyed-nylon/orchard/8.jpg",
      "/img/solution-dyed-nylon/orchard/9.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 9 colours",
    short: "Orchard solution dyed nylon carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "Orchards' combination of chic design with durability, elevates spaces with earthy colours and a striated pattern. Its construction mirrors the elegance of wool, yet maintains a pristine appearance free from wear marks.",
      "Orchard provides an outstanding combination of high-specification quality and affordability, with a rich texture and subtle heather that strongly, and beautifully, resembles wool.",
      "Incorporating a luxurious feel into bedrooms and living spaces, Orchard excels in enduring abrasion and maintaining its plushness. With an extra heavy-duty rating for residential use, it thrives even in high-traffic areas like hallways and rumpus rooms.",
    ],
    features: [
      "A touch of wool-like class",
      "Durability meets opulence",
      "Stylish simplicity",
      "Colourfast and made to last",
      "Easy to maintain",
    ],
    seoTitle: "Orchard | Capital Tiles",
    seoDesc: "Orchard, 9 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Akane 2619",
      "Calville 2641",
      "Sansa 2628",
      "Melrose 2638",
      "Cortland 2604",
      "Cameo 2626",
      "Ida 2637",
      "Jonamac 2632",
      "Ashmead 2607",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "tunes",
    name: "Tunes",
    brand: "EC Carpets",
    card: "/img/solution-dyed-nylon/tunes.jpg",
    images: [
      "/img/solution-dyed-nylon/tunes/1.jpg",
      "/img/solution-dyed-nylon/tunes/2.jpg",
      "/img/solution-dyed-nylon/tunes/3.jpg",
      "/img/solution-dyed-nylon/tunes/4.jpg",
      "/img/solution-dyed-nylon/tunes/5.jpg",
      "/img/solution-dyed-nylon/tunes/6.jpg",
      "/img/solution-dyed-nylon/tunes/7.jpg",
      "/img/solution-dyed-nylon/tunes/8.jpg",
      "/img/solution-dyed-nylon/tunes/9.jpg",
    ],
    tagline: "Solution dyed nylon carpet in 9 colours",
    short: "Tunes solution dyed nylon carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "Experience the appeal of beautiful organic tones, twisted in a striated pattern. Displaying unrivalled durability, this combination of nature-inspired tones transforms a space into a haven of beauty.",
      "Linear chic redefines elegance with its sleek and contemporary design, this carpet seamlessly combines modern style with timeless appeal.",
      "With the ability to complement a modern decor scheme, neutral tones simplify the design process, allowing you to create an elevated look with ease. Embrace the timeless allure of neutral tones and elevate your space with understated elegance.",
    ],
    features: ["Sleek sophistication", "Elevated Look", "Simplified Cleaning", "Budget-Friendly"],
    seoTitle: "Tunes | Capital Tiles",
    seoDesc: "Tunes, 9 colours. Solution dyed nylon carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Classical 9719",
      "Country 9741",
      "Legato 9728",
      "Jazz 9738",
      "Scalar 9704",
      "Pop 9726",
      "Blues 9737",
      "Disco 9732",
      "Chromatic 9707",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
]

export function byHandle(handle) {
  return NYLON_PRODUCTS.find((p) => p.handle === handle)
}
