/* Outdoor range, taken from the live capitaltiles.com.au pavers + out-door
   collection: names, blurbs, brands and the colour / finish / size options
   each product actually ships with. */

export const OUTDOOR = [
  {
    name: "Bari Collection",
    handle: "bari-collection",
    blurb: "The Bari Collection Travertine Tile — Belconnen Timeless elegance meets natural artistry with The Bari Collection . A luxurious travertine-look porcel",
    brand: "Capital Tiles",
    colours: ["Bianco", "Taupe", "Beige"],
    finishes: ["Versa Touch", "P5 20mm", "Cobbles VT", "P5 20mm Pencil Edge"],
    sizes: ["300x600", "600x600", "1200x600", "75x300", "307x307 mm sheets", "Crazy Pave", "French Pattern", "600x400 mm DF", "600x400"],
  },
  {
    name: "Chiswick Outdoor Collection",
    handle: "chiswick-paver-collection",
    blurb: "Seamless Stone Style, Made for the Outdoors Elevate your exterior with Chiswick Outdoor , the latest evolution in the Chiswick Collection—designed to ",
    brand: "Capital Tiles",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    finishes: ["Square Edge Coper", "External Paver"],
    sizes: ["400x600x20", "600x600x20"],
  },
  {
    name: "Iceland",
    handle: "iceland",
    blurb: "Available in 1 colour and 1 finish, in 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Gold"],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Tundra",
    handle: "tundra",
    blurb: "Available in 1 colour and 1 finish, in 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["White"],
    finishes: ["Matt"],
    sizes: ["600x1200"],
  },
  {
    name: "Taj Mahal",
    handle: "taj-mahal",
    blurb: "Available in 3 colours and 4 finishes, in 600x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Natural", "Ivory", "Silver"],
    finishes: ["Matt", "StoneTouch Tec", "Soft Matt", "Flute"],
    sizes: ["600x600", "600x1200"],
  },
  {
    name: "Flat-Alps",
    handle: "flat-alps",
    blurb: "Available in 4 colours and 4 finishes, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Silver", "Grey", "White", "Beige"],
    finishes: ["In&Out Solution", "StoneTouch Tec", "Paver", "Flute"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Gelato",
    handle: "gelato",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Light", "Medium", "Dark"],
    finishes: ["In&Out Solution"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Riverstone",
    handle: "riverstone",
    blurb: "Available in 1 colour and 1 finish, in 600x600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "HF Tiles",
    colours: ["Silver"],
    finishes: ["External"],
    sizes: ["600x600"],
  },
  {
    name: "Luxstone",
    handle: "luxstone",
    blurb: "Effortless Stone-Look Sophistication Bring the timeless beauty of natural stone into your space with the Luxstone Collection — a refined, versatile ra",
    brand: "Capital Tiles",
    colours: ["White", "Natural", "Beige"],
    finishes: [],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Everest",
    handle: "everest",
    blurb: "Bold Stone Look, Built for Endurance Elevate your space with the Everest Collection, where modern design meets natural stone elegance. Inspired by the",
    brand: "HF Tiles",
    colours: ["Ivory", "Silver", "Grey"],
    finishes: ["In&Out Solution", "StoneTouch Tec"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Karzai Green",
    handle: "karzai-green",
    blurb: "The Karzai Green tile offers a striking combination of elegance and durability, featuring a 600 × 1200 mm size and a high-quality 4D Glue & Grit Full ",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Ferragamo",
    handle: "ferragamo",
    blurb: "The Ferragamo tile from Muses Australia is a premium glazed porcelain tile crafted to bring a refined, modern look to interior and exterior spaces. It",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Balcan",
    handle: "balcan",
    blurb: "quality ceramic wall and floor tile offered by Muses Ceramics Australia, designed to elevate interiors with a refined aesthetic and reliable performan",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Aegean Sea",
    handle: "aegean-sea",
    blurb: "The Aegean Sea tile from Muses Australia is a high‑quality 600 × 1200 mm glazed porcelain tile featuring a refined finish and subtle texture. It’s sui",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Sassy",
    handle: "sassy",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Ash", "Beige", "Slate"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Starry",
    handle: "starry",
    blurb: "Starry is a premium porcelain tile offered by Muses Australia that combines understated elegance with everyday performance. Designed to bring a warm a",
    brand: "Muses",
    colours: ["Beige", "Light Grey", "Black"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Trav Vein Cut",
    handle: "trav-vein-cut",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Trav Cross Cut",
    handle: "trav-cross-cut",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Quartzite Paver",
    handle: "quartzite-paver",
    blurb: "Available in 2 colours and 1 finish, in 600 x 600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Charcoal", "Grigio"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Petra Mix Paver",
    handle: "petra-mix-paver",
    blurb: "Sizes : 600×600 (20mm Thick) Color Beige, Ivory, Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Imperial Stone Paver",
    handle: "imperial-stone-paver",
    blurb: "Sizes : 600×600 (20mm Thick) Color Ivory, Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Light Grey", "Ivory"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Crest Paver",
    handle: "crest-paver",
    blurb: "Available in 3 colours and 1 finish, in 600 x 600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Light Grey", "Ivory", "Dark Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Blaze Paver",
    handle: "blaze-paver",
    blurb: "Color Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Roccia Series",
    handle: "roccia",
    blurb: "Earthy Porcelain Tiles with Modern Durability Bring the rugged charm of natural stone into your home with the Roccia Collection . These porcelain tile",
    brand: "Muses",
    colours: ["Greige", "Charcoal"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Ardesia Paver",
    handle: "ardesia-collection",
    blurb: "The ARDESIA collection captures the timeless elegance of slate, bringing the raw beauty of nature into refined interior and exterior spaces. With its ",
    brand: "Muses",
    colours: ["Ivory", "Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
]
