/* Patio tile range, taken from the live capitaltiles.com.au patio-tiles
   collection: names, blurbs, brands and the colour / finish / size options
   each product actually ships with. */

export const PATIO = [
  {
    name: "Ferragamo",
    handle: "ferragamo",
    blurb: "The Ferragamo tile from Muses Australia is a premium glazed porcelain tile crafted to bring a refined, modern look to interior and exterior spaces. It",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Balcan",
    handle: "balcan",
    blurb: "quality ceramic wall and floor tile offered by Muses Ceramics Australia, designed to elevate interiors with a refined aesthetic and reliable performan",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Aegean Sea",
    handle: "aegean-sea",
    blurb: "The Aegean Sea tile from Muses Australia is a high‑quality 600 × 1200 mm glazed porcelain tile featuring a refined finish and subtle texture. It’s sui",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Sassy",
    handle: "sassy",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Ash", "Beige", "Slate"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Blended",
    handle: "blended",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["White", "Ash", "Taupe"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Nova Stone",
    handle: "nova-stone",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Ivory", "Fog", "White"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Port Travertino",
    handle: "port-travertino",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Limestone",
    handle: "limestone",
    blurb: "Available in 4 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Beige Fluted", "Ivory Fluted", "Ivory"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Find",
    handle: "find",
    blurb: "Available in 2 colours and 1 finish, in 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Cool Grey", "Light Grey"],
    finishes: ["Felltec"],
    sizes: ["600x1200"],
  },
  {
    name: "Starry",
    handle: "starry",
    blurb: "Starry is a premium porcelain tile offered by Muses Australia that combines understated elegance with everyday performance. Designed to bring a warm a",
    brand: "Muses",
    colours: ["Beige", "Light Grey", "Black"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Trav Vein Cut",
    handle: "trav-vein-cut",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Trav Cross Cut",
    handle: "trav-cross-cut",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Quartzite Paver",
    handle: "quartzite-paver",
    blurb: "Available in 2 colours and 1 finish, in 600 x 600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Charcoal", "Grigio"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Petra Mix Paver",
    handle: "petra-mix-paver",
    blurb: "Sizes : 600×600 (20mm Thick) Color Beige, Ivory, Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Imperial Stone Paver",
    handle: "imperial-stone-paver",
    blurb: "Sizes : 600×600 (20mm Thick) Color Ivory, Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Light Grey", "Ivory"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Crest Paver",
    handle: "crest-paver",
    blurb: "Available in 3 colours and 1 finish, in 600 x 600. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Light Grey", "Ivory", "Dark Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Blaze Paver",
    handle: "blaze-paver",
    blurb: "Color Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Vutton Series",
    handle: "vutton-series",
    blurb: "The VUTTON collection combines refined elegance with contemporary style, making it the perfect choice for sophisticated interiors. Inspired by natural",
    brand: "Muses",
    colours: ["Ash", "Ice", "Night", "Pearl", "Sage"],
    finishes: [],
    sizes: ["Mosaic Sheets (275.2×275.2mm)"],
  },
  {
    name: "Mistery Dark Grey",
    handle: "mistery-dark-grey",
    blurb: "Available in 2 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Light Grey", "Dark Grey"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Find Honed",
    handle: "find-honed",
    blurb: "Available in 2 colours and 1 finish, in 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Cool Grey", "Light Grey"],
    finishes: ["Honed"],
    sizes: ["600x1200"],
  },
  {
    name: "Calacatta Pro",
    handle: "calacatta-pro",
    blurb: "The Calacatta Pro Marble collection delivers the timeless elegance of classic Calacatta with a modern twist. Featuring a bright white base enriched by",
    brand: "Muses",
    colours: [],
    finishes: ["Felltec", "Polished"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Bari Collection",
    handle: "bari-collection",
    blurb: "The Bari Collection Travertine Tile — Belconnen Timeless elegance meets natural artistry with The Bari Collection . A luxurious travertine-look porcel",
    brand: "Capital Tiles",
    colours: ["Bianco", "Taupe", "Beige"],
    finishes: ["Versa Touch", "P5 20mm", "Cobbles VT", "P5 20mm Pencil Edge"],
    sizes: ["300x600", "600x600", "1200x600", "75x300", "307x307 mm sheets", "Crazy Pave", "French Pattern", "600x400 mm DF", "600x400"],
  },
  {
    name: "Roccia Series",
    handle: "roccia",
    blurb: "Earthy Porcelain Tiles with Modern Durability Bring the rugged charm of natural stone into your home with the Roccia Collection . These porcelain tile",
    brand: "Muses",
    colours: ["Greige", "Charcoal"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Silver Root",
    handle: "silver-root",
    blurb: "Polished Sophistication with Stone Soul Inspired by the intricate veining of high-end marble and the organic movement of natural stone, the Silver Roo",
    brand: "Muses",
    colours: ["Ivory", "Light Grey", "Brown"],
    finishes: ["Satin"],
    sizes: [],
  },
  {
    name: "Stazzema Series",
    handle: "stazzema",
    blurb: "Textured Elegance with Natural Depth Inspired by the fine textures of honed limestone, the Stazzema Collection offers a refined balance of elegance, v",
    brand: "Muses",
    colours: ["Ivory", "Smokey Grey"],
    finishes: ["Felltec"],
    sizes: ["300x600mm", "600x600mm", "600x1200mm"],
  },
  {
    name: "Zouks",
    handle: "zouks",
    blurb: "Bold. Textured. Modern. Make a strong design statement with the Zouks Collection – a contemporary tile range defined by its bold texture and dramatic ",
    brand: "Muses",
    colours: [],
    finishes: ["3D"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Aquastone",
    handle: "vienna",
    blurb: "Understated. Natural. Refined. Inspired by the soft textures and organic tones of natural stone, the Aquastone Collection brings effortless elegance t",
    brand: "Capital Tiles",
    colours: ["Ivory"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Calacatta",
    handle: "calacatta",
    blurb: "Classic Marble, Effortlessly Modern Bring timeless elegance into your space with the Calacatta Collection, a stunning marble-look porcelain tile serie",
    brand: "Muses",
    colours: [],
    finishes: ["Polished", "Satin"],
    sizes: ["700x1500"],
  },
  {
    name: "Alps",
    handle: "alps",
    blurb: "Seamless Stone-Look Indoors & Out Inspired by the raw beauty of alpine stone, the Alps Collection delivers a sophisticated, textured finish perfect fo",
    brand: "Capital Tiles",
    colours: ["Beige", "Silver", "Grey"],
    finishes: ["In&Out Solution"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Arctic Tundra",
    handle: "arctic-tundra",
    blurb: "Nature-Inspired Porcelain for Seamless Indoor & Outdoor Spaces Discover the pristine beauty of the wild with the Arctic Tundra Collection – a porcelai",
    brand: "Capital Tiles",
    colours: ["White", "Grey", "Beige"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Jura Collection",
    handle: "jura-collection",
    blurb: "Timeless Limestone-Look Elegance Inspired by the natural beauty of limestone from the Jura region in Germany, the Jura Series brings a refined and sop",
    brand: "Capital Tiles",
    colours: ["White", "Greige", "Grey", "Ivory"],
    finishes: [],
    sizes: ["75x300", "300x300", "300x600", "600x600"],
  },
  {
    name: "Crete Collection",
    handle: "crete-collection",
    blurb: "Soft Stone-Look Porcelain for Seamless Indoor-Outdoor Design The Crete Collection is a refined take on natural stone, offering gentle movement and a s",
    brand: "Capital Tiles",
    colours: ["Warm Beige", "Pearl Grey", "Nero Black", "Bianco White"],
    finishes: [],
    sizes: ["75x300mm", "300x600mm", "600x600mm", "600x1200mm"],
  },
  {
    name: "Ardesia Paver",
    handle: "ardesia-collection",
    blurb: "The ARDESIA collection captures the timeless elegance of slate, bringing the raw beauty of nature into refined interior and exterior spaces. With its ",
    brand: "Muses",
    colours: ["Ivory", "Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Chiswick Outdoor Collection",
    handle: "chiswick-paver-collection",
    blurb: "Seamless Stone Style, Made for the Outdoors Elevate your exterior with Chiswick Outdoor , the latest evolution in the Chiswick Collection—designed to ",
    brand: "Capital Tiles",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    finishes: ["Square Edge Coper", "External Paver"],
    sizes: ["400x600x20", "600x600x20"],
  },
  {
    name: "Chiswick Collection",
    handle: "chiswick-collection",
    blurb: "Where Natural Stone Meets Contemporary Performance Bring timeless elegance and modern function together with the Chiswick Collection —a sophisticated ",
    brand: "Capital Tiles",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    finishes: ["Honed", "Matte"],
    sizes: ["600x1200", "600x600", "300x600", "75x300"],
  },
]
