/* Patio Tiles product detail data.

   Specs, colours, sizes and the copy are the same records already built
   for the ranges shared with our other tile collections, so no product is
   described twice and no image is stored twice. Generated — edit the
   source data, not this file.
*/

export const PATIO_PRODUCTS = [
  {
    handle: "ferragamo",
    name: "Ferragamo",
    brand: "Muses",
    card: "/img/patio/ferragamo.jpg",
    images: [
      "/img/bathroom/ferragamo/1.png",
      "/img/bathroom/ferragamo/2.png",
      "/img/bathroom/ferragamo/3.png",
      "/img/bathroom/ferragamo/4.png",
      "/img/bathroom/ferragamo/5.png",
      "/img/bathroom/ferragamo/6.png",
      "/img/bathroom/ferragamo/7.png",
    ],
    tagline: "4D Glue & Grit finish",
    short: "Ferragamo by Muses. 4D Glue & Grit finish and a single 600x1200 format. On display in our Mitchell showroom.",
    overview: [
      "Ferragamo is part of the bathroom range we hold at Capital Tiles, supplied by Muses.",
      "Formats published for this range are 600x1200. It is offered in 4D Glue & Grit finish. We list it under Bathroom Tiles, Outdoor Tiles and Patio Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Finish: 4D Glue & Grit",
      "Size: 600x1200",
      "Listed under Bathroom Tiles, Outdoor Tiles and Patio Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Ferragamo Bathroom Tiles | Capital Tiles",
    seoDesc: "Ferragamo in 4D Glue & Grit, 600x1200. Supplied and installed across Canberra by Capital Tiles.",
    colours: [],
    sizes: ["600x1200"],
    finishes: ["4D Glue & Grit"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "balcan",
    name: "Balcan",
    brand: "Muses",
    card: "/img/patio/balcan.jpg",
    images: [
      "/img/bathroom/balcan/1.png",
      "/img/bathroom/balcan/2.png",
      "/img/bathroom/balcan/3.png",
      "/img/bathroom/balcan/4.png",
      "/img/bathroom/balcan/5.png",
      "/img/bathroom/balcan/6.png",
      "/img/bathroom/balcan/7.png",
      "/img/bathroom/balcan/8.png",
    ],
    tagline: "4D Glue & Grit finish",
    short: "Balcan by Muses. 4D Glue & Grit finish and a single 600x1200 format. On display in our Mitchell showroom.",
    overview: [
      "Balcan is part of the bathroom range we hold at Capital Tiles, supplied by Muses.",
      "Formats published for this range are 600x1200. It is offered in 4D Glue & Grit finish. We list it under Bathroom Tiles, Kitchen Tiles, Wall Tiles, Outdoor Tiles and Patio Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Finish: 4D Glue & Grit",
      "Size: 600x1200",
      "Listed under Bathroom Tiles, Kitchen Tiles and Wall Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Balcan Bathroom Tiles | Capital Tiles",
    seoDesc: "Balcan in 4D Glue & Grit, 600x1200. Supplied and installed across Canberra by Capital Tiles.",
    colours: [],
    sizes: ["600x1200"],
    finishes: ["4D Glue & Grit"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "aegean-sea",
    name: "Aegean Sea",
    brand: "Muses",
    card: "/img/patio/aegean-sea.jpg",
    images: [
      "/img/patio/aegean-sea/1.jpg",
      "/img/patio/aegean-sea/2.jpg",
      "/img/patio/aegean-sea/3.jpg",
      "/img/patio/aegean-sea/4.jpg",
      "/img/patio/aegean-sea/5.jpg",
      "/img/patio/aegean-sea/6.jpg",
    ],
    tagline: "4D Glue & Grit finish",
    short: "Aegean Sea by Muses. 4D Glue & Grit finish and a single 600x1200 format. On display in our Mitchell showroom.",
    overview: [
      "Aegean Sea is part of the patio tiles range we hold at Capital Tiles, supplied by Muses.",
      "Formats published for this range are 600x1200. It is offered in 4D Glue & Grit finish. We list it under Outdoor Tiles and Patio Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Finish: 4D Glue & Grit",
      "Size: 600x1200",
      "Listed under Outdoor Tiles and Patio Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Aegean Sea Patio Tiles | Capital Tiles",
    seoDesc: "Aegean Sea in 4D Glue & Grit, 600x1200. Supplied and installed across Canberra by Capital Tiles.",
    colours: [],
    sizes: ["600x1200"],
    finishes: ["4D Glue & Grit"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "sassy",
    name: "Sassy",
    brand: "Muses",
    card: "/img/patio/sassy.jpg",
    images: ["/img/patio/sassy/1.jpg", "/img/patio/sassy/2.jpg", "/img/patio/sassy/3.jpg", "/img/patio/sassy/4.jpg"],
    tagline: "Matt in 3 colours",
    short: "Sassy by Muses. 3 colours, matt finish and 3 formats from 300x600 to 600x1200. On display in our Mitchell showroom.",
    overview: [
      "Sassy is part of the patio tiles range we hold at Capital Tiles, supplied by Muses. It runs in ash, beige and slate, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 300x600, 600x600 and 600x1200. It is offered in matt finish. We list it under Kitchen Tiles, Wall Tiles, Outdoor Tiles and Patio Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Ash, Beige and Slate",
      "Finish: Matt",
      "Sizes: 300x600, 600x600, 600x1200",
      "Listed under Kitchen Tiles, Wall Tiles and Outdoor Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Sassy Patio Tiles | Capital Tiles",
    seoDesc: "Sassy in matt, 300x600, 600x600, 600x1200. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["Ash", "Beige", "Slate"],
    sizes: ["300x600", "600x600", "600x1200"],
    finishes: ["Matt"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "blended",
    name: "Blended",
    brand: "Muses",
    card: "/img/patio/blended.jpg",
    images: ["/img/patio/blended/1.jpg", "/img/patio/blended/2.jpg", "/img/patio/blended/3.jpg"],
    tagline: "Matt in 3 colours",
    short: "Blended by Muses. 3 colours, matt finish and 3 formats from 300x600 to 600x1200. On display in our Mitchell showroom.",
    overview: [
      "Blended is part of the patio tiles range we hold at Capital Tiles, supplied by Muses. It runs in white, ash and taupe, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 300x600, 600x600 and 600x1200. It is offered in matt finish. We list it under Kitchen Tiles, Wall Tiles and Patio Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: White, Ash and Taupe",
      "Finish: Matt",
      "Sizes: 300x600, 600x600, 600x1200",
      "Listed under Kitchen Tiles, Wall Tiles and Patio Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Blended Patio Tiles | Capital Tiles",
    seoDesc: "Blended in matt, 300x600, 600x600, 600x1200. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["White", "Ash", "Taupe"],
    sizes: ["300x600", "600x600", "600x1200"],
    finishes: ["Matt"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "nova-stone",
    name: "Nova Stone",
    brand: "Muses",
    card: "/img/patio/nova-stone.jpg",
    images: ["/img/patio/nova-stone/1.jpg", "/img/patio/nova-stone/2.jpg", "/img/patio/nova-stone/3.jpg"],
    tagline: "Matt in 3 colours",
    short: "Nova Stone by Muses. 3 colours, matt finish and 3 formats from 300x600 to 600x1200. On display in our Mitchell showroom.",
    overview: [
      "Nova Stone is part of the patio tiles range we hold at Capital Tiles, supplied by Muses. It runs in ivory, fog and white, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 300x600, 600x600 and 600x1200. It is offered in matt finish. We list it under Kitchen Tiles, Wall Tiles and Patio Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Ivory, Fog and White",
      "Finish: Matt",
      "Sizes: 300x600, 600x600, 600x1200",
      "Listed under Kitchen Tiles, Wall Tiles and Patio Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Nova Stone Patio Tiles | Capital Tiles",
    seoDesc: "Nova Stone in matt, 300x600, 600x600, 600x1200. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["Ivory", "Fog", "White"],
    sizes: ["300x600", "600x600", "600x1200"],
    finishes: ["Matt"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "port-travertino",
    name: "Port Travertino",
    brand: "Muses",
    card: "/img/patio/port-travertino.jpg",
    images: ["/img/bathroom/port-travertino/1.png", "/img/bathroom/port-travertino/2.png"],
    tagline: "3d in 3 colours",
    short: "Port Travertino by Muses. 3 colours, 3D finish and 3 formats from 300x600 to 600x1200. On display in our Mitchell showroom.",
    overview: [
      "Port Travertino is part of the bathroom range we hold at Capital Tiles, supplied by Muses. It runs in beige, ivory and Light Grey, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 300x600, 600x600 and 600x1200. It is offered in 3D finish. We list it under Bathroom Tiles, Kitchen Tiles, Wall Tiles, Patio Tiles and Floor Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Beige, Ivory and Light Grey",
      "Finish: 3D",
      "Sizes: 300x600, 600x600, 600x1200",
      "Listed under Bathroom Tiles, Kitchen Tiles and Wall Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Port Travertino Bathroom Tiles | Capital Tiles",
    seoDesc: "Port Travertino in 3D, 300x600, 600x600, 600x1200. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["Beige", "Ivory", "Light Grey"],
    sizes: ["300x600", "600x600", "600x1200"],
    finishes: ["3D"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "limestone",
    name: "Limestone",
    brand: "Muses",
    card: "/img/patio/limestone.jpg",
    images: ["/img/bathroom/limestone/1.png", "/img/bathroom/limestone/2.png"],
    tagline: "Matt in 4 colours",
    short: "Limestone by Muses. 4 colours, matt finish and 3 formats from 300x600 to 600x1200. On display in our Mitchell showroom.",
    overview: [
      "Limestone is part of the bathroom range we hold at Capital Tiles, supplied by Muses. It runs in beige, Beige Fluted, Ivory Fluted and ivory, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 300x600, 600x600 and 600x1200. It is offered in matt finish. We list it under Bathroom Tiles, Kitchen Tiles, Wall Tiles, Patio Tiles and Floor Tiles.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Beige, Beige Fluted, Ivory Fluted and Ivory",
      "Finish: Matt",
      "Sizes: 300x600, 600x600, 600x1200",
      "Listed under Bathroom Tiles, Kitchen Tiles and Wall Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Limestone Bathroom Tiles | Capital Tiles",
    seoDesc: "Limestone in matt, 300x600, 600x600, 600x1200. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["Beige", "Beige Fluted", "Ivory Fluted", "Ivory"],
    sizes: ["300x600", "600x600", "600x1200"],
    finishes: ["Matt"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "find",
    name: "Find",
    brand: "Muses",
    card: "/img/patio/find.jpg",
    images: [
      "/img/bathroom/find/1.png",
      "/img/bathroom/find/2.png",
      "/img/bathroom/find/3.png",
      "/img/bathroom/find/4.png",
      "/img/bathroom/find/5.png",
      "/img/bathroom/find/6.png",
    ],
    tagline: "large-format grey with Felltec finish",
    short: "Find is a 600 x 1200 tile in Cool Grey and Light Grey with a Felltec finish. Big pieces, few grout lines, and a colour that stays out of the way.",
    overview: [
      "Find keeps things restrained. Two greys, Cool Grey and Light Grey, in a single 600 x 1200 format with a Felltec finish. Cool Grey sits on the cooler side of neutral and holds its own against black or chrome tapware. Light Grey is the softer of the pair and tends to take on whatever colour is around it, which makes a room easy to plan.",
      "The single 600 x 1200 format means fewer grout lines and a calmer surface, though the substrate has to be right, since a large tile shows every hollow underneath. Muses prints 8 faces in this size, so the same tile does not keep reappearing across a floor. Find is listed for bathrooms, kitchens, walls, patios and floors.",
      "You will find both colours at Mitchell. A 600 x 1200 is a tile worth seeing whole before it is ordered, since the face and the colour both change at that scale. We sell to trade and to homeowners, and our installers can cover removal, substrate prep, laying, grouting and sealing. Measures and quotes are free.",
    ],
    features: [
      "Two colourways: Cool Grey and Light Grey",
      "Single large format: 600 x 1200",
      "Felltec finish across both colours",
      "8 faces at 600 x 1200 to limit visible repeats",
      "Listed for bathrooms, kitchens, walls, patios and floors",
      "Free measure and quote, with installation by our own team",
    ],
    seoTitle: "Find Tiles 600x1200 | Capital Tiles",
    seoDesc: "Find by Muses in Cool Grey and Light Grey, 600 x 1200 with a Felltec finish. Listed for bathrooms, kitchens, walls and floors. Mitchell showroom.",
    colours: ["Cool Grey", "Light Grey"],
    sizes: ["600x1200"],
    finishes: ["Felltec"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "starry",
    name: "Starry",
    brand: "Muses",
    card: "/img/patio/starry.jpg",
    images: [
      "/img/bathroom/starry/1.png",
      "/img/bathroom/starry/2.png",
      "/img/bathroom/starry/3.png",
      "/img/bathroom/starry/4.png",
      "/img/bathroom/starry/5.png",
    ],
    tagline: "stone-textured porcelain in three colours",
    short: "Muses porcelain with the texture and appearance of natural stone, in Beige, Light Grey and Black. Felltec finish, in 300x600, 600x600 and 600x1200.",
    overview: [
      "Starry is a porcelain tile from Muses built around the texture and appearance of natural stone. It is a quiet, warm look rather than a busy one, and it works as a background surface in a room where the joinery or the view is meant to be the interest. Three colours are offered: Beige, Light Grey and Black. The finish is Felltec.",
      "Sizes are 300 x 600, 600 x 600 and 600 x 1200, which covers a wall, a floor and a large open area from the one range. Starry is listed for bathrooms, kitchens, walls, outdoor areas and patios. Muses builds it for the wear of modern homes and commercial spaces, which is the useful part when a tile has to look good and still cop daily traffic.",
      "The Starry range sits in the Mitchell showroom in full tiles, so you can see how the stone texture reads at 600 x 1200 rather than guessing from a chip. We supply trade and homeowners, and our installers can take a job from removal and substrate prep through laying, grouting and sealing. Free measure and quote.",
    ],
    features: [
      "Porcelain with the texture and appearance of natural stone",
      "Colours: Beige, Light Grey and Black",
      "Felltec finish across the range",
      "Sizes: 300 x 600, 600 x 600 and 600 x 1200",
      "Built for the demands of modern homes and commercial spaces",
      "Listed for bathrooms, kitchens, walls, outdoor areas and patios",
    ],
    seoTitle: "Starry Porcelain Tiles | Capital Tiles",
    seoDesc: "Starry porcelain by Muses in Beige, Light Grey and Black with a Felltec finish. 300x600, 600x600 and 600x1200. See the range at our Mitchell showroom.",
    colours: ["Beige", "Light Grey", "Black"],
    sizes: ["300x600", "600 x 600", "600x1200"],
    finishes: ["Felltec"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "trav-vein-cut",
    name: "Trav Vein Cut",
    brand: "Muses",
    card: "/img/patio/trav-vein-cut.jpg",
    images: [
      "/img/bathroom/trav-vein-cut/1.png",
      "/img/bathroom/trav-vein-cut/2.png",
      "/img/bathroom/trav-vein-cut/3.png",
    ],
    tagline: "vein-cut travertine with linear movement",
    short: "Cut along the vein, so the movement runs in bands rather than clouds. Beige, Ivory and Light Grey in 300x600, 600x600 and 600x1200, with a 3D Deep Ink finish.",
    overview: [
      "Vein cut is the other way of cutting travertine, and it gives long directional banding instead of an open cloud pattern. Laid with the veins running the same way, a floor stretches visually along that line, which is worth knowing in a narrow bathroom or a galley kitchen. Trav Vein Cut comes in Beige, Ivory and Light Grey with the 3D Deep Ink finish.",
      "The range covers 300 x 600, 600 x 600 and 600 x 1200, and it is listed for bathrooms, kitchens, walls, outdoor areas and patios. Face counts sit at 24 for the 300 x 600, 12 for the 600 x 600 and 8 for the 600 x 1200. Because the pattern is directional, set out matters more than it does with a random face, so decide the vein direction before the first tile goes down.",
      "Full tiles in all three colours are at our Mitchell showroom, which is the only real way to judge directional veining, since a chip cuts the pattern off before it does anything. We supply trade and homeowners, and our own installers handle removal, substrate prep, laying, grouting and sealing. Free measure and quote.",
    ],
    features: [
      "Vein-cut travertine look with linear, directional banding",
      "Surface texture from the 3D Deep Ink finish",
      "Available in 300 x 600, 600 x 600 and 600 x 1200",
      "Beige, Ivory and Light Grey colourways",
      "8 faces at 600 x 1200, 12 at 600 x 600, 24 at 300 x 600",
      "Listed for bathrooms, kitchens, walls, outdoor areas and patios",
    ],
    seoTitle: "Trav Vein Cut Tiles | Capital Tiles",
    seoDesc: "Trav Vein Cut by Muses in Beige, Ivory and Light Grey. 300x600, 600x600 and 600x1200, 3D Deep Ink finish. On display at our Mitchell showroom.",
    colours: ["Beige", "Ivory", "Light Grey"],
    sizes: ["300x600", "600 x 600", "600x1200"],
    finishes: ["3D"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "trav-cross-cut",
    name: "Trav Cross Cut",
    brand: "Muses",
    card: "/img/patio/trav-cross-cut.jpg",
    images: [
      "/img/bathroom/trav-cross-cut/1.png",
      "/img/bathroom/trav-cross-cut/2.jpg",
      "/img/bathroom/trav-cross-cut/3.png",
    ],
    tagline: "cross-cut travertine look, three sizes",
    short: "Trav Cross Cut takes the cloudy, cross-cut travertine face and prints it with a 3D Deep Ink finish across 300x600, 600x600 and 600x1200, in Beige, Ivory and Light Grey.",
    overview: [
      "Trav Cross Cut copies the face you get when travertine is cut across the bed: soft cloudy movement rather than straight lines, with the pattern spreading in every direction. Muses uses a 3D Deep Ink finish, which puts texture into the surface rather than printing a flat picture. Three colours are available, Beige, Ivory and Light Grey.",
      "Sizes run 300 x 600, 600 x 600 and 600 x 1200, so you can drop to the small format on a shower wall and use the long tile across an open floor without changing the look. Face counts are generous at 24 for the 300 x 600, 12 for the 600 x 600 and 8 for the 600 x 1200, which is what stops a big floor turning into a visible pattern. The range is listed for bathrooms, kitchens, walls, outdoor areas and patios.",
      "We hold Trav Cross Cut at Mitchell, where you can lay a 600 x 1200 next to a 300 x 600 and see how the face carries between the two before you settle on a layout. Supply goes to trade and homeowners. Our installers take on removal, substrate prep, laying, grouting and sealing, and the measure and quote is free.",
    ],
    features: [
      "Cross-cut travertine face with cloudy, multi-directional movement",
      "3D Deep Ink finish for surface texture, not a flat print",
      "Three sizes: 300 x 600, 600 x 600 and 600 x 1200",
      "Colours: Beige, Ivory and Light Grey",
      "24 faces at 300 x 600, 12 at 600 x 600, 8 at 600 x 1200",
      "Listed for bathrooms, kitchens, walls, outdoor areas and patios",
    ],
    seoTitle: "Trav Cross Cut Tiles | Capital Tiles",
    seoDesc: "Trav Cross Cut by Muses in Beige, Ivory and Light Grey. 300x600, 600x600 and 600x1200 with a 3D Deep Ink finish. See it at our Mitchell showroom.",
    colours: ["Beige", "Ivory", "Light Grey"],
    sizes: ["300x600", "600 x 600", "600x1200"],
    finishes: ["3D"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "quartzite-paver",
    name: "Quartzite Paver",
    brand: "Muses",
    card: "/img/patio/quartzite-paver.jpg",
    images: [
      "/img/bathroom/quartzite-paver/1.png",
      "/img/bathroom/quartzite-paver/2.png",
      "/img/bathroom/quartzite-paver/3.png",
      "/img/bathroom/quartzite-paver/4.png",
    ],
    tagline: "Charcoal and Grigio paving in 20mm",
    short: "The darker end of the paver format: Charcoal and Grigio, 600 x 600, 20mm thick. Paving that sits back and lets the planting and the walls do the talking.",
    overview: [
      "Quartzite takes the paver format to the darker end, in Charcoal and Grigio. Charcoal is the deeper of the two and reads close to black against pale render. Grigio is a mid grey and easier to live with across a large area. Both come in the Paver finish at 20mm thick, in a single 600 x 600 size.",
      "The range is listed for outdoor areas and patios, and for bathrooms, kitchens and walls. With one size to set out, the planning is mostly about where your cuts land. Run a dry lay against the longest straight edge and push the part tiles to the least visible side. Allow for the 20mm thickness at every threshold and step.",
      "Both colours are in the Mitchell showroom, and dark paving in particular is worth seeing full size, since a small chip of Charcoal tells you almost nothing about how a whole courtyard will look. We supply trade and homeowners, install with our own crew, and quote after a free measure.",
    ],
    features: [
      "Two colours: Charcoal and Grigio",
      "600 x 600 paver at 20mm thick",
      "Supplied in the Paver finish",
      "Listed for outdoor areas, patios, bathrooms, kitchens and walls",
      "Full Charcoal and Grigio pavers on display at Mitchell",
      "Removal, prep, laying, grouting and sealing by our installers",
    ],
    seoTitle: "Quartzite Paver Charcoal & Grigio | Capital Tiles",
    seoDesc: "Quartzite Paver by Muses in Charcoal and Grigio. 600 x 600 pavers, 20mm thick, Paver finish. Listed for outdoor and patio use. Mitchell showroom.",
    colours: ["Charcoal", "Grigio"],
    sizes: ["600 x 600"],
    finishes: ["Paver"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "petra-mix-paver",
    name: "Petra Mix Paver",
    brand: "Muses",
    card: "/img/patio/petra-mix-paver.jpg",
    images: [
      "/img/bathroom/petra-mix-paver/1.png",
      "/img/bathroom/petra-mix-paver/2.png",
      "/img/bathroom/petra-mix-paver/3.jpg",
      "/img/bathroom/petra-mix-paver/4.png",
      "/img/bathroom/petra-mix-paver/5.jpg",
    ],
    tagline: "blendable beige, ivory and Light Grey paving",
    short: "Petra Mix runs Beige, Ivory and Light Grey in one 600 x 600 paver at 20mm. Use a single tone, or blend all three across a larger paved area.",
    overview: [
      "Petra Mix is a Muses paver in three tones: Beige, Ivory and Light Grey. The three are close in weight, which is what makes blending them work. Lay them at random across a courtyard and the paving picks up variation without any one colour jumping out. Used on their own, Beige gives the warmest result and Light Grey the coolest of the three.",
      "The format is 600 x 600 in the Paver finish, 20mm thick. It is listed for outdoor areas and patios, and for bathroom, kitchen and wall use. If you are mixing colours, work out the ratio before ordering rather than after, and open several boxes at once when laying so the blend stays even right across the area.",
      "Come and see all three at Mitchell. We hold full pavers rather than chips, so you can lay a few together on the showroom floor and settle the mix before anything is ordered. Trade and homeowners are both welcome, installation is available through our own team, and measures and quotes are free.",
    ],
    features: [
      "Three tones: Beige, Ivory and Light Grey",
      "600 x 600 paver at 20mm thick",
      "Paver finish, suited to blending or single-colour laying",
      "Listed for outdoor areas, patios, bathrooms, kitchens and walls",
      "Settle your colour mix on the showroom floor before ordering",
      "Installed by our own team, or supplied to trade",
    ],
    seoTitle: "Petra Mix Paver 600x600 | Capital Tiles",
    seoDesc: "Petra Mix Paver by Muses in Beige, Ivory and Light Grey. 600 x 600 pavers at 20mm thick with a Paver finish. Full pavers at our Mitchell showroom.",
    colours: ["Beige", "Ivory", "Light Grey"],
    sizes: ["600 x 600"],
    finishes: ["Paver"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "imperial-stone-paver",
    name: "Imperial Stone Paver",
    brand: "Muses",
    card: "/img/patio/imperial-stone-paver.jpg",
    images: [
      "/img/bathroom/imperial-stone-paver/1.png",
      "/img/bathroom/imperial-stone-paver/2.png",
      "/img/bathroom/imperial-stone-paver/3.png",
      "/img/bathroom/imperial-stone-paver/4.png",
    ],
    tagline: "two pale tones for paving",
    short: "Ivory and Light Grey in a 600 x 600 paver, 20mm thick. Two pale tones that keep a courtyard feeling open without going stark white.",
    overview: [
      "Imperial Stone is a paver from Muses in Ivory and Light Grey. Both are pale, and both keep a paved area feeling open rather than closing it in the way a dark floor can. Ivory is the warmer of the two. Light Grey is the more neutral, and sits better against rendered walls and dark window frames. Each comes in the Paver finish.",
      "One size covers the range, 600 x 600, at 20mm thick. That thickness means planning the finished level early, particularly against a door threshold or where new paving meets an old slab. The range is listed for outdoor areas and patios, and also for bathrooms, kitchens and walls if you are carrying one surface from inside to out.",
      "Both colours are on the floor at our Mitchell showroom in full 600 x 600 pieces, which tells you far more than a chip about how pale paving behaves in Canberra light. We supply trade and homeowners, our installers do removal, substrate prep, laying, grouting and sealing, and the measure and quote is free.",
    ],
    features: [
      "Two colours: Ivory and Light Grey",
      "600 x 600 paver at 20mm thick",
      "Supplied in the Paver finish",
      "Listed for outdoor areas, patios, bathrooms, kitchens and walls",
      "Full-size pavers held in the Mitchell showroom",
      "Free measure and quote across Canberra and Queanbeyan",
    ],
    seoTitle: "Imperial Stone Paver | Capital Tiles",
    seoDesc: "Imperial Stone Paver by Muses in Ivory and Light Grey. 600 x 600, 20mm thick, Paver finish, listed for outdoor and patio use. Mitchell showroom.",
    colours: ["Light Grey", "Ivory"],
    sizes: ["600 x 600"],
    finishes: ["Paver"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "crest-paver",
    name: "Crest Paver",
    brand: "Muses",
    card: "/img/patio/crest-paver.jpg",
    images: [
      "/img/bathroom/crest-paver/1.png",
      "/img/bathroom/crest-paver/2.png",
      "/img/bathroom/crest-paver/3.png",
      "/img/bathroom/crest-paver/4.png",
      "/img/bathroom/crest-paver/5.png",
      "/img/bathroom/crest-paver/6.png",
      "/img/bathroom/crest-paver/7.png",
      "/img/bathroom/crest-paver/8.png",
    ],
    tagline: "three greys in a 20mm paver",
    short: "Crest runs Light Grey, Ivory and Dark Grey in a 600 x 600 paver at 20mm, with twelve faces printed in that size so repeats are hard to pick once the paving is down.",
    overview: [
      "Crest is a 20mm paver from Muses in three colours: Light Grey, Ivory and Dark Grey. They sit close enough to blend across a large area, and far enough apart to work as a border and a field if you want the paving to have some structure. Twelve faces are printed in the 600 x 600 size, so the same tile does not keep turning up.",
      "The range is listed for outdoor areas and patios, and for bathrooms, kitchens and walls, which is useful when a courtyard sits behind a glass door and you want the floor to carry through. Everything comes in the one size, 600 x 600, with the Paver finish. At 20mm the tile is substantial, so allow for the extra height where it meets a threshold or an existing slab.",
      "All three colours are stocked at Mitchell. Bring a photo of the space and we will put full pavers side by side so you can see how Ivory reads against Dark Grey before you order. We sell to trade and to homeowners doing their own job, and our installers can cover removal, substrate prep, laying, grouting and sealing.",
    ],
    features: [
      "Three colours: Light Grey, Ivory and Dark Grey",
      "600 x 600 paver at 20mm thick",
      "Twelve faces in the 600 x 600 size to reduce visible repeats",
      "Paver finish across all three colours",
      "Listed for outdoor areas, patios, bathrooms, kitchens and walls",
      "Removal, prep, laying, grouting and sealing by our own installers",
    ],
    seoTitle: "Crest Paver 600x600 20mm | Capital Tiles",
    seoDesc: "Crest Paver by Muses in Light Grey, Ivory and Dark Grey. 600 x 600 pavers, 20mm thick, twelve faces. On display at our Mitchell showroom.",
    colours: ["Light Grey", "Ivory", "Dark Grey"],
    sizes: ["600 x 600"],
    finishes: ["Paver"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "blaze-paver",
    name: "Blaze Paver",
    brand: "Muses",
    card: "/img/patio/blaze-paver.jpg",
    images: [
      "/img/bathroom/blaze-paver/1.png",
      "/img/bathroom/blaze-paver/2.png",
      "/img/bathroom/blaze-paver/3.png",
      "/img/bathroom/blaze-paver/4.png",
      "/img/bathroom/blaze-paver/5.png",
      "/img/bathroom/blaze-paver/6.png",
      "/img/bathroom/blaze-paver/7.jpg",
      "/img/bathroom/blaze-paver/8.jpg",
    ],
    tagline: "one Light Grey paver, 20mm thick",
    short: "Blaze keeps it simple. Light Grey, 600 x 600, 20mm thick, in the Paver finish, and listed for outdoor areas and patios as well as bathrooms, kitchens and walls.",
    overview: [
      "Blaze is a paver from Muses in a single colour, Light Grey. Sticking to one shade keeps a courtyard, path or alfresco floor reading as one continuous surface, with no sorting between boxes on site. The format is 600 x 600 in the Paver finish, and it runs 20mm thick, which is heavier than a standard indoor floor tile.",
      "Blaze is listed for outdoor areas and patios, and also for bathroom, kitchen and wall use if you want the same face carried from an alfresco floor through to the space it opens onto. The one size, 600 x 600, keeps setting out simple around drains, steps and edges, and cuts down the number of part tiles at the perimeter.",
      "We keep Blaze in the Mitchell showroom so you can put a full 600 x 600 paver on the ground and look at it in daylight, which is the only honest way to judge an outdoor colour. Supply is open to trade and homeowners. Our installers handle removal, substrate prep, laying, grouting and sealing, and a measure and quote costs nothing.",
    ],
    features: [
      "600 x 600 format at 20mm thick",
      "Single colour: Light Grey",
      "Supplied in the Paver finish",
      "Listed for outdoor areas, patios, bathrooms, kitchens and walls",
      "Full pavers on display at Mitchell, not sample chips",
      "Free measure and quote, installation by our own team",
    ],
    seoTitle: "Blaze Paver 600x600 | Capital Tiles",
    seoDesc: "Blaze Paver by Muses in Light Grey, 600 x 600, 20mm thick, Paver finish. Listed for outdoor and patio use. See the full paver at our Mitchell showroom.",
    colours: ["Light Grey"],
    sizes: ["600 x 600"],
    finishes: ["Paver"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "vutton-series",
    name: "Vutton Series",
    brand: "Muses",
    card: "/img/patio/vutton-series.jpg",
    images: [
      "/img/bathroom/vutton-series/1.jpg",
      "/img/bathroom/vutton-series/2.jpg",
      "/img/bathroom/vutton-series/3.jpg",
      "/img/bathroom/vutton-series/4.png",
      "/img/bathroom/vutton-series/5.png",
    ],
    tagline: "mosaic sheets in five colours",
    short: "Mosaic sheets in Ash, Ice, Night, Pearl and Sage. Each sheet runs 275.2 x 275.2mm at 6mm thick, so it sits flat behind a vanity or across a splashback.",
    overview: [
      "Vutton is a mosaic range from Muses, supplied on 275.2 x 275.2mm sheets. Five colours cover the usual decisions: Ash and Night for the darker end, Ice and Pearl for something lighter, and Sage when a room needs a bit of colour without going loud. At 6mm the sheets stay thin enough to sit neatly against the surfaces around them.",
      "The range is listed for bathrooms, kitchens, walls, patios and floors, so one sheet type can carry a shower recess, a splashback and a small floor without changing product. Boxes hold 15 sheets and cover 1.1364sqm, which makes ordering straightforward once you have a measure. Mosaic sheets also work around falls and curved sections better than a large tile does.",
      "All five colours are held at our Mitchell showroom, where you can see a full sheet rather than a chip and check how the colour reads under the lights you actually have. We supply trade and homeowners, and our own installers can take on removal, substrate prep, laying, grouting and sealing. Free measure and quote if you want the numbers before you commit.",
    ],
    features: [
      "Mosaic sheets at 275.2 x 275.2mm",
      "Five colours: Ash, Ice, Night, Pearl and Sage",
      "6mm thickness across the range",
      "15 sheets per box, covering 1.1364sqm",
      "Listed for bathrooms, kitchens, walls, patios and floors",
      "Full sheets on display at our Mitchell showroom",
    ],
    seoTitle: "Vutton Series Mosaic Sheets | Capital Tiles",
    seoDesc: "Vutton Series mosaic sheets by Muses in Ash, Ice, Night, Pearl and Sage. 275.2 x 275.2mm sheets, 6mm thick. See the range at our Mitchell showroom.",
    colours: ["Ash", "Ice", "Night", "Pearl", "Sage"],
    sizes: ["Mosaic Sheets (275.2×275.2mm)"],
    finishes: [],
    thickness: ["6mm"],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "mistery-dark-grey",
    name: "Mistery Dark Grey",
    brand: "Muses",
    card: "/img/patio/mistery-dark-grey.jpg",
    images: [
      "/img/bathroom/mistery-dark-grey/1.png",
      "/img/bathroom/mistery-dark-grey/2.png",
      "/img/bathroom/mistery-dark-grey/3.png",
      "/img/bathroom/mistery-dark-grey/4.png",
      "/img/bathroom/mistery-dark-grey/5.jpg",
      "/img/bathroom/mistery-dark-grey/6.jpg",
      "/img/bathroom/mistery-dark-grey/7.png",
    ],
    tagline: "Two Felltec greys, three sizes",
    short: "Light Grey and Dark Grey in a Felltec finish, from 300x600 up to 600x1200, listed for bathrooms, kitchens, walls, patios and floors.",
    overview: [
      "Mistery Dark Grey runs in two tones, Light Grey and Dark Grey, both in a Felltec finish. The pair sits in the same range, so a darker floor and a lighter wall can be drawn from one collection instead of trying to match across two. Three sizes cover most of what a job needs, from a wall tile up to a large-format floor.",
      "Sizes are 300x600, 600x600 and 600x1200, with faces supplied at 600x1200mm, 600x600mm and 300x600mm so the surface varies across a run. The 300x600 is the wall size, the 600x600 the standard floor, and the 600x1200 the one to reach for when you want fewer joints. It is listed for bathrooms, kitchens, walls, patios and floors.",
      "Light Grey and Dark Grey are both held at Mitchell, so you can put the two side by side as full tiles before deciding which goes where. We supply trade and homeowners across Canberra, Queanbeyan and surrounding areas. Our installers handle removal, substrate prep, laying, grouting and sealing, and the measure and quote is free.",
    ],
    features: [
      "Two tones: Light Grey and Dark Grey",
      "Felltec finish across the range",
      "Sizes 300x600, 600x600 and 600x1200",
      "Faces at 600x1200mm, 600x600mm and 300x600mm",
      "Listed for bathrooms, kitchens, walls, patios and floors",
    ],
    seoTitle: "Mistery Dark Grey Tiles | Capital Tiles",
    seoDesc: "Mistery Dark Grey in Light Grey and Dark Grey, Felltec finish, 300x600 to 600x1200. Bathrooms, kitchens, patios and floors. Canberra showroom.",
    colours: ["Light Grey", "Dark Grey"],
    sizes: ["300x600", "600x600", "600x1200"],
    finishes: ["Felltec"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "find-honed",
    name: "Find Honed",
    brand: "Muses",
    card: "/img/patio/find-honed.jpg",
    images: [
      "/img/bathroom/find-honed/1.png",
      "/img/bathroom/find-honed/2.png",
      "/img/bathroom/find-honed/3.png",
      "/img/bathroom/find-honed/4.png",
      "/img/bathroom/find-honed/5.png",
      "/img/bathroom/find-honed/6.png",
      "/img/bathroom/find-honed/7.png",
    ],
    tagline: "Honed grey in 600x1200 format",
    short: "Large format 600x1200 in Cool Grey or Light Grey with a honed finish, and eight faces so a laid floor does not repeat.",
    overview: [
      "Find Honed comes in two greys, Cool Grey and Light Grey, both in a honed finish. Honed is a flat, low-sheen face rather than a polished one, so the tile holds its colour under downlights instead of bouncing glare back. The range is supplied with eight faces at 600x1200mm and twelve at 600x600mm, which keeps a laid floor from falling into an obvious repeat.",
      "The format is 600x1200. At that size there are fewer grout lines across a floor, which suits open living areas and bathrooms where the surface should read as one plane rather than a grid. Find Honed is listed for bathrooms, kitchens, walls, patios and floors, so the same tile can run from an indoor floor out onto a covered patio.",
      "Full 600x1200 tiles are in the Mitchell showroom, worth a look before ordering large format, since the size is what makes or breaks the finished floor. Capital Tiles sells to trade and to homeowners. Our installers cover removal, substrate prep, laying, grouting and sealing across Canberra and Queanbeyan, and we measure and quote for free.",
    ],
    features: [
      "Two colours: Cool Grey and Light Grey",
      "Honed finish",
      "600x1200 large format",
      "8 faces at 600x1200mm, 12 at 600x600mm",
      "Listed for bathrooms, kitchens, walls, patios and floors",
    ],
    seoTitle: "Find Honed 600x1200 Tiles | Capital Tiles",
    seoDesc: "Find Honed in Cool Grey and Light Grey, 600x1200 with a honed finish and eight faces. Bathrooms, kitchens, patios and floors. Mitchell showroom.",
    colours: ["Cool Grey", "Light Grey"],
    sizes: ["600x1200"],
    finishes: ["Honed"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "calacatta-pro",
    name: "Calacatta Pro",
    brand: "Muses",
    card: "/img/patio/calacatta-pro.jpg",
    images: ["/img/bathroom/calacatta-pro/1.png", "/img/bathroom/calacatta-pro/2.png"],
    tagline: "Bright white Calacatta with grey veining",
    short: "A bright white Calacatta base with grey veining, offered in Felltec or Polished across 300x600, 600x600 and 600x1200.",
    overview: [
      "Calacatta Pro takes the classic Calacatta pattern, a bright white base cut through with grey veining. The veining gives the face depth and balance without the busyness of a heavier marble, which is why it settles as easily into a contemporary bathroom as a traditional one. Two finishes are offered, Felltec and Polished, so the same pattern can be specified soft or bright.",
      "Three sizes are held: 300x600, 600x600 and 600x1200. Faces are supplied at 600x1200mm, 600x600mm and 300x600mm, so the veining shifts across a run instead of repeating tile for tile. Calacatta Pro is listed for bathrooms, kitchens, walls, patios and floors, which means one pattern can carry a floor, a shower wall and a kitchen splashback.",
      "Both finishes are in the Mitchell showroom, and with a veined tile that matters more than usual, because a sample chip only shows you one piece of one vein. Capital Tiles supplies trade and homeowners. Our installers handle removal, substrate prep, laying, grouting and sealing, and a free measure and quote is available across Canberra and Queanbeyan.",
    ],
    features: [
      "Bright white base with grey veining",
      "Felltec and Polished finishes",
      "Sizes 300x600, 600x600 and 600x1200",
      "Faces at 600x1200mm, 600x600mm and 300x600mm",
      "Listed for bathrooms, kitchens, walls, patios and floors",
    ],
    seoTitle: "Calacatta Pro by Muses | Capital Tiles",
    seoDesc: "Calacatta Pro: a bright white Calacatta base with grey veining, in Felltec or Polished, 300x600 to 600x1200. See it in full at our Mitchell showroom.",
    colours: [],
    sizes: ["300x600", "600x600", "600x1200"],
    finishes: ["Felltec", "Polished"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "bari-collection",
    name: "Bari Collection",
    brand: "Capital Tiles",
    card: "/img/patio/bari-collection.jpg",
    images: [
      "/img/bathroom/bari-collection/1.jpg",
      "/img/bathroom/bari-collection/2.jpg",
      "/img/bathroom/bari-collection/3.jpg",
      "/img/bathroom/bari-collection/4.jpg",
      "/img/bathroom/bari-collection/5.jpg",
      "/img/bathroom/bari-collection/6.jpg",
      "/img/bathroom/bari-collection/7.jpg",
      "/img/bathroom/bari-collection/8.jpg",
      "/img/bathroom/bari-collection/9.jpg",
      "/img/bathroom/bari-collection/10.jpg",
      "/img/bathroom/bari-collection/11.jpg",
      "/img/bathroom/bari-collection/12.jpg",
      "/img/bathroom/bari-collection/13.jpg",
      "/img/bathroom/bari-collection/14.jpg",
      "/img/bathroom/bari-collection/15.jpg",
      "/img/bathroom/bari-collection/16.jpg",
      "/img/bathroom/bari-collection/17.jpg",
    ],
    tagline: "Versa touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge in 3 colours",
    short: "Bari Collection. 3 colours, Versa Touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge finishes and 9 formats from 300x600 to 600x400. On display in our Mitchell showroom.",
    overview: [
      "Bari Collection is part of the bathroom range we hold at Capital Tiles. It runs in bianco, taupe and beige, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 300x600, 600x600, 1200x600, 75x300, 307x307 mm sheets, Crazy Pave, French Pattern, 600x400 mm DF and 600x400. It is offered in Versa Touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge finishes. We list it under Bathroom Tiles, Kitchen Tiles, Outdoor Tiles, Patio Tiles, Pool Tiles, Floor Tiles and Pavers.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Bianco, Taupe and Beige",
      "Finishes: Versa Touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge",
      "Sizes: 300x600, 600x600, 1200x600, 75x300",
      "Listed under Bathroom Tiles, Kitchen Tiles and Outdoor Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Bari Collection Bathroom Tiles | Capital Tiles",
    seoDesc: "Bari Collection in Versa Touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge, 300x600, 600x600, 1200x600. Supplied and installed across Canberra by Capital.",
    colours: ["Bianco", "Taupe", "Beige"],
    sizes: ["300x600", "600x600", "1200x600", "75x300", "307x307 mm sheets", "Crazy Pave", "French Pattern", "600x400 mm DF", "600x400"],
    finishes: ["Versa Touch", "P5 20mm", "Cobbles VT", "P5 20mm Pencil Edge"],
    thickness: [],
    slip: [],
    material: [],
    specCols: ["Size (mm)", "Finish", "Pcs/CTN", "m²/CTN", "KG/CTN", "CTNS/PLT", "KG/PLT", "m²/PLT"],
    specRows: [
      ["300 × 600", "Versa Touch P4", "8", "1.44", "31", "40", "1240", "57.60"],
      ["600 × 600", "Versa Touch P4", "4", "1.44", "31", "40", "1240", "57.60"],
      ["75 × 300", "Versa Touch P4", "36", "0.81", "0.47", "72", "1224", "58.32"],
      ["600 × 600 × 20 mm", "Versa Touch P4", "2", "0.72", "34", "40", "1360", "28.80"],
      ["600 × 1200", "Versa Touch P4", "2", "1.44", "34", "56", "1904", "80.64"],
      ["Crazy Pave", "Versa Touch P4", "—", "1.08", "18", "22", "396", "23.76"],
      ["French Pattern", "Versa Touch P4", "6", "0.72", "16", "52", "832", "37.44"],
      ["Cobbles (Straight & Brickbond)", "Versa Touch / Cobbles VT", "11", "1.03", "19", "45", "855", "46.35"],
      ["600 × 400 (20 mm Pencil Edge)", "P5 20 mm", "—", "—", "—", "—", "—", "—"],
      ["600 × 400 (40 mm Drop Face)", "P5 20 mm", "—", "—", "—", "—", "—", "—"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Pool Tiles", href: "/tiles/pool" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
      { label: "Pavers", href: "/tiles/pavers" },
    ],
  },
  {
    handle: "roccia",
    name: "Roccia Series",
    brand: "Muses",
    card: "/img/patio/roccia.jpg",
    images: ["/img/bathroom/roccia/1.png", "/img/bathroom/roccia/2.png", "/img/bathroom/roccia/3.png"],
    tagline: "Rugged stone texture, P4 outdoor option",
    short: "Roccia has the coarse, tactile face of natural stone in two tones, Greige and Charcoal. The Felltec finish is P4 rated, so the same tile runs from the living area out to the patio.",
    overview: [
      "Roccia sits at the rougher end of the stone-look catalogue. The face has real texture to it rather than a smooth print, and it comes in two tones that suit modern Australian interiors: Greige and Charcoal. Multiple faces run across the range, so a laid area does not fall into a visible repeat. The body is porcelain and rated for high-traffic residential and commercial areas.",
      "Two finishes. Matt is not slip rated and belongs indoors, on floors, walls and feature walls. Felltec is P4 rated and is the one to specify for bathrooms, patios, courtyards and other alfresco zones, which is what lets a living area floor carry straight out to an outdoor one without changing material. Sizes are 300x600, 600x600 and 600x1200.",
      "Texture is the whole point of this range and it does not photograph well, so come and put a hand on it. Full tiles in both tones are at the Mitchell showroom. We supply trade and homeowners, our installers take care of removal, substrate prep, laying, grouting and sealing, and there is no charge for a measure and quote.",
    ],
    features: [
      "Porcelain with an authentic, textured stone face",
      "Two tones: Greige and Charcoal",
      "Felltec finish is P4 rated for wet and outdoor areas",
      "Matt finish is not slip rated and is for indoor use",
      "Sizes: 300x600, 600x600 and 600x1200",
      "Multiple faces per tile avoid a repeating layout",
    ],
    seoTitle: "Roccia Series Porcelain Tiles | Capital Tiles",
    seoDesc: "Roccia Series porcelain in Greige and Charcoal. P4-rated Felltec and Matt finishes in 300x600, 600x600 and 600x1200, for indoor and outdoor areas.",
    colours: ["Greige", "Charcoal"],
    sizes: ["300x600", "600x600", "600x1200"],
    finishes: ["Felltec"],
    thickness: [],
    slip: ["P4"],
    material: [],
    specCols: ["Finish", "Slip Rating"],
    specRows: [
      ["Matt", "Not Rated"],
      ["Felltec™ (T)", "P4"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "silver-root",
    name: "Silver Root",
    brand: "Muses",
    card: "/img/patio/silver-root.jpg",
    images: [
      "/img/bathroom/silver-root/1.png",
      "/img/bathroom/silver-root/2.png",
      "/img/bathroom/silver-root/3.jpg",
      "/img/bathroom/silver-root/4.jpg",
      "/img/bathroom/silver-root/5.jpg",
      "/img/bathroom/silver-root/6.jpg",
      "/img/bathroom/silver-root/7.jpg",
      "/img/bathroom/silver-root/8.png",
      "/img/bathroom/silver-root/9.png",
    ],
    tagline: "Marble-veined porcelain in large formats",
    short: "Fine veining, gentle V2 variation, and panels up to 750x1500. Silver Root is a polished porcelain for rooms where you want fewer grout lines and more surface.",
    overview: [
      "Silver Root borrows from high-end marble: fine veining that drifts across the face, with organic movement rather than a hard-edged printed pattern. Variation is V2, so tiles differ a little but the floor stays cohesive. Three tones cover the usual briefs, Ivory for light rooms, Light Grey for cooler schemes, and Brown for warmth. The body is porcelain and built for high-traffic indoor use.",
      "Four sizes run from 300x600 to a 750x1500 panel. The large format is for big living areas, feature walls and lobbies, where cutting the number of joints makes the room feel larger. 600x1200 suits bedrooms, dining rooms and office floors, 600x600 covers residential and commercial floors and walls, and 300x600 takes bathrooms, splashbacks and vertical surfaces. Polished gives a sleek, reflective face, while Soft Polish is the calmer option and is available P4 slip rated.",
      "Handling a 750x1500 panel is a two-person job and the substrate has to be right, which is where our installers earn their keep: removal, substrate prep, laying, grouting and sealing, done by our own crew across Canberra and Queanbeyan. Full panels are up at the Mitchell showroom. We supply trade and homeowners, and the measure and quote is free.",
    ],
    features: [
      "Porcelain with fine marble-style veining and V2 variation",
      "Three tones: Ivory, Light Grey and Brown",
      "Polished and Soft Polish finishes",
      "P4 slip rating available on the Soft Polish surface",
      "Sizes from 300x600 up to 750x1500 panels",
      "Large formats reduce grout lines across big floors",
    ],
    seoTitle: "Silver Root Porcelain Tiles | Capital Tiles",
    seoDesc: "Silver Root marble-look porcelain in Ivory, Light Grey and Brown. Polished and Soft Polish finishes, 300x600 to 750x1500 panels. Mitchell showroom.",
    colours: ["Ivory", "Light Grey", "Brown"],
    sizes: ["750x1500", "600x1200", "600x600", "300x600"],
    finishes: ["Satin"],
    thickness: [],
    slip: ["Not Rated / P4"],
    material: [],
    specCols: ["Size (mm)", "Finish", "Slip Rating", "Pieces/Box", "m²/Box", "Recommended Use"],
    specRows: [
      ["750x1500", "Polished / Soft Polish", "Not Rated / P4", "2", "2.25", "Large living areas, feature walls, lobbies"],
      ["600x1200", "Polished / Soft Polish", "Not Rated / P4", "2", "1.44", "Bedrooms, dining rooms, office floors"],
      ["600x600", "Polished / Soft Polish", "Not Rated / P4", "4", "1.44", "Residential and commercial flooring & walls"],
      ["300x600", "Polished / Soft Polish", "Not Rated / P4", "6", "1.08", "Bathrooms, splashbacks, vertical surfaces"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "stazzema",
    name: "Stazzema Series",
    brand: "Muses",
    card: "/img/patio/stazzema.jpg",
    images: [
      "/img/bathroom/stazzema/1.png",
      "/img/bathroom/stazzema/2.png",
      "/img/bathroom/stazzema/3.png",
      "/img/bathroom/stazzema/4.png",
      "/img/bathroom/stazzema/5.png",
      "/img/bathroom/stazzema/6.png",
      "/img/bathroom/stazzema/7.png",
    ],
    tagline: "Honed limestone look, P4 Felltec option",
    short: "Honed limestone texture in Ivory and Smokey Grey, with a Felltec finish rated P4 for wet areas and a Lappato option for a softer sheen indoors.",
    overview: [
      "Stazzema copies the fine, close texture you get on honed limestone rather than the heavy veining of marble. Two colours: Ivory, which is pale and warm, and Smokey Grey, which is darker and cooler. The range runs V3 variation, meaning the face changes noticeably from tile to tile, so a laid floor moves the way stone does instead of repeating a pattern.",
      "Three sizes: 600x1200mm, 600x600mm and 300x600mm. Two finishes cover different jobs. Lappato has a soft sheen and suits living areas, feature floors and lobbies. Felltec is the P4-rated surface, which is what you want in bathrooms, entryways and anywhere the floor gets wet. The 300x600mm handles bathrooms, splashbacks and entryways, while the larger formats work across floors and walls in commercial and residential spaces.",
      "V3 variation is the reason to see this one in person. Several tiles laid out together at the Mitchell showroom will tell you how far the face moves, which no sample chip can. Capital Tiles supplies trade and homeowners, and we can lay it too: our crew does removal, substrate prep, laying, grouting and sealing. Free measure and quote.",
    ],
    features: [
      "Inspired by the fine texture of honed limestone",
      "Two colours: Ivory and Smokey Grey",
      "Felltec finish carries a P4 slip rating",
      "Lappato finish gives a soft sheen for interiors",
      "Sizes: 600x1200mm, 600x600mm and 300x600mm",
      "V3 variation gives natural movement across a laid floor",
    ],
    seoTitle: "Stazzema Series Tiles | Capital Tiles",
    seoDesc: "Stazzema Series in Ivory and Smokey Grey. P4-rated Felltec and soft-sheen Lappato finishes in 600x1200mm, 600x600mm and 300x600mm. Mitchell showroom.",
    colours: ["Ivory", "Smokey Grey"],
    sizes: ["300x600mm", "600x600mm", "600x1200mm"],
    finishes: ["Felltec"],
    thickness: [],
    slip: ["P4 (Felltec)"],
    material: [],
    specCols: ["Size (mm)", "Finish", "Slip Rating", "Pieces/Box", "m²/Box", "Recommended Use"],
    specRows: [
      ["600x1200", "Lappato / Felltec™", "P4 (Felltec)", "2", "1.44", "Living areas, feature floors, lobbies"],
      [
        "600x600",
        "Lappato / Felltec™",
        "P4 (Felltec)",
        "4",
        "1.44",
        "Floors & walls in commercial and residential spaces",
      ],
      ["300x600", "Lappato / Felltec™", "P4 (Felltec)", "6", "1.08", "Bathrooms, splashbacks, entryways"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "zouks",
    name: "Zouks",
    brand: "Muses",
    card: "/img/patio/zouks.jpg",
    images: [
      "/img/bathroom/zouks/1.png",
      "/img/bathroom/zouks/2.png",
      "/img/bathroom/zouks/3.png",
      "/img/bathroom/zouks/4.png",
      "/img/bathroom/zouks/5.png",
    ],
    tagline: "Textured 3D tiles with dramatic depth",
    short: "Zouks is built around surface texture. The Deep Ink and 3D finishes catch light and throw shadow, which is what makes a feature wall look considered rather than flat.",
    overview: [
      "Most tile ranges try to look like stone. Zouks does not. It is a textured range from Muses with two finishes doing the work: Deep Ink for rich, saturated tone, and 3D for physical relief across the face. The result changes through the day as light moves over it, which is the whole reason to choose a textured tile in the first place.",
      "The size range runs wide, from 300x600 up to 750x1500. The big panels suit statement flooring and feature walls, and 600x1200 works in living areas, lobbies and large open spaces where fewer joints help. 600x600 handles floors and walls in residential or office settings. The 300x600 is the one for vertical surfaces, bathrooms and splashbacks.",
      "Texture is hard to judge from a photo or a sample chip, so we keep Zouks in the Mitchell showroom where you can stand a full 750x1500 panel up and see how the relief reads under light. We supply trade and homeowners. Our installers handle removal, substrate prep, laying, grouting and sealing, and the measure and quote costs nothing.",
    ],
    features: [
      "Two finishes: Deep Ink for tone and 3D for surface relief",
      "Four sizes from 300x600 up to 750x1500 large format",
      "750x1500 panels suit statement flooring and feature walls",
      "600x1200 works in living areas, lobbies and open spaces",
      "300x600 for vertical surfaces, bathrooms and splashbacks",
      "Low-maintenance surface that is easy to clean",
    ],
    seoTitle: "Zouks 3D Textured Tiles | Capital Tiles",
    seoDesc: "Zouks by Muses: Deep Ink and 3D textured tiles in 300x600, 600x600, 600x1200 and 750x1500. Feature walls and statement floors, stocked in Mitchell.",
    colours: [],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
    finishes: ["3D"],
    thickness: [],
    slip: ["None"],
    material: [],
    specCols: ["Size (mm)", "Finish", "Slip Rating", "Pieces/Box", "m²/Box", "Recommended Use"],
    specRows: [
      ["750x1500", "Deep Ink / 3D", "None", "2", "2.25", "Statement flooring, feature walls"],
      ["600x1200", "Deep Ink / 3D", "None", "2", "1.44", "Living areas, lobbies, large open spaces"],
      ["600x600", "Deep Ink / 3D", "None", "4", "1.44", "Floors and walls in residential or office settings"],
      ["300x600", "Deep Ink / 3D", "None", "6", "1.08", "Vertical surfaces, bathrooms, splashbacks"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "vienna",
    name: "Aquastone",
    brand: "Capital Tiles",
    card: "/img/patio/vienna.jpg",
    images: ["/img/bathroom/vienna/1.jpg"],
    tagline: "Ivory matt porcelain for interiors",
    short: "One colour, one finish, no fuss. Aquastone is an Ivory matt porcelain with rectified edges, made for bathroom walls, splashbacks and indoor floors.",
    overview: [
      "Aquastone is a single-colour range and that is rather the point. The Ivory tone is soft and warm-neutral, drawn from natural stone rather than printed to imitate a specific slab, so it sits comfortably against both warm timbers and cool greys. The porcelain body is built for high-traffic indoor use, and the matt face keeps glare down.",
      "It comes in 300x600 and 600x600. The smaller format is the one for bathroom walls, kitchen splashbacks and other vertical surfaces. The 600x600 goes on the floor in living rooms, bedrooms and commercial interiors. Rectified edges mean the tiles can be set with tight grout lines, which matters more on a plain tile than a patterned one, because the joint is the only line you see.",
      "Ivory shifts more than people expect between morning light and downlights, so look at a full tile before you commit. We hold Aquastone at the Mitchell showroom for exactly that reason. Capital Tiles supplies trade and homeowners, and our installers handle removal, substrate prep, laying, grouting and sealing. A free measure and quote comes first.",
    ],
    features: [
      "Single Ivory colourway with a soft, stone-derived tone",
      "Matt finish for a low-glare, non-glossy surface",
      "Porcelain body suited to high-traffic indoor use",
      "300x600 for walls and splashbacks, 600x600 for floors",
      "Rectified edges for tight grout lines",
    ],
    seoTitle: "Aquastone Ivory Matt Tiles | Capital Tiles",
    seoDesc: "Aquastone Ivory matt porcelain with rectified edges. 300x600 for bathroom walls and splashbacks, 600x600 for living room and bedroom floors.",
    colours: ["Ivory"],
    sizes: ["300x600", "600x600"],
    finishes: ["Matt"],
    thickness: [],
    slip: ["None"],
    material: [],
    specCols: ["Size (mm)", "Finish", "Slip Rating", "Pieces/Box", "m²/Box", "Recommended Use"],
    specRows: [
      ["300x600", "Matt", "None", "6", "1.08", "Bathroom walls, kitchen splashbacks, vertical surfaces"],
      ["600x600", "Matt", "None", "4", "1.44", "Living rooms, bedrooms, commercial interiors"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "calacatta",
    name: "Calacatta",
    brand: "Muses",
    card: "/img/patio/calacatta.jpg",
    images: [
      "/img/bathroom/calacatta/1.png",
      "/img/bathroom/calacatta/2.png",
      "/img/bathroom/calacatta/3.png",
      "/img/bathroom/calacatta/4.png",
      "/img/bathroom/calacatta/5.png",
      "/img/bathroom/calacatta/6.png",
      "/img/bathroom/calacatta/7.png",
      "/img/bathroom/calacatta/8.png",
      "/img/bathroom/calacatta/9.png",
      "/img/bathroom/calacatta/10.png",
    ],
    tagline: "Marble-look panels in one large format",
    short: "White marble looks with fine veining, in a single 700x1500 format. Polished for shine, Satin for a softer face, both for interior floors and feature walls.",
    overview: [
      "Calacatta is a marble-look tile taken from the stone of the same name: a white ground with fine veining running through it. Muses produces it in a single large format, which means the veining plays out across a big surface instead of being interrupted by grout lines every few hundred millimetres. It is the look people ask for when they want marble without stone maintenance.",
      "One size, 700x1500, in two finishes. Polished gives the reflective, glassy face marble is usually specified for. Satin keeps the same veining with the shine pulled back. The surface is smooth, so it is best kept to low-traffic or dry indoor areas. The range is at its strongest on interior floors and feature walls, including bathroom and kitchen walls.",
      "A 700x1500 panel is hard to judge from a photo. We keep Calacatta at the Mitchell showroom so you can see a full panel and the direction of the veining before ordering, rather than working off a chip. Capital Tiles supplies trade and homeowners, and our installers handle removal, substrate prep, laying, grouting and sealing on large-format work. Free measure and quote.",
    ],
    features: [
      "Marble look with fine veining over a white ground",
      "One format: 700x1500",
      "Polished or Satin finish",
      "Suited to interior floors and feature walls",
      "Smooth surface, best in low-traffic or dry indoor areas",
      "Full panels on display at the Mitchell showroom",
    ],
    seoTitle: "Calacatta Marble-Look Tiles | Capital Tiles",
    seoDesc: "Calacatta marble-look tiles by Muses in 700x1500, Polished or Satin. For interior floors and feature walls. See full panels at our Mitchell showroom.",
    colours: [],
    sizes: ["700x1500"],
    finishes: ["Polished", "Satin"],
    thickness: [],
    slip: [],
    material: [],
    specCols: ["Finish", "Slip Rating"],
    specRows: [
      ["Polished", "N/A"],
      ["Satin", "N/A"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "alps",
    name: "Alps",
    brand: "Capital Tiles",
    card: "/img/patio/alps.jpg",
    images: [
      "/img/bathroom/alps/1.jpg",
      "/img/bathroom/alps/2.jpg",
      "/img/bathroom/alps/3.jpg",
      "/img/bathroom/alps/4.jpg",
      "/img/bathroom/alps/5.jpg",
      "/img/bathroom/alps/6.jpg",
      "/img/bathroom/alps/7.jpg",
      "/img/bathroom/alps/8.jpg",
      "/img/bathroom/alps/9.jpg",
    ],
    tagline: "One tile, indoors and out",
    short: "One In&Out Solution finish, P4 across all three sizes, in Beige, Silver or Grey. Lay the same tile on an indoor floor and the patio it opens onto.",
    overview: [
      "Alps is built around a single idea: one stone-look tile that works on both sides of the back door. The In&Out Solution finish is the same across every size, so an internal floor and the outdoor area it opens onto can be laid in the one product with no change of tile at the threshold. Three earthy colours, Beige, Silver and Grey, with soft texture and tonal depth.",
      "All three sizes hold a P4 slip rating. 600x1200 comes at 10mm, two per box, for indoor and outdoor floors and walls. 600x600 at 9mm, four per box, does the same job in a smaller module. 300x600 at 9mm, eight per box, is the size for walls, feature areas and outdoor paths. Every box covers 1.44m2.",
      "No sealing is required, which is the difference between this and real stone on an exposed path. We hold Alps in the Mitchell showroom as full tiles, so you can see the texture at scale before ordering. Capital Tiles supplies trade and homeowners, and our installers handle removal, substrate prep, laying, grouting and sealing. Free measure and quote.",
    ],
    features: [
      "In&Out Solution finish across every size",
      "P4 slip rating on all three formats",
      "600x1200 at 10mm; 600x600 and 300x600 at 9mm",
      "Colours: Beige, Silver and Grey",
      "300x600 for walls, feature areas and outdoor paths",
      "No sealing required; 1.44m2 per box",
    ],
    seoTitle: "Alps In&Out Stone-Look Tiles | Capital Tiles",
    seoDesc: "Alps Collection stone-look tiles with In&Out Solution finish, P4, in Beige, Silver and Grey. 300x600 to 600x1200. Supplied and laid across Canberra.",
    colours: ["Beige", "Silver", "Grey"],
    sizes: ["600x600", "600x1200", "300x600"],
    finishes: ["In&Out Solution"],
    thickness: ["10mm", "9mm"],
    slip: ["P4"],
    material: [],
    specCols: ["Size (mm)", "Finish", "Thickness", "Slip Rating", "Pieces/Box", "m²/Box", "Recommended Use"],
    specRows: [
      ["600x1200", "In&Out Solution", "10mm", "P4", "2", "1.44", "Indoor & Outdoor Floors/Walls"],
      ["600x600", "In&Out Solution", "9mm", "P4", "4", "1.44", "Indoor & Outdoor Floors/Walls"],
      ["300x600", "In&Out Solution", "9mm", "P4", "8", "1.44", "Walls, Feature Areas, Outdoor Paths"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "arctic-tundra",
    name: "Arctic Tundra",
    brand: "Capital Tiles",
    card: "/img/patio/arctic-tundra.jpg",
    images: [
      "/img/bathroom/arctic-tundra/1.jpg",
      "/img/bathroom/arctic-tundra/2.jpg",
      "/img/bathroom/arctic-tundra/3.jpg",
      "/img/bathroom/arctic-tundra/4.jpg",
      "/img/bathroom/arctic-tundra/5.jpg",
      "/img/bathroom/arctic-tundra/6.jpg",
      "/img/bathroom/arctic-tundra/7.jpg",
      "/img/bathroom/arctic-tundra/8.jpg",
      "/img/bathroom/arctic-tundra/9.jpg",
      "/img/bathroom/arctic-tundra/10.jpg",
      "/img/bathroom/arctic-tundra/11.jpg",
      "/img/bathroom/arctic-tundra/12.jpg",
    ],
    tagline: "Pale porcelain with an external option",
    short: "Pale, low-contrast Glazed Porcelain in White, Grey and Beige. Matt at P3 for indoors, with a P5 external finish in 600x600 for patios, courtyards and pathways.",
    overview: [
      "Cool, pale and low in contrast, Arctic Tundra runs White, Grey and Beige in Glazed Porcelain with rectified edges for clean lines and minimal grout. Nothing in the range shouts. It is the sort of floor you put down when the joinery, the benchtop or the view out the window is meant to be the thing people notice first.",
      "There are two surfaces. The matt finish is P3 and does the indoor work: 300x300 for bathrooms, laundry floors and feature walls, 300x600 for internal walls and floors, splashbacks and wet areas, and 600x1200 for open-plan interiors, commercial spaces and large floors. The external finish is P5, available in 600x600 only, and that is the one for outdoor zones such as patios, courtyards and pathways.",
      "The porcelain body is frost-resistant, which is the practical reason it holds up on an exposed patio. The range is held in our Mitchell showroom as full tiles, so the difference between the matt and external faces is obvious in the hand. We supply trade and homeowners, our installers cover removal, substrate prep, laying, grouting and sealing, and measure and quote is free.",
    ],
    features: [
      "Glazed porcelain with rectified edges in White, Grey and Beige",
      "Matt finish rated P3 for internal floors and walls",
      "External finish rated P5, available in 600x600 only",
      "Four sizes: 300x300, 300x600, 600x600 and 600x1200",
      "600x1200 for open-plan interiors, commercial spaces and large floors",
      "Frost-resistant body for outdoor zones",
    ],
    seoTitle: "Arctic Tundra Porcelain Tiles | Capital Tiles",
    seoDesc: "Arctic Tundra Glazed Porcelain in White, Grey and Beige. Matt P3 indoors, P5 external in 600x600. Sizes to 600x1200. Supplied and laid in Canberra.",
    colours: ["White", "Grey", "Beige"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
    finishes: ["Matt", "External"],
    thickness: [],
    slip: ["P3", "P3 / P5"],
    material: ["Glazed Porcelain"],
    specCols: ["Size (mm)", "Finish", "Slip Rating", "Material", "Recommended Use"],
    specRows: [
      ["300 x 300", "Matt", "P3", "Glazed Porcelain", "Bathrooms, laundry floors, feature walls"],
      ["300 x 600", "Matt", "P3", "Glazed Porcelain", "Internal walls and floors, splashbacks, wet areas"],
      [
        "600 x 600",
        "Matt / External",
        "P3 / P5",
        "Glazed Porcelain",
        "Indoor living areas (P3) / outdoor zones (P5 only)",
      ],
      ["600 x 1200", "Matt", "P3", "Glazed Porcelain", "Open-plan interiors, commercial spaces, large floors"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "jura-collection",
    name: "Jura Collection",
    brand: "Capital Tiles",
    card: "/img/patio/jura-collection.jpg",
    images: [
      "/img/bathroom/jura-collection/1.jpg",
      "/img/bathroom/jura-collection/2.jpg",
      "/img/bathroom/jura-collection/3.jpg",
      "/img/bathroom/jura-collection/4.jpg",
      "/img/bathroom/jura-collection/5.jpg",
      "/img/bathroom/jura-collection/6.jpg",
      "/img/bathroom/jura-collection/7.jpg",
      "/img/bathroom/jura-collection/8.jpg",
    ],
    tagline: "Limestone-look ceramic for internal rooms",
    short: "Limestone-look ceramic in four quiet tones, matt, P3 rated, in sizes from 75x300 to 600x600. Specified for internal floors and walls.",
    overview: [
      "Jura is a ceramic tile with a limestone face, named after the pale stone of Germany's Jura region. The matt surface carries a light texture, and multiple face variation keeps the pattern from repeating obviously across a laid floor. Four colours run through the range: White, Ivory, Greige and Grey, all at the quiet end where they work as a background rather than a statement.",
      "This one is specified for internal floors and walls only. All four sizes are matt, P3 rated and rectified. 75x300 is the feature wall, splashback and vertical accent size. 300x300 suits small-format floors and mosaic-style layouts. 300x600 covers internal walls, bathrooms and floor work. 600x600 goes into open-plan interiors, floors and larger feature walls.",
      "P3 is the rating for dry and damp internal areas, so Jura belongs indoors and stays there. We keep the range in the Mitchell showroom so you can see a full tile, and several together, to judge how the face variation reads at scale. Capital Tiles supplies trade and homeowners, our own installers do the laying, and a measure and quote costs nothing.",
    ],
    features: [
      "Ceramic body with a matt finish and rectified edges",
      "P3 slip rating for dry and damp internal areas",
      "Sizes: 75x300, 300x300, 300x600 and 600x600",
      "Colours: White, Greige, Grey and Ivory",
      "Multiple face variation for a non-repetitive laid appearance",
      "Specified for internal floor and wall use only",
    ],
    seoTitle: "Jura Collection Limestone-Look Tiles | Capital Tiles",
    seoDesc: "Jura Collection limestone-look ceramic in White, Greige, Grey and Ivory. Matt, P3, 75x300 to 600x600, for internal floors and walls. Mitchell showroom.",
    colours: ["White", "Greige", "Grey", "Ivory"],
    sizes: ["75x300", "300x300", "300x600", "600x600"],
    finishes: ["Matt"],
    thickness: [],
    slip: ["P3"],
    material: ["Ceramic"],
    specCols: ["Size (mm)", "Slip Rating", "Finish", "Material", "Recommended Use"],
    specRows: [
      ["75 x 300", "P3", "Matt", "Ceramic", "Feature walls, splashbacks, vertical accents"],
      ["300 x 300", "P3", "Matt", "Ceramic", "Small-format floors, mosaic-style layouts"],
      ["300 x 600", "P3", "Matt", "Ceramic", "Internal walls, bathrooms, floor applications"],
      ["600 x 600", "P3", "Matt", "Ceramic", "Open-plan interiors, floors & large feature walls"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "crete-collection",
    name: "Crete Collection",
    brand: "Capital Tiles",
    card: "/img/patio/crete-collection.jpg",
    images: [
      "/img/bathroom/crete-collection/1.jpg",
      "/img/bathroom/crete-collection/2.jpg",
      "/img/bathroom/crete-collection/3.jpg",
      "/img/bathroom/crete-collection/4.jpg",
      "/img/bathroom/crete-collection/5.jpg",
      "/img/bathroom/crete-collection/6.jpg",
      "/img/bathroom/crete-collection/7.jpg",
      "/img/bathroom/crete-collection/8.jpg",
      "/img/bathroom/crete-collection/9.jpg",
      "/img/bathroom/crete-collection/10.jpg",
      "/img/bathroom/crete-collection/11.jpg",
      "/img/bathroom/crete-collection/12.jpg",
      "/img/bathroom/crete-collection/13.jpg",
      "/img/bathroom/crete-collection/14.jpg",
      "/img/bathroom/crete-collection/15.jpg",
      "/img/bathroom/crete-collection/16.jpg",
      "/img/bathroom/crete-collection/17.jpg",
      "/img/bathroom/crete-collection/18.jpg",
    ],
    tagline: "Soft stone-look porcelain, inside and out",
    short: "Glazed porcelain with soft stone movement, a matt finish and a P4 slip rating in every size from 75x300mm splashbacks to 600x1200mm floors.",
    overview: [
      "Crete is Glazed Porcelain with a soft stone face. The movement is gentle rather than heavily veined, and the matt surface keeps the sheen down. Rectified edges mean tight, minimal grout lines. Four colours cover most decisions: Warm Beige and Bianco White for light rooms, Pearl Grey for something cooler, and Nero Black when the floor is meant to be the dark element.",
      "Every size carries a P4 slip rating and the same matt finish. 75x300mm is the feature wall, vertical accent and splashback size. 300x600mm goes on internal floors and walls, bathrooms and laundries. 600x600mm handles living areas, kitchens, outdoor zones and covered alfresco. 600x1200mm is the large-format option for open-plan interiors and commercial floors.",
      "The In&Out finish is what lets the same tile run from an internal floor out to a covered deck. Crete is fully vitrified and frost-resistant, which matters on an exposed alfresco slab. The full range sits in our Mitchell showroom as whole tiles. We supply trade and homeowners, our installers handle removal, substrate prep, laying, grouting and sealing, and the measure and quote is free.",
    ],
    features: [
      "Glazed porcelain, matt finish, rectified edges",
      "P4 slip rating across all four sizes",
      "Sizes: 75x300mm, 300x600mm, 600x600mm and 600x1200mm",
      "Colours: Warm Beige, Pearl Grey, Nero Black and Bianco White",
      "In&Out finish runs the same floor from inside to covered alfresco",
      "Fully vitrified and frost-resistant",
    ],
    seoTitle: "Crete Collection Porcelain Tiles | Capital Tiles",
    seoDesc: "Crete Collection Glazed Porcelain, matt finish, P4 slip rating, 75x300mm to 600x1200mm. Four stone-look colours, supplied and laid across Canberra.",
    colours: ["Warm Beige", "Pearl Grey", "Nero Black", "Bianco White"],
    sizes: ["75x300mm", "300x600mm", "600x600mm", "600x1200mm"],
    finishes: ["Matt"],
    thickness: [],
    slip: ["P4"],
    material: ["Glazed Porcelain"],
    specCols: ["Size (mm)", "Slip Rating", "Finish", "Material", "Recommended Use"],
    specRows: [
      ["75 x 300", "P4", "Matt", "Glazed Porcelain", "Feature walls, vertical accents, splashbacks"],
      ["300 x 600", "P4", "Matt", "Glazed Porcelain", "Internal floors and walls, bathrooms, laundries"],
      [
        "600 x 600",
        "P4",
        "Matt",
        "Glazed Porcelain",
        "Living areas, kitchens, outdoor zones, covered alfresco areas",
      ],
      ["600 x 1200", "P4", "Matt", "Glazed Porcelain", "Large-format floors, commercial spaces, open-plan interiors"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
  {
    handle: "ardesia-collection",
    name: "Ardesia Paver",
    brand: "Muses",
    card: "/img/patio/ardesia-collection.jpg",
    images: [
      "/img/bathroom/ardesia-collection/1.png",
      "/img/bathroom/ardesia-collection/2.png",
      "/img/bathroom/ardesia-collection/3.png",
      "/img/bathroom/ardesia-collection/4.png",
    ],
    tagline: "Slate-look paver in two tones",
    short: "Split-slate texture in a 600x600 paver, 20mm thick, in Ivory or Light Grey. Listed for outdoor and patio areas as well as bathrooms, kitchens and walls.",
    overview: [
      "Ardesia takes its cue from split slate. The face is textured and the tone shifts from tile to tile, so a laid wall or floor carries movement rather than a repeating print. Muses offers it in two colours, Ivory and Light Grey, both restrained enough to sit under stronger joinery or a dark benchtop without competing for attention.",
      "The range runs in one format, 600x600, in a paver finish at 20mm thick. That body is what puts it in paver territory rather than standard floor tile. It is listed for outdoor and patio areas, and for bathrooms, kitchens and walls indoors, so a courtyard and the room opening onto it can be laid in the same product.",
      "We hold the range in the Mitchell showroom, so you can stand a full 600x600 on the floor and see how the texture reads at your own light levels rather than judging it off a chip. Capital Tiles supplies trade and homeowners, and our own installers handle removal, substrate prep, laying, grouting and sealing. Measure and quote is free.",
    ],
    features: [
      "Slate-look face with tonal variation between tiles",
      "Two colours: Ivory and Light Grey",
      "Single 600x600 format in a Paver finish",
      "20mm thick paver body",
      "Listed for outdoor and patio areas, bathrooms, kitchens and walls",
      "Full tiles on display in the Mitchell showroom, not sample chips",
    ],
    seoTitle: "Ardesia Paver Slate-Look Tiles | Capital Tiles",
    seoDesc: "Ardesia Paver by Muses: 600x600 paver finish, 20mm, in Ivory and Light Grey. See full tiles at the Capital Tiles showroom in Mitchell, Canberra.",
    colours: ["Ivory", "Light Grey"],
    sizes: ["600 x 600"],
    finishes: ["Paver"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
    ],
  },
  {
    handle: "chiswick-paver-collection",
    name: "Chiswick Outdoor Collection",
    brand: "Capital Tiles",
    card: "/img/patio/chiswick-paver-collection.jpg",
    images: [
      "/img/patio/chiswick-paver-collection/1.jpg",
      "/img/patio/chiswick-paver-collection/2.jpg",
      "/img/patio/chiswick-paver-collection/3.jpg",
      "/img/patio/chiswick-paver-collection/4.jpg",
      "/img/patio/chiswick-paver-collection/5.jpg",
    ],
    tagline: "Square edge coper and External Paver in 4 colours",
    short: "Chiswick Outdoor Collection. 4 colours, Square Edge Coper and External Paver finishes and 2 formats from 400x600x20 to 600x600x20. On display in our Mitchell showroom.",
    overview: [
      "Chiswick Outdoor Collection is part of the patio tiles range we hold at Capital Tiles. It runs in white, cream, gray and charcoal, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 400x600x20 and 600x600x20. It is offered in Square Edge Coper and External Paver finishes. We list it under Outdoor Tiles, Patio Tiles, Pool Tiles and Pavers.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: White, Cream, Gray and Charcoal",
      "Finishes: Square Edge Coper and External Paver",
      "Sizes: 400x600x20, 600x600x20",
      "Listed under Outdoor Tiles, Patio Tiles and Pool Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Chiswick Outdoor Collection Patio Tiles | Capital Tiles",
    seoDesc: "Chiswick Outdoor Collection in Square Edge Coper and External Paver, 400x600x20, 600x600x20. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    sizes: ["400x600x20", "600x600x20"],
    finishes: ["Square Edge Coper", "External Paver"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Pool Tiles", href: "/tiles/pool" },
      { label: "Pavers", href: "/tiles/pavers" },
    ],
  },
  {
    handle: "chiswick-collection",
    name: "Chiswick Collection",
    brand: "Capital Tiles",
    card: "/img/patio/chiswick-collection.jpg",
    images: [
      "/img/bathroom/chiswick-collection/1.jpg",
      "/img/bathroom/chiswick-collection/2.jpg",
      "/img/bathroom/chiswick-collection/3.jpg",
      "/img/bathroom/chiswick-collection/4.jpg",
    ],
    tagline: "Stone-look tiles in four neutrals",
    short: "Four stone-look colours from White to Charcoal, in honed or matte, across four sizes. One range that covers a bathroom wall, a kitchen floor and the patio outside.",
    overview: [
      "Chiswick is a stone-look range built around four colours: White, Cream, Gray and Charcoal. That spread covers everything from a pale bathroom to a near-black floor without changing tile. Two finishes sit over the top of it. Honed is achieved through a double polishing process and comes out ultra-smooth. Matte keeps the face flat and the sheen down.",
      "Sizes run from 75x300, which is subway proportions for splashbacks and vertical work, up to 600x1200 for open floors with fewer joints. In between sit 300x600 and 600x600. The collection is listed for bathrooms, kitchens, walls, patios and floors, so one colour can carry through a wet area and continue outside onto the patio.",
      "Chiswick is our own range, held in the Mitchell showroom as full tiles rather than chips, so you can see honed and matte side by side in the same colour before committing. Capital Tiles supplies trade and homeowners. Our installers take on removal, substrate prep, laying, grouting and sealing, and a free measure and quote comes first.",
    ],
    features: [
      "Four colours: White, Cream, Gray and Charcoal",
      "Honed finish, double polished to an ultra-smooth surface",
      "Matte finish for a flat, low-sheen face",
      "Four sizes: 75x300, 300x600, 600x600 and 600x1200",
      "Listed for bathrooms, kitchens, walls, patios and floors",
      "Free measure and quote, supply to trade and homeowners",
    ],
    seoTitle: "Chiswick Collection Stone-Look Tiles | Capital Tiles",
    seoDesc: "Chiswick Collection stone-look tiles in White, Cream, Gray and Charcoal. Honed or matte, 75x300 to 600x1200. Supplied and installed across Canberra.",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    sizes: ["600x1200", "600x600", "300x600", "75x300"],
    finishes: ["Honed", "Matte"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Wall Tiles", href: "/tiles/wall" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
    ],
  },
]

export function byHandle(handle) {
  return PATIO_PRODUCTS.find((p) => p.handle === handle)
}
