/* Polypropylene carpet range, taken from the live capitaltiles.com.au polypropylene collection:
   names, blurbs, brands and the colour / finish / size options each product
   actually ships with. */

export const POLYPROPYLENE = [
  {
    name: "Enforcer 4M",
    handle: "enforcer-4m",
    blurb: "An economical flooring solution for the cost conscious buyer, this high low loop pile carpet is a great option for your first home or investment prope",
    brand: "God Freyhirst",
    colours: ["Warmstone", "Windspray", "Smoke", "Lava", "Aggregate", "Basalt", "Mineral", "Monolith"],
    finishes: ["Loop Pile", "High-Low", "Textured"],
    sizes: ["4m wide"],
  },
  {
    name: "Ovation",
    handle: "ovation",
    blurb: "Ovation is a versatile and affordable Textured Loop Pile carpet that is sure to add style and value to your home. Details Fibre : Polypropylene Carpet",
    brand: "God Freyhirst",
    colours: ["Doeskin", "Oyster", "Heron", "Pumice", "Woodland", "Folkstone", "Caviar", "Blacksmith"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Forest Park",
    handle: "forest-park",
    blurb: "Versatile and stylish, Forest Park is a textured loop carpet that is sure to add value to your home. Details Fibre : Polypropylene Carpet Brand: Yarn:",
    brand: "God Freyhirst",
    colours: ["Waterfall", "Sandstone", "Clay Stone", "Beacon", "Smoke", "Bedrock", "Cloud", "Forge"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Campaspe",
    handle: "campaspe",
    blurb: "An economical flooring solution for the cost conscious buyer, this high low loop pile carpet is a great option for your first home or investment prope",
    brand: "God Freyhirst",
    colours: ["China Clay", "Mortar", "Glacial", "Siltstone", "Overcast", "Boulder", "Storm Grey", "Cinders"],
    finishes: ["Loop Pile", "High-Low", "Textured"],
    sizes: [],
  },
  {
    name: "Callisto",
    handle: "callisto",
    blurb: "An economical flooring solution for the cost conscious buyer, this high low loop pile carpet is a great option for your first home or investment prope",
    brand: "God Freyhirst",
    colours: ["Light Brown", "Grey", "Charcoal", "Panther"],
    finishes: ["Level Loop", "Loop Pile", "High-Low"],
    sizes: [],
  },
  {
    name: "Riviera",
    handle: "riviera",
    blurb: "Riviera is a versatile and affordable high low loop patterned carpet that is sure to add style and value to your home. Details Fibre : Polypropylene C",
    brand: "God Freyhirst",
    colours: ["Claystone", "Vapour", "Sea Fog", "Nimbus", "Masonry", "Gravel", "Storm Grey", "Gunmetal"],
    finishes: ["Loop Pile", "High-Low", "Textured"],
    sizes: [],
  },
  {
    name: "Astra",
    handle: "astra",
    blurb: "Australian Made, versatile and stylish, Astra is an on-trend, chunky loop pile carpet that adds value to your home. Details Fibre : Polypropylene Carp",
    brand: "God Freyhirst",
    colours: ["Palatial", "Plateau", "Mirage", "Beyond", "Affinity", "Ornate"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Encounter",
    handle: "encounter",
    blurb: "Encounter is a trendy and budget-friendly, tough, stain-resistant carpet ideal for active families, offering easy maintenance and exceptional affordab",
    brand: "EC carpets",
    colours: ["Sandbar 7574", "Shorebird 7579", "Spice 7585", "Anchorage 7576", "Newland 7577", "Pontoon 7575", "Botany 7578", "Storm 7589"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Montrosa",
    handle: "montrosa",
    blurb: "Montrosa is a stain-resistant carpet designed for active families, combining stylish design and affordability for homeowners, landlords, builders, and",
    brand: "EC carpets",
    colours: ["Spire 2504", "Faber 2506", "Hillford 2508", "Vistron 2509", "Bottania 2516", "Leedon 2511", "Avila 2525", "Chantilly 2515"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Savanna",
    handle: "savanna",
    blurb: "Savanna is a medium-duty, tough stain-resistant carpet ideal for active families, raising the bar for premium polypropylene carpets by providing outst",
    brand: "EC carpets",
    colours: ["Rivergum 2932", "Candlebark 2931", "Coolibah 2933", "Cottonwood 2938", "Wattle 2937", "Applebush 2935", "Copperburr 2936"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Summit Point",
    handle: "summit-point",
    blurb: "Summit Point is a medium-duty, tough stain-resistant carpet ideal for active families, raising the bar for premium polypropylene carpets by providing ",
    brand: "EC carpets",
    colours: ["Feathertop+2922", "Selwyn+2921", "Howitt+2923", "Townsend+2928", "Riverina+2927", "Hotham+2925", "Franklin+2926"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Woodchester",
    handle: "woodchester",
    blurb: "Woodchester offers stylish and budget-friendly polypropylene carpeting, combining contemporary design with affordability for homeowners, landlords, bu",
    brand: "EC carpets",
    colours: ["Callington 3504", "Meechi 3508", "Tinpot 3509", "Rodwell 3516", "Dalveen 3511", "Macallan 3525"],
    finishes: [],
    sizes: [],
  },
]
