/* Polyester Carpet product detail data.

   Style, fibre, roll width, thickness, ratings and the descriptions come
   from the live capitaltiles.com.au feed for this collection. Generated —
   edit the source data, not this file.
*/

export const POLYESTER_PRODUCTS = [
  {
    handle: "classic-city",
    name: "Classic City",
    brand: "Godfrey Hirst",
    card: "/img/polyester/classic-city.jpg",
    images: [
      "/img/polyester/classic-city/1.jpg",
      "/img/polyester/classic-city/2.jpg",
      "/img/polyester/classic-city/3.jpg",
      "/img/polyester/classic-city/4.jpg",
      "/img/polyester/classic-city/5.jpg",
      "/img/polyester/classic-city/6.jpg",
      "/img/polyester/classic-city/7.jpg",
      "/img/polyester/classic-city/8.jpg",
      "/img/polyester/classic-city/9.jpg",
      "/img/polyester/classic-city/10.jpg",
      "/img/polyester/classic-city/11.jpg",
      "/img/polyester/classic-city/12.jpg",
      "/img/polyester/classic-city/13.jpg",
      "/img/polyester/classic-city/14.jpg",
      "/img/polyester/classic-city/15.jpg",
    ],
    tagline: "Polyester carpet in 15 colours",
    short: "Classic City Polyester Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 15 colours. Supplied and laid across Canberra.",
    overview: [
      "Classic City is a polyester Cut Pile Twist carpet bringing comfort and practicality at an affordable price. Beautifully soft, this carpet is perfect for bedrooms and features a versatile colour palette.",
      "Godfrey Hirst Best Seller Australian Made Cut Pile Twist 5 Year Standard Limited Residential Warranty* Affordable",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Cut Pile Twist",
      "5 Year Standard Limited Residential Warranty*",
      "Affordable",
    ],
    seoTitle: "Classic City | Capital Tiles",
    seoDesc: "Classic City, Cut Pile Twist, 15 colours. Polyester carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Rice Paper",
      "Amaretti",
      "Pebble Bay",
      "Hazelnut",
      "Bolero",
      "Drizzle",
      "Whisper",
      "Ashville",
      "Deep Grey",
      "Mouse Grey",
      "Cloud Stipple",
      "Grey Pebble",
      "Urban Grey",
      "Night Sky",
      "Lobelia",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Polyester Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Polyester Carpet"],
      ["Yarn", "100% Solution Dyed P.E.T."],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "10.5 (+/- 1.0)mm"],
      ["Pile Height", "8.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "15"],
    ],
    rooms: [],
  },
  {
    handle: "penny-lane",
    name: "Penny Lane",
    brand: "Godfrey Hirst",
    card: "/img/polyester/penny-lane.jpg",
    images: [
      "/img/polyester/penny-lane/1.jpg",
      "/img/polyester/penny-lane/2.jpg",
      "/img/polyester/penny-lane/3.jpg",
      "/img/polyester/penny-lane/4.jpg",
      "/img/polyester/penny-lane/5.jpg",
      "/img/polyester/penny-lane/6.jpg",
      "/img/polyester/penny-lane/7.jpg",
      "/img/polyester/penny-lane/8.jpg",
      "/img/polyester/penny-lane/9.jpg",
      "/img/polyester/penny-lane/10.jpg",
      "/img/polyester/penny-lane/11.jpg",
      "/img/polyester/penny-lane/12.jpg",
      "/img/polyester/penny-lane/13.jpg",
      "/img/polyester/penny-lane/14.jpg",
      "/img/polyester/penny-lane/15.jpg",
      "/img/polyester/penny-lane/16.jpg",
    ],
    tagline: "Polyester carpet in 16 colours",
    short: "Penny Lane polyester carpet by Godfrey Hirst. 3.66m roll width and 16 colours. Supplied and laid across Canberra.",
    overview: [
      "Create a comfortable and stylish home with Penny Lane. This soft and affordable polyester cut pile twist carpet is well suited to low traffic areas. Choose from modern neutral or bold highlight colours that will make a splash.",
      "Australian Made Cut Pile Twist 5 Year Standard Limited Residential Warranty* Affordable",
    ],
    features: ["Australian Made", "Cut Pile Twist", "5 Year Standard Limited Residential Warranty*", "Affordable"],
    seoTitle: "Penny Lane | Capital Tiles",
    seoDesc: "Penny Lane, 16 colours. Polyester carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Snow Blossom",
      "Ecru",
      "Sandalwood",
      "Vintage",
      "Hearthstone",
      "Calm Grey",
      "Dove",
      "Stone Stipple",
      "Suede",
      "Rhino",
      "Greystone",
      "Urban Stipple",
      "Tempest",
      "Android",
      "Onyx",
      "Cobalt",
    ],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Solution Dyed Nylon Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Solution Dyed Nylon Carpet"],
      ["Yarn", "100% Solution Dyed Nylon"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "13.5 (+/- 1.0)mm"],
      ["Pile Height", "11.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "16"],
    ],
    rooms: [],
  },
  {
    handle: "dolomites",
    name: "Dolomites",
    brand: "EC Carpets",
    card: "/img/polyester/dolomites.jpg",
    images: [
      "/img/polyester/dolomites/1.jpg",
      "/img/polyester/dolomites/2.jpg",
      "/img/polyester/dolomites/3.jpg",
      "/img/polyester/dolomites/4.jpg",
      "/img/polyester/dolomites/5.jpg",
      "/img/polyester/dolomites/6.jpg",
      "/img/polyester/dolomites/7.jpg",
      "/img/polyester/dolomites/8.jpg",
    ],
    tagline: "Polyester carpet in 8 colours",
    short: "Dolomites polyester carpet by EC Carpets. 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Dolomites is a stylish loop pile carpet, ideal for those seeking a sophisticated look at a cost-effective price. Its chunky, textured loops offer a comfortable underfoot feel, while the high-quality polyester ensures easy cleaning and maintenance.",
      "Dolomites presents a stylish combination of chic heathered colours and chunky textures, making it the perfect foundation for contemporary interiors.",
      "Dolomites' beautiful colour palette will work great with any interior design.",
    ],
    features: ["Modern aesthetic", "Budget-friendly carpet", "Modern colours"],
    seoTitle: "Dolomites | Capital Tiles",
    seoDesc: "Dolomites, 8 colours. Polyester carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Stelvio 8005", "Rosa 8007", "Gavia 8001", "Cervino 8008", "Brenta 8003", "Bianco 8006", "Corvara 8002", "Madonna 8104"],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "sky-bridge",
    name: "Sky Bridge",
    brand: "EC Carpets",
    card: "/img/polyester/sky-bridge.jpg",
    images: [
      "/img/polyester/sky-bridge/1.jpg",
      "/img/polyester/sky-bridge/2.jpg",
      "/img/polyester/sky-bridge/3.jpg",
      "/img/polyester/sky-bridge/4.jpg",
      "/img/polyester/sky-bridge/5.jpg",
      "/img/polyester/sky-bridge/6.jpg",
      "/img/polyester/sky-bridge/7.jpg",
      "/img/polyester/sky-bridge/8.jpg",
    ],
    tagline: "Polyester carpet in 8 colours",
    short: "Sky Bridge polyester carpet by EC Carpets. 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Sky Bridge is a stylish loop pile carpet, ideal for those seeking a sophisticated look at a cost-effective price. Its chunky, textured loops offer a comfortable underfoot feel, while the high-quality polyester ensures easy cleaning and maintenance.",
      "Sky Bridge presents a stylish combination of chic heathered colours and chunky textures, making it the perfect foundation for contemporary interiors.",
      "Sky Bridges' beautiful colour palette will work great with any interior design.",
    ],
    features: ["Modern aesthetic", "Budget-friendly carpet", "Modern colours"],
    seoTitle: "Sky Bridge | Capital Tiles",
    seoDesc: "Sky Bridge, 8 colours. Polyester carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Bowen 8105", "Tasman 8107", "Harbour 8101", "Hampden 8108", "Webb 8103", "Macleay 8106", "Paringa 8102", "Marlow 8104"],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
]

export function byHandle(handle) {
  return POLYESTER_PRODUCTS.find((p) => p.handle === handle)
}
