/* Polypropylene Carpet product detail data.

   Style, fibre, roll width, thickness, ratings and the descriptions come
   from the live capitaltiles.com.au feed for this collection. Generated —
   edit the source data, not this file.
*/

export const POLYPROPYLENE_PRODUCTS = [
  {
    handle: "enforcer-4m",
    name: "Enforcer 4M",
    brand: "Godfrey Hirst",
    card: "/img/polypropylene/enforcer-4m.jpg",
    images: [
      "/img/polypropylene/enforcer-4m/1.jpg",
      "/img/polypropylene/enforcer-4m/2.jpg",
      "/img/polypropylene/enforcer-4m/3.jpg",
      "/img/polypropylene/enforcer-4m/4.jpg",
      "/img/polypropylene/enforcer-4m/5.jpg",
      "/img/polypropylene/enforcer-4m/6.jpg",
      "/img/polypropylene/enforcer-4m/7.jpg",
      "/img/polypropylene/enforcer-4m/8.jpg",
    ],
    tagline: "Polypropylene carpet in 8 colours",
    short: "Enforcer 4M Polypropylene Carpet by Godfrey Hirst. 4.00m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "An economical flooring solution for the cost conscious buyer, this high low loop pile carpet is a great option for your first home or investment property. Add a real sense of style to your floor with Enforcer.",
      "Australian Made 10 Year Standard Limited Residential Warranty* Affordable Textured Loop Pile",
    ],
    features: ["Australian Made", "10 Year Standard Limited Residential Warranty*", "Affordable", "Textured Loop Pile"],
    seoTitle: "Enforcer 4M | Capital Tiles",
    seoDesc: "Enforcer 4M, 8 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Warmstone", "Windspray", "Smoke", "Lava", "Aggregate", "Basalt", "Mineral", "Monolith"],
    sizes: ["4.00m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Polypropylene Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Polypropylene Carpet"],
      ["Yarn", "100% Polypropylene"],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "4.00m"],
      ["Total Product Thickness", "7 (+/- 1.0)mm"],
      ["Pile Height", "5 (+/- 1.0)mm"],
      ["Pattern Repeat", "2.5cm (w) x 2.5cm (l)"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "ovation",
    name: "Ovation",
    brand: "Godfrey Hirst",
    card: "/img/polypropylene/ovation.jpg",
    images: [
      "/img/polypropylene/ovation/1.jpg",
      "/img/polypropylene/ovation/2.jpg",
      "/img/polypropylene/ovation/3.jpg",
      "/img/polypropylene/ovation/4.jpg",
      "/img/polypropylene/ovation/5.jpg",
      "/img/polypropylene/ovation/6.jpg",
      "/img/polypropylene/ovation/7.jpg",
      "/img/polypropylene/ovation/8.jpg",
    ],
    tagline: "Polypropylene carpet in 8 colours",
    short: "Ovation Polypropylene Carpet by Godfrey Hirst. 4.00m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Ovation is a versatile and affordable Textured Loop Pile carpet that is sure to add style and value to your home.",
      "Australian Made 10 Year Standard Limited Residential Warranty* Affordable Textured Loop Pile",
    ],
    features: ["Australian Made", "10 Year Standard Limited Residential Warranty*", "Affordable", "Textured Loop Pile"],
    seoTitle: "Ovation | Capital Tiles",
    seoDesc: "Ovation, 8 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Doeskin", "Oyster", "Heron", "Pumice", "Woodland", "Folkstone", "Caviar", "Blacksmith"],
    sizes: ["4.00m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Polypropylene Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Polypropylene Carpet"],
      ["Yarn", "100% Polypropylene"],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "4.00m"],
      ["Total Product Thickness", "7.5 (+/- 1.0)mm"],
      ["Pile Height", "5.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "forest-park",
    name: "Forest Park",
    brand: "Godfrey Hirst",
    card: "/img/polypropylene/forest-park.jpg",
    images: [
      "/img/polypropylene/forest-park/1.jpg",
      "/img/polypropylene/forest-park/2.jpg",
      "/img/polypropylene/forest-park/3.jpg",
      "/img/polypropylene/forest-park/4.jpg",
      "/img/polypropylene/forest-park/5.jpg",
      "/img/polypropylene/forest-park/6.jpg",
      "/img/polypropylene/forest-park/7.jpg",
      "/img/polypropylene/forest-park/8.jpg",
    ],
    tagline: "Polypropylene carpet in 8 colours",
    short: "Forest Park Polypropylene Carpet by Godfrey Hirst. 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Versatile and stylish, Forest Park is a textured loop carpet that is sure to add value to your home.",
      "Australian Made 10 Year Standard Limited Residential Warranty* Affordable Textured Loop Pile",
    ],
    features: ["Australian Made", "10 Year Standard Limited Residential Warranty*", "Affordable", "Textured Loop Pile"],
    seoTitle: "Forest Park | Capital Tiles",
    seoDesc: "Forest Park, 8 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Waterfall", "Sandstone", "Clay Stone", "Beacon", "Smoke", "Bedrock", "Cloud", "Forge"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Polypropylene Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Polypropylene Carpet"],
      ["Yarn", "100% Polypropylene"],
      ["Gauge", "15.7/10cm (1/4th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "9.5 (+/- 1.0)mm"],
      ["Pile Height", "7.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "campaspe",
    name: "Campaspe",
    brand: "Godfrey Hirst",
    card: "/img/polypropylene/campaspe.jpg",
    images: [
      "/img/polypropylene/campaspe/1.jpg",
      "/img/polypropylene/campaspe/2.jpg",
      "/img/polypropylene/campaspe/3.jpg",
      "/img/polypropylene/campaspe/4.jpg",
      "/img/polypropylene/campaspe/5.jpg",
      "/img/polypropylene/campaspe/6.jpg",
      "/img/polypropylene/campaspe/7.jpg",
      "/img/polypropylene/campaspe/8.jpg",
    ],
    tagline: "Polypropylene carpet in 8 colours",
    short: "Campaspe Polypropylene Carpet by Godfrey Hirst. 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "An economical flooring solution for the cost conscious buyer, this high low loop pile carpet is a great option for your first home or investment property. Add a real sense of style to your floor with Campaspe.",
      "Godfrey Hirst Best Seller Australian Made 10 Year Standard Limited Residential Warranty* Affordable Textured Loop Pile",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "10 Year Standard Limited Residential Warranty*",
      "Affordable",
      "Textured Loop Pile",
    ],
    seoTitle: "Campaspe | Capital Tiles",
    seoDesc: "Campaspe, 8 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["China Clay", "Mortar", "Glacial", "Siltstone", "Overcast", "Boulder", "Storm Grey", "Cinders"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Polypropylene Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Polypropylene Carpet"],
      ["Yarn", "100% Polypropylene"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "7 (+/- 1.0)mm"],
      ["Pile Height", "5 (+/- 1.0)mm"],
      ["Pattern Repeat", "1.3cm (w) x 2.4cm (l)"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "callisto",
    name: "Callisto",
    brand: "Godfrey Hirst",
    card: "/img/polypropylene/callisto.jpg",
    images: [
      "/img/polypropylene/callisto/1.jpg",
      "/img/polypropylene/callisto/2.jpg",
      "/img/polypropylene/callisto/3.jpg",
      "/img/polypropylene/callisto/4.jpg",
    ],
    tagline: "Polypropylene carpet in 4 colours",
    short: "Callisto Polypropylene Carpet by Godfrey Hirst. Level loop pile, 3.66m roll width and 4 colours. Supplied and laid across Canberra.",
    overview: [
      "An economical flooring solution for the cost conscious buyer, this high low loop pile carpet is a great option for your first home or investment property. Add a real sense of style to your floor with Callisto.",
      "Australian Made Level Loop Pile 10 Year Standard Limited Residential Warranty* Affordable",
    ],
    features: ["Australian Made", "Level Loop Pile", "10 Year Standard Limited Residential Warranty*", "Affordable"],
    seoTitle: "Callisto | Capital Tiles",
    seoDesc: "Callisto, Level Loop Pile, 4 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Light Brown", "Grey", "Charcoal", "Panther"],
    sizes: ["3.66m"],
    finishes: ["Level Loop Pile"],
    thickness: [],
    slip: [],
    material: ["Polypropylene Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Level Loop Pile"],
      ["Fibre", "Polypropylene Carpet"],
      ["Yarn", "100% Polypropylene"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "6 (+/- 1.0)mm"],
      ["Pile Height", "4 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "4"],
    ],
    rooms: [],
  },
  {
    handle: "riviera",
    name: "Riviera",
    brand: "Godfrey Hirst",
    card: "/img/polypropylene/riviera.jpg",
    images: [
      "/img/polypropylene/riviera/1.jpg",
      "/img/polypropylene/riviera/2.jpg",
      "/img/polypropylene/riviera/3.jpg",
      "/img/polypropylene/riviera/4.jpg",
      "/img/polypropylene/riviera/5.jpg",
      "/img/polypropylene/riviera/6.jpg",
      "/img/polypropylene/riviera/7.jpg",
      "/img/polypropylene/riviera/8.jpg",
    ],
    tagline: "Polypropylene carpet in 8 colours",
    short: "Riviera Polypropylene Carpet by Godfrey Hirst. 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Riviera is a versatile and affordable high low loop patterned carpet that is sure to add style and value to your home.",
      "Australian Made 10 Year Standard Limited Residential Warranty* Affordable Textured Loop Pile",
    ],
    features: ["Australian Made", "10 Year Standard Limited Residential Warranty*", "Affordable", "Textured Loop Pile"],
    seoTitle: "Riviera | Capital Tiles",
    seoDesc: "Riviera, 8 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Claystone", "Vapour", "Sea Fog", "Nimbus", "Masonry", "Gravel", "Storm Grey", "Gunmetal"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Polypropylene Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Polypropylene Carpet"],
      ["Yarn", "100% Polypropylene"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "7 (+/- 1.0)mm"],
      ["Pile Height", "5 (+/- 1.0)mm"],
      ["Pattern Repeat", "1.3cm (w) x 1.3cm (l)"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "astra",
    name: "Astra",
    brand: "Godfrey Hirst",
    card: "/img/polypropylene/astra.jpg",
    images: [
      "/img/polypropylene/astra/1.jpg",
      "/img/polypropylene/astra/2.jpg",
      "/img/polypropylene/astra/3.jpg",
      "/img/polypropylene/astra/4.jpg",
      "/img/polypropylene/astra/5.jpg",
    ],
    tagline: "Polypropylene carpet in 6 colours",
    short: "Astra Polypropylene Carpet by Godfrey Hirst. 3.66m roll width and 6 colours. Supplied and laid across Canberra.",
    overview: [
      "Australian Made, versatile and stylish, Astra is an on-trend, chunky loop pile carpet that adds value to your home.",
      "Australian Made 10 Year Standard Limited Residential Warranty* Affordable Textured Loop Pile",
    ],
    features: ["Australian Made", "10 Year Standard Limited Residential Warranty*", "Affordable", "Textured Loop Pile"],
    seoTitle: "Astra | Capital Tiles",
    seoDesc: "Astra, 6 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Palatial", "Plateau", "Mirage", "Beyond", "Affinity", "Ornate"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Polypropylene Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Polypropylene Carpet"],
      ["Yarn", "100% Polypropylene"],
      ["Gauge", "15.7/10cm (1/4th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "12 (+/- 1.0)mm"],
      ["Pile Height", "10 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "6"],
    ],
    rooms: [],
  },
  {
    handle: "encounter",
    name: "Encounter",
    brand: "EC Carpets",
    card: "/img/polypropylene/encounter.jpg",
    images: [
      "/img/polypropylene/encounter/1.jpg",
      "/img/polypropylene/encounter/2.jpg",
      "/img/polypropylene/encounter/3.jpg",
      "/img/polypropylene/encounter/4.jpg",
      "/img/polypropylene/encounter/5.jpg",
      "/img/polypropylene/encounter/6.jpg",
      "/img/polypropylene/encounter/7.jpg",
      "/img/polypropylene/encounter/8.jpg",
    ],
    tagline: "Polypropylene carpet in 8 colours",
    short: "Encounter polypropylene carpet by EC Carpets. 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Encounter is a trendy and budget-friendly, tough, stain-resistant carpet ideal for active families, offering easy maintenance and exceptional affordability for homeowners, landlords, builders, and developers.",
      "Designed for active families, Encounter offers practicality with modern tones and textures that complement contemporary interiors. With tough stain resistance and effortless upkeep, it is chosen as a smart choice for busy households.",
      "Encounter is designed to set a new standard for polypropylene carpets, providing an outstanding combination of practicality and affordability for homeowners, landlords, builders, and developers.",
    ],
    features: ["Stylish and budget-friendly", "Quality made carpet", "Effortless maintenance", "Fade-resistant"],
    seoTitle: "Encounter | Capital Tiles",
    seoDesc: "Encounter, 8 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Sandbar 7574",
      "Shorebird 7579",
      "Spice 7585",
      "Anchorage 7576",
      "Newland 7577",
      "Pontoon 7575",
      "Botany 7578",
      "Storm 7589",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "montrosa",
    name: "Montrosa",
    brand: "EC Carpets",
    card: "/img/polypropylene/montrosa.jpg",
    images: [
      "/img/polypropylene/montrosa/1.jpg",
      "/img/polypropylene/montrosa/2.jpg",
      "/img/polypropylene/montrosa/3.jpg",
      "/img/polypropylene/montrosa/4.jpg",
      "/img/polypropylene/montrosa/5.jpg",
      "/img/polypropylene/montrosa/6.jpg",
      "/img/polypropylene/montrosa/7.jpg",
      "/img/polypropylene/montrosa/8.jpg",
    ],
    tagline: "Polypropylene carpet in 8 colours",
    short: "Montrosa polypropylene carpet by EC Carpets. 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Montrosa is a stain-resistant carpet designed for active families, combining stylish design and affordability for homeowners, landlords, builders, and developers. With polypropylene fibres that resist staining and moisture, Montrosa requires minimal maintenance even in high humidity, while its colourfast design preserves its aesthetic appeal, resisting fading from sunlight and wear.",
      "With a combination of chicly heathered colours, geometric patterns and a rich, organic texture, Montrosa sets an ideal foundation for contemporary interiors.",
      "Montrosa is a tough, stain-resistant carpet designed for active households, offering both practicality and modern appeal.",
    ],
    features: [
      "Modern style",
      "Stylish and stain-resistant",
      "Quality made carpet",
      "Virtually cares for itself",
      "Colourfast and reliably beautiful",
    ],
    seoTitle: "Montrosa | Capital Tiles",
    seoDesc: "Montrosa, 8 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Spire 2504",
      "Faber 2506",
      "Hillford 2508",
      "Vistron 2509",
      "Bottania 2516",
      "Leedon 2511",
      "Avila 2525",
      "Chantilly 2515",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "savanna",
    name: "Savanna",
    brand: "EC Carpets",
    card: "/img/polypropylene/savanna.jpg",
    images: [
      "/img/polypropylene/savanna/1.jpg",
      "/img/polypropylene/savanna/2.jpg",
      "/img/polypropylene/savanna/3.jpg",
      "/img/polypropylene/savanna/4.jpg",
      "/img/polypropylene/savanna/5.jpg",
      "/img/polypropylene/savanna/6.jpg",
      "/img/polypropylene/savanna/7.jpg",
    ],
    tagline: "Polypropylene carpet in 7 colours",
    short: "Savanna polypropylene carpet by EC Carpets. 7 colours. Supplied and laid across Canberra.",
    overview: [
      "Savanna is a medium-duty, tough stain-resistant carpet ideal for active families, raising the bar for premium polypropylene carpets by providing outstanding quality and affordability for homeowners, landlords, builders, and developers.",
      "Savanna combines contemporary design with affordability , featuring a modern, neutral colour palette and a tailored pattern that complements a variety of interior styles. Its chic yet versatile look makes it an ideal choice for homeowners, landlords, builders, and developers.",
      "Savanna's polypropylene fibres are impervious to staining, will not absorb dyes, and will not absorb moisture. This ensures exceptional ease of maintenance, even in high humidity.",
    ],
    features: ["Trendy and budget-friendly", "Virtually cares for itself", "Fade-resistant"],
    seoTitle: "Savanna | Capital Tiles",
    seoDesc: "Savanna, 7 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Rivergum 2932",
      "Candlebark 2931",
      "Coolibah 2933",
      "Cottonwood 2938",
      "Wattle 2937",
      "Applebush 2935",
      "Copperburr 2936",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "summit-point",
    name: "Summit Point",
    brand: "EC Carpets",
    card: "/img/polypropylene/summit-point.jpg",
    images: [
      "/img/polypropylene/summit-point/1.jpg",
      "/img/polypropylene/summit-point/2.jpg",
      "/img/polypropylene/summit-point/3.jpg",
      "/img/polypropylene/summit-point/4.jpg",
      "/img/polypropylene/summit-point/5.jpg",
      "/img/polypropylene/summit-point/6.jpg",
      "/img/polypropylene/summit-point/7.jpg",
    ],
    tagline: "Polypropylene carpet in 7 colours",
    short: "Summit Point polypropylene carpet by EC Carpets. 7 colours. Supplied and laid across Canberra.",
    overview: [
      "Summit Point is a medium-duty, tough stain-resistant carpet ideal for active families, raising the bar for premium polypropylene carpets by providing outstanding quality and affordability for homeowners, landlords, builders, and developers.",
      "Summit point combines contemporary design with affordability, featuring a modern, neutral colour palette and a tailored pattern that complements a variety of interior styles. Its chic yet versatile look makes it an ideal choice for homeowners, landlords, builders, and developers.",
      "Summit Point's polypropylene fibres are impervious to staining, will not absorb dyes, and will not absorb moisture. This ensures exceptional ease of maintenance, even in high humidity.",
    ],
    features: ["Trendy and budget-friendly", "Virtually cares for itself", "Fade-resistant"],
    seoTitle: "Summit Point | Capital Tiles",
    seoDesc: "Summit Point, 7 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Feathertop+2922", "Selwyn+2921", "Howitt+2923", "Townsend+2928", "Riverina+2927", "Hotham+2925", "Franklin+2926"],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "woodchester",
    name: "Woodchester",
    brand: "EC Carpets",
    card: "/img/polypropylene/woodchester.jpg",
    images: [
      "/img/polypropylene/woodchester/1.jpg",
      "/img/polypropylene/woodchester/2.jpg",
      "/img/polypropylene/woodchester/3.jpg",
      "/img/polypropylene/woodchester/4.jpg",
      "/img/polypropylene/woodchester/5.jpg",
      "/img/polypropylene/woodchester/6.jpg",
    ],
    tagline: "Polypropylene carpet in 6 colours",
    short: "Woodchester polypropylene carpet by EC Carpets. 6 colours. Supplied and laid across Canberra.",
    overview: [
      "Woodchester offers stylish and budget-friendly polypropylene carpeting, combining contemporary design with affordability for homeowners, landlords, builders, and developers. With chic heathered colours, geometric patterns, and an organic texture, Woodchester enhances modern living spaces. Its polypropylene fibres resist staining, moisture, and colour fading, ensuring effortless maintenance and lasting visual appeal, even in high humidity.",
      "Woodchester combines contemporary design with affordability, featuring a modern, neutral colour palette and a tailored pattern that complements a variety of interior styles. Its chic yet versatile look makes it an ideal choice for homeowners, landlords, builders, and developers.",
      "Woodchester's polypropylene fibres are impervious to staining, will not absorb dyes, and will not absorb moisture. This ensures exceptional ease of maintenance, even in high humidity.",
    ],
    features: ["Trendy and budget-friendly", "Virtually cares for itself", "Fade-resistant"],
    seoTitle: "Woodchester | Capital Tiles",
    seoDesc: "Woodchester, 6 colours. Polypropylene carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Callington 3504", "Meechi 3508", "Tinpot 3509", "Rodwell 3516", "Dalveen 3511", "Macallan 3525"],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
]

export function byHandle(handle) {
  return POLYPROPYLENE_PRODUCTS.find((p) => p.handle === handle)
}
