/* Pool Tiles product detail data.

   Specs, colours, sizes and the copy are the same records already built
   for the ranges shared with our other tile collections, so no product is
   described twice and no image is stored twice. Generated — edit the
   source data, not this file.
*/

export const POOL_PRODUCTS = [
  {
    handle: "bari-collection",
    name: "Bari Collection",
    brand: "Capital Tiles",
    card: "/img/pool/bari-collection.jpg",
    images: [
      "/img/bathroom/bari-collection/1.jpg",
      "/img/bathroom/bari-collection/2.jpg",
      "/img/bathroom/bari-collection/3.jpg",
      "/img/bathroom/bari-collection/4.jpg",
      "/img/bathroom/bari-collection/5.jpg",
      "/img/bathroom/bari-collection/6.jpg",
      "/img/bathroom/bari-collection/7.jpg",
      "/img/bathroom/bari-collection/8.jpg",
      "/img/bathroom/bari-collection/9.jpg",
      "/img/bathroom/bari-collection/10.jpg",
      "/img/bathroom/bari-collection/11.jpg",
      "/img/bathroom/bari-collection/12.jpg",
      "/img/bathroom/bari-collection/13.jpg",
      "/img/bathroom/bari-collection/14.jpg",
      "/img/bathroom/bari-collection/15.jpg",
      "/img/bathroom/bari-collection/16.jpg",
      "/img/bathroom/bari-collection/17.jpg",
    ],
    tagline: "Versa touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge in 3 colours",
    short: "Bari Collection. 3 colours, Versa Touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge finishes and 9 formats from 300x600 to 600x400. On display in our Mitchell showroom.",
    overview: [
      "Bari Collection is part of the bathroom range we hold at Capital Tiles. It runs in bianco, taupe and beige, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 300x600, 600x600, 1200x600, 75x300, 307x307 mm sheets, Crazy Pave, French Pattern, 600x400 mm DF and 600x400. It is offered in Versa Touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge finishes. We list it under Bathroom Tiles, Kitchen Tiles, Outdoor Tiles, Patio Tiles, Pool Tiles, Floor Tiles and Pavers.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: Bianco, Taupe and Beige",
      "Finishes: Versa Touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge",
      "Sizes: 300x600, 600x600, 1200x600, 75x300",
      "Listed under Bathroom Tiles, Kitchen Tiles and Outdoor Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Bari Collection Bathroom Tiles | Capital Tiles",
    seoDesc: "Bari Collection in Versa Touch, P5 20mm, Cobbles VT and P5 20mm Pencil Edge, 300x600, 600x600, 1200x600. Supplied and installed across Canberra by Capital.",
    colours: ["Bianco", "Taupe", "Beige"],
    sizes: ["300x600", "600x600", "1200x600", "75x300", "307x307 mm sheets", "Crazy Pave", "French Pattern", "600x400 mm DF", "600x400"],
    finishes: ["Versa Touch", "P5 20mm", "Cobbles VT", "P5 20mm Pencil Edge"],
    thickness: [],
    slip: [],
    material: [],
    specCols: ["Size (mm)", "Finish", "Pcs/CTN", "m²/CTN", "KG/CTN", "CTNS/PLT", "KG/PLT", "m²/PLT"],
    specRows: [
      ["300 × 600", "Versa Touch P4", "8", "1.44", "31", "40", "1240", "57.60"],
      ["600 × 600", "Versa Touch P4", "4", "1.44", "31", "40", "1240", "57.60"],
      ["75 × 300", "Versa Touch P4", "36", "0.81", "0.47", "72", "1224", "58.32"],
      ["600 × 600 × 20 mm", "Versa Touch P4", "2", "0.72", "34", "40", "1360", "28.80"],
      ["600 × 1200", "Versa Touch P4", "2", "1.44", "34", "56", "1904", "80.64"],
      ["Crazy Pave", "Versa Touch P4", "—", "1.08", "18", "22", "396", "23.76"],
      ["French Pattern", "Versa Touch P4", "6", "0.72", "16", "52", "832", "37.44"],
      ["Cobbles (Straight & Brickbond)", "Versa Touch / Cobbles VT", "11", "1.03", "19", "45", "855", "46.35"],
      ["600 × 400 (20 mm Pencil Edge)", "P5 20 mm", "—", "—", "—", "—", "—", "—"],
      ["600 × 400 (40 mm Drop Face)", "P5 20 mm", "—", "—", "—", "—", "—", "—"],
    ],
    rooms: [
      { label: "Bathroom Tiles", href: "/tiles/bathroom" },
      { label: "Kitchen Tiles", href: "/tiles/kitchen" },
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Pool Tiles", href: "/tiles/pool" },
      { label: "Floor Tiles", href: "/tiles/floor-tiles" },
      { label: "Pavers", href: "/tiles/pavers" },
    ],
  },
  {
    handle: "altto-glass-pool-mosaics",
    name: "Altto Glass Pool Mosaics",
    brand: "Capital Tiles",
    card: "/img/pool/altto-glass-pool-mosaics.jpg",
    images: [
      "/img/pool/altto-glass-pool-mosaics/1.jpg",
      "/img/pool/altto-glass-pool-mosaics/2.jpg",
      "/img/pool/altto-glass-pool-mosaics/3.jpg",
      "/img/pool/altto-glass-pool-mosaics/4.jpg",
      "/img/pool/altto-glass-pool-mosaics/5.jpg",
      "/img/pool/altto-glass-pool-mosaics/6.jpg",
      "/img/pool/altto-glass-pool-mosaics/7.jpg",
      "/img/pool/altto-glass-pool-mosaics/8.jpg",
      "/img/pool/altto-glass-pool-mosaics/9.jpg",
      "/img/pool/altto-glass-pool-mosaics/10.jpg",
      "/img/pool/altto-glass-pool-mosaics/11.jpg",
      "/img/pool/altto-glass-pool-mosaics/12.jpg",
      "/img/pool/altto-glass-pool-mosaics/13.jpg",
      "/img/pool/altto-glass-pool-mosaics/14.jpg",
      "/img/pool/altto-glass-pool-mosaics/15.jpg",
      "/img/pool/altto-glass-pool-mosaics/16.jpg",
      "/img/pool/altto-glass-pool-mosaics/17.jpg",
      "/img/pool/altto-glass-pool-mosaics/18.jpg",
      "/img/pool/altto-glass-pool-mosaics/19.jpg",
      "/img/pool/altto-glass-pool-mosaics/20.jpg",
      "/img/pool/altto-glass-pool-mosaics/21.jpg",
      "/img/pool/altto-glass-pool-mosaics/22.jpg",
      "/img/pool/altto-glass-pool-mosaics/23.jpg",
      "/img/pool/altto-glass-pool-mosaics/24.jpg",
      "/img/pool/altto-glass-pool-mosaics/25.jpg",
    ],
    tagline: "Available in white, blanco, azul, claro, Azul Celeste, turquoise.",
    short: "Altto Glass Pool Mosaics. 14 colours. On display in our Mitchell showroom.",
    overview: [
      "Altto Glass Pool Mosaics is part of the pool tiles range we hold at Capital Tiles. It runs in white, blanco, azul, claro, Azul Celeste, turquoise, verde, Mix Arctic, Mix Light, Mix Saphire, Mix Medium, Mix Dark, mallorca and cabrera, so there is a tone here for a light room and for a darker, more grounded one.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: White, Blanco, Azul, Claro, Azul Celeste, Turquoise, Verde, Mix Arctic, Mix Light.",
      "Listed under Pool Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Altto Glass Pool Mosaics Pool Tiles | Capital Tiles",
    seoDesc: "Altto Glass Pool Mosaics. Supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "White",
      "Blanco",
      "Azul",
      "Claro",
      "Azul Celeste",
      "Turquoise",
      "Verde",
      "Mix Arctic",
      "Mix Light",
      "Mix Saphire",
      "Mix Medium",
      "Mix Dark",
      "Mallorca",
      "Cabrera",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Pool Tiles", href: "/tiles/pool" },
    ],
  },
  {
    handle: "chiswick-paver-collection",
    name: "Chiswick Outdoor Collection",
    brand: "Capital Tiles",
    card: "/img/pool/chiswick-paver-collection.jpg",
    images: [
      "/img/pool/chiswick-paver-collection/1.jpg",
      "/img/pool/chiswick-paver-collection/2.jpg",
      "/img/pool/chiswick-paver-collection/3.jpg",
      "/img/pool/chiswick-paver-collection/4.jpg",
      "/img/pool/chiswick-paver-collection/5.jpg",
    ],
    tagline: "Square edge coper and External Paver in 4 colours",
    short: "Chiswick Outdoor Collection. 4 colours, Square Edge Coper and External Paver finishes and 2 formats from 400x600x20 to 600x600x20. On display in our Mitchell showroom.",
    overview: [
      "Chiswick Outdoor Collection is part of the pool tiles range we hold at Capital Tiles. It runs in white, cream, gray and charcoal, so there is a tone here for a light room and for a darker, more grounded one.",
      "Formats published for this range are 400x600x20 and 600x600x20. It is offered in Square Edge Coper and External Paver finishes. We list it under Outdoor Tiles, Patio Tiles, Pool Tiles and Pavers.",
      "Come and see a full tile rather than a sample chip — the range sits in our Mitchell showroom where you can carry one to the doorway and check the colour in daylight. We supply trade and homeowners, and our own installers can take care of removal, substrate preparation, laying, grouting and sealing. The measure and quote is free.",
    ],
    features: [
      "Colours: White, Cream, Gray and Charcoal",
      "Finishes: Square Edge Coper and External Paver",
      "Sizes: 400x600x20, 600x600x20",
      "Listed under Outdoor Tiles, Patio Tiles and Pool Tiles",
      "Full tiles on display in the Mitchell showroom",
    ],
    seoTitle: "Chiswick Outdoor Collection Pool Tiles | Capital Tiles",
    seoDesc: "Chiswick Outdoor Collection in Square Edge Coper and External Paver, 400x600x20, 600x600x20. Supplied and installed across Canberra by Capital Tiles.",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    sizes: ["400x600x20", "600x600x20"],
    finishes: ["Square Edge Coper", "External Paver"],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [
      { label: "Outdoor Tiles", href: "/tiles/outdoor" },
      { label: "Patio Tiles", href: "/tiles/patio" },
      { label: "Pool Tiles", href: "/tiles/pool" },
      { label: "Pavers", href: "/tiles/pavers" },
    ],
  },
]

export function byHandle(handle) {
  return POOL_PRODUCTS.find((p) => p.handle === handle)
}
