/* Tiles — the full range, taken from the live capitaltiles.com.au tiles
   collection: names, blurbs, brands and the colour / finish / size options each
   product actually ships with. */

export const TILES = [
  {
    name: "Calacatta",
    handle: "calacatta-1",
    blurb: "Thickness: 9.0mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles 360 View",
    brand: "HF Tiles",
    colours: ["White", "Gold"],
    finishes: ["Soft Matt", "Polish"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Carrara Mosaic",
    handle: "carrara-mosaic",
    blurb: "Thickness: 10mm Edge: Rectified Slip Rating: None ETA: - Specification: 0.9702 sqm/Box, 54 Box/ Pallet, 11 PC/ Box Areas: Mosaic",
    brand: "HF Tiles",
    colours: ["Herringbone", "kitKat", "Convex", "Concave"],
    finishes: ["Soft Matt"],
    sizes: [],
  },
  {
    name: "Carrara",
    handle: "carrara",
    blurb: "Thickness: 9 mm Edge: Rectified Slip Rating: None ETA: - Specification: Same design as Snowwhite, for polish, please choose Snowwhite Areas: Floor Til",
    brand: "HF Tiles",
    colours: ["White"],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Nova Grey 200x1200",
    handle: "nova-grey-200x1200",
    blurb: "Thickness: 10 mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles, Timber Look Tiles",
    brand: "HF Tiles",
    colours: ["Grey"],
    finishes: ["External"],
    sizes: ["200x1200"],
  },
  {
    name: "21206 Off White",
    handle: "21206-off-white",
    blurb: "Thickness: 10 mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles, Timber Look Tiles 360 View",
    brand: "HF Tiles",
    colours: ["Off White"],
    finishes: ["Matt"],
    sizes: ["200x1200"],
  },
  {
    name: "21205 200x1200 Matt",
    handle: "21205-200x1200-matt",
    blurb: "Thickness: 10 mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles, Timber Look Tiles 360 View",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt"],
    sizes: ["200x1200"],
  },
  {
    name: "21203 Natural",
    handle: "21203-natural",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles, Timber Look Tiles 360 View",
    brand: "HF Tiles",
    colours: ["Natural"],
    finishes: ["Matt"],
    sizes: ["200x1200"],
  },
  {
    name: "Matera",
    handle: "matera",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles",
    brand: "HF Tiles",
    colours: ["Natural", "Grey", "White", "Beige"],
    finishes: ["StoneTouch Tec"],
    sizes: ["600x600"],
  },
  {
    name: "Iceland",
    handle: "iceland",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: P5 ETA: - Specification: Areas: Floor Tiles, Wall Tiles, Bathroom Floor 360 View",
    brand: "HF Tiles",
    colours: ["Gold"],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Tundra",
    handle: "tundra",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: P5 ETA: - Specification: Areas: Floor Tiles, Wall Tiles, Bathroom Floor 360 View",
    brand: "HF Tiles",
    colours: ["White"],
    finishes: ["Matt"],
    sizes: ["600x1200"],
  },
  {
    name: "Taj Mahal",
    handle: "taj-mahal",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: ETA: - Specification: Areas: Floor Tiles, Wall tiles, Outdoor Tiles, Bathroom Floor 360 View",
    brand: "HF Tiles",
    colours: ["Natural", "Ivory", "Silver"],
    finishes: ["Matt", "StoneTouch Tec", "Soft Matt", "Flute"],
    sizes: ["600x600", "600x1200"],
  },
  {
    name: "Flat-Alps",
    handle: "flat-alps",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: ETA: - Specification: Areas: Floor Tiles, Wall tiles, Outdoor Tiles, Bathroom Floor 360 View",
    brand: "HF Tiles",
    colours: ["Silver", "Grey", "White", "Beige"],
    finishes: ["In&Out Solution", "StoneTouch Tec", "Paver", "Flute"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Gelato",
    handle: "gelato",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: ETA: - Specification: Areas: Floor Tiles, Wall tiles, Outdoor Tiles, Bathroom Floor",
    brand: "HF Tiles",
    colours: ["Light", "Medium", "Dark"],
    finishes: ["In&Out Solution"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Riverstone",
    handle: "riverstone",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: P5 ETA: - Specification: Areas: Floor Tiles, Outdoor Tiles 360 View",
    brand: "HF Tiles",
    colours: ["Silver"],
    finishes: ["External"],
    sizes: ["600x600"],
  },
  {
    name: "Boutique",
    handle: "boutique",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles 360 View",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Fg Grey",
    handle: "fg-grey",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles, Bathroom Floor 360 View",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt", "Polish"],
    sizes: ["600x600"],
  },
  {
    name: "Vista",
    handle: "vista",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: ETA: - Specification: Areas: Floor Tiles, Wall tiles, Bathroom Tiles",
    brand: "HF Tiles",
    colours: ["Ivory", "Silver"],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Terrazzo Grey",
    handle: "terrazzo-grey",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: ETA: - Specification: Areas: Floor Tiles, Wall tiles, Bathroom Tiles",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Loft Dark",
    handle: "loft-dark",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: ETA: - Specification: Areas: Floor Tiles, Wall tiles, Bathroom Tiles 360 View",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["600x600"],
  },
  {
    name: "Limestone Dark",
    handle: "limestone-dark",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: P3 ETA: - Specification: Areas: Floor Tiles, Wall tiles, Bathroom Tiles 360 View",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Matt"],
    sizes: ["600x600"],
  },
  {
    name: "Statuario",
    handle: "statuario",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles 360 View",
    brand: "HF Tiles",
    colours: ["Gold"],
    finishes: ["Polish", "Soft Matt"],
    sizes: ["600x600", "600x1200"],
  },
  {
    name: "Flurries",
    handle: "flurries",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles 360 View",
    brand: "HF Tiles",
    colours: ["White"],
    finishes: ["Matt", "Polish", "Soft Matt"],
    sizes: ["600x600", "300x600", "600x1200"],
  },
  {
    name: "SnowWhite",
    handle: "snowwhite",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles 360 View",
    brand: "HF Tiles",
    colours: ["Grey"],
    finishes: ["Soft Matt", "Polish"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Vienna",
    handle: "vienna-1",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles, Bathroom Floor 360 View",
    brand: "HF Tiles",
    colours: ["Grey", "Ivory"],
    finishes: ["Matt", "Polish", "Soft Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Pandora",
    handle: "pandora-1",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles",
    brand: "HF Tiles",
    colours: [],
    finishes: ["Soft Matt"],
    sizes: ["600x1200"],
  },
  {
    name: "Apex",
    handle: "apex",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles, Bathroom Floor 360 View",
    brand: "HF Tiles",
    colours: ["Silver"],
    finishes: ["Matt", "Polish"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Diamond",
    handle: "diamond",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles, Bathroom Floor 360 View",
    brand: "HF Tiles",
    colours: ["Silver"],
    finishes: ["Lappato"],
    sizes: ["600x1200"],
  },
  {
    name: "Monash",
    handle: "monash",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles, Bathroom Floor",
    brand: "HF Tiles",
    colours: ["Black"],
    finishes: ["Matt"],
    sizes: ["600x600", "600x1200"],
  },
  {
    name: "Ionic",
    handle: "origin-copy",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles 360 View",
    brand: "HF Tiles",
    colours: ["Grey", "Silver"],
    finishes: ["Matt", "Polish", "Soft Matt"],
    sizes: ["600x600", "300x600", "600x1200"],
  },
  {
    name: "Elegance",
    handle: "elegance",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: None ETA: - Specification: Areas: Floor Tiles, Wall tiles 360 View",
    brand: "HF Tiles",
    colours: ["Grey", "Silver"],
    finishes: ["In&Out Solution", "StoneTouch Tec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Tasmania",
    handle: "tasmania",
    blurb: "Thickness: 9mm Edge: Rectified Slip Rating: P3 ETA: - Specification: Areas: Floor Tiles, Wall tiles",
    brand: "HF Tiles",
    colours: ["Grey", "Ivory"],
    finishes: ["Matt", "StoneTouch Tec"],
    sizes: ["600x600", "600x1200"],
  },
  {
    name: "The Louvre",
    handle: "the-louvre",
    blurb: "The Louvre tile from Muses Australia is a refined glazed porcelain tile in a 600 × 1200 mm size with a 4D Glue & Grit Full Body finish. It delivers a ",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Pilates Green",
    handle: "pilates-green",
    blurb: "Pilates Green is a premium large-format porcelain tile from Muses Australia’s Elegance Collection. This tile brings a striking yet refined green tone ",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Pandora Elegance",
    handle: "pandora",
    blurb: "The Pandora tile from Muses Australia is a stylish glazed porcelain tile in a 600 × 1200 mm size with a 4D Glue & Grit Full Body finish. It delivers a",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Navona Cross",
    handle: "navona-cross",
    blurb: "The Navona Cross Beige tile from Muses Australia is a stylish glazed porcelain tile in a 600 × 1200 mm size, finished with a refined texture and warm ",
    brand: "Muses",
    colours: ["Beige", "Ivory"],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Karzai Green",
    handle: "karzai-green",
    blurb: "The Karzai Green tile offers a striking combination of elegance and durability, featuring a 600 × 1200 mm size and a high-quality 4D Glue & Grit Full ",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Ferragamo",
    handle: "ferragamo",
    blurb: "The Ferragamo tile from Muses Australia is a premium glazed porcelain tile crafted to bring a refined, modern look to interior and exterior spaces. It",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Balcan",
    handle: "balcan",
    blurb: "Balcan is a high-quality ceramic wall and floor tile offered by Muses Ceramics Australia, designed to elevate interiors with a refined aesthetic and r",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Aegean Sea",
    handle: "aegean-sea",
    blurb: "The Aegean Sea tile from Muses Australia is a high‑quality 600 × 1200 mm glazed porcelain tile featuring a refined finish and subtle texture. It’s sui",
    brand: "Muses",
    colours: [],
    finishes: ["4D Glue & Grit"],
    sizes: ["600x1200"],
  },
  {
    name: "Sassy",
    handle: "sassy",
    blurb: "Faces : 8(750×1500), 8(600×1200), 12(600x600mm), 24(300×600) Finishes Matt Sizes 300×600 , 600×600 , 600×1200",
    brand: "Muses",
    colours: ["Ash", "Beige", "Slate"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Blended",
    handle: "blended",
    blurb: "Faces : 8(750×1500), 8(600×1200), 12(600x600mm), 24(300×600) Finishes Matt Sizes 300×600 , 600×600 , 600×1200",
    brand: "Muses",
    colours: ["White", "Ash", "Taupe"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Nova Stone",
    handle: "nova-stone",
    blurb: "Faces : 8(750×1500), 8(600×1200), 12(600x600mm), 24(300×600) Finishes Matt Sizes 300×600 , 600×600 , 600×1200",
    brand: "Muses",
    colours: ["Ivory", "Fog", "White"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Port Travertino",
    handle: "port-travertino",
    blurb: "Faces : (600x1200mm), (600x600mm),(300x600mm) Finishes 3D Sizes 300×600 , 600×600 , 600×1200",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Limestone",
    handle: "limestone",
    blurb: "Faces : (600x1200mm), (600x600mm),(300x600mm) Finishes Matt Sizes 300×600 , 600×600 , 600×1200",
    brand: "Muses",
    colours: ["Beige", "Beige Fluted", "Ivory Fluted", "Ivory"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Find",
    handle: "find",
    blurb: "Faces : 8(600x1200mm), 12(600x600mm)",
    brand: "Muses",
    colours: ["Cool Grey", "Light Grey"],
    finishes: ["Felltec"],
    sizes: ["600x1200"],
  },
  {
    name: "Starry",
    handle: "starry",
    blurb: "Starry is a premium porcelain tile offered by Muses Australia that combines understated elegance with everyday performance. Designed to bring a warm a",
    brand: "Muses",
    colours: ["Beige", "Light Grey", "Black"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Trav Vein Cut",
    handle: "trav-vein-cut",
    blurb: "Faces : 8(750×1500), 8(600×1200), 12(600x600mm), 24(300×600) Finishes 3D Deep Ink Sizes 300×600 , 600×600 , 600×1200",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Trav Cross Cut",
    handle: "trav-cross-cut",
    blurb: "Faces : 8(750×1500), 8(600×1200), 12(600x600mm), 24(300×600) Finishes 3D Deep Ink Sizes 300×600 , 600×600 , 600×1200",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600 x 600", "600x1200"],
  },
  {
    name: "Quartzite Paver",
    handle: "quartzite-paver",
    blurb: "Faces : 600×600 (20mm Thick) Color Charcoal, Grigio Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Charcoal", "Grigio"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Petra Mix Paver",
    handle: "petra-mix-paver",
    blurb: "Sizes : 600×600 (20mm Thick) Color Beige, Ivory, Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Imperial Stone Paver",
    handle: "imperial-stone-paver",
    blurb: "Sizes : 600×600 (20mm Thick) Color Ivory, Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Light Grey", "Ivory"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Crest Paver",
    handle: "crest-paver",
    blurb: "Faces : 8(600x1200mm), 12(600x600mm) Color Dark Grey, Ivory, Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Light Grey", "Ivory", "Dark Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Blaze Paver",
    handle: "blaze-paver",
    blurb: "Color Light Grey Finishes Paver Sizes 600×600 (20mm Thick)",
    brand: "Muses",
    colours: ["Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
  {
    name: "Vutton Series",
    handle: "vutton-series",
    blurb: "The VUTTON collection combines refined elegance with contemporary style, making it the perfect choice for sophisticated interiors. Inspired by natural",
    brand: "Muses",
    colours: ["Ash", "Ice", "Night", "Pearl", "Sage"],
    finishes: [],
    sizes: ["Mosaic Sheets (275.2×275.2mm)"],
  },
  {
    name: "Mistery Dark Grey",
    handle: "mistery-dark-grey",
    blurb: "Faces : (600x1200mm), (600x600mm), (300x600mm)",
    brand: "Muses",
    colours: ["Light Grey", "Dark Grey"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Find Honed",
    handle: "find-honed",
    blurb: "Faces : 8(600x1200mm), 12(600x600mm)",
    brand: "Muses",
    colours: ["Cool Grey", "Light Grey"],
    finishes: ["Honed"],
    sizes: ["600x1200"],
  },
  {
    name: "Calacatta Pro",
    handle: "calacatta-pro",
    blurb: "The Calacatta Pro Marble collection delivers the timeless elegance of classic Calacatta with a modern twist. Featuring a bright white base enriched by",
    brand: "Muses",
    colours: [],
    finishes: ["Felltec", "Polished"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Milano",
    handle: "milano",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 1200*1200 10mm Matt P2 600*600 ",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200", "1200x1200", "400x600", "10mm", "20mm"],
  },
  {
    name: "Stone Cladding",
    handle: "stone-cladding",
    blurb: "Colour: Natural, Bali, Luna Packaging: Sold Per Square Metre, Crates Hold 15 m² Available Corner Pieces Per Lineal Metre Recommended Applications (Nat",
    brand: "CIE Ceramic",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Stone Cobblestone",
    handle: "stone-cobblestone",
    blurb: "Colour: Bali, Luna, Imperial Packaging: Sold Per Square Metre, Sheet Size Meshed 300*300 Full Crates Hold 20.25m² Recommended Applications (Natural St",
    brand: "CIE Ceramic",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Kit Kat Mosaic",
    handle: "kit-kat-mosaic",
    blurb: "Colour: Gloss White Concave 20mm, Gloss Grey Concave 20mm, Plain Matt White 20mm, Plain Matt White 12mm Size: Sheet Size 12mm 293*298 Sheet Size 20mm ",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "Gloss"],
    sizes: [],
  },
  {
    name: "Pool Glass mosaic",
    handle: "pool-glass-mosaic",
    blurb: "Specification Details Sizes 327x327mm Material Mosaics are decorative tiles composed of small pieces of ceramic, glass, stone, metal, or other materia",
    brand: "CIE Ceramic",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Patrone",
    handle: "patrone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P4 300*600 10mm Matt P4 600*600 10mm Matt P4 600*600 20mm External P5 400*600 20mm External P5 Not",
    brand: "CIE Ceramic",
    colours: ["Beige", "Silver", "Ebony"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "400x600"],
  },
  {
    name: "Cairo",
    handle: "cairo",
    blurb: "Size Thickness Finish Slip Rating 600*600 20mm External P5 400*600 20mm External Drop Edge Copping P5 Recommended Applications (Glazed Porcelain) : Ex",
    brand: "CIE Ceramic",
    colours: ["Light", "Dark"],
    finishes: ["External"],
    sizes: ["400x600", "600x600"],
  },
  {
    name: "Shine",
    handle: "shine",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Bianco", "Moon"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Millenia",
    handle: "millenia",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm Matt P2 600*1200 1",
    brand: "CIE Ceramic",
    colours: ["White", "Pearl Grey"],
    finishes: ["Matt", "Polished"],
    sizes: ["300x300", "300x600", "600x600", "600x1200", "1200x1200"],
  },
  {
    name: "Dusk",
    handle: "dusk",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Greige", "White"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Travertine",
    handle: "travertine-1",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Silver", "Bravo"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Terrazzo",
    handle: "terrazzo",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 Recommended Applications (Glazed Porcelain) : Interio",
    brand: "CIE Ceramic",
    colours: ["Bianco"],
    finishes: ["Matt"],
    sizes: ["300x300", "300x600", "600x600"],
  },
  {
    name: "Polar Ice",
    handle: "polar-ice",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 Recommended Applications (Glaze",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "SandStone",
    handle: "sandstone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Bianco"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Simply Stone",
    handle: "simply-stone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Divine Stone",
    handle: "divine-stone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Republic",
    handle: "republic",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 600*60",
    brand: "CIE Ceramic",
    colours: ["White", "Silver"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200", "400x600"],
  },
  {
    name: "Orobico",
    handle: "orobico",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 Recommended Applications (Glaze",
    brand: "CIE Ceramic",
    colours: ["Bianco", "Grey"],
    finishes: ["Matt"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Ciement",
    handle: "ciement",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["White"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Cocoon Collection",
    handle: "cocoon-collection",
    blurb: "Cocoon Honed Porcelain Tile — Weston Creek & Molonglo Cocoon is an Italian-made porcelain collection that wraps spaces in calm. With 16 unique faces, ",
    brand: "Capital Tiles",
    colours: ["Hazelnut", "Beige"],
    finishes: ["Honed"],
    sizes: ["600x1200mm"],
  },
  {
    name: "UNICO GREY",
    handle: "unico-grey",
    blurb: "Unico Grey Matt 3D Luxury Marble-Look Tile — Woden Valley Italian-made and effortlessly refined, Unico Grey reimagines classic marble with twenty uniq",
    brand: "Capital Tiles",
    colours: ["Unico Grey"],
    finishes: ["Matt 3D"],
    sizes: ["600x1200mm"],
  },
  {
    name: "Bari Collection",
    handle: "bari-collection",
    blurb: "The Bari Collection Travertine Tile — Belconnen Timeless elegance meets natural artistry with The Bari Collection . A luxurious travertine-look porcel",
    brand: "Capital Tiles",
    colours: ["Bianco", "Taupe", "Beige"],
    finishes: ["Versa Touch", "P5 20mm", "Cobbles VT", "P5 20mm Pencil Edge"],
    sizes: ["300x600", "600x600", "1200x600", "75x300", "307x307 mm sheets", "Crazy Pave", "French Pattern", "600x400 mm DF", "600x400"],
  },
  {
    name: "Aroma Collection",
    handle: "aroma-collection",
    blurb: "Aroma Collection – Italian Subway Tiles with Glossy Texture The Aroma Collection brings Italian craftsmanship to a modern classic. These elongated 60x",
    brand: "Capital Tiles",
    colours: ["Verde", "Verde Scuro", "Rosa Scuro", "Blu", "Turchese", "Sabbia", "Bianco"],
    finishes: ["Gloss"],
    sizes: ["60 x 240"],
  },
  {
    name: "Altea Collection",
    handle: "altea-collection",
    blurb: "Altea Collection – Spanish Subway Tiles with Glossy Character The Altea Collection brings a fresh twist to classic subway tiles, with a wavy structure",
    brand: "Capital Tiles",
    colours: ["Dusty Pink", "Matcha", "Ash Blue", "Black", "Smoke", "Pine Green", "White"],
    finishes: ["Gloss", "Twist"],
    sizes: ["75 x 150", "100 x 100"],
  },
  {
    name: "Aqua",
    handle: "aqua-collection",
    blurb: "Aqua Polished Wall Tiles 60x240mm – Modern Coastal Finish Bring a refreshing, contemporary look to your interiors with the Aqua 60x240mm polished tile",
    brand: "Muses",
    colours: ["Crystal", "Opal", "Rune", "Jade", "Berry", "Core"],
    finishes: ["Polished"],
    sizes: [],
  },
  {
    name: "Alhambra Collection",
    handle: "alhambra",
    blurb: "Alhambra Collection – Elegant Embossed Tiles for Walls & Floors Bring European sophistication to your home with the Alhambra Collection . These decor ",
    brand: "Capital Tiles",
    colours: ["Rojo", "Negro", "Gris", "Azul", "Arena", "Barcelona"],
    finishes: ["Matt", "Satin", "Embossed"],
    sizes: [],
  },
  {
    name: "Picasso",
    handle: "picasso",
    blurb: "Picasso Collection – Artful Texture Meets Modern Scale Bring bold creativity into your interiors with the Picasso Collection , a porcelain tile range ",
    brand: "Muses",
    colours: [],
    finishes: ["Deep Ink (IK) & 3D"],
    sizes: ["300x600", "600×600", "600×1200", "750×1500"],
  },
  {
    name: "Kolor Series",
    handle: "kolor",
    blurb: "Kolor Collection – Contemporary Concrete-Inspired Minimalism Refined, architectural, and effortlessly modern, the Kolor Collection brings the understa",
    brand: "Muses",
    colours: ["White", "Ivory", "Light Grey", "Medium Grey"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Calacatta Gold",
    handle: "calacatta-gold",
    blurb: "Calacatta Gold – Timeless Elegance with a Golden Touch Inspired by the luxurious veining of Italian Calacatta marble, the Calacatta Gold Collection br",
    brand: "Muses",
    colours: ["Gold"],
    finishes: ["Polished", "Satin"],
    sizes: ["600x1200mm", "750x1500mm"],
  },
  {
    name: "Onyx Series",
    handle: "onyx",
    blurb: "Onyx Collection – Polished Perfection in Stone-Inspired Style Elevate your interiors with the Onyx Collection — a porcelain tile range inspired by the",
    brand: "Muses",
    colours: ["Ivory", "Beige", "Light Grey", "Brown"],
    finishes: ["Polished", "Satin"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Roccia Series",
    handle: "roccia",
    blurb: "Roccia Collection – Earthy Porcelain Tiles with Modern Durability Bring the rugged charm of natural stone into your home with the Roccia Collection . ",
    brand: "Muses",
    colours: ["Greige", "Charcoal"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Silver Root",
    handle: "silver-root",
    blurb: "Silver Root Collection – Polished Sophistication with Stone Soul Inspired by the intricate veining of high-end marble and the organic movement of natu",
    brand: "Muses",
    colours: ["Ivory", "Light Grey", "Brown"],
    finishes: ["Satin"],
    sizes: [],
  },
  {
    name: "Stazzema Series",
    handle: "stazzema",
    blurb: "Stazzema Collection – Textured Elegance with Natural Depth Inspired by the fine textures of honed limestone, the Stazzema Collection offers a refined ",
    brand: "Muses",
    colours: ["Ivory", "Smokey Grey"],
    finishes: ["Felltec"],
    sizes: ["300x600mm", "600x600mm", "600x1200mm"],
  },
  {
    name: "Zouks",
    handle: "zouks",
    blurb: "Zouks Collection – Bold. Textured. Modern. Make a strong design statement with the Zouks Collection – a contemporary tile range defined by its bold te",
    brand: "Muses",
    colours: [],
    finishes: ["3D"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Aquastone",
    handle: "vienna",
    blurb: "Aquastone Collection – Understated. Natural. Refined. Inspired by the soft textures and organic tones of natural stone, the Aquastone Collection bring",
    brand: "Capital Tiles",
    colours: ["Ivory"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Luxstone",
    handle: "luxstone",
    blurb: "Luxstone Collection – Effortless Stone-Look Sophistication Bring the timeless beauty of natural stone into your space with the Luxstone Collection — a",
    brand: "Capital Tiles",
    colours: ["White", "Natural", "Beige"],
    finishes: ["Matt", "Textured"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Origin",
    handle: "origin",
    blurb: "Origin Collection – Modern Minimalism with a Stone Edge Clean lines meet timeless surface texture in the Origin Collection, a versatile tile range des",
    brand: "HF Tiles",
    colours: ["White", "Beige", "Grey", "Black"],
    finishes: ["Matt", "Lappato", "Polish", "Flute"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Caesarstone",
    handle: "caesarstone",
    blurb: "Caesarstone Collection – Sleek Stone-Inspired Sophistication Elevate your interior and exterior spaces with the Caesarstone Collection—a refined porce",
    brand: "HF Tiles",
    colours: ["Light", "Medium", "Dark"],
    finishes: ["In&Out Solution", "Lappato", "Soft Matt", "Flute"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Calacatta",
    handle: "calacatta",
    blurb: "Calacatta Collection – Classic Marble, Effortlessly Modern Bring timeless elegance into your space with the Calacatta Collection, a stunning marble-lo",
    brand: "Muses",
    colours: [],
    finishes: ["Polished", "Satin"],
    sizes: ["700x1500"],
  },
  {
    name: "Everest",
    handle: "everest",
    blurb: "Everest Collection – Bold Stone Look, Built for Endurance Elevate your space with the Everest Collection, where modern design meets natural stone eleg",
    brand: "HF Tiles",
    colours: ["Ivory", "Silver", "Grey"],
    finishes: ["In&Out Solution", "StoneTouch Tec"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Alps",
    handle: "alps",
    blurb: "Alps Collection – Seamless Stone-Look Indoors & Out Inspired by the raw beauty of alpine stone, the Alps Collection delivers a sophisticated, textured",
    brand: "Capital Tiles",
    colours: ["Beige", "Silver", "Grey"],
    finishes: ["In&Out Solution"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Travertine",
    handle: "travertine",
    blurb: "Travertine Collection – Classic Stone Look, Modern Performance Bring timeless sophistication to your interiors with the Travertine Collection, inspire",
    brand: "HF Tiles",
    colours: ["Beige", "White"],
    finishes: ["Matt", "Lappato"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Jade Collection",
    handle: "jade",
    blurb: "Jade Collection – Soft Texture, Polished Sophistication Bring subtle elegance and contemporary calm to your interiors with the Jade Collection . Inspi",
    brand: "HF Tiles",
    colours: ["Beige", "White"],
    finishes: ["Soft Matt", "Polish", "Matt"],
    sizes: ["600x600", "600x1200"],
  },
  {
    name: "Arctic Tundra",
    handle: "arctic-tundra",
    blurb: "Arctic Tundra Collection – Nature-Inspired Porcelain for Seamless Indoor & Outdoor Spaces Discover the pristine beauty of the wild with the Arctic Tun",
    brand: "Capital Tiles",
    colours: ["White", "Grey", "Beige"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Jura Collection",
    handle: "jura-collection",
    blurb: "Jura Series – Timeless Limestone-Look Elegance Inspired by the natural beauty of limestone from the Jura region in Germany, the Jura Series brings a r",
    brand: "Capital Tiles",
    colours: ["White", "Greige", "Grey", "Ivory"],
    finishes: ["Matt"],
    sizes: ["75x300", "300x300", "300x600", "600x600"],
  },
  {
    name: "Crete Collection",
    handle: "crete-collection",
    blurb: "Crete Collection – Soft Stone-Look Porcelain for Seamless Indoor-Outdoor Design The Crete Collection is a refined take on natural stone, offering gent",
    brand: "Capital Tiles",
    colours: ["Warm Beige", "Pearl Grey", "Nero Black", "Bianco White"],
    finishes: ["Matt"],
    sizes: ["75x300mm", "300x600mm", "600x600mm", "600x1200mm"],
  },
  {
    name: "Chiswick Outdoor Collection",
    handle: "chiswick-paver-collection",
    blurb: "Chiswick Outdoor Collection – Seamless Stone Style, Made for the Outdoors Elevate your exterior with Chiswick Outdoor , the latest evolution in the Ch",
    brand: "Capital Tiles",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    finishes: ["Square Edge Coper", "External Paver"],
    sizes: ["400x600x20", "600x600x20"],
  },
  {
    name: "Chiswick Collection",
    handle: "chiswick-collection",
    blurb: "Chiswick Collection – Where Natural Stone Meets Contemporary Performance Bring timeless elegance and modern function together with the Chiswick Collec",
    brand: "Capital Tiles",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    finishes: ["Honed", "Matte"],
    sizes: ["600x1200", "600x600", "300x600", "75x300"],
  },
  {
    name: "Ardesia Paver",
    handle: "ardesia-collection",
    blurb: "The ARDESIA collection captures the timeless elegance of slate, bringing the raw beauty of nature into refined interior and exterior spaces. With its ",
    brand: "Muses",
    colours: ["Ivory", "Light Grey"],
    finishes: ["Paver"],
    sizes: ["600 x 600"],
  },
]
