/* Engineered timber range, taken from the live capitaltiles.com.au engineered-timber collection:
   names, blurbs, brands and the colour / finish / size options each product
   actually ships with. */

export const TIMBER = [
  {
    name: "Scenic Rim 12mm",
    handle: "scenic-rim-12mm",
    blurb: "Scenic Rim engineered timber flooring offers the perfect balance of elegance and durability. Featuring a cross-laminated core for enhanced stability, ",
    brand: "National Flooring Distributors",
    colours: ["Scenic Rim - Almond Oak 722", "Scenic Rim - Danish Oak 708", "Scenic Rim - Harvest Oak 706", "Scenic Rim - Milky Oak 711", "Scenic Rim - Mocha 721", "Scenic Rim - Pale Oak 701", "Scenic Rim - Revlon Oak 705", "Scenic Rim - Vintage Oak 703"],
    finishes: ["Brushed"],
    sizes: ["12mm"],
  },
  {
    name: "Daintree XL 15mm",
    handle: "daintree-xl-15mm",
    blurb: "Elevate your space with the grandeur of Daintree XL Engineered Timber. Designed with extra-large planks for a more expansive and seamless look, this p",
    brand: "National Flooring Distributors",
    colours: ["Daintree XL - Blackbutt", "Daintree XL - Spotted Gum", "Daintree XL - Tasmanian Oak"],
    finishes: ["Brushed"],
    sizes: ["15mm"],
  },
  {
    name: "Eternity - European Oaks 14mm",
    handle: "eternity-european-oaks-14mm",
    blurb: "Transform your space with the premium look and feel of Eternity European Oaks Engineered Timber flooring. Combining the natural elegance of real timbe",
    brand: "National Flooring Distributors",
    colours: ["Eternity - Beachwood 811", "Eternity - Blonde Oak 808", "Eternity - Cashew Oak 803", "Eternity - Celtic Snow 801", "Eternity - Chestnut 804", "Eternity - Chocolate Oak 809", "Eternity - Fawn Oak 805", "Eternity - Haven 807", "Eternity - Natural Oak 806", "Eternity - River Oak 802"],
    finishes: ["Brushed"],
    sizes: ["14mm"],
  },
  {
    name: "Daintree 15mm",
    handle: "daintree-15mm",
    blurb: "Embrace the warmth of nature with Daintree, our premium engineered timber collection designed to bring comfort and timeless beauty to any space. Featu",
    brand: "National Flooring Distributors",
    colours: ["Daintree XL - Blackbutt", "Daintree XL - Spotted Gum", "Daintree XL - Tasmanian Oak"],
    finishes: ["Brushed"],
    sizes: ["15mm"],
  },
  {
    name: "Rustic Blackbutt",
    handle: "rustic-blackbutt",
    blurb: "Rustic Blackbutt Laminate Flooring – Stylish, Resilient & Whisper-Quiet Bring the timeless charm of Australian hardwood into your home with Rustic Bla",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Cream Oak",
    handle: "cream-oak",
    blurb: "Durable, Waterproof, and Quiet – Cream Oak Laminate Flooring The Cream Oak laminate plank delivers a soft, neutral timber look that enhances both cont",
    brand: "Capital Tiles",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Spotted Gum",
    handle: "spotted-gum",
    blurb: "Spotted Gum Engineered & Hybrid Flooring – Durable, Waterproof, Acoustic Timber Floors for Canberra Homes The Spotted Gum collection brings the rich, ",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed"],
    sizes: [],
  },
  {
    name: "Lime Wash",
    handle: "lime-wash",
    blurb: "Lime Wash Engineered Timber – Water-Resistant European Oak Flooring for Canberra Homes The Lime Wash collection combines the calming elegance of a sof",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed"],
    sizes: [],
  },
  {
    name: "Classic Oak",
    handle: "classic-oak",
    blurb: "Classic Oak – Traditional Timber Elegance with Modern Performance Classic Oak engineered timber flooring brings the warmth of natural oak together wit",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed"],
    sizes: [],
  },
  {
    name: "Cream White",
    handle: "cream-white",
    blurb: "Cream White – Timeless Oak with Modern Strength Cream White engineered timber flooring blends the elegance of European oak with the durability of mode",
    brand: "Capital Tiles",
    colours: [],
    finishes: ["Brushed"],
    sizes: [],
  },
]
