/* Triexta Carpet product detail data.

   Style, fibre, roll width, thickness, ratings and the descriptions come
   from the live capitaltiles.com.au feed for this collection. Generated —
   edit the source data, not this file.
*/

export const TRIEXTA_PRODUCTS = [
  {
    handle: "soft-glow",
    name: "Soft Glow",
    brand: "Godfrey Hirst",
    card: "/img/triexta/soft-glow.jpg",
    images: [
      "/img/triexta/soft-glow/1.jpg",
      "/img/triexta/soft-glow/2.jpg",
      "/img/triexta/soft-glow/3.jpg",
      "/img/triexta/soft-glow/4.jpg",
      "/img/triexta/soft-glow/5.jpg",
      "/img/triexta/soft-glow/6.jpg",
      "/img/triexta/soft-glow/7.jpg",
      "/img/triexta/soft-glow/8.jpg",
      "/img/triexta/soft-glow/9.jpg",
      "/img/triexta/soft-glow/10.jpg",
      "/img/triexta/soft-glow/11.jpg",
      "/img/triexta/soft-glow/12.jpg",
      "/img/triexta/soft-glow/13.jpg",
      "/img/triexta/soft-glow/14.jpg",
      "/img/triexta/soft-glow/15.jpg",
      "/img/triexta/soft-glow/16.jpg",
      "/img/triexta/soft-glow/17.jpg",
    ],
    tagline: "Triexta carpet in 16 colours",
    short: "Soft Glow Triexta Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 16 colours. Supplied and laid across Canberra.",
    overview: [
      "Australian Made Soft Glow features permanent built-in stain resistance, excellent durability and it cleans with just water. This beautifully soft Triexta Carpet allows you to sit back and enjoy life's special moments.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Heavy Duty - 3 Star ECS Level 4+ 25 Year Triexta Limited Residential Warranty Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre Beautifully Soft Pet Friendly Cut Pile Twist Premium",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Heavy Duty - 3 Star",
      "ECS Level 4+",
      "25 Year Triexta Limited Residential Warranty",
    ],
    seoTitle: "Soft Glow | Capital Tiles",
    seoDesc: "Soft Glow, Cut Pile Twist, 16 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Luminous",
      "Serene",
      "Glimmer",
      "Radiance",
      "Dazzling",
      "Yoga",
      "Iridescent",
      "Lucent",
      "Shimmer",
      "Vivid",
      "Ablaze",
      "Karma",
      "Twinkle",
      "Sunrise",
      "Ray",
      "Nightlight",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: ["16.5 (+/- 1.0)mm"],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "Triexta"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "16.5 (+/- 1.0)mm"],
      ["Pile Height", "14.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "16"],
    ],
    rooms: [],
  },
  {
    handle: "soft-sunrise",
    name: "Soft Sunrise",
    brand: "Godfrey Hirst",
    card: "/img/triexta/soft-sunrise.jpg",
    images: [
      "/img/triexta/soft-sunrise/1.jpg",
      "/img/triexta/soft-sunrise/2.jpg",
      "/img/triexta/soft-sunrise/3.jpg",
      "/img/triexta/soft-sunrise/4.jpg",
      "/img/triexta/soft-sunrise/5.jpg",
      "/img/triexta/soft-sunrise/6.jpg",
      "/img/triexta/soft-sunrise/7.jpg",
      "/img/triexta/soft-sunrise/8.jpg",
      "/img/triexta/soft-sunrise/9.jpg",
      "/img/triexta/soft-sunrise/10.jpg",
      "/img/triexta/soft-sunrise/11.jpg",
      "/img/triexta/soft-sunrise/12.jpg",
      "/img/triexta/soft-sunrise/13.jpg",
      "/img/triexta/soft-sunrise/14.jpg",
      "/img/triexta/soft-sunrise/15.jpg",
      "/img/triexta/soft-sunrise/16.jpg",
      "/img/triexta/soft-sunrise/17.jpg",
      "/img/triexta/soft-sunrise/18.jpg",
      "/img/triexta/soft-sunrise/19.jpg",
      "/img/triexta/soft-sunrise/20.jpg",
      "/img/triexta/soft-sunrise/21.jpg",
    ],
    tagline: "Triexta carpet in 20 colours",
    short: "Soft Sunrise Triexta Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 20 colours. Supplied and laid across Canberra.",
    overview: [
      "If you are looking for a wonderfully soft yet practical carpet then look no further! Made in Australia, Soft Sunrise is durable and stain resistant Triexta Carpet and available in a selection of inspiring colours, including vibrant highlights and on-trend neutral tones.",
      "Godfrey Hirst Best Seller Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty 2 Star ECS Level 4+ 25 Year Triexta Limited Residential Warranty Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre d Fibre Pet Friendly Beautifully Soft Cut Pile Twist $$ Mid Range",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty 2 Star",
      "ECS Level 4+",
    ],
    seoTitle: "Soft Sunrise | Capital Tiles",
    seoDesc: "Soft Sunrise, Cut Pile Twist, 20 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Earthen",
      "Cloud",
      "Angora",
      "Sandshell",
      "Oatmeal",
      "Overcast",
      "Dove",
      "Stormy",
      "Canyon",
      "Vapour",
      "Haze",
      "Aluminium",
      "Alloy",
      "Summit",
      "Fog",
      "Fieldstone",
      "Cavern",
      "Cameo",
      "Lake",
      "Meadow",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: ["14 (+/- 1.0)mm"],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "Triexta"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "14 (+/- 1.0)mm"],
      ["Pile Height", "12 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "20"],
    ],
    rooms: [],
  },
  {
    handle: "inspirational",
    name: "Inspirational",
    brand: "Godfrey Hirst",
    card: "/img/triexta/inspirational.jpg",
    images: [
      "/img/triexta/inspirational/1.jpg",
      "/img/triexta/inspirational/2.jpg",
      "/img/triexta/inspirational/3.jpg",
      "/img/triexta/inspirational/4.jpg",
      "/img/triexta/inspirational/5.jpg",
      "/img/triexta/inspirational/6.jpg",
      "/img/triexta/inspirational/7.jpg",
      "/img/triexta/inspirational/8.jpg",
      "/img/triexta/inspirational/9.jpg",
      "/img/triexta/inspirational/10.jpg",
      "/img/triexta/inspirational/11.jpg",
      "/img/triexta/inspirational/12.jpg",
      "/img/triexta/inspirational/13.jpg",
      "/img/triexta/inspirational/14.jpg",
      "/img/triexta/inspirational/15.jpg",
      "/img/triexta/inspirational/16.jpg",
      "/img/triexta/inspirational/17.jpg",
      "/img/triexta/inspirational/18.jpg",
      "/img/triexta/inspirational/19.jpg",
      "/img/triexta/inspirational/20.jpg",
      "/img/triexta/inspirational/21.jpg",
      "/img/triexta/inspirational/22.jpg",
      "/img/triexta/inspirational/23.jpg",
      "/img/triexta/inspirational/24.jpg",
      "/img/triexta/inspirational/25.jpg",
      "/img/triexta/inspirational/26.jpg",
      "/img/triexta/inspirational/27.jpg",
      "/img/triexta/inspirational/28.jpg",
      "/img/triexta/inspirational/29.jpg",
      "/img/triexta/inspirational/30.jpg",
      "/img/triexta/inspirational/31.jpg",
    ],
    tagline: "Triexta carpet in 30 colours",
    short: "Inspirational Triexta Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 30 colours. Supplied and laid across Canberra.",
    overview: [
      "If you are looking for a wonderfully soft, dependable carpet then you have found it – meet Inspirational! This durable, soft and easy to clean Triexta Carpet that is available in a gorgeous selection of inspiring colours, including vibrant highlights and on-trend neutral tones.",
      "Godfrey Hirst Best Seller Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4+ 25 Year Triexta Limited Residential Warranty* Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre Pet Friendly Beautifully Soft Cut Pile Twist Mid Range",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
    ],
    seoTitle: "Inspirational | Capital Tiles",
    seoDesc: "Inspirational, Cut Pile Twist, 30 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Deep Purple",
      "Dover White",
      "Birchwood",
      "Acorn",
      "Super Nova",
      "Cygnet",
      "Dove",
      "Glacier",
      "Limestone",
      "Cloudy Day",
      "Silver Berry",
      "Argent",
      "Sharkskin",
      "Dolphin",
      "Greystone",
      "Driftwood",
      "Arctic Grey",
      "Manatee",
      "Dark Grey",
      "Mica",
      "Dark Shadow",
      "Fresh Breeze",
      "Ice Blue",
      "Smokey Blue",
      "Deep Sky",
      "Blue Shadow",
      "Mountain Blue",
      "Ice Green",
      "Greendale",
      "Cameo",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: ["16 (+/- 1.0)mm"],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "Triexta"],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "16 (+/- 1.0)mm"],
      ["Pile Height", "13 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "30"],
    ],
    rooms: [],
  },
  {
    handle: "winter-charm",
    name: "Winter Charm",
    brand: "Godfrey Hirst",
    card: "/img/triexta/winter-charm.jpg",
    images: [
      "/img/triexta/winter-charm/1.jpg",
      "/img/triexta/winter-charm/2.jpg",
      "/img/triexta/winter-charm/3.jpg",
      "/img/triexta/winter-charm/4.jpg",
      "/img/triexta/winter-charm/5.jpg",
      "/img/triexta/winter-charm/6.jpg",
      "/img/triexta/winter-charm/7.jpg",
      "/img/triexta/winter-charm/8.jpg",
      "/img/triexta/winter-charm/9.jpg",
      "/img/triexta/winter-charm/10.jpg",
      "/img/triexta/winter-charm/11.jpg",
      "/img/triexta/winter-charm/12.jpg",
      "/img/triexta/winter-charm/13.jpg",
      "/img/triexta/winter-charm/14.jpg",
      "/img/triexta/winter-charm/15.jpg",
      "/img/triexta/winter-charm/16.jpg",
    ],
    tagline: "Triexta carpet in 16 colours",
    short: "Winter Charm Triexta Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 16 colours. Supplied and laid across Canberra.",
    overview: [
      "Sink your toes into sumptuously soft Winter Charm. With built-in stain protection from household spills and pet mishaps, as well as excellent durability, this cosy Triexta Carpet will continue to charm you year after year.",
      "Australian Made Declare Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 25 Year Premium Limited Residential Warranty Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre Beautifully Soft Pet Friendly Cut Pile Twist Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "25 Year Premium Limited Residential Warranty",
    ],
    seoTitle: "Winter Charm | Capital Tiles",
    seoDesc: "Winter Charm, Cut Pile Twist, 16 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Pressed Rose",
      "Bleached Shell",
      "Sandy Day",
      "Beige Royal",
      "Papyrus",
      "Pebblestone",
      "Light Clay",
      "Vapour",
      "Silver Wheel",
      "Wood Ash",
      "City Grey",
      "Industrial Grey",
      "Coalmine",
      "Dolomite",
      "Seafront",
      "Fern",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: ["11.5 (+/- 1.0)mm"],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "Triexta"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "11.5 (+/- 1.0)mm"],
      ["Pile Height", "8.50 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "16"],
    ],
    rooms: [],
  },
  {
    handle: "natural-artistry",
    name: "Natural Artistry",
    brand: "Godfrey Hirst",
    card: "/img/triexta/natural-artistry.jpg",
    images: [
      "/img/triexta/natural-artistry/1.jpg",
      "/img/triexta/natural-artistry/2.jpg",
      "/img/triexta/natural-artistry/3.jpg",
      "/img/triexta/natural-artistry/4.jpg",
      "/img/triexta/natural-artistry/5.jpg",
      "/img/triexta/natural-artistry/6.jpg",
    ],
    tagline: "Triexta carpet in 6 colours",
    short: "Natural Artistry Triexta Carpet by Godfrey Hirst. Textured cut and loop, 3.66m roll width and 6 colours. Supplied and laid across Canberra.",
    overview: [
      "Make a design statement with this stunning Textured Cut And Loop carpet, Natural Artistry. This unique highlighted design is formed by the inimitable combination of durable triexta and soft polyester fibres which come together to create a sophisticated visual effect while still offering supreme performance.",
      "Residential Extra Heavy Duty & Stairs - 5 Star Contract Light Duty - 1 Star ECS Level 4 25 Year Triexta Limited Residential Warranty* Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre Beautifully Soft Pet Friendly Textured Cut and Loop Pile Mid Range Declare® Red List Free",
    ],
    features: [
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Light Duty - 1 Star",
      "ECS Level 4",
      "25 Year Triexta Limited Residential Warranty*",
      "Built In Stain Resistance",
      "Cleanable with Cold Water",
    ],
    seoTitle: "Natural Artistry | Capital Tiles",
    seoDesc: "Natural Artistry, Textured Cut And Loop, 6 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Arctic", "Moon Shine", "Vintage", "Bazar", "Mist", "Mineral"],
    sizes: ["3.66m"],
    finishes: ["Textured Cut And Loop"],
    thickness: [],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Textured Cut And Loop"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "75% Triexta / 25% Polyester"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "11.5 ( +/- 1.0)mm"],
      ["Pile Height", "9.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "6"],
    ],
    rooms: [],
  },
  {
    handle: "royal-charm",
    name: "Royal Charm",
    brand: "Godfrey Hirst",
    card: "/img/triexta/royal-charm.jpg",
    images: [
      "/img/triexta/royal-charm/1.jpg",
      "/img/triexta/royal-charm/2.jpg",
      "/img/triexta/royal-charm/3.jpg",
      "/img/triexta/royal-charm/4.jpg",
      "/img/triexta/royal-charm/5.jpg",
      "/img/triexta/royal-charm/6.jpg",
      "/img/triexta/royal-charm/7.jpg",
      "/img/triexta/royal-charm/8.jpg",
      "/img/triexta/royal-charm/9.jpg",
      "/img/triexta/royal-charm/10.jpg",
      "/img/triexta/royal-charm/11.jpg",
      "/img/triexta/royal-charm/12.jpg",
      "/img/triexta/royal-charm/13.jpg",
      "/img/triexta/royal-charm/14.jpg",
      "/img/triexta/royal-charm/15.jpg",
      "/img/triexta/royal-charm/16.jpg",
      "/img/triexta/royal-charm/17.jpg",
      "/img/triexta/royal-charm/18.jpg",
    ],
    tagline: "Triexta carpet in 18 colours",
    short: "Royal Charm Triexta Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 18 colours. Supplied and laid across Canberra.",
    overview: [
      "Made in Australia from our incredibly soft triexta fibre, this carpet features permanent built-in stain resistance and excellent durability. This luxuriously soft Triexta Carpet allows you to enjoy life's special moments worry-free.",
      "Godfrey Hirst Best Seller Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 25 Year Triexta Limited Residential Warranty* Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre Pet Friendly Beautifully Soft Cut Pile Twist Premium",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
    ],
    seoTitle: "Royal Charm | Capital Tiles",
    seoDesc: "Royal Charm, Cut Pile Twist, 18 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Dusky Pink",
      "White Feather",
      "Moonlight",
      "Biscotti",
      "Arctic Mist",
      "Glacier Grey",
      "Grey Haze",
      "Cloud Grey",
      "Grey Crystal",
      "Smoke",
      "Cool Grey",
      "Ash Grey",
      "Night Storm",
      "Sierra Night",
      "Dark Slate",
      "Dark Shadow",
      "Blue Charm",
      "Dark Denim",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "Triexta"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "16.5 (+/- 1.0)mm"],
      ["Pile Height", "14 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "18"],
    ],
    rooms: [],
  },
  {
    handle: "unwind",
    name: "Unwind",
    brand: "Godfrey Hirst",
    card: "/img/triexta/unwind.jpg",
    images: [
      "/img/triexta/unwind/1.jpg",
      "/img/triexta/unwind/2.jpg",
      "/img/triexta/unwind/3.jpg",
      "/img/triexta/unwind/4.jpg",
      "/img/triexta/unwind/5.jpg",
      "/img/triexta/unwind/6.jpg",
      "/img/triexta/unwind/7.jpg",
      "/img/triexta/unwind/8.jpg",
      "/img/triexta/unwind/9.jpg",
      "/img/triexta/unwind/10.jpg",
      "/img/triexta/unwind/11.jpg",
      "/img/triexta/unwind/12.jpg",
      "/img/triexta/unwind/13.jpg",
      "/img/triexta/unwind/14.jpg",
      "/img/triexta/unwind/15.jpg",
      "/img/triexta/unwind/16.jpg",
      "/img/triexta/unwind/17.jpg",
      "/img/triexta/unwind/18.jpg",
      "/img/triexta/unwind/19.jpg",
    ],
    tagline: "Triexta carpet in 19 colours",
    short: "Unwind Triexta Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 19 colours. Supplied and laid across Canberra.",
    overview: [
      "You can live worry-free with this soft, high-performing Triexta Carpet that is ideal for busy family households. With less time spent cleaning, you'll have more time to relax and Unwind in your home.",
      "Australian Made Declare® Red List Free 20 Year Triexta Limited Residential Warranty* Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre Beautifully Soft Pet Friendly Cut Pile Twist Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "20 Year Triexta Limited Residential Warranty*",
      "Built In Stain Resistance",
      "Cleanable with Cold Water",
      "Built-In Durability",
    ],
    seoTitle: "Unwind | Capital Tiles",
    seoDesc: "Unwind, Cut Pile Twist, 19 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Blush",
      "Pearl Blush",
      "Cottonseed",
      "Ambrosia",
      "Feldspar",
      "Red Engine",
      "Dahlia",
      "Tradewind",
      "Light Grey",
      "Grey Mood",
      "Steel",
      "Seal",
      "Tranquility",
      "Pewter",
      "Charcoal",
      "Wrought Iron",
      "Stormy Blue",
      "Cobalt",
      "Green Haze",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "Triexta"],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "14 (+/- 1.0)mm"],
      ["Pile Height", "11 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "19"],
    ],
    rooms: [],
  },
  {
    handle: "luxury-appeal",
    name: "Luxury Appeal",
    brand: "Godfrey Hirst",
    card: "/img/triexta/luxury-appeal.jpg",
    images: [
      "/img/triexta/luxury-appeal/1.jpg",
      "/img/triexta/luxury-appeal/2.jpg",
      "/img/triexta/luxury-appeal/3.jpg",
      "/img/triexta/luxury-appeal/4.jpg",
      "/img/triexta/luxury-appeal/5.jpg",
      "/img/triexta/luxury-appeal/6.jpg",
      "/img/triexta/luxury-appeal/7.jpg",
      "/img/triexta/luxury-appeal/8.jpg",
      "/img/triexta/luxury-appeal/9.jpg",
      "/img/triexta/luxury-appeal/10.jpg",
      "/img/triexta/luxury-appeal/11.jpg",
      "/img/triexta/luxury-appeal/12.jpg",
      "/img/triexta/luxury-appeal/13.jpg",
      "/img/triexta/luxury-appeal/14.jpg",
      "/img/triexta/luxury-appeal/15.jpg",
      "/img/triexta/luxury-appeal/16.jpg",
    ],
    tagline: "Triexta carpet in 16 colours",
    short: "Luxury Appeal Triexta Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 16 colours. Supplied and laid across Canberra.",
    overview: [
      "Indulge in luxuriously soft carpet every day with Luxury Appeal. Meticulously crafted in Australia from our extremely durable and stain resistant triexta fibre, this high performing carpet promises unbelievable amounts of cosy comfort underfoot. This silky soft carpet will retain its beautiful look and feel year after year.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 25 Year Triexta Limited Residential Warranty* Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre Pet Friendly Beautifully Soft Cut Pile Twist Premium",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "25 Year Triexta Limited Residential Warranty*",
    ],
    seoTitle: "Luxury Appeal | Capital Tiles",
    seoDesc: "Luxury Appeal, Cut Pile Twist, 16 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Cream Cloak",
      "Champagne",
      "Silk Paper",
      "Shortbread",
      "Stone House",
      "Bagel",
      "Elusion",
      "Grey Fog",
      "Urban Chic",
      "City Shadow",
      "Smoke Stack",
      "Stonehenge",
      "Stone Partition",
      "Tinsmith",
      "Blue Iris",
      "Mint Slice",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "Triexta"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "18 (+/- 1.0)mm"],
      ["Pile Height", "15 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "16"],
    ],
    rooms: [],
  },
  {
    handle: "winter-flair",
    name: "Winter Flair",
    brand: "Godfrey Hirst",
    card: "/img/triexta/winter-flair.jpg",
    images: [
      "/img/triexta/winter-flair/1.jpg",
      "/img/triexta/winter-flair/2.jpg",
      "/img/triexta/winter-flair/3.jpg",
      "/img/triexta/winter-flair/4.jpg",
      "/img/triexta/winter-flair/5.jpg",
      "/img/triexta/winter-flair/6.jpg",
      "/img/triexta/winter-flair/7.jpg",
      "/img/triexta/winter-flair/8.jpg",
      "/img/triexta/winter-flair/9.jpg",
      "/img/triexta/winter-flair/10.jpg",
      "/img/triexta/winter-flair/11.jpg",
      "/img/triexta/winter-flair/12.jpg",
      "/img/triexta/winter-flair/13.jpg",
      "/img/triexta/winter-flair/14.jpg",
      "/img/triexta/winter-flair/15.jpg",
      "/img/triexta/winter-flair/16.jpg",
    ],
    tagline: "Triexta carpet in 16 colours",
    short: "Winter Flair Triexta Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 16 colours. Supplied and laid across Canberra.",
    overview: [
      "Perfect your interior vision with the incredibly stylish Winter Flair. Crafted from our extremely durable and stain resistant triexta fibre, this high performing carpet promises unbelievable amounts of cosy comfort underfoot. Choose from modern neutral tones and vibrant highlight colours to make a statement on the floor.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 25 Year Triexta Limited Residential Warranty* Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre Beautifully Soft Pet Friendly Cut Pile Twist Mid Range",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "25 Year Triexta Limited Residential Warranty*",
    ],
    seoTitle: "Winter Flair | Capital Tiles",
    seoDesc: "Winter Flair, Cut Pile Twist, 16 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Fawn Pink",
      "Powder White",
      "Cargo Beige",
      "Honey Glow",
      "Smoked Pearl",
      "Tapestry Beige",
      "Ash Grey",
      "Morning Grey",
      "Bedrock",
      "Dark Mushroom",
      "Charcoal",
      "Obsidian",
      "Blue Print",
      "Deep Sea",
      "Ocean View",
      "Everglades",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "Triexta"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "12 (+/- 1.0)mm"],
      ["Pile Height", "10 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "16"],
    ],
    rooms: [],
  },
  {
    handle: "velvet-appeal",
    name: "Velvet Appeal",
    brand: "Godfrey Hirst",
    card: "/img/triexta/velvet-appeal.jpg",
    images: [
      "/img/triexta/velvet-appeal/1.jpg",
      "/img/triexta/velvet-appeal/2.jpg",
      "/img/triexta/velvet-appeal/3.jpg",
      "/img/triexta/velvet-appeal/4.jpg",
      "/img/triexta/velvet-appeal/5.jpg",
      "/img/triexta/velvet-appeal/6.jpg",
      "/img/triexta/velvet-appeal/7.jpg",
      "/img/triexta/velvet-appeal/8.jpg",
      "/img/triexta/velvet-appeal/9.jpg",
      "/img/triexta/velvet-appeal/10.jpg",
      "/img/triexta/velvet-appeal/11.jpg",
      "/img/triexta/velvet-appeal/12.jpg",
      "/img/triexta/velvet-appeal/13.jpg",
      "/img/triexta/velvet-appeal/14.jpg",
      "/img/triexta/velvet-appeal/15.jpg",
      "/img/triexta/velvet-appeal/16.jpg",
      "/img/triexta/velvet-appeal/17.jpg",
      "/img/triexta/velvet-appeal/18.jpg",
      "/img/triexta/velvet-appeal/19.jpg",
      "/img/triexta/velvet-appeal/20.jpg",
      "/img/triexta/velvet-appeal/21.jpg",
      "/img/triexta/velvet-appeal/22.jpg",
      "/img/triexta/velvet-appeal/23.jpg",
      "/img/triexta/velvet-appeal/24.jpg",
    ],
    tagline: "Triexta carpet in 24 colours",
    short: "Velvet Appeal Triexta Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 24 colours. Supplied and laid across Canberra.",
    overview: [
      "Wake up to luxury every day with Velvet Appeal. Made in Australia from our incredibly soft triexta fibre, this carpet features permanent built-in stain resistance and excellent durability. This silky soft Triexta Carpet allows you to enjoy life's special moments worry-free.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 25 Year Triexta Limited Residential Warranty* Built In Stain Resistance Cleanable with Cold Water Built-In Durability Partly Plant Based Fibre Pet Friendly Beautifully Soft Cut Pile Twist Premium",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "25 Year Triexta Limited Residential Warranty*",
    ],
    seoTitle: "Velvet Appeal | Capital Tiles",
    seoDesc: "Velvet Appeal, Cut Pile Twist, 24 colours. Triexta carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Coconut",
      "Aged Paper",
      "Manuscript",
      "Sand Glass",
      "Harpe",
      "Alpaca",
      "Clean Vapour",
      "Ocean Air",
      "Silk Grey",
      "Silver Drop",
      "Frosty Touch",
      "Silverton",
      "Flooded Gum",
      "Soothing Grey",
      "Grey Concrete",
      "Tuscan Path",
      "Pond Pebble",
      "Grey Calm",
      "Night Horizon",
      "Metal Links",
      "Dark Whale",
      "Cornflower",
      "Stone Blue",
      "Green Crystal",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Triexta Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Triexta Carpet"],
      ["Yarn", "Triexta"],
      ["Gauge", "39.4/10cm (1/10th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "16 (+/- 1.0)mm"],
      ["Pile Height", "14 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "24"],
    ],
    rooms: [],
  },
]

export function byHandle(handle) {
  return TRIEXTA_PRODUCTS.find((p) => p.handle === handle)
}
