/* Triexta floor tile range, taken from the live capitaltiles.com.au floor-tiles
   collection: names, blurbs, brands and the colour / finish / size options
   each product actually ships with. */

export const TRIEXTA = [
  {
    name: "Port Travertino",
    handle: "port-travertino",
    blurb: "Available in 3 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Ivory", "Light Grey"],
    finishes: ["3D"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Limestone",
    handle: "limestone",
    blurb: "Available in 4 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Beige", "Beige Fluted", "Ivory Fluted", "Ivory"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Find",
    handle: "find",
    blurb: "Available in 2 colours and 1 finish, in 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Cool Grey", "Light Grey"],
    finishes: ["Felltec"],
    sizes: ["600x1200"],
  },
  {
    name: "Vutton Series",
    handle: "vutton-series",
    blurb: "The VUTTON collection combines refined elegance with contemporary style, making it the perfect choice for sophisticated interiors. Inspired by natural",
    brand: "Muses",
    colours: ["Ash", "Ice", "Night", "Pearl", "Sage"],
    finishes: [],
    sizes: ["Mosaic Sheets (275.2×275.2mm)"],
  },
  {
    name: "Mistery Dark Grey",
    handle: "mistery-dark-grey",
    blurb: "Available in 2 colours and 1 finish, in 300x600 to 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Light Grey", "Dark Grey"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Find Honed",
    handle: "find-honed",
    blurb: "Available in 2 colours and 1 finish, in 600x1200. Floor and wall rated, supplied and installed across Canberra.",
    brand: "Muses",
    colours: ["Cool Grey", "Light Grey"],
    finishes: ["Honed"],
    sizes: ["600x1200"],
  },
  {
    name: "Calacatta Pro",
    handle: "calacatta-pro",
    blurb: "The Calacatta Pro Marble collection delivers the timeless elegance of classic Calacatta with a modern twist. Featuring a bright white base enriched by",
    brand: "Muses",
    colours: [],
    finishes: ["Felltec", "Polished"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Milano",
    handle: "milano",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 1200*1200 10mm Matt P2 600*600 ",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200", "1200x1200", "400x600"],
  },
  {
    name: "Pool Glass mosaic",
    handle: "pool-glass-mosaic",
    blurb: "Available. Floor and wall rated, supplied and installed across Canberra.",
    brand: "CIE Ceramic",
    colours: [],
    finishes: [],
    sizes: [],
  },
  {
    name: "Patrone",
    handle: "patrone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P4 300*600 10mm Matt P4 600*600 10mm Matt P4 600*600 20mm External P5 400*600 20mm External P5 Not",
    brand: "CIE Ceramic",
    colours: ["Beige", "Silver", "Ebony"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "400x600"],
  },
  {
    name: "Cairo",
    handle: "cairo",
    blurb: "Size Thickness Finish Slip Rating 600*600 20mm External P5 400*600 20mm External Drop Edge Copping P5 Recommended Applications (Glazed Porcelain) : Ex",
    brand: "CIE Ceramic",
    colours: ["Light", "Dark"],
    finishes: ["External"],
    sizes: ["400x600", "600x600"],
  },
  {
    name: "Shine",
    handle: "shine",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Bianco", "Moon"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Millenia",
    handle: "millenia",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm Matt P2 600*1200 1",
    brand: "CIE Ceramic",
    colours: ["White", "Pearl Grey"],
    finishes: ["Matt", "Polished"],
    sizes: ["300x300", "300x600", "600x600", "600x1200", "1200x1200"],
  },
  {
    name: "Dusk",
    handle: "dusk",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Greige", "White"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Travertine",
    handle: "travertine-1",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Silver", "Bravo"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Terrazzo",
    handle: "terrazzo",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 Recommended Applications (Glazed Porcelain) : Interio",
    brand: "CIE Ceramic",
    colours: ["Bianco"],
    finishes: ["Matt"],
    sizes: ["300x300", "300x600", "600x600"],
  },
  {
    name: "Polar Ice",
    handle: "polar-ice",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 Recommended Applications (Glaze",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "SandStone",
    handle: "sandstone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["Bianco"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Simply Stone",
    handle: "simply-stone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Divine Stone",
    handle: "divine-stone",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: [],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Republic",
    handle: "republic",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 600*60",
    brand: "CIE Ceramic",
    colours: ["White", "Silver"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200", "400x600"],
  },
  {
    name: "Orobico",
    handle: "orobico",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 Recommended Applications (Glaze",
    brand: "CIE Ceramic",
    colours: ["Bianco", "Grey"],
    finishes: ["Matt"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Ciement",
    handle: "ciement",
    blurb: "Size Thickness Finish Slip Rating 300*300 10mm Matt P3 300*600 10mm Matt P3 600*600 10mm Matt P3 600*1200 10mm Matt P2 600*600 10mm External P5 Recomm",
    brand: "CIE Ceramic",
    colours: ["White"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Cocoon Collection",
    handle: "cocoon-collection",
    blurb: "Cocoon Honed Porcelain Tile — Weston Creek & Molonglo Cocoon is an Italian-made porcelain collection that wraps spaces in calm. With 16 unique faces, ",
    brand: "Capital Tiles",
    colours: ["Hazelnut", "Beige"],
    finishes: ["Honed"],
    sizes: ["600x1200 mm"],
  },
  {
    name: "UNICO GREY",
    handle: "unico-grey",
    blurb: "Look Tile — Woden Valley Italian-made and effortlessly refined, Unico Grey reimagines classic marble with twenty unique faces and innovative, high-imp",
    brand: "Capital Tiles",
    colours: ["Unico Grey"],
    finishes: ["Matt 3D"],
    sizes: ["600x1200 mm"],
  },
  {
    name: "Bari Collection",
    handle: "bari-collection",
    blurb: "The Bari Collection Travertine Tile — Belconnen Timeless elegance meets natural artistry with The Bari Collection . A luxurious travertine-look porcel",
    brand: "Capital Tiles",
    colours: ["Bianco", "Taupe", "Beige"],
    finishes: ["Versa Touch", "P5 20mm", "Cobbles VT", "P5 20mm Pencil Edge"],
    sizes: ["300x600", "600x600", "1200x600", "75x300", "307x307 mm sheets", "Crazy Pave", "French Pattern", "600x400 mm DF", "600x400"],
  },
  {
    name: "Aqua",
    handle: "aqua-collection",
    blurb: "Modern Coastal Finish Bring a refreshing, contemporary look to your interiors with the Aqua 60x240mm polished tile. Its sleek finish is ideal for brig",
    brand: "Muses",
    colours: ["Crystal", "Opal", "Rune", "Jade", "Berry", "Core"],
    finishes: ["Polished"],
    sizes: [],
  },
  {
    name: "Alhambra Collection",
    handle: "alhambra",
    blurb: "Elegant Embossed Tiles for Walls & Floors Bring European sophistication to your home with the Alhambra Collection . These decor tiles feature delicate",
    brand: "Capital Tiles",
    colours: ["Rojo", "Negro", "Gris", "Azul", "Arena", "Barcelona"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Kolor Series",
    handle: "kolor",
    blurb: "Contemporary Concrete-Inspired Minimalism Refined, architectural, and effortlessly modern, the Kolor Collection brings the understated beauty of concr",
    brand: "Muses",
    colours: ["White", "Ivory", "Light Grey", "Medium Grey"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Calacatta Gold",
    handle: "calacatta-gold",
    blurb: "Timeless Elegance with a Golden Touch Inspired by the luxurious veining of Italian Calacatta marble, the Calacatta Gold Collection brings soft opulenc",
    brand: "Muses",
    colours: ["Gold"],
    finishes: ["Polished", "Satin"],
    sizes: ["600x1200mm", "750x1500mm"],
  },
  {
    name: "Onyx Series",
    handle: "onyx",
    blurb: "Polished Perfection in Stone-Inspired Style Elevate your interiors with the Onyx Collection — a porcelain tile range inspired by the depth and veining",
    brand: "Muses",
    colours: ["Ivory", "Beige", "Light Grey", "Brown"],
    finishes: ["Polished", "Satin"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Picasso",
    handle: "picasso",
    blurb: "Artful Texture Meets Modern Scale Bring bold creativity into your interiors with the Picasso Collection , a porcelain tile range inspired by contempor",
    brand: "Muses",
    colours: [],
    finishes: ["Deep Ink (IK) & 3D"],
    sizes: ["300x600", "600×600", "600×1200", "750×1500"],
  },
  {
    name: "Roccia Series",
    handle: "roccia",
    blurb: "Earthy Porcelain Tiles with Modern Durability Bring the rugged charm of natural stone into your home with the Roccia Collection . These porcelain tile",
    brand: "Muses",
    colours: ["Greige", "Charcoal"],
    finishes: ["Felltec"],
    sizes: ["300x600", "600x600", "600x1200"],
  },
  {
    name: "Silver Root",
    handle: "silver-root",
    blurb: "Polished Sophistication with Stone Soul Inspired by the intricate veining of high-end marble and the organic movement of natural stone, the Silver Roo",
    brand: "Muses",
    colours: ["Ivory", "Light Grey", "Brown"],
    finishes: ["Satin"],
    sizes: [],
  },
  {
    name: "Stazzema Series",
    handle: "stazzema",
    blurb: "Textured Elegance with Natural Depth Inspired by the fine textures of honed limestone, the Stazzema Collection offers a refined balance of elegance, v",
    brand: "Muses",
    colours: ["Ivory", "Smokey Grey"],
    finishes: ["Felltec"],
    sizes: ["300x600mm", "600x600mm", "600x1200mm"],
  },
  {
    name: "Zouks",
    handle: "zouks",
    blurb: "Bold. Textured. Modern. Make a strong design statement with the Zouks Collection – a contemporary tile range defined by its bold texture and dramatic ",
    brand: "Muses",
    colours: [],
    finishes: ["3D"],
    sizes: ["300x600", "600x600", "600x1200", "750x1500"],
  },
  {
    name: "Aquastone",
    handle: "vienna",
    blurb: "Understated. Natural. Refined. Inspired by the soft textures and organic tones of natural stone, the Aquastone Collection brings effortless elegance t",
    brand: "Capital Tiles",
    colours: ["Ivory"],
    finishes: ["Matt"],
    sizes: ["300x600", "600x600"],
  },
  {
    name: "Calacatta",
    handle: "calacatta",
    blurb: "Classic Marble, Effortlessly Modern Bring timeless elegance into your space with the Calacatta Collection, a stunning marble-look porcelain tile serie",
    brand: "Muses",
    colours: [],
    finishes: ["Polished", "Satin"],
    sizes: ["700x1500"],
  },
  {
    name: "Alps",
    handle: "alps",
    blurb: "Seamless Stone-Look Indoors & Out Inspired by the raw beauty of alpine stone, the Alps Collection delivers a sophisticated, textured finish perfect fo",
    brand: "Capital Tiles",
    colours: ["Beige", "Silver", "Grey"],
    finishes: ["In&Out Solution"],
    sizes: ["600x600", "600x1200", "300x600"],
  },
  {
    name: "Arctic Tundra",
    handle: "arctic-tundra",
    blurb: "Nature-Inspired Porcelain for Seamless Indoor & Outdoor Spaces Discover the pristine beauty of the wild with the Arctic Tundra Collection – a porcelai",
    brand: "Capital Tiles",
    colours: ["White", "Grey", "Beige"],
    finishes: ["Matt", "External"],
    sizes: ["300x300", "300x600", "600x600", "600x1200"],
  },
  {
    name: "Jura Collection",
    handle: "jura-collection",
    blurb: "Timeless Limestone-Look Elegance Inspired by the natural beauty of limestone from the Jura region in Germany, the Jura Series brings a refined and sop",
    brand: "Capital Tiles",
    colours: ["White", "Greige", "Grey", "Ivory"],
    finishes: [],
    sizes: ["75x300", "300x300", "300x600", "600x600"],
  },
  {
    name: "Crete Collection",
    handle: "crete-collection",
    blurb: "Soft Stone-Look Porcelain for Seamless Indoor-Outdoor Design The Crete Collection is a refined take on natural stone, offering gentle movement and a s",
    brand: "Capital Tiles",
    colours: ["Warm Beige", "Pearl Grey", "Nero Black", "Bianco White"],
    finishes: [],
    sizes: ["75x300mm", "300x600mm", "600x600mm", "600x1200mm"],
  },
  {
    name: "Chiswick Collection",
    handle: "chiswick-collection",
    blurb: "Where Natural Stone Meets Contemporary Performance Bring timeless elegance and modern function together with the Chiswick Collection —a sophisticated ",
    brand: "Capital Tiles",
    colours: ["White", "Cream", "Gray", "Charcoal"],
    finishes: ["Honed", "Matte"],
    sizes: ["600x1200", "600x600", "300x600", "75x300"],
  },
]
