/* Triexta carpet range, taken from the live capitaltiles.com.au triexta
   collection: names, blurbs, brands and the colour / style / roll width each
   range actually ships with. */

export const TRIEXTA = [
  {
    name: "Soft Glow",
    handle: "soft-glow",
    blurb: "Australian Made Soft Glow features permanent built-in stain resistance, excellent durability and it cleans with just water. This beautifully soft triexta...",
    brand: "Godfrey Hirst",
    colours: ["Luminous", "Serene", "Glimmer", "Radiance", "Dazzling", "Yoga", "Iridescent", "Lucent", "Shimmer", "Vivid", "Ablaze", "Karma", "Twinkle", "Sunrise", "Ray", "Nightlight"],
    finishes: ["Cut Pile Twist"],
    sizes: ["3.66m"],
  },
  {
    name: "Soft Sunrise",
    handle: "soft-sunrise",
    blurb: "If you are looking for a wonderfully soft yet practical carpet then look no further! Made in Australia, Soft Sunrise is durable and stain resistant triexta...",
    brand: "Godfrey Hirst",
    colours: ["Earthen", "Cloud", "Angora", "Sandshell", "Oatmeal", "Overcast", "Dove", "Stormy", "Canyon", "Vapour", "Haze", "Aluminium", "Alloy", "Summit", "Fog", "Fieldstone", "Cavern", "Cameo", "Lake", "Meadow"],
    finishes: ["Cut Pile Twist"],
    sizes: ["3.66m"],
  },
  {
    name: "Inspirational",
    handle: "inspirational",
    blurb: "If you are looking for a wonderfully soft, dependable carpet then you have found it – meet Inspirational! This durable, soft and easy to clean triexta carpet...",
    brand: "Godfrey Hirst",
    colours: ["Deep Purple", "Dover White", "Birchwood", "Acorn", "Super Nova", "Cygnet", "Dove", "Glacier", "Limestone", "Cloudy Day", "Silver Berry", "Argent", "Sharkskin", "Dolphin", "Greystone", "Driftwood", "Arctic Grey", "Manatee", "Dark Grey", "Mica", "Dark Shadow", "Fresh Breeze", "Ice Blue", "Smokey Blue", "Deep Sky", "Blue Shadow", "Mountain Blue", "Ice Green", "Greendale", "Cameo"],
    finishes: ["Cut Pile Twist"],
    sizes: ["3.66m"],
  },
  {
    name: "Winter Charm",
    handle: "winter-charm",
    blurb: "Sink your toes into sumptuously soft Winter Charm. With built-in stain protection from household spills and pet mishaps, as well as excellent durability, this...",
    brand: "Godfrey Hirst",
    colours: ["Pressed Rose", "Bleached Shell", "Sandy Day", "Beige Royal", "Papyrus", "Pebblestone", "Light Clay", "Vapour", "Silver Wheel", "Wood Ash", "City Grey", "Industrial Grey", "Coalmine", "Dolomite", "Seafront", "Fern"],
    finishes: ["Cut Pile Twist"],
    sizes: ["3.66m"],
  },
  {
    name: "Natural Artistry",
    handle: "natural-artistry",
    blurb: "Make a design statement with this stunning textured cut and loop carpet, Natural Artistry. This unique highlighted design is formed by the inimitable...",
    brand: "Godfrey Hirst",
    colours: ["Arctic", "Moon Shine", "Vintage", "Bazar", "Mist", "Mineral"],
    finishes: ["Textured Cut And Loop"],
    sizes: ["3.66m"],
  },
  {
    name: "Royal Charm",
    handle: "royal-charm",
    blurb: "Made in Australia from our incredibly soft triexta fibre, this carpet features permanent built-in stain resistance and excellent durability. This luxuriously...",
    brand: "Godfrey Hirst",
    colours: ["Dusky Pink", "White Feather", "Moonlight", "Biscotti", "Arctic Mist", "Glacier Grey", "Grey Haze", "Cloud Grey", "Grey Crystal", "Smoke", "Cool Grey", "Ash Grey", "Night Storm", "Sierra Night", "Dark Slate", "Dark Shadow", "Blue Charm", "Dark Denim"],
    finishes: ["Cut Pile Twist"],
    sizes: ["3.66m"],
  },
  {
    name: "Unwind",
    handle: "unwind",
    blurb: "You can live worry-free with this soft, high-performing triexta carpet that is ideal for busy family households. With less time spent cleaning, you'll have...",
    brand: "Godfrey Hirst",
    colours: ["Blush", "Pearl Blush", "Cottonseed", "Ambrosia", "Feldspar", "Red Engine", "Dahlia", "Tradewind", "Light Grey", "Grey Mood", "Steel", "Seal", "Tranquility", "Pewter", "Charcoal", "Wrought Iron", "Stormy Blue", "Cobalt", "Green Haze"],
    finishes: ["Cut Pile Twist"],
    sizes: ["3.66m"],
  },
  {
    name: "Luxury Appeal",
    handle: "luxury-appeal",
    blurb: "Indulge in luxuriously soft carpet every day with Luxury Appeal. Meticulously crafted in Australia from our extremely durable and stain resistant triexta...",
    brand: "Godfrey Hirst",
    colours: ["Cream Cloak", "Champagne", "Silk Paper", "Shortbread", "Stone House", "Bagel", "Elusion", "Grey Fog", "Urban Chic", "City Shadow", "Smoke Stack", "Stonehenge", "Stone Partition", "Tinsmith", "Blue Iris", "Mint Slice"],
    finishes: ["Cut Pile Twist"],
    sizes: ["3.66m"],
  },
  {
    name: "Winter Flair",
    handle: "winter-flair",
    blurb: "Perfect your interior vision with the incredibly stylish Winter Flair. Crafted from our extremely durable and stain resistant triexta fibre, this high...",
    brand: "Godfrey Hirst",
    colours: ["Fawn Pink", "Powder White", "Cargo Beige", "Honey Glow", "Smoked Pearl", "Tapestry Beige", "Ash Grey", "Morning Grey", "Bedrock", "Dark Mushroom", "Charcoal", "Obsidian", "Blue Print", "Deep Sea", "Ocean View", "Everglades"],
    finishes: ["Cut Pile Twist"],
    sizes: ["3.66m"],
  },
  {
    name: "Velvet Appeal",
    handle: "velvet-appeal",
    blurb: "Wake up to luxury every day with Velvet Appeal. Made in Australia from our incredibly soft triexta fibre, this carpet features permanent built-in stain...",
    brand: "Godfrey Hirst",
    colours: ["Coconut", "Aged Paper", "Manuscript", "Sand Glass", "Harpe", "Alpaca", "Clean Vapour", "Ocean Air", "Silk Grey", "Silver Drop", "Frosty Touch", "Silverton", "Flooded Gum", "Soothing Grey", "Grey Concrete", "Tuscan Path", "Pond Pebble", "Grey Calm", "Night Horizon", "Metal Links", "Dark Whale", "Cornflower", "Stone Blue", "Green Crystal"],
    finishes: ["Cut Pile Twist"],
    sizes: ["3.66m"],
  },
]
