/* Vinyl Flooring product detail data.

   Specs, colours, sizes and the descriptions come from the live
   capitaltiles.com.au feed for this collection. Generated — edit the
   source data, not this file.
*/

export const VINYL_PRODUCTS = [
  {
    handle: "tranquility-5-0mm",
    name: "Tranquility 5.0mm",
    brand: "National Flooring Distributors",
    card: "/img/vinyl/tranquility-5-0mm.jpg",
    images: [
      "/img/vinyl/tranquility-5-0mm/1.jpg",
      "/img/vinyl/tranquility-5-0mm/2.jpg",
      "/img/vinyl/tranquility-5-0mm/3.jpg",
      "/img/vinyl/tranquility-5-0mm/4.jpg",
      "/img/vinyl/tranquility-5-0mm/5.jpg",
      "/img/vinyl/tranquility-5-0mm/6.jpg",
      "/img/vinyl/tranquility-5-0mm/7.jpg",
      "/img/vinyl/tranquility-5-0mm/8.jpg",
      "/img/vinyl/tranquility-5-0mm/9.jpg",
      "/img/vinyl/tranquility-5-0mm/10.jpg",
      "/img/vinyl/tranquility-5-0mm/11.jpg",
      "/img/vinyl/tranquility-5-0mm/12.jpg",
      "/img/vinyl/tranquility-5-0mm/13.jpg",
      "/img/vinyl/tranquility-5-0mm/14.jpg",
      "/img/vinyl/tranquility-5-0mm/15.jpg",
      "/img/vinyl/tranquility-5-0mm/16.jpg",
      "/img/vinyl/tranquility-5-0mm/17.jpg",
      "/img/vinyl/tranquility-5-0mm/18.jpg",
      "/img/vinyl/tranquility-5-0mm/19.jpg",
      "/img/vinyl/tranquility-5-0mm/20.jpg",
      "/img/vinyl/tranquility-5-0mm/21.jpg",
      "/img/vinyl/tranquility-5-0mm/22.jpg",
    ],
    tagline: "Luxury vinyl plank flooring in 22 colours",
    short: "Tranquility 5.0mm luxury vinyl plank flooring by National Flooring Distributors. 228mm x 1524mm planks, 5.0mm thick and 22 colours. Supplied and installed across Canberra.",
    overview: [
      "Transform your space with Tranquility Luxury Vinyl Planks, designed to bring elegance, durability, and peace of mind to any environment. Whether in a residential haven or a bustling commercial space, these planks combine stunning aesthetics with high-performance features.",
      "Crafted with a built-in acoustic backing for quieter interiors and fiberglass reinforcement for enhanced stability, Tranquility ensures long-lasting beauty and resilience. The waterproof surface makes it ideal for kitchens, bathrooms, and high-traffic areas, while the P3 slip rating provides added safety underfoot.",
      "With quick and easy installation, maintaining a stylish and practical floor has never been simpler. Plus, Tranquility is FloorScore certified, ensuring healthier indoor air quality for your home or business.",
    ],
    features: [
      "Slip Rating: P3",
      "Built-in Acoustic Backing",
      "Fibreglass Reinforcement",
      "FloorScore Certifed product",
      "Warranty: Lifetime* Residential, 15 yrs Commercial",
    ],
    seoTitle: "Tranquility 5.0mm | Capital Tiles",
    seoDesc: "Tranquility 5.0mm, 228mm x 1524mm, 5.0mm. Luxury vinyl plank flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Ashen Mist",
      "Bristle Oak",
      "Classic Teak",
      "Coastline Oak",
      "Ernest Spotted Gum",
      "Eucalypti Gum",
      "Field Oak",
      "Florence Oak",
      "Ghost Gum",
      "Hazel Oak",
      "Ivory Oak",
      "Limed Oak",
      "Magnolia Oak",
      "Pewter Oak",
      "Phantom Oak",
      "Rover Spotted Gum",
      "Samford Oak",
      "Smokey Blackbutt",
      "Stanley Oak",
      "Sterling Oak",
      "Village Blackbutt",
      "Weathered Blackbutt",
    ],
    sizes: ["228mm x 1524mm"],
    finishes: [],
    thickness: ["5.0mm"],
    slip: [],
    material: ["0.5mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Plank Size", "228mm x 1524mm"],
      ["Total Thickness", "5.0mm"],
      ["Wear Layer", "0.5mm"],
      ["AREA PER CARTON", "2.09m²"],
      ["Qty Per Carton", "6pcs"],
    ],
    rooms: [],
  },
  {
    handle: "tempess",
    name: "Tempess 4.5mm",
    brand: "National Flooring Distributors",
    card: "/img/vinyl/tempess.jpg",
    images: [
      "/img/vinyl/tempess/1.jpg",
      "/img/vinyl/tempess/2.jpg",
      "/img/vinyl/tempess/3.jpg",
      "/img/vinyl/tempess/4.jpg",
      "/img/vinyl/tempess/5.jpg",
      "/img/vinyl/tempess/6.jpg",
      "/img/vinyl/tempess/7.jpg",
      "/img/vinyl/tempess/8.jpg",
      "/img/vinyl/tempess/9.jpg",
      "/img/vinyl/tempess/10.jpg",
      "/img/vinyl/tempess/11.jpg",
      "/img/vinyl/tempess/12.jpg",
    ],
    tagline: "Luxury vinyl plank flooring in 12 colours",
    short: "Tempess 4.5mm luxury vinyl plank flooring by National Flooring Distributors. 228.6mm x 1219.2mm planks, 4.5mm thick and 12 colours. Supplied and installed across Canberra.",
    overview: [
      "Introducing Tempess Luxury Vinyl Plank, the epitome of elegance and empowerment. Tempess is an industry-leading range creating sophisticated spaces you can be proud of.",
      "Tempess was crafted to capture the timeless beauty of natural wood with unparalleled durability, ensuring that your floors remain stunning for years to come.",
      "Choose from a selection of captivating designs that seamlessly integrate with your unique style and elegantly transform any room.",
    ],
    features: [
      "Plank size: 228.6mm x 1219.2mm",
      "Thickness: 4.5mm",
      "Wear layer: 0.5mm",
      "12 colours in the range",
      "Full boards on display in the Mitchell showroom",
    ],
    seoTitle: "Tempess 4.5mm | Capital Tiles",
    seoDesc: "Tempess 4.5mm, 228.6mm x 1219.2mm, 4.5mm. Luxury vinyl plank flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Brighton Oak B1",
      "Dawn Oak D1",
      "Mature Oak M2",
      "Meadow Blackbutt M4",
      "Merryland Oak M3",
      "Moonlight Oak M1",
      "Nickle Oak N1",
      "Odyssey Tassie Oak O1",
      "Rainy Oak R1",
      "Riverstone R2",
      "Tamsyn Oak T1",
      "Western Spotted Gum W1",
    ],
    sizes: ["228.6mm x 1219.2mm"],
    finishes: [],
    thickness: ["4.5mm"],
    slip: [],
    material: ["0.5mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["PLANK SIZE", "228.6mm x 1219.2mm"],
      ["THICKNESS", "4.5mm"],
      ["WEAR LAYER", "0.5mm"],
      ["QTY PER CARTON", "10pcs"],
      ["AREA PER CARTON", "2.79m²"],
    ],
    rooms: [],
  },
  {
    handle: "sunvista-4-5mm",
    name: "Sunvista 4.5mm",
    brand: "National Flooring Distributors",
    card: "/img/vinyl/sunvista-4-5mm.jpg",
    images: [
      "/img/vinyl/sunvista-4-5mm/1.jpg",
      "/img/vinyl/sunvista-4-5mm/2.jpg",
      "/img/vinyl/sunvista-4-5mm/3.jpg",
      "/img/vinyl/sunvista-4-5mm/4.jpg",
      "/img/vinyl/sunvista-4-5mm/5.jpg",
      "/img/vinyl/sunvista-4-5mm/6.jpg",
      "/img/vinyl/sunvista-4-5mm/7.jpg",
      "/img/vinyl/sunvista-4-5mm/8.jpg",
      "/img/vinyl/sunvista-4-5mm/9.jpg",
      "/img/vinyl/sunvista-4-5mm/10.jpg",
      "/img/vinyl/sunvista-4-5mm/11.jpg",
      "/img/vinyl/sunvista-4-5mm/12.jpg",
    ],
    tagline: "Luxury vinyl plank flooring in 12 colours",
    short: "Sunvista 4.5mm luxury vinyl plank flooring by National Flooring Distributors. 177.8mm x 1219.2mm planks, 4.5mm thick and 12 colours. Supplied and installed across Canberra.",
    overview: [
      "Create a welcoming space you'll love to come home to. With effortless style, Sunvista offers excellence in artistry and design. Available in 12 of the latest colour trends, there's a tone to suit every interior.",
      "Relax with a low maintenance, water resistant floor that features the most recent advances in technology. The ever-popular Sunvista is a crowd pleaser and a truly luxurious product.",
    ],
    features: [
      "Plank size: 177.8mm x 1219.2mm",
      "Thickness: 4.5mm",
      "Wear layer: 0.5mm",
      "12 colours in the range",
      "Full boards on display in the Mitchell showroom",
    ],
    seoTitle: "Sunvista 4.5mm | Capital Tiles",
    seoDesc: "Sunvista 4.5mm, 177.8mm x 1219.2mm, 4.5mm. Luxury vinyl plank flooring supplied and installed across Canberra by Capital Tiles.",
    colours: ["13", "17", "18", "19", "73", "79", "111", "113", "131", "207", "312", "715"],
    sizes: ["177.8mm x 1219.2mm"],
    finishes: [],
    thickness: ["4.5mm"],
    slip: [],
    material: ["0.5mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Plank Size", "177.8mm x 1219.2mm"],
      ["Total Thickness", "4.5mm"],
      ["Wear Layer", "0.5mm"],
      ["AREA PER CARTON", "2.17m²"],
      ["Qty Per Carton", "10pcs"],
    ],
    rooms: [],
  },
  {
    handle: "stella-4-5mm",
    name: "Stella 4.5mm",
    brand: "National Flooring Distributors",
    card: "/img/vinyl/stella-4-5mm.jpg",
    images: [
      "/img/vinyl/stella-4-5mm/1.jpg",
      "/img/vinyl/stella-4-5mm/2.jpg",
      "/img/vinyl/stella-4-5mm/3.jpg",
      "/img/vinyl/stella-4-5mm/4.jpg",
      "/img/vinyl/stella-4-5mm/5.jpg",
      "/img/vinyl/stella-4-5mm/6.jpg",
      "/img/vinyl/stella-4-5mm/7.jpg",
      "/img/vinyl/stella-4-5mm/8.jpg",
      "/img/vinyl/stella-4-5mm/9.jpg",
      "/img/vinyl/stella-4-5mm/10.jpg",
    ],
    tagline: "Luxury vinyl plank flooring in 10 colours",
    short: "Stella 4.5mm luxury vinyl plank flooring by National Flooring Distributors. 228.6mm x 1524mm planks, 4.5mm thick and 10 colours. Supplied and installed across Canberra.",
    overview: [
      "Experience the warmth and comfort of natural timber with the resilience of Stella Luxury Vinyl Planks. Designed for families and pets, Stella withstands scratches, stains, and wear. Elevate your home with Stella Luxury Vinyl Planks and enjoy lasting beauty.",
    ],
    features: [
      "Plank size: 228.6mm x 1524mm",
      "Thickness: 4.5mm",
      "Wear layer: 0.5mm",
      "10 colours in the range",
      "Full boards on display in the Mitchell showroom",
    ],
    seoTitle: "Stella 4.5mm | Capital Tiles",
    seoDesc: "Stella 4.5mm, 228.6mm x 1524mm, 4.5mm. Luxury vinyl plank flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Ashen Oak 573",
      "Coastal Oak 552",
      "Earl Oak 553",
      "Mellow Blackbutt 557",
      "Oasis Oak 555",
      "Oyster Grey 570",
      "Regal Oak 556",
      "Seaside Oak 571",
      "Tidal Grey 561",
      "Warm Spotted Gum 572",
    ],
    sizes: ["228.6mm x 1524mm"],
    finishes: [],
    thickness: ["4.5mm"],
    slip: [],
    material: ["0.5mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["PLANK SIZE", "228.6mm x 1524mm"],
      ["THICKNESS", "4.5mm"],
      ["WEAR LAYER", "0.5mm"],
      ["QTY PER CARTON", "8pcs"],
      ["AREA PER CARTON", "2.79m²"],
    ],
    rooms: [],
  },
  {
    handle: "illusions-5mm",
    name: "Illusions 5mm",
    brand: "National Flooring Distributors",
    card: "/img/vinyl/illusions-5mm.jpg",
    images: [
      "/img/vinyl/illusions-5mm/1.jpg",
      "/img/vinyl/illusions-5mm/2.jpg",
      "/img/vinyl/illusions-5mm/3.jpg",
      "/img/vinyl/illusions-5mm/4.jpg",
      "/img/vinyl/illusions-5mm/5.jpg",
      "/img/vinyl/illusions-5mm/6.jpg",
      "/img/vinyl/illusions-5mm/7.jpg",
      "/img/vinyl/illusions-5mm/8.jpg",
      "/img/vinyl/illusions-5mm/9.jpg",
      "/img/vinyl/illusions-5mm/10.jpg",
      "/img/vinyl/illusions-5mm/11.jpg",
      "/img/vinyl/illusions-5mm/12.jpg",
      "/img/vinyl/illusions-5mm/13.jpg",
      "/img/vinyl/illusions-5mm/14.jpg",
      "/img/vinyl/illusions-5mm/15.jpg",
      "/img/vinyl/illusions-5mm/16.jpg",
      "/img/vinyl/illusions-5mm/17.jpg",
      "/img/vinyl/illusions-5mm/18.jpg",
      "/img/vinyl/illusions-5mm/19.jpg",
      "/img/vinyl/illusions-5mm/20.jpg",
      "/img/vinyl/illusions-5mm/21.jpg",
      "/img/vinyl/illusions-5mm/22.jpg",
      "/img/vinyl/illusions-5mm/23.jpg",
      "/img/vinyl/illusions-5mm/24.jpg",
    ],
    tagline: "Luxury vinyl plank flooring in 12 colours",
    short: "Illusions 5mm luxury vinyl plank flooring by National Flooring Distributors. 177.8mm x 1219.2mm planks, 5mm thick and 12 colours. Supplied and installed across Canberra.",
    overview: [
      "The ever-popular Illusions Vinyl Plank now comes in 12 fresh, new colours, ensuring the utmost in style for your home. From cool pearl tones to warm honeys and dramatic deep greys, enrich your space with timber-inspired flooring.",
      "Tough, water resistant and long lasting, Illusions is ideal for both homes and commercial areas. Designed with quietness and durability in mind, experience this luxury floor and make it your own.",
    ],
    features: [
      "Plank size: 177.8mm x 1219.2mm",
      "Thickness: 5mm",
      "Wear layer: 0.5mm",
      "Surface: Semi Wild 2",
      "Slip rating: P3",
      "12 colours in the range",
    ],
    seoTitle: "Illusions 5mm | Capital Tiles",
    seoDesc: "Illusions 5mm, 177.8mm x 1219.2mm, 5mm. Luxury vinyl plank flooring supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Ambush",
      "Ashwood",
      "Aspen",
      "Blackbutt",
      "Cinnamon Oak",
      "Dune",
      "Grey Gum",
      "Mahogany",
      "Native Spotted Gum",
      "Natural Pearl",
      "NSW Spotted Gum",
      "Urban Grey",
    ],
    sizes: ["177.8mm x 1219.2mm"],
    finishes: ["Semi Wild 2"],
    thickness: ["5mm"],
    slip: ["P3"],
    material: ["0.5mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Plank Size", "177.8mm x 1219.2mm"],
      ["Total Thickness", "5mm"],
      ["Wear Layer", "0.5mm"],
      ["M 2 Per Carton", "2.17m²"],
      ["Qty Per Carton", "10 Planks"],
      ["Slip Rating", "P3"],
      ["Surface Finish", "Semi Wild 2"],
    ],
    rooms: [],
  },
  {
    handle: "spellbound-3-0mm",
    name: "Spellbound 3.0mm",
    brand: "National Flooring Distributors",
    card: "/img/vinyl/spellbound-3-0mm.jpg",
    images: [
      "/img/vinyl/spellbound-3-0mm/1.jpg",
      "/img/vinyl/spellbound-3-0mm/2.jpg",
      "/img/vinyl/spellbound-3-0mm/3.jpg",
      "/img/vinyl/spellbound-3-0mm/4.jpg",
      "/img/vinyl/spellbound-3-0mm/5.jpg",
      "/img/vinyl/spellbound-3-0mm/6.jpg",
      "/img/vinyl/spellbound-3-0mm/7.jpg",
      "/img/vinyl/spellbound-3-0mm/8.jpg",
      "/img/vinyl/spellbound-3-0mm/9.jpg",
      "/img/vinyl/spellbound-3-0mm/10.jpg",
      "/img/vinyl/spellbound-3-0mm/11.jpg",
      "/img/vinyl/spellbound-3-0mm/12.jpg",
    ],
    tagline: "Luxury vinyl plank flooring in 12 colours",
    short: "Spellbound 3.0mm luxury vinyl plank flooring by National Flooring Distributors. 228.6mm x 1524mm planks, 3.0mm thick and 12 colours. Supplied and installed across Canberra.",
    overview: [
      "Create a sense of wonder with Spellbound Luxury Vinyl Plank. With a colour palette ranging from mythical greys to warm honeys and deep earthy tones, you'll find a tone that works like magic in your space. Combining the natural look of wood with the resilience of vinyl, Spellbound offers a divine flooring option that will enchant residents and guests alike. With a Global GreenTag certification, Spellbound is a luxury choice for homes and is commercially rated for offices, retail, hospitality and educational facilities.",
    ],
    features: ["Acoustic Test", "Slip Rating"],
    seoTitle: "Spellbound 3.0mm | Capital Tiles",
    seoDesc: "Spellbound 3.0mm, 228.6mm x 1524mm, 3.0mm. Luxury vinyl plank flooring supplied and installed across Canberra by Capital Tiles.",
    colours: ["Amulet", "Aura", "Bewitch", "Charm", "Crystal", "Divine", "Enchant", "Magic", "Merlin", "Myth", "Rune", "Wonder"],
    sizes: ["228.6mm x 1524mm"],
    finishes: [],
    thickness: ["3.0mm"],
    slip: [],
    material: ["0.5mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["PLANK SIZE", "228.6mm x 1524mm"],
      ["THICKNESS", "3.0mm"],
      ["WEAR LAYER", "0.5mm"],
      ["QTY PER CARTON", "12pcs"],
      ["AREA PER CARTON", "4.18m²"],
    ],
    rooms: [],
  },
  {
    handle: "reaction",
    name: "Reaction 2.5mm",
    brand: "National Flooring Distributors",
    card: "/img/vinyl/reaction.jpg",
    images: [
      "/img/vinyl/reaction/1.jpg",
      "/img/vinyl/reaction/2.jpg",
      "/img/vinyl/reaction/3.jpg",
      "/img/vinyl/reaction/4.jpg",
      "/img/vinyl/reaction/5.jpg",
      "/img/vinyl/reaction/6.jpg",
    ],
    tagline: "Luxury vinyl plank flooring in 6 colours",
    short: "Reaction 2.5mm luxury vinyl plank flooring by National Flooring Distributors. 228.6mm x 1219.2mm planks, 2.5mm thick and 6 colours. Supplied and installed across Canberra.",
    overview: [
      "Evoke the ultimate reaction from guests with this stylish choice in flooring. The natural embossed wood grain and matte surface finish gives an authentic feel that boasts elegance and warmth. Embrace classic and modern colour selections to create the perfect ambiance for your home.",
    ],
    features: [
      "Plank size: 228.6mm x 1219.2mm",
      "Thickness: 2.5mm",
      "Wear layer: 0.5mm",
      "6 colours in the range",
      "Full boards on display in the Mitchell showroom",
    ],
    seoTitle: "Reaction 2.5mm | Capital Tiles",
    seoDesc: "Reaction 2.5mm, 228.6mm x 1219.2mm, 2.5mm. Luxury vinyl plank flooring supplied and installed across Canberra by Capital Tiles.",
    colours: ["Coastal Blackbutt", "Highland Silver Oak", "Natural Oak", "Spotted Gum", "Tasmanian Oak", "White Rustic Oak"],
    sizes: ["228.6mm x 1219.2mm"],
    finishes: [],
    thickness: ["2.5mm"],
    slip: [],
    material: ["0.5mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["PLANK SIZE", "228.6mm x 1219.2mm"],
      ["THICKNESS", "2.5mm"],
      ["WEAR LAYER", "0.5mm"],
      ["QTY PER CARTON", "12pcs"],
      ["AREA PER CARTON", "3.345m"],
    ],
    rooms: [],
  },
  {
    handle: "cascade",
    name: "Cascade 4.5mm",
    brand: "National Flooring Distributors",
    card: "/img/vinyl/cascade.jpg",
    images: [
      "/img/vinyl/cascade/1.jpg",
      "/img/vinyl/cascade/2.jpg",
      "/img/vinyl/cascade/3.jpg",
      "/img/vinyl/cascade/4.jpg",
      "/img/vinyl/cascade/5.jpg",
      "/img/vinyl/cascade/6.jpg",
      "/img/vinyl/cascade/7.jpg",
      "/img/vinyl/cascade/8.jpg",
      "/img/vinyl/cascade/9.jpg",
      "/img/vinyl/cascade/10.jpg",
      "/img/vinyl/cascade/11.jpg",
      "/img/vinyl/cascade/12.jpg",
    ],
    tagline: "Luxury vinyl plank flooring in 12 colours",
    short: "Cascade 4.5mm luxury vinyl plank flooring by National Flooring Distributors. 228.6mm x 1524mm planks, 4.5mm thick and 12 colours. Supplied and installed across Canberra.",
    overview: [
      "Create stunning spaces with the luxurious Cascade range. Our expertly designed 'longboards' perfectly accommodate the 'less is more' trend that is sweeping the globe. Featuring unique prints inspired by natural woodgrain, your home will have a visual flow that beautifully emulates a select grade timber floor. Cascade is available in a variety of warm and welcoming tones that will instantly feel like home.",
    ],
    features: [
      "Plank size: 228.6mm x 1524mm",
      "Thickness: 4.5mm",
      "Wear layer: 0.5mm",
      "12 colours in the range",
      "Full boards on display in the Mitchell showroom",
    ],
    seoTitle: "Cascade 4.5mm | Capital Tiles",
    seoDesc: "Cascade 4.5mm, 228.6mm x 1524mm, 4.5mm. Luxury vinyl plank flooring supplied and installed across Canberra by Capital Tiles.",
    colours: ["Belmore", "Chandler", "Edith", "Gordon", "Kearney", "Murray", "Niagara", "Oaky", "Rawson", "Teviot", "Trinity", "Tully"],
    sizes: ["228.6mm x 1524mm"],
    finishes: [],
    thickness: ["4.5mm"],
    slip: [],
    material: ["0.5mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["PLANK SIZE", "228.6mm x 1524mm"],
      ["THICKNESS", "4.5mm"],
      ["WEAR LAYER", "0.5mm"],
      ["QTY PER CARTON", "8pcs"],
      ["AREA PER CARTON", "2.79m²"],
    ],
    rooms: [],
  },
  {
    handle: "calloway",
    name: "Calloway 2.0mm",
    brand: "National Flooring Distributors",
    card: "/img/vinyl/calloway.jpg",
    images: [
      "/img/vinyl/calloway/1.jpg",
      "/img/vinyl/calloway/2.jpg",
      "/img/vinyl/calloway/3.jpg",
      "/img/vinyl/calloway/4.jpg",
    ],
    tagline: "Luxury vinyl plank flooring in 4 colours",
    short: "Calloway 2.0mm luxury vinyl plank flooring by National Flooring Distributors. 228mm x 1219mm planks, 2.0mm thick and 4 colours. Supplied and installed across Canberra.",
    overview: [
      "Elevate your interiors with the sleek, sophisticated appeal of Calloway Luxury Vinyl Planks. Designed for both beauty and durability, these planks are the perfect choice for any commercial or residential setting.",
      "Calloway planks offer a high-end look that mimics the natural charm of real wood, bringing a touch of elegance to your space whilst still withstanding the rigors of daily wear and tear.",
      "The resilient surface is easy to clean and maintain, ensuring your floors always look pristine with minimal effort.",
    ],
    features: [
      "Plank size: 228mm x 1219mm",
      "Thickness: 2.0mm",
      "Wear layer: 0.2mm",
      "4 colours in the range",
      "Full boards on display in the Mitchell showroom",
    ],
    seoTitle: "Calloway 2.0mm | Capital Tiles",
    seoDesc: "Calloway 2.0mm, 228mm x 1219mm, 2.0mm. Luxury vinyl plank flooring supplied and installed across Canberra by Capital Tiles.",
    colours: ["Frontier Blackbutt", "Hudson Oak", "Isle Oak", "Junction Spotted Gum"],
    sizes: ["228mm x 1219mm"],
    finishes: [],
    thickness: ["2.0mm"],
    slip: [],
    material: ["0.2mm top layer"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["PLANK SIZE", "228mm x 1219mm"],
      ["THICKNESS", "2.0mm"],
      ["WEAR LAYER", "0.2mm"],
      ["QTY PER CARTON", "20pcs"],
      ["AREA PER CARTON", "5.57m²"],
    ],
    rooms: [],
  },
]

export function byHandle(handle) {
  return VINYL_PRODUCTS.find((p) => p.handle === handle)
}
