/* Vinyl flooring range, taken from the live capitaltiles.com.au vinyl collection:
   names, blurbs, brands and the colour / finish / size options each product
   actually ships with. */

export const VINYL = [
  {
    name: "Tranquility 5.0mm",
    handle: "tranquility-5-0mm",
    blurb: "Transform your space with Tranquility Luxury Vinyl Planks, designed to bring elegance, durability, and peace of mind to any environment. Whether in a ",
    brand: "National Flooring Distributors",
    colours: ["Tranquility - Ashen Mist", "Tranquility - Bristle Oak", "Tranquility - Classic Teak", "Tranquility - Coastline Oak", "Tranquility -Ernest Spotted Gum", "Tranquility - Eucalypti Gum", "Tranquility - Field Oak", "Tranquility - Florence Oak", "Tranquility - Ghost Gum", "Tranquility - Hazel Oak", "Tranquility - Ivory Oak", "Tranquility - Limed Oak", "Tranquility - Magnolia Oak", "Tranquility - Pewter Oak", "Tranquility - Phantom Oak", "Tranquility - Rover Spotted Gum", "Tranquility - Samford Oak", "Tranquility - Smokey Blackbutt", "Tranquility - Stanley Oak", "Tranquility - Sterling Oak", "Tranquility - Village Blackbutt", "Tranquility - Weathered Blackbutt"],
    finishes: ["Limed"],
    sizes: ["5mm"],
  },
  {
    name: "Tempess 4.5mm",
    handle: "tempess",
    blurb: "Introducing Tempess Luxury Vinyl Plank, the epitome of elegance and empowerment. Tempess is an industry-leading range creating sophisticated spaces yo",
    brand: "National Flooring Distributors",
    colours: ["Brighton Oak B1", "Dawn Oak D1", "Mature Oak M2", "Meadow Blackbutt M4", "Merryland Oak M3", "Moonlight Oak M1", "Nickle Oak N1", "Odyssey Tassie Oak O1", "Rainy Oak R1", "Riverstone R2", "Tamsyn Oak T1", "Western Spotted Gum W1"],
    finishes: [],
    sizes: ["4.5mm"],
  },
  {
    name: "Sunvista 4.5mm",
    handle: "sunvista-4-5mm",
    blurb: "Create a welcoming space you’ll love to come home to. With effortless style, Sunvista offers excellence in artistry and design. Available in 12 of the",
    brand: "National Flooring Distributors",
    colours: ["Sunvista - 13", "Sunvista - 17", "Sunvista - 18", "Sunvista - 19", "Sunvista - 73", "Sunvista - 79", "Sunvista - 111", "Sunvista - 113", "Sunvista - 131", "Sunvista - 207", "Sunvista - 312", "Sunvista - 715"],
    finishes: [],
    sizes: ["4.5mm"],
  },
  {
    name: "Stella 4.5mm",
    handle: "stella-4-5mm",
    blurb: "Experience the warmth and comfort of natural timber with the resilience of Stella Luxury Vinyl Planks. Designed for families and pets, Stella withstan",
    brand: "National Flooring Distributors",
    colours: ["Ashen Oak 573", "Coastal Oak 552", "Earl Oak 553", "Mellow Blackbutt 557", "Oasis Oak 555", "Oyster Grey 570", "Regal Oak 556", "Seaside Oak 571", "Tidal Grey 561", "Warm Spotted Gum 572"],
    finishes: [],
    sizes: ["4.5mm"],
  },
  {
    name: "Illusions 5mm",
    handle: "illusions-5mm",
    blurb: "The ever-popular Illusions Vinyl Plank now comes in 12 fresh, new colours, ensuring the utmost in style for your home. From cool pearl tones to warm h",
    brand: "National Flooring Distributors",
    colours: ["Ambush", "Ashwood", "Aspen", "Blackbutt", "Cinnamon Oak", "Dune", "Grey Gum", "Mahogany", "Native Spotted Gum", "Natural Pearl", "NSW Spotted Gum", "Urban Grey"],
    finishes: [],
    sizes: ["5mm"],
  },
  {
    name: "Spellbound 3.0mm",
    handle: "spellbound-3-0mm",
    blurb: "Create a sense of wonder with Spellbound Luxury Vinyl Plank. With a colour palette ranging from mythical greys to warm honeys and deep earthy tones, y",
    brand: "National Flooring Distributors",
    colours: ["Amulet", "Aura", "Bewitch", "Charm", "Crystal", "Divine", "Enchant", "Magic", "Merlin", "Myth", "Rune", "Wonder"],
    finishes: [],
    sizes: ["3mm"],
  },
  {
    name: "Reaction 2.5mm",
    handle: "reaction",
    blurb: "Evoke the ultimate reaction from guests with this stylish choice in flooring. The natural embossed wood grain and matte surface finish gives an authen",
    brand: "National Flooring Distributors",
    colours: ["Coastal Blackbutt", "Highland Silver Oak", "Natural Oak", "Spotted Gum", "Tasmanian Oak", "White Rustic Oak"],
    finishes: ["Matt", "Embossed"],
    sizes: ["2.5mm"],
  },
  {
    name: "Cascade 4.5mm",
    handle: "cascade",
    blurb: "Create stunning spaces with the luxurious Cascade range. Our expertly designed 'longboards' perfectly accommodate the 'less is more' trend that is swe",
    brand: "National Flooring Distributors",
    colours: ["Belmore", "Chandler", "Edith", "Gordon", "Kearney", "Murray", "Niagara", "Oaky", "Rawson", "Teviot", "Trinity", "Tully"],
    finishes: ["Select Grade"],
    sizes: ["4.5mm"],
  },
  {
    name: "Calloway 2.0mm",
    handle: "calloway",
    blurb: "Elevate your interiors with the sleek, sophisticated appeal of Calloway Luxury Vinyl Planks. Designed for both beauty and durability, these planks are",
    brand: "National Flooring Distributors",
    colours: ["Frontier Blackbutt", "Hudson Oak", "Isle Oak", "Junction Spotted Gum"],
    finishes: [],
    sizes: ["2mm"],
  },
]
