/* Wool carpet range, taken from the live capitaltiles.com.au wool collection:
   names, blurbs, brands and the colour / finish / size options each product
   actually ships with. */

export const WOOL = [
  {
    name: "Caribbean",
    handle: "caribbean",
    blurb: "Caribbean is a level loop wool carpet that provides style, durability and stain resistance to your floor. This level loop pile carpet's intricate desi",
    brand: "God Freyhirst",
    colours: ["Havana", "Bahamas", "Aruba", "San Juan", "Santiago"],
    finishes: ["Level Loop", "Loop Pile"],
    sizes: [],
  },
  {
    name: "Pegasus",
    handle: "pegasus",
    blurb: "Pegasus seamlessly combines aesthetic appeal with functional excellence, serving as a natural insulator for any space. Beyond its visually striking de",
    brand: "God Freyhirst",
    colours: ["Orpheus", "Medusa", "Perseus", "Ares", "Zeus"],
    finishes: ["Cut Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Chatsworth",
    handle: "chatsworth",
    blurb: "Chatsworth is a beautiful chunky loop pile carpet in natural earthy tone shades, making it a focal point in your home. Made in Australia, its tactile ",
    brand: "God Freyhirst",
    colours: ["Talman", "Bakewell", "Devonshire", "Cavendish", "Shrewsbury", "Thompson", "Sir William", "Derwent", "Archer"],
    finishes: ["Level Loop", "Loop Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Petra",
    handle: "petra",
    blurb: "Inspired by the hand-hewn caves and temples carved from ancient Jordanian desert sandstone, Petra promises raw beauty and earthy charm. The wool low-l",
    brand: "God Freyhirst",
    colours: ["Corinthian", "Damascus", "Bedouin", "Renaissance", "Obelisk", "Parapet", "Jordan", "Fortress"],
    finishes: ["Level Loop", "Loop Pile"],
    sizes: [],
  },
  {
    name: "Vintage Grace",
    handle: "vintage-grace",
    blurb: "Superbly crafted from wool and proudly Australian Made, Vintage Grace is a stunning new release from Hycraft. The rustic and highly textural chunky lo",
    brand: "God Freyhirst",
    colours: ["Tweed", "Suede", "Calico", "Pearl", "Taffeta", "Burlap", "Ticking", "Ebony"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Queenstwist",
    handle: "queenstwist",
    blurb: "A stunning range of cut pile twist wool carpet for all seasons. Its twisted yarns create a textured surface, enhancing comfort and resilience. This ca",
    brand: "God Freyhirst",
    colours: ["Ecru", "Riversand", "Balsa Stone", "Jarrah", "Merbau", "Silver", "Dove Grey", "Zodiac", "Michelin", "Nightsky", "Musket"],
    finishes: ["Cut Pile", "Twist", "Textured"],
    sizes: [],
  },
  {
    name: "Trinidad",
    handle: "trinidad",
    blurb: "Enjoy this beautiful textured level loop carpet. Trinidad is beautifully soft underfoot and the wool properties help to keep your space cooler in summ",
    brand: "God Freyhirst",
    colours: ["Matelot", "Maracas Bay", "La Brea"],
    finishes: ["Level Loop", "Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Carramar 4M",
    handle: "carramar-4m",
    blurb: "This luxury designer wool carpet delivers a superb modern foundation for contemporary styling. Crafted from beautiful wool, this 4 metre wide close te",
    brand: "God Freyhirst",
    colours: ["Sea Pearl", "Coastal Dune", "Buckwheat", "Avalanche", "Oyster Shell", "Dove Grey", "Winter Mist", "Evening Grey", "Coal Ash", "Aged Pewter", "Mulch", "Industrial Grey"],
    finishes: ["Level Loop", "Loop Pile", "Textured"],
    sizes: ["4m wide"],
  },
  {
    name: "Luxury Living",
    handle: "luxury-living",
    blurb: "Encapsulating the hallmarks of an aspirational lifestyle, Luxury Living, a new, elegantly textured 100% wool carpet from Hycraft, teams quality, comfo",
    brand: "God Freyhirst",
    colours: ["Lavish", "Classic", "Sumptious", "Marble", "Ornate", "Modern", "Silhouette"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Tranquil Texture",
    handle: "tranquil-texture",
    blurb: "Tranquil Texture, a stylish artisan wool carpet from Hycraft, takes inspiration from the places that bring us peace and happiness. The chunky textured",
    brand: "God Freyhirst",
    colours: ["Ocean Sand", "Mountain Ranges", "Tropical Oasis", "Springtime", "Summer Rain", "Country Retreat", "Lake House"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Montrose",
    handle: "montrose",
    blurb: "Montrose features a rustic chunky textured loop pile, creating a pebbled effect that adds handcrafted charm and character to contemporary living space",
    brand: "God Freyhirst",
    colours: ["Saratoga", "Gindera", "Mallard", "Borrowfield", "Del Mar", "Langley", "Belmont", "Rosehill"],
    finishes: ["Loop Pile", "Textured"],
    sizes: [],
  },
  {
    name: "Grand Luxury",
    handle: "grand-luxury",
    blurb: "Making a design statement has never been easier with magnificent Grand Luxury carpet. Created from gorgeous wool in a classic cut pile twist with subt",
    brand: "God Freyhirst",
    colours: ["Raw Cotton", "Almond Beige", "Savannah", "Dusty Plain", "Grainger", "Stonewashed", "Gun Metal", "Greywacke"],
    finishes: ["Cut Pile", "Twist", "Textured"],
    sizes: [],
  },
  {
    name: "Pebble Grid 4M",
    handle: "pebble-grid-4m",
    blurb: "Our ever popular Pebble Grid is now available in a practical 4 metre width. Pebble Grid’s sophisticated latticed pattern draws the eye, creating an il",
    brand: "God Freyhirst",
    colours: ["Calcite", "Sandstone", "Gypsum", "Borax", "Fieldspace", "Kimberlite", "Shale", "Basalt", "Dolomite", "Bauxite"],
    finishes: ["Level Loop", "Loop Pile"],
    sizes: ["4m wide"],
  },
  {
    name: "Ravine 4M",
    handle: "ravine-4m",
    blurb: "A stunning and versatile range of carpet for all seasons, Ravine 4M will sustain luxurious comfort all year round. This textured loop pile carpet enha",
    brand: "God Freyhirst",
    colours: ["Oatmeal", "Crevice", "Cobblestone", "Stonewall", "Smokey Ash", "Fissure", "Pewter", "Tussock", "Stone Haze"],
    finishes: ["Loop Pile", "Textured"],
    sizes: ["4m wide"],
  },
  {
    name: "Bellavista",
    handle: "bellavista",
    blurb: "Create your own beautiful interior view with Bellavista, a sumptuously soft wool carpet. A cut pile twist with random textured finish, the natural woo",
    brand: "God Freyhirst",
    colours: ["Bohemia", "Pebble Bay", "Murray River", "Satay", "Market Place", "Asteroid", "School Grey", "Pewter", "Deep Space", "Stone Age"],
    finishes: ["Cut Pile", "Twist", "Textured"],
    sizes: [],
  },
  {
    name: "Odyssey",
    handle: "odyssey",
    blurb: "Odyssey seamlessly blends style with practicality, acting as a natural insulator for any living space. Beyond its captivating design, the inherent qua",
    brand: "God Freyhirst",
    colours: ["Argos", "Penelope", "Trojan", "Sparta", "Stella"],
    finishes: ["Cut Pile", "Plush"],
    sizes: [],
  },
  {
    name: "Regency Twist",
    handle: "regency-twist",
    blurb: "The soft wool fibres of Regency Twist provide luxury underfoot with its luxurious texture, adding elegance and warmth while elevating the overall ambi",
    brand: "God Freyhirst",
    colours: ["Almond", "Vintage Stone", "Linen", "Fur", "Montego", "Obelisk", "Steel", "Zinc", "Enchanted", "Cashmere"],
    finishes: ["Cut Pile", "Twist"],
    sizes: [],
  },
  {
    name: "Enchant",
    handle: "enchant",
    blurb: "Indulge in luxury with our exquisite 100% wool carpet, Enchant. Crafted for unparalleled comfort and durability, its plush texture and timeless design",
    brand: "God Freyhirst",
    colours: ["Raw Cotton", "Almond Beige", "Puddle", "Dusty Plain", "Woodland", "Pelaco", "Stonewashed", "Concrete", "Midnight Blue", "Greywacke"],
    finishes: ["Cut Pile", "Twist", "Plush"],
    sizes: [],
  },
  {
    name: "Dawson Falls",
    handle: "dawson-falls",
    blurb: "Dawson Falls, our luxurious pure wool carpet, redefines elegance with its refined linear pattern and stunning colour palette, bringing timeless style ",
    brand: "EC carpets",
    colours: ["Meadow 5403", "Canyon 5417", "Sunlit 5454", "Serenity 5447", "Summit 5445", "Cascade 5423", "Mist 5428", "Frosted 5488", "Harmony 5411"],
    finishes: [],
    sizes: [],
  },
  {
    name: "Elmsford",
    handle: "elmsford",
    blurb: "Elmsford is a premium 100% New Zealand wool loop carpet, where natural warmth meets considered design. Its offset, organic pattern introduces a quiet,",
    brand: "EC carpets",
    colours: ["Clara 5801", "Birley 5802", "Rowden 5803", "Caden 5804", "Magnor 5805", "Nox 5806", "Solmorra 5807", "Oakmere 5808", "Garnet 5809"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Hause",
    handle: "hause",
    blurb: "A modern take on classic Berber, this premium 100% New Zealand wool carpet offers elegance and practicality with its neutral heathered colours effortl",
    brand: "EC carpets",
    colours: ["Three 5003", "Seventeen 5017", "Fifty Four 5054", "Forty Seven 5047", "Forty Five 5045", "Twenty Three 5023", "Twenty EIGHT 5028", "Eighty Eight 5088", "Eleven 5011"],
    finishes: ["Twist"],
    sizes: [],
  },
  {
    name: "Sirocco",
    handle: "sirocco",
    blurb: "Sirocco is an entry-level wool loop pile carpet crafted from 100% pure wool, offering natural comfort and everyday practicality. Inspired by the class",
    brand: "EC carpets",
    colours: ["Desert Clay 5917", "Barley Sand 5954", "Argan Spice 5947", "Market Bazaar 5945", "Quarry Mist 5923", "Cinder Stone 5928", "Basalt Dune 5988"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Cotswolds",
    handle: "cotswolds",
    blurb: "Cotswolds is a premium 100% New Zealand wool loop carpet that brings architectural confidence to the floor. Its geometric loop pattern delivers a stru",
    brand: "EC carpets",
    colours: ["Willowby 6001", "Alderwick 6002", "Fallow 6003", "Thornleigh 6004", "Millthorpe 6005", "Hollowmere 6006", "Kingswell 6007", "Hazelwood 6008", "Maplehurst 6009"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
  {
    name: "Bahamas",
    handle: "bahamas",
    blurb: "rafted from 100% New Zealand Wool, Bahamas offers a rustic, sisal-inspired loop. This timeless colour palette comes in natural earthy tones, suitable ",
    brand: "EC carpets",
    colours: ["Caribbean 5705", "Grenada 5706", "Barbados 5707", "Cayman 5704", "Cuba 5701", "Jamaica 5703", "Nevis 5702"],
    finishes: ["Loop Pile"],
    sizes: [],
  },
]
