/* Wool Carpet product detail data.

   Style, fibre, roll width, thickness, ratings and the descriptions come
   from the live capitaltiles.com.au feed for this collection. Generated —
   edit the source data, not this file.
*/

export const WOOL_PRODUCTS = [
  {
    handle: "caribbean",
    name: "Caribbean",
    brand: "Godfrey Hirst",
    card: "/img/wool/caribbean.jpg",
    images: [
      "/img/wool/caribbean/1.jpg",
      "/img/wool/caribbean/2.jpg",
      "/img/wool/caribbean/3.jpg",
      "/img/wool/caribbean/4.jpg",
      "/img/wool/caribbean/5.jpg",
      "/img/wool/caribbean/6.jpg",
    ],
    tagline: "Wool carpet in 5 colours",
    short: "Caribbean Wool Carpet by Godfrey Hirst. Level loop pile, 3.66m roll width and 5 colours. Supplied and laid across Canberra.",
    overview: [
      "Caribbean is a level loop Wool Carpet that provides style, durability and stain resistance to your floor. This Level Loop Pile carpet's intricate design and luxurious texture creates a cosy ambience, infusing the room with warmth. Its stunning pattern and texture adds depth and dimension to your interior design.",
      "Made in New Zealand Declare® Red List Free ECS Level 4 Residential Extra Heavy Duty & Stairs 5 Star Contract Medium Duty - 2 Star 15 Year Hycraft Limited Residential Warranty ISO 9001 Quality Management System ISO 14001 Environment Management System Natural Fibre Fire Rated Carpet Level Loop Pile Mid Range",
    ],
    features: [
      "Made in New Zealand",
      "Declare® Red List Free",
      "ECS Level 4",
      "Residential Extra Heavy Duty & Stairs 5 Star",
      "Contract Medium Duty - 2 Star",
      "15 Year Hycraft Limited Residential Warranty",
    ],
    seoTitle: "Caribbean | Capital Tiles",
    seoDesc: "Caribbean, Level Loop Pile, 5 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Havana", "Bahamas", "Aruba", "San Juan", "Santiago"],
    sizes: ["3.66m"],
    finishes: ["Level Loop Pile"],
    thickness: ["11 (+/- 1)mm"],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Level Loop Pile"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "Wool"],
      ["Gauge", "12.6/10cm (5/16th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "11 (+/- 1)mm"],
      ["Pile Height", "8 (+/- 1)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "5"],
    ],
    rooms: [],
  },
  {
    handle: "pegasus",
    name: "Pegasus",
    brand: "Godfrey Hirst",
    card: "/img/wool/pegasus.jpg",
    images: [
      "/img/wool/pegasus/1.jpg",
      "/img/wool/pegasus/2.jpg",
      "/img/wool/pegasus/3.jpg",
      "/img/wool/pegasus/4.jpg",
      "/img/wool/pegasus/5.jpg",
      "/img/wool/pegasus/6.jpg",
    ],
    tagline: "Wool carpet in 5 colours",
    short: "Pegasus Wool Carpet by Godfrey Hirst. Cut pile plush, 3.66m roll width and 5 colours. Supplied and laid across Canberra.",
    overview: [
      "Pegasus seamlessly combines aesthetic appeal with functional excellence, serving as a natural insulator for any space. Beyond its visually striking design, the inherent properties of wool create an insulating barrier, retaining warmth in colder seasons and maintaining a cool atmosphere during warmer months. Pegasus becomes more than a stylish design element; it transforms into a foundation for cosiness and elegance in every room. Embracing the inherent qualities of wool, it enriches living spaces with both visual allure and thermal comfort.",
      "Made in New Zealand Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty ISO 9001 Quality Management System ISO 14001 Environment Management System Natural Fibre Fire Rated Carpet Cut Pile Plush Premium",
    ],
    features: [
      "Made in New Zealand",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty",
    ],
    seoTitle: "Pegasus | Capital Tiles",
    seoDesc: "Pegasus, Cut Pile Plush, 5 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Orpheus", "Medusa", "Perseus", "Ares", "Zeus"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Plush"],
    thickness: ["13.5 (+/- 1)mm"],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Plush"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "80% Wool / 20% Synthetic"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "13.5 (+/- 1)mm"],
      ["Pile Height", "10.5 (+/- 1)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "5"],
    ],
    rooms: [],
  },
  {
    handle: "chatsworth",
    name: "Chatsworth",
    brand: "Godfrey Hirst",
    card: "/img/wool/chatsworth.jpg",
    images: [
      "/img/wool/chatsworth/1.jpg",
      "/img/wool/chatsworth/2.jpg",
      "/img/wool/chatsworth/3.jpg",
      "/img/wool/chatsworth/4.jpg",
      "/img/wool/chatsworth/5.jpg",
      "/img/wool/chatsworth/6.jpg",
      "/img/wool/chatsworth/7.jpg",
      "/img/wool/chatsworth/8.jpg",
      "/img/wool/chatsworth/9.jpg",
    ],
    tagline: "Wool carpet in 9 colours",
    short: "Chatsworth Wool Carpet by Godfrey Hirst. Level loop pile, 3.66m roll width and 9 colours. Supplied and laid across Canberra.",
    overview: [
      "Chatsworth is a beautiful chunky loop pile carpet in natural earthy tone shades, making it a focal point in your home. Made in Australia, its tactile charm is irresistible, offering a plush and luxurious feel underfoot. Embraced for its unique texture, this carpet transforms living spaces, infusing a modern aesthetic while providing a tactile experience that redefines comfort.",
      "Godfrey Hirst Best Seller Australian Made Residential Extra Heavy Duty & Stairs-6 Star Contract Medium Duty 2 Star ISO 9001 Quality Management System ISO 14001 Environment Management System 15 Year Hycraft Limited Residential Warranty Natural Fibre Fire Rated Carpet Level Loop Pile Premium Declare® Red List Free ECS Level 4+",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Australian Made",
      "Residential Extra Heavy Duty & Stairs-6 Star",
      "Contract Medium Duty 2 Star",
      "ISO 9001 Quality Management System",
      "ISO 14001 Environment Management System",
    ],
    seoTitle: "Chatsworth | Capital Tiles",
    seoDesc: "Chatsworth, Level Loop Pile, 9 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Talman", "Bakewell", "Devonshire", "Cavendish", "Shrewsbury", "Thompson", "Sir William", "Derwent", "Archer"],
    sizes: ["3.66m"],
    finishes: ["Level Loop Pile"],
    thickness: ["12.5 (+/- 1.0)mm"],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Level Loop Pile"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "Wool"],
      ["Gauge", "10.5/10cm (3/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "12.5 (+/- 1.0)mm"],
      ["Pile Height", "9.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "9"],
    ],
    rooms: [],
  },
  {
    handle: "petra",
    name: "Petra",
    brand: "Godfrey Hirst",
    card: "/img/wool/petra.jpg",
    images: [
      "/img/wool/petra/1.jpg",
      "/img/wool/petra/2.jpg",
      "/img/wool/petra/3.jpg",
      "/img/wool/petra/4.jpg",
      "/img/wool/petra/5.jpg",
      "/img/wool/petra/6.jpg",
      "/img/wool/petra/7.jpg",
      "/img/wool/petra/8.jpg",
      "/img/wool/petra/9.jpg",
    ],
    tagline: "Wool carpet in 8 colours",
    short: "Petra Wool Carpet by Godfrey Hirst. Level loop pile, 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Inspired by the hand-hewn caves and temples carved from ancient Jordanian desert sandstone, Petra promises raw beauty and earthy charm. The wool low-Level Loop Pile creates a distinct uniform texture that won't show tracks, making it an inspired choice for high traffic rooms.",
      "Australian Made Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4+ 15 Year Hycraft Limited Residential Warranty Natural Fibre Fire Rated Carpet Level Loop Pile Premium",
    ],
    features: [
      "Australian Made",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4+",
      "15 Year Hycraft Limited Residential Warranty",
    ],
    seoTitle: "Petra | Capital Tiles",
    seoDesc: "Petra, Level Loop Pile, 8 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Corinthian", "Damascus", "Bedouin", "Renaissance", "Obelisk", "Parapet", "Jordan", "Fortress"],
    sizes: ["3.66m"],
    finishes: ["Level Loop Pile"],
    thickness: ["12.5 (+/- 1.0)mm"],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Level Loop Pile"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "Wool"],
      ["Gauge", "10.5/10cm (3/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "12.5 (+/- 1.0)mm"],
      ["Pile Height", "9.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "9"],
    ],
    rooms: [],
  },
  {
    handle: "vintage-grace",
    name: "Vintage Grace",
    brand: "Godfrey Hirst",
    card: "/img/wool/vintage-grace.jpg",
    images: [
      "/img/wool/vintage-grace/1.jpg",
      "/img/wool/vintage-grace/2.jpg",
      "/img/wool/vintage-grace/3.jpg",
      "/img/wool/vintage-grace/4.jpg",
      "/img/wool/vintage-grace/5.jpg",
      "/img/wool/vintage-grace/6.jpg",
      "/img/wool/vintage-grace/7.jpg",
      "/img/wool/vintage-grace/8.jpg",
    ],
    tagline: "Wool carpet in 8 colours",
    short: "Vintage Grace Wool Carpet by Godfrey Hirst. 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Superbly crafted from wool and proudly Australian Made, Vintage Grace is a stunning new release from Hycraft. The rustic and highly textural chunky loop, a tactile ode to Celtic charm, delivers the perfect marriage of comfort and durability.",
      "Australian Made Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Premium Declare® Red List Free Wear Resistance Fire Rated Carpet Textured Loop Pile",
    ],
    features: [
      "Australian Made",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
      "Natural Fibre",
    ],
    seoTitle: "Vintage Grace | Capital Tiles",
    seoDesc: "Vintage Grace, 8 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Tweed", "Suede", "Calico", "Pearl", "Taffeta", "Burlap", "Ticking", "Ebony"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: ["16.5 (+/- 1.0)mm"],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Wool Carpet"],
      ["Yarn", "Wool"],
      ["Gauge", "10.5/10cm (3/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "16.5 (+/- 1.0)mm"],
      ["Pile Height", "13.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "queenstwist",
    name: "Queenstwist",
    brand: "Godfrey Hirst",
    card: "/img/wool/queenstwist.jpg",
    images: [
      "/img/wool/queenstwist/1.jpg",
      "/img/wool/queenstwist/2.jpg",
      "/img/wool/queenstwist/3.jpg",
      "/img/wool/queenstwist/4.jpg",
      "/img/wool/queenstwist/5.jpg",
      "/img/wool/queenstwist/6.jpg",
      "/img/wool/queenstwist/7.jpg",
      "/img/wool/queenstwist/8.jpg",
      "/img/wool/queenstwist/9.jpg",
      "/img/wool/queenstwist/10.jpg",
      "/img/wool/queenstwist/11.jpg",
    ],
    tagline: "Wool carpet in 11 colours",
    short: "Queenstwist Wool Carpet by Godfrey Hirst. 3.66m roll width and 11 colours. Supplied and laid across Canberra.",
    overview: [
      "A stunning range of cut pile twist Wool Carpet for all seasons. Its twisted yarns create a textured surface, enhancing comfort and resilience. This carpet serves as a versatile foundation for interior design, offering warmth, style, and adaptability to various decor schemes. Queenstwist carpet will sustain luxurious comfort all year round.",
      "Made in New Zealand Residential Extra Heavy Duty & Stairs - 6 Star Contract Heavy Duty - 3 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Cut Pile Twist Premium Declare® Red List Free",
    ],
    features: [
      "Made in New Zealand",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Heavy Duty - 3 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
      "Natural Fibre",
    ],
    seoTitle: "Queenstwist | Capital Tiles",
    seoDesc: "Queenstwist, 11 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Ecru", "Riversand", "Balsa Stone", "Jarrah", "Merbau", "Silver", "Dove Grey", "Zodiac", "Michelin", "Nightsky", "Musket"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: ["13 (+/- 1.0)mm"],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "Wool"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "13 (+/- 1.0)mm"],
      ["Pile Height", "10 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "11"],
    ],
    rooms: [],
  },
  {
    handle: "trinidad",
    name: "Trinidad",
    brand: "Godfrey Hirst",
    card: "/img/wool/trinidad.jpg",
    images: ["/img/wool/trinidad/1.jpg", "/img/wool/trinidad/2.jpg", "/img/wool/trinidad/3.jpg"],
    tagline: "Wool carpet in 3 colours",
    short: "Trinidad Wool Carpet by Godfrey Hirst. 3.66m roll width and 3 colours. Supplied and laid across Canberra.",
    overview: [
      "Enjoy this beautiful textured level loop carpet. Trinidad is beautifully soft underfoot and the wool properties help to keep your space cooler in summer and warmer in winter. Its simplicity enhances the overall aesthetic, offering a versatile foundation for diverse interior styles. Trinidad's subtle beauty lies in its ability to elevate any room effortlessly.",
      "Made in New Zealand 15 Year Hycraft Limited Residential Warranty* Residential Extra Heavy Duty & Stairs - 6 Star Contract Heavy Duty - 3 Star ECS Level 4 ISO 9001 Quality Management System ISO 14001 Environment Management System Fire Rated Carpet Natural Fibre Mid Range Declare® Red List Free Textured Loop Pile",
    ],
    features: [
      "Made in New Zealand",
      "15 Year Hycraft Limited Residential Warranty*",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Heavy Duty - 3 Star",
      "ECS Level 4",
      "ISO 9001 Quality Management System",
    ],
    seoTitle: "Trinidad | Capital Tiles",
    seoDesc: "Trinidad, 3 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Matelot", "Maracas Bay", "La Brea"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Wool"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "10 (+/- 1.0)mm"],
      ["Pile Height", "7 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "3"],
    ],
    rooms: [],
  },
  {
    handle: "carramar-4m",
    name: "Carramar 4M",
    brand: "Godfrey Hirst",
    card: "/img/wool/carramar-4m.jpg",
    images: [
      "/img/wool/carramar-4m/1.jpg",
      "/img/wool/carramar-4m/2.jpg",
      "/img/wool/carramar-4m/3.jpg",
      "/img/wool/carramar-4m/4.jpg",
      "/img/wool/carramar-4m/5.jpg",
      "/img/wool/carramar-4m/6.jpg",
      "/img/wool/carramar-4m/7.jpg",
      "/img/wool/carramar-4m/8.jpg",
      "/img/wool/carramar-4m/9.jpg",
      "/img/wool/carramar-4m/10.jpg",
      "/img/wool/carramar-4m/11.jpg",
      "/img/wool/carramar-4m/12.jpg",
    ],
    tagline: "Wool carpet in 12 colours",
    short: "Carramar 4M Wool Carpet by Godfrey Hirst. Level loop pile, 4.00m roll width and 12 colours. Supplied and laid across Canberra.",
    overview: [
      "This luxury designer Wool Carpet delivers a superb modern foundation for contemporary styling. Crafted from beautiful wool, this 4 metre wide close textured level loop is available in a selection of sophisticated neutrals, Carramar delivers on incredible durability and perfect style.",
      "Godfrey Hirst Best Seller Made in New Zealand Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Level Loop Pile Mid Range Declare® Red List Free",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Made in New Zealand",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
    ],
    seoTitle: "Carramar 4M | Capital Tiles",
    seoDesc: "Carramar 4M, Level Loop Pile, 12 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Sea Pearl",
      "Coastal Dune",
      "Buckwheat",
      "Avalanche",
      "Oyster Shell",
      "Dove Grey",
      "Winter Mist",
      "Evening Grey",
      "Coal Ash",
      "Aged Pewter",
      "Mulch",
      "Industrial Grey",
    ],
    sizes: ["4.00m"],
    finishes: ["Level Loop Pile"],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Level Loop Pile"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Wool"],
      ["Gauge", "15.7/10cm (1/4th Gauge)"],
      ["Roll Width", "4.00m"],
      ["Total Product Thickness", "10 (+/- 1.0)mm"],
      ["Pile Height", "7 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "12"],
    ],
    rooms: [],
  },
  {
    handle: "luxury-living",
    name: "Luxury Living",
    brand: "Godfrey Hirst",
    card: "/img/wool/luxury-living.jpg",
    images: [
      "/img/wool/luxury-living/1.jpg",
      "/img/wool/luxury-living/2.jpg",
      "/img/wool/luxury-living/3.jpg",
      "/img/wool/luxury-living/4.jpg",
      "/img/wool/luxury-living/5.jpg",
      "/img/wool/luxury-living/6.jpg",
      "/img/wool/luxury-living/7.jpg",
    ],
    tagline: "Wool carpet in 7 colours",
    short: "Luxury Living Wool Carpet by Godfrey Hirst. 4.00m roll width and 7 colours. Supplied and laid across Canberra.",
    overview: [
      "Encapsulating the hallmarks of an aspirational lifestyle, Luxury Living, a new, elegantly textured 100% Wool Carpet from Hycraft, teams quality, comfort and elegance, with remarkable high performance. The linear loop pile, available in eight rich neutrals, delivers the perfect base.",
      "Made in New Zealand Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Premium Declare® Red List Free Textured Loop Pile",
    ],
    features: [
      "Made in New Zealand",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
      "Natural Fibre",
    ],
    seoTitle: "Luxury Living | Capital Tiles",
    seoDesc: "Luxury Living, 7 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Lavish", "Classic", "Sumptious", "Marble", "Ornate", "Modern", "Silhouette"],
    sizes: ["4.00m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Wool"],
      ["Gauge", "15.7/10cm (1/4th Gauge)"],
      ["Roll Width", "4.00m"],
      ["Total Product Thickness", "10.5 (+/- 1.0)mm"],
      ["Pile Height", "7.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "1.2cm (w) x 0.8cm (l)"],
      ["Colours", "7"],
    ],
    rooms: [],
  },
  {
    handle: "tranquil-texture",
    name: "Tranquil Texture",
    brand: "Godfrey Hirst",
    card: "/img/wool/tranquil-texture.jpg",
    images: [
      "/img/wool/tranquil-texture/1.jpg",
      "/img/wool/tranquil-texture/2.jpg",
      "/img/wool/tranquil-texture/3.jpg",
      "/img/wool/tranquil-texture/4.jpg",
      "/img/wool/tranquil-texture/5.jpg",
      "/img/wool/tranquil-texture/6.jpg",
      "/img/wool/tranquil-texture/7.jpg",
    ],
    tagline: "Wool carpet in 7 colours",
    short: "Tranquil Texture Wool Carpet by Godfrey Hirst. 3.66m roll width and 7 colours. Supplied and laid across Canberra.",
    overview: [
      "Tranquil Texture, a stylish artisan Wool Carpet from Hycraft, takes inspiration from the places that bring us peace and happiness. The chunky textured loop is silky soft, super resilient and comes in eight inspired neutral shades.",
      "Australian Made Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Premium Declare® Red List Free Textured Loop Pile",
    ],
    features: [
      "Australian Made",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
      "Natural Fibre",
    ],
    seoTitle: "Tranquil Texture | Capital Tiles",
    seoDesc: "Tranquil Texture, 7 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Ocean Sand", "Mountain Ranges", "Tropical Oasis", "Springtime", "Summer Rain", "Country Retreat", "Lake House"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Wool Carpet"],
      ["Yarn", "Wool"],
      ["Gauge", "10.5/10cm (3/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "16.5 (+/- 1.0)mm"],
      ["Pile Height", "13.5 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "7"],
    ],
    rooms: [],
  },
  {
    handle: "montrose",
    name: "Montrose",
    brand: "Godfrey Hirst",
    card: "/img/wool/montrose.jpg",
    images: [
      "/img/wool/montrose/1.jpg",
      "/img/wool/montrose/2.jpg",
      "/img/wool/montrose/3.jpg",
      "/img/wool/montrose/4.jpg",
      "/img/wool/montrose/5.jpg",
      "/img/wool/montrose/6.jpg",
      "/img/wool/montrose/7.jpg",
      "/img/wool/montrose/8.jpg",
    ],
    tagline: "Wool carpet in 8 colours",
    short: "Montrose Wool Carpet by Godfrey Hirst. 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Montrose features a rustic chunky textured loop pile, creating a pebbled effect that adds handcrafted charm and character to contemporary living spaces. Meticulously crafted from high-quality wool, Montrose is available in a selection of modern earthy colours.",
      "Australian Made Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Premium Declare® Red List Free Textured Loop Pile",
    ],
    features: [
      "Australian Made",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
      "Natural Fibre",
    ],
    seoTitle: "Montrose | Capital Tiles",
    seoDesc: "Montrose, 8 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Saratoga", "Gindera", "Mallard", "Borrowfield", "Del Mar", "Langley", "Belmont", "Rosehill"],
    sizes: ["3.66m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Wool Carpet"],
      ["Yarn", "Wool"],
      ["Gauge", "10.5/10cm (3/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "14 (+/- 1.0)mm"],
      ["Pile Height", "11 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "grand-luxury",
    name: "Grand Luxury",
    brand: "Godfrey Hirst",
    card: "/img/wool/grand-luxury.jpg",
    images: [
      "/img/wool/grand-luxury/1.jpg",
      "/img/wool/grand-luxury/2.jpg",
      "/img/wool/grand-luxury/3.jpg",
      "/img/wool/grand-luxury/4.jpg",
      "/img/wool/grand-luxury/5.jpg",
      "/img/wool/grand-luxury/6.jpg",
      "/img/wool/grand-luxury/7.jpg",
      "/img/wool/grand-luxury/8.jpg",
    ],
    tagline: "Wool carpet in 8 colours",
    short: "Grand Luxury Wool Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 8 colours. Supplied and laid across Canberra.",
    overview: [
      "Making a design statement has never been easier with magnificent Grand Luxury carpet. Created from gorgeous wool in a classic Cut Pile Twist with subtle tonal fleck, the tight textured finish discourages footprints, creating a polished and elegant look in every room.",
      "Made in New Zealand Residential Extra Heavy Duty & Stairs - 6 Star Contract Heavy Duty - 3 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Cut Pile Twist Premium Declare® Red List Free",
    ],
    features: [
      "Made in New Zealand",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Heavy Duty - 3 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
      "Natural Fibre",
    ],
    seoTitle: "Grand Luxury | Capital Tiles",
    seoDesc: "Grand Luxury, Cut Pile Twist, 8 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Raw Cotton", "Almond Beige", "Savannah", "Dusty Plain", "Grainger", "Stonewashed", "Gun Metal", "Greywacke"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Wool"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "15 (+/- 1.0)mm"],
      ["Pile Height", "12 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "8"],
    ],
    rooms: [],
  },
  {
    handle: "pebble-grid-4m",
    name: "Pebble Grid 4M",
    brand: "Godfrey Hirst",
    card: "/img/wool/pebble-grid-4m.jpg",
    images: [
      "/img/wool/pebble-grid-4m/1.jpg",
      "/img/wool/pebble-grid-4m/2.jpg",
      "/img/wool/pebble-grid-4m/3.jpg",
      "/img/wool/pebble-grid-4m/4.jpg",
      "/img/wool/pebble-grid-4m/5.jpg",
      "/img/wool/pebble-grid-4m/6.jpg",
      "/img/wool/pebble-grid-4m/7.jpg",
      "/img/wool/pebble-grid-4m/8.jpg",
      "/img/wool/pebble-grid-4m/9.jpg",
      "/img/wool/pebble-grid-4m/10.jpg",
    ],
    tagline: "Wool carpet in 10 colours",
    short: "Pebble Grid 4M Wool Carpet by Godfrey Hirst. Level loop pile, 4.00m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Our ever popular Pebble Grid is now available in a practical 4 metre width. Pebble Grid's sophisticated latticed pattern draws the eye, creating an illusion of space and making it an especially inspired choice for any interior space. This uniform Level Loop Pile is available in a stunning selection of new neutrals. The palette is reminiscent of natural geological elements such as sandstone, granite and stone.",
      "Godfrey Hirst Best Seller Made in New Zealand Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Level Loop Pile Mid Range Declare® Red List Free",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Made in New Zealand",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
    ],
    seoTitle: "Pebble Grid 4M | Capital Tiles",
    seoDesc: "Pebble Grid 4M, Level Loop Pile, 10 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Calcite", "Sandstone", "Gypsum", "Borax", "Fieldspace", "Kimberlite", "Shale", "Basalt", "Dolomite", "Bauxite"],
    sizes: ["4.00m"],
    finishes: ["Level Loop Pile"],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Level Loop Pile"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Wool"],
      ["Gauge", "15.7/10cm (1/4th Gauge)"],
      ["Roll Width", "4.00m"],
      ["Total Product Thickness", "9 (+/- 1.0)mm"],
      ["Pile Height", "6 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "ravine-4m",
    name: "Ravine 4M",
    brand: "Godfrey Hirst",
    card: "/img/wool/ravine-4m.jpg",
    images: [
      "/img/wool/ravine-4m/1.jpg",
      "/img/wool/ravine-4m/2.jpg",
      "/img/wool/ravine-4m/3.jpg",
      "/img/wool/ravine-4m/4.jpg",
      "/img/wool/ravine-4m/5.jpg",
      "/img/wool/ravine-4m/6.jpg",
      "/img/wool/ravine-4m/7.jpg",
      "/img/wool/ravine-4m/8.jpg",
      "/img/wool/ravine-4m/9.jpg",
    ],
    tagline: "Wool carpet in 9 colours",
    short: "Ravine 4M Wool Carpet by Godfrey Hirst. 4.00m roll width and 9 colours. Supplied and laid across Canberra.",
    overview: [
      "A stunning and versatile range of carpet for all seasons, Ravine 4M will sustain luxurious comfort all year round. This textured loop pile carpet enhances room aesthetics, creating depth and dimension. Its tactile surface adds visual interest, transforming spaces with a luxurious feel, making it a stylish and inviting choice.",
      "Godfrey Hirst Best Seller Made in New Zealand Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Premium Declare® Red List Free Textured Loop Pile",
    ],
    features: [
      "Godfrey Hirst Best Seller",
      "Made in New Zealand",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
    ],
    seoTitle: "Ravine 4M | Capital Tiles",
    seoDesc: "Ravine 4M, 9 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Oatmeal", "Crevice", "Cobblestone", "Stonewall", "Smokey Ash", "Fissure", "Pewter", "Tussock", "Stone Haze"],
    sizes: ["4.00m"],
    finishes: [],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Wool"],
      ["Gauge", "25.2/10cm (5/32nd Gauge)"],
      ["Roll Width", "4.00m"],
      ["Total Product Thickness", "10 (+/- 1.0)mm"],
      ["Pile Height", "7 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "9"],
    ],
    rooms: [],
  },
  {
    handle: "bellavista",
    name: "Bellavista",
    brand: "Godfrey Hirst",
    card: "/img/wool/bellavista.jpg",
    images: [
      "/img/wool/bellavista/1.jpg",
      "/img/wool/bellavista/2.jpg",
      "/img/wool/bellavista/3.jpg",
      "/img/wool/bellavista/4.jpg",
      "/img/wool/bellavista/5.jpg",
      "/img/wool/bellavista/6.jpg",
      "/img/wool/bellavista/7.jpg",
      "/img/wool/bellavista/8.jpg",
      "/img/wool/bellavista/9.jpg",
      "/img/wool/bellavista/10.jpg",
    ],
    tagline: "Wool carpet in 10 colours",
    short: "Bellavista Wool Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Create your own beautiful interior view with Bellavista, a sumptuously soft Wool Carpet. A Cut Pile Twist with random textured finish, the natural wool acts to thermally regulate temperatures all year round, while also offering a resilient, stain resistant finish.",
      "Made in New Zealand Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* Natural Fibre Fire Rated Carpet Cut Pile Twist Mid Range Declare® Red List Free",
    ],
    features: [
      "Made in New Zealand",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
      "Natural Fibre",
    ],
    seoTitle: "Bellavista | Capital Tiles",
    seoDesc: "Bellavista, Cut Pile Twist, 10 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Bohemia", "Pebble Bay", "Murray River", "Satay", "Market Place", "Asteroid", "School Grey", "Pewter", "Deep Space", "Stone Age"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Wool"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "13 (+/- 1.0)mm"],
      ["Pile Height", "10 (+/- 1.0)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "odyssey",
    name: "Odyssey",
    brand: "Godfrey Hirst",
    card: "/img/wool/odyssey.jpg",
    images: [
      "/img/wool/odyssey/1.jpg",
      "/img/wool/odyssey/2.jpg",
      "/img/wool/odyssey/3.jpg",
      "/img/wool/odyssey/4.jpg",
      "/img/wool/odyssey/5.jpg",
    ],
    tagline: "Wool carpet in 5 colours",
    short: "Odyssey Wool Carpet by Godfrey Hirst. Cut pile plush, 3.66m roll width and 5 colours. Supplied and laid across Canberra.",
    overview: [
      "Odyssey seamlessly blends style with practicality, acting as a natural insulator for any living space. Beyond its captivating design, the inherent qualities of wool establish an insulating layer, preserving warmth in colder seasons and fostering a cool atmosphere in hotter weather. This dual functionality not only enhances energy efficiency but also ensures a pleasant ambience throughout the year.",
      "Made in New Zealand Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Hycraft Limited Residential Warranty* ISO 9001 Quality Management System ISO 14001 Environment Management System Natural Fibre Fire Rated Carpet Cut Pile Plush Premium",
    ],
    features: [
      "Made in New Zealand",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Hycraft Limited Residential Warranty*",
    ],
    seoTitle: "Odyssey | Capital Tiles",
    seoDesc: "Odyssey, Cut Pile Plush, 5 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Argos", "Penelope", "Trojan", "Sparta", "Stella"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Plush"],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Plush"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "80% Wool / 20% Synthetic"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "17.5 (+/- 1)mm"],
      ["Pile Height", "14.5 (+/- 1)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "5"],
    ],
    rooms: [],
  },
  {
    handle: "regency-twist",
    name: "Regency Twist",
    brand: "Godfrey Hirst",
    card: "/img/wool/regency-twist.jpg",
    images: [
      "/img/wool/regency-twist/1.jpg",
      "/img/wool/regency-twist/2.jpg",
      "/img/wool/regency-twist/3.jpg",
      "/img/wool/regency-twist/4.jpg",
      "/img/wool/regency-twist/5.jpg",
      "/img/wool/regency-twist/6.jpg",
      "/img/wool/regency-twist/7.jpg",
      "/img/wool/regency-twist/8.jpg",
      "/img/wool/regency-twist/9.jpg",
      "/img/wool/regency-twist/10.jpg",
    ],
    tagline: "Wool carpet in 10 colours",
    short: "Regency Twist Wool Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "The soft wool fibres of Regency Twist provide luxury underfoot with its luxurious texture, adding elegance and warmth while elevating the overall ambience. The twist pile carpet is available in a range of fashionable colours to suit your interior.",
      "Made in New Zealand Declare® Red List Free Residential Extra Heavy Duty & Stairs - 6 Star Contract Heavy Duty - 3 Star ECS Level 4 15 Year Wool Limited Residential Warranty* ISO 9001 Quality Management System ISO 14001 Environment Management System Fire Rated Carpet Cut Pile Twist Natural Fibre Premium",
    ],
    features: [
      "Made in New Zealand",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 6 Star",
      "Contract Heavy Duty - 3 Star",
      "ECS Level 4",
      "15 Year Wool Limited Residential Warranty*",
    ],
    seoTitle: "Regency Twist | Capital Tiles",
    seoDesc: "Regency Twist, Cut Pile Twist, 10 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Almond", "Vintage Stone", "Linen", "Fur", "Montego", "Obelisk", "Steel", "Zinc", "Enchanted", "Cashmere"],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Wool"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "13 (+/- 1)mm"],
      ["Pile Height", "10 (+/- 1)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "enchant",
    name: "Enchant",
    brand: "Godfrey Hirst",
    card: "/img/wool/enchant.jpg",
    images: [
      "/img/wool/enchant/1.jpg",
      "/img/wool/enchant/2.jpg",
      "/img/wool/enchant/3.jpg",
      "/img/wool/enchant/4.jpg",
      "/img/wool/enchant/5.jpg",
      "/img/wool/enchant/6.jpg",
      "/img/wool/enchant/7.jpg",
      "/img/wool/enchant/8.jpg",
      "/img/wool/enchant/9.jpg",
      "/img/wool/enchant/10.jpg",
    ],
    tagline: "Wool carpet in 10 colours",
    short: "Enchant Wool Carpet by Godfrey Hirst. Cut pile twist, 3.66m roll width and 10 colours. Supplied and laid across Canberra.",
    overview: [
      "Indulge in luxury with our exquisite 100% Wool Carpet, Enchant. Crafted for unparalleled comfort and durability, its plush texture and timeless design elevate any space, creating a warm and inviting ambience. The twist pile carpet is available in a range of fashionable colours to suit your home.",
      "Made in New Zealand Declare® Red List Free Residential Extra Heavy Duty & Stairs - 5 Star Contract Medium Duty - 2 Star ECS Level 4 15 Year Wool Limited Residential Warranty* ISO 14001 Environment Management System Fire Rated Carpet Cut Pile Twist Natural Fibre Mid Range",
    ],
    features: [
      "Made in New Zealand",
      "Declare® Red List Free",
      "Residential Extra Heavy Duty & Stairs - 5 Star",
      "Contract Medium Duty - 2 Star",
      "ECS Level 4",
      "15 Year Wool Limited Residential Warranty*",
    ],
    seoTitle: "Enchant | Capital Tiles",
    seoDesc: "Enchant, Cut Pile Twist, 10 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Raw Cotton",
      "Almond Beige",
      "Puddle",
      "Dusty Plain",
      "Woodland",
      "Pelaco",
      "Stonewashed",
      "Concrete",
      "Midnight Blue",
      "Greywacke",
    ],
    sizes: ["3.66m"],
    finishes: ["Cut Pile Twist"],
    thickness: [],
    slip: [],
    material: ["Wool Carpet"],
    specCols: ["Specification", "Detail"],
    specRows: [
      ["Style", "Cut Pile Twist"],
      ["Fibre", "Wool Carpet"],
      ["Yarn", "100% Wool"],
      ["Gauge", "31.5/10cm (1/8th Gauge)"],
      ["Roll Width", "3.66m"],
      ["Total Product Thickness", "13.5 (+/- 1)mm"],
      ["Pile Height", "10.5 (+/- 1)mm"],
      ["Pattern Repeat", "Not Applicable"],
      ["Colours", "10"],
    ],
    rooms: [],
  },
  {
    handle: "dawson-falls",
    name: "Dawson Falls",
    brand: "EC Carpets",
    card: "/img/wool/dawson-falls.jpg",
    images: [
      "/img/wool/dawson-falls/1.jpg",
      "/img/wool/dawson-falls/2.jpg",
      "/img/wool/dawson-falls/3.jpg",
      "/img/wool/dawson-falls/4.jpg",
      "/img/wool/dawson-falls/5.jpg",
      "/img/wool/dawson-falls/6.jpg",
      "/img/wool/dawson-falls/7.jpg",
      "/img/wool/dawson-falls/8.jpg",
      "/img/wool/dawson-falls/9.jpg",
    ],
    tagline: "Wool carpet in 9 colours",
    short: "Dawson Falls wool carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "Dawson Falls, our luxurious pure wool carpet, redefines elegance with its refined linear pattern and stunning colour palette, bringing timeless style and natural beauty to any space.",
      "Dawson Falls, an exquisite 100% New Zealand wool carpet that elevates the classic wool to a chunkier, more comfortable texture with a contemporary flair.",
      "Designed with a classic, geometric pattern and a thoughtfully curated organic colour palette. Dawson Falls seamlessly enhances any interior aesthetic, embodying on-trend simplicity.",
    ],
    features: ["Premium Wool", "Timeless Elegance", "Refined Heathered Colours", "Manufactured in Australia"],
    seoTitle: "Dawson Falls | Capital Tiles",
    seoDesc: "Dawson Falls, 9 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Meadow 5403",
      "Canyon 5417",
      "Sunlit 5454",
      "Serenity 5447",
      "Summit 5445",
      "Cascade 5423",
      "Mist 5428",
      "Frosted 5488",
      "Harmony 5411",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "elmsford",
    name: "Elmsford",
    brand: "EC Carpets",
    card: "/img/wool/elmsford.jpg",
    images: [
      "/img/wool/elmsford/1.jpg",
      "/img/wool/elmsford/2.jpg",
      "/img/wool/elmsford/3.jpg",
      "/img/wool/elmsford/4.jpg",
      "/img/wool/elmsford/5.jpg",
      "/img/wool/elmsford/6.jpg",
      "/img/wool/elmsford/7.jpg",
      "/img/wool/elmsford/8.jpg",
      "/img/wool/elmsford/9.jpg",
    ],
    tagline: "Wool carpet in 9 colours",
    short: "Elmsford wool carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "Elmsford is a premium 100% New Zealand wool loop carpet, where natural warmth meets considered design. Its offset, organic pattern introduces a quiet, shifting texture that brings depth and movement to the floor – refined without being rigid. A palette of rich, layered tones balanced with soft neutrals adapts effortlessly across modern and transitional interiors. Built on EC's CoreLoop™ construction and backed by PestGuard Pro™ protection, Elmsford is made for homes where beauty and everyday life coexist.",
      "The offset, organic loop pattern creates subtle movement and depth across the floor, a design that reads as both current and enduring, suited to modern, elegant spaces without demanding attention.",
      "Sourced from New Zealand's finest wool-growing regions, Elmsford delivers genuine underfoot warmth and comfort. Wool's natural crimp provides lasting recovery underfoot, preserving its appearance year after year.",
    ],
    features: [
      "Timeless Texture",
      "100% New Zealand Premium Wool",
      "CoreLoop™ Construction",
      "Low-Fluff by Construction",
      "PestGuard Pro™ Long-lasting Protection",
      "ECS 4+ Certified",
    ],
    seoTitle: "Elmsford | Capital Tiles",
    seoDesc: "Elmsford, 9 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Clara 5801",
      "Birley 5802",
      "Rowden 5803",
      "Caden 5804",
      "Magnor 5805",
      "Nox 5806",
      "Solmorra 5807",
      "Oakmere 5808",
      "Garnet 5809",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "hause",
    name: "Hause",
    brand: "EC Carpets",
    card: "/img/wool/hause.jpg",
    images: [
      "/img/wool/hause/1.jpg",
      "/img/wool/hause/2.jpg",
      "/img/wool/hause/3.jpg",
      "/img/wool/hause/4.jpg",
      "/img/wool/hause/5.jpg",
      "/img/wool/hause/6.jpg",
      "/img/wool/hause/7.jpg",
      "/img/wool/hause/8.jpg",
      "/img/wool/hause/9.jpg",
    ],
    tagline: "Wool carpet in 9 colours",
    short: "Hause wool carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "A modern take on classic Berber, this premium 100% New Zealand wool carpet offers elegance and practicality with its neutral heathered colours effortlessly complements any interior theme.",
      "Certified to the highest level under the Environmental Certification Scheme, Hause supports healthier interiors and contributes to Green Star building ratings.",
      "Hause is a premium New Zealand wool carpet with a modern twist to the classic wool Berber.",
    ],
    features: [
      "ECS 4+ Accredited",
      "Premium Wool",
      "Stylish simplicity",
      "Neutral heathered colours",
      "Manufactured in Australia",
    ],
    seoTitle: "Hause | Capital Tiles",
    seoDesc: "Hause, 9 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Three 5003",
      "Seventeen 5017",
      "Fifty Four 5054",
      "Forty Seven 5047",
      "Forty Five 5045",
      "Twenty Three 5023",
      "Twenty EIGHT 5028",
      "Eighty Eight 5088",
      "Eleven 5011",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "sirocco",
    name: "Sirocco",
    brand: "EC Carpets",
    card: "/img/wool/sirocco.jpg",
    images: [
      "/img/wool/sirocco/1.jpg",
      "/img/wool/sirocco/2.jpg",
      "/img/wool/sirocco/3.jpg",
      "/img/wool/sirocco/4.jpg",
      "/img/wool/sirocco/5.jpg",
      "/img/wool/sirocco/6.jpg",
      "/img/wool/sirocco/7.jpg",
    ],
    tagline: "Wool carpet in 7 colours",
    short: "Sirocco wool carpet by EC Carpets. 7 colours. Supplied and laid across Canberra.",
    overview: [
      "Sirocco is an entry-level wool loop pile carpet crafted from 100% pure wool, offering natural comfort and everyday practicality. Inspired by the classic Berber styling, its subtle texture and neutral heathered tones bring effortless versatility to modern interiors.",
      "Its neutral, heathered palette draws inspiration from natural landscapes, creating a versatile",
      "foundation that complements a wide range of interior styles, from modern minimalist to classic contemporary.",
    ],
    features: ["Timeless Tones", "Everyday Resilience", "Effortless Style", "Practical Comfort"],
    seoTitle: "Sirocco | Capital Tiles",
    seoDesc: "Sirocco, 7 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Desert Clay 5917",
      "Barley Sand 5954",
      "Argan Spice 5947",
      "Market Bazaar 5945",
      "Quarry Mist 5923",
      "Cinder Stone 5928",
      "Basalt Dune 5988",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "cotswolds",
    name: "Cotswolds",
    brand: "EC Carpets",
    card: "/img/wool/cotswolds.jpg",
    images: [
      "/img/wool/cotswolds/1.jpg",
      "/img/wool/cotswolds/2.jpg",
      "/img/wool/cotswolds/3.jpg",
      "/img/wool/cotswolds/4.jpg",
      "/img/wool/cotswolds/5.jpg",
      "/img/wool/cotswolds/6.jpg",
      "/img/wool/cotswolds/7.jpg",
      "/img/wool/cotswolds/8.jpg",
      "/img/wool/cotswolds/9.jpg",
    ],
    tagline: "Wool carpet in 9 colours",
    short: "Cotswolds wool carpet by EC Carpets. 9 colours. Supplied and laid across Canberra.",
    overview: [
      "Cotswolds is a premium 100% New Zealand wool loop carpet that brings architectural confidence to the floor. Its geometric loop pattern delivers a structured, precise aesthetic – refined in detail, composed in character – that harmonises with both contemporary and classic interiors. A nuanced palette spanning warm neutrals and grounded earthy tones ensures lasting design relevance across evolving spaces. Built on EC's CoreLoop™ construction and PestGuard Pro™ technology, Cotswolds brings the perfect balance between performance and aesthetics.",
      "The geometric loop pattern creates a refined, structured surface – precise in form, poised in character. It brings a sense of order and sophistication to both contemporary and classic interiors without overpowering the broader design scheme.",
      "Sourced from New Zealand's finest wool-growing regions, Cotswolds offers a naturally soft, breathable underfoot experience with the inherent resilience that only pure wool provides. Comfort that holds its character over time.",
    ],
    features: [
      "Architectural Elegance",
      "100% New Zealand Premium Wool",
      "CoreLoop™ Construction",
      "Low-Fluff by Construction",
      "PestGuard Pro™ Long-lasting Protection",
      "ECS 4+ Certified",
    ],
    seoTitle: "Cotswolds | Capital Tiles",
    seoDesc: "Cotswolds, 9 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: [
      "Willowby 6001",
      "Alderwick 6002",
      "Fallow 6003",
      "Thornleigh 6004",
      "Millthorpe 6005",
      "Hollowmere 6006",
      "Kingswell 6007",
      "Hazelwood 6008",
      "Maplehurst 6009",
    ],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
  {
    handle: "bahamas",
    name: "Bahamas",
    brand: "EC Carpets",
    card: "/img/wool/bahamas.jpg",
    images: [
      "/img/wool/bahamas/1.jpg",
      "/img/wool/bahamas/2.jpg",
      "/img/wool/bahamas/3.jpg",
      "/img/wool/bahamas/4.jpg",
      "/img/wool/bahamas/5.jpg",
      "/img/wool/bahamas/6.jpg",
      "/img/wool/bahamas/7.jpg",
    ],
    tagline: "Wool carpet in 7 colours",
    short: "Bahamas wool carpet by EC Carpets. 7 colours. Supplied and laid across Canberra.",
    overview: [
      "rafted from 100% New Zealand Wool, Bahamas offers a rustic, sisal-inspired loop. This timeless colour palette comes in natural earthy tones, suitable for homes from the country to the coast.",
      "Certified to the highest level under the Environmental Certification Scheme, Bahamas supports",
      "healthier interiors and contributes to Green Star building ratings.",
    ],
    features: ["ECS 4+ Accredited", "Premium Wool", "Country to Coast", "Sisal Elevated", "Easy to Maintain"],
    seoTitle: "Bahamas | Capital Tiles",
    seoDesc: "Bahamas, 7 colours. Wool carpet supplied and installed across Canberra by Capital Tiles.",
    colours: ["Caribbean 5705", "Grenada 5706", "Barbados 5707", "Cayman 5704", "Cuba 5701", "Jamaica 5703", "Nevis 5702"],
    sizes: [],
    finishes: [],
    thickness: [],
    slip: [],
    material: [],
    specCols: [],
    specRows: [],
    rooms: [],
  },
]

export function byHandle(handle) {
  return WOOL_PRODUCTS.find((p) => p.handle === handle)
}
